# -*- coding: utf-8 -*-
"""Emit the K5 Bariah decision-ingestion and policy artifacts.

    python3 docs/pl06/tools/k5_policy_emit_v1.py

Every string is projected from k5_pattern_policy_v1 and k5_policy_apply_v1. Edit those,
not the files this writes.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PL06 = os.path.dirname(HERE)
OUT = os.path.join(PL06, "k5_policy")
sys.path.insert(0, HERE)
import k5_pattern_policy_v1 as P   # noqa: E402
import k5_policy_apply_v1 as AP    # noqa: E402
import k5_policy_qa_v1 as QA       # noqa: E402
import k5_policy_mutations_v1 as MU  # noqa: E402

BANNER = ("<!-- GENERATED by docs/pl06/tools/k5_policy_emit_v1.py — "
          f"Stage {P.STAGE}. Edit the model, not this file. -->")


def _w(name, text):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text)
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1) + "\n")


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def _ingestion_md(r):
    L = [BANNER, "", "# K5 Kelompok 0 v1.2 — Bariah decision ingestion", "", "```",
         f"DOCUMENT   = {r['source_document']['filename']}",
         f"SHA256     = {r['source_document']['sha256']}",
         f"BYTES      = {r['source_document']['bytes']:,}",
         f"REVIEWER   = {r['reviewer']['name']} ({r['reviewer']['role']})",
         f"VERDICT    = {r['overall_verdict']['ticked']}",
         f"DECISIONS  = {r['modelled_total']} of {r['declared_total']} declared",
         f"APPROVED   = {len(r['approved_ids'])}",
         f"PENDING    = {len(r['pending_ids'])}  {r['pending_ids']}", "```", "",
         "## Provenance", "", r["reviewer"]["provenance_note"], "",
         _tbl(["field", "value"],
              [["name", r["reviewer"]["name"]], ["role", r["reviewer"]["role"]],
               ["course", r["reviewer"]["course"]],
               ["scope", r["reviewer"]["document_scope"]],
               ["version", r["reviewer"]["document_version"]],
               ["date in closing block", r["reviewer"]["date_in_closing_block"]],
               ["header-table review date",
                r["reviewer"]["review_date_field_in_header_table"]],
               ["signature line", r["reviewer"]["signature_line"]],
               ["tracked changes", r["source_document"]["tracked_changes"]],
               ["Word comments", r["source_document"]["word_comments"]]]), "",
         r["source_document"]["tracked_changes_basis"], "",
         "## Bariah's closing note, verbatim", "",
         "> " + r["overall_verdict"]["closing_note_verbatim"], "",
         "## Deadlines stated in the document", "",
         _tbl(["item", "value"],
              [["Bariah feedback required before",
                r["deadlines"]["bariah_feedback_required_before"]],
               ["internal K5 storyboard target",
                r["deadlines"]["internal_k5_storyboard_target"]]]), "",
         r["deadlines"]["caveat_verbatim"], "",
         "## The seventeen decisions", "",
         _tbl(["id", "title", "checkbox", "status", "scope", "prose overrides tick"],
              [[d["id"], d["title"], d.get("checkbox") or "— none ticked —",
                d["status"], d.get("scope") or "—",
                "**YES**" if d.get("prose_overrides_checkbox") else "no"]
               for d in r["decisions"]]), ""]
    L += ["## Effective rules, and Bariah's own words", ""]
    for d in r["decisions"]:
        L += [f"### {d['id']} — {d['title']}", ""]
        if d.get("checkbox"):
            L.append(f"Ticked: **{d['checkbox']}**")
        else:
            L.append("Ticked: **nothing** — no option selected")
        L.append("")
        if d.get("bariah_prose"):
            L += ["Bariah's amendment, verbatim:", ""]
            L += ["> " + ln for ln in d["bariah_prose"].split("\n")]
            L.append("")
        else:
            L += ["Bariah's amendment field: *blank*", ""]
        if d.get("effective_rule"):
            L += [f"**Effective rule.** {d['effective_rule']}", ""]
        else:
            L += ["**No effective rule** — this decision is pending.", ""]
        for k in ("override_note", "note_for_summaries", "cross_course_note",
                  "worked_example", "tick_note", "unblocked_by"):
            if d.get(k):
                L += [f"*{k.replace('_', ' ')}:* {d[k]}", ""]
    L += ["## CAIR sub-points Bariah did not answer", "",
          "Silence is not approval. These stay CAIR proposals.", "",
          _tbl(["decision", "sub-point", "status"],
               [[s["decision"], s["subpoint"], s["status"]]
                for s in r["unresolved_subpoints"]]), "",
          "## Section B", "", r["section_b_note"], ""]
    return "\n".join(L)


def _matrix_md(m):
    return "\n".join([
        BANNER, "", "# K5 decision-impact matrix", "",
        f"{m['total']} rulings. {len(m['affected_by_section_b'])} are themselves Section B "
        f"and remain undecided: {', '.join(m['affected_by_section_b'])}.", "",
        "No approved ruling in Sections A, C or D depends on Section B — Section B governs "
        "the review package and schedule, not the pattern policy. That is why storyboard "
        "modelling can continue while B is open.", "",
        _tbl(["ruling", "affected rule or generator", "affected units", "scope",
              "implementation status", "Section B affects it"],
             [[f"**{r['decision']}** {r['title']}", r["affected_rule_or_generator"],
               r["affected_units"], r["scope"] or "—", r["implementation_status"],
               "**yes**" if r["section_b_affects_it"] else "no"]
              for r in m["rows"]]), "",
        "## Notes", "",
        "\n".join(f"- **{r['decision']}** — {r['note']}" for r in m["rows"] if r["note"]),
        ""])


def _calibration_md(c):
    L = [BANNER, "", "# K5 four-unit calibration re-evaluation under the Bariah policy", "",
         f"{c['count']} units re-evaluated. Controlled source rows are unchanged — the "
         f"ruling changes pattern and obligation, not extraction.", "",
         _tbl(["unit", "scenario", "Rumusan beats", "Rumusan visual", "min screens",
               "closing", "narrator"],
              [[u["unit_id"], u["scenario_obligation"]["change"],
                u["summary_visual_obligation"]["change"],
                u["summary_visual_obligation"]["visual_change"],
                f"{u['screen_pattern_plan']['minimum_total_before']} → "
                f"{u['screen_pattern_plan']['minimum_total_after']}",
                u["closing_screen"]["closing_text"], u["narrator"]["name"]]
               for u in c["units"]]), ""]
    for u in c["units"]:
        sp, so = u["screen_pattern_plan"], u["scenario_obligation"]
        sv, cl = u["summary_visual_obligation"], u["closing_screen"]
        L += [f"## {u['unit_id']} — {u['lesson_title']}", "",
              _tbl(["aspect", "value"],
                   [["controlled source rows", u["controlled_source_rows"]["status"]],
                    ["primary pattern", sp["primary"]],
                    ["secondary pattern", sp["secondary"]],
                    ["A3 stepwise applies", sp["a3_applies"]],
                    ["shell screens", f"{sp['shell_screens_before']} → "
                                      f"{sp['shell_screens_after']}"],
                    ["content groups", sp["content_groups"]],
                    ["closing screens", sp["closing_screens"]],
                    ["minimum total", f"{sp['minimum_total_before']} → "
                                      f"{sp['minimum_total_after']}"],
                    ["maximum total", sp["maximum_total"]],
                    ["scenario required", so["required"]],
                    ["previous CAIR verdict", so["previous_cair_verdict"]],
                    ["scenario change", so["change"]],
                    ["Rumusan beats", f"{sv['beats_before']} → {sv['beats_required']}"],
                    ["Rumusan visual", sv["visual_change"]],
                    ["Rumusan visual subject", sv["visual_subject"]],
                    ["quiz", f"{u['quiz_structure']['mcq']} MCQ + "
                             f"{u['quiz_structure']['multiple_response']} MR @ "
                             f"{u['quiz_structure']['pass_percent']}%"],
                    ["answer key", u["quiz_structure"]["key_status"]],
                    ["narrator", u["narrator"]["name"]],
                    ["characters", u["characters"]["cast"]],
                    ["segmentation", cl["segmentation"]],
                    ["Bahagian label shown", cl["bahagian_label_shown"]],
                    ["closing text", cl["closing_text"]],
                    ["Comparison re-test", u["comparison_retest"]["status"]],
                    ["ready to emit PPTX", u["readiness"]["ready_to_emit_pptx"]]]), "",
              f"*Scenario note.* {so['note']}", "",
              "**State-model implications.** added states: "
              f"{u['state_model_implications']['added_states']}; "
              f"{u['state_model_implications']['summary_visual_state']}; total runtime "
              f"states {u['state_model_implications']['total_runtime_states']}.", "",
              "**Ambiguities and exceptions.**", ""]
        L += [f"- {a}" for a in u["ambiguities_and_exceptions"]]
        L += [""]
    return "\n".join(L)


def _structures_md(s):
    t = s["confirmed_segmentation"]
    r0 = s["renamed_counts"][0]
    return "\n".join([
        BANNER, "", "# K5 structures outside PL06, reassessed under D4", "",
        f"Population: **{s['population']}** — "
        f"{s['pakej_latihan_outside_pl06']} of {s['pakej_latihan_in_module']} Pakej "
        f"Latihan in the module.", "", "```",
        f"CONFIRMED_STORYBOARD_PRODUCTION_UNITS_OUTSIDE_PL06 = "
        f"{s['confirmed_storyboard_production_units_outside_pl06']}",
        f"CANDIDATE_STRUCTURES                              = "
        f"{s['candidate_structures']}",
        f"CLEAN_CANDIDATES                                  = {s['clean_candidates']}",
        f"AMBER_CANDIDATES                                  = {s['amber_candidates']}",
        f"UNMAPPED_SOURCE_REGIONS                           = "
        f"{s['unmapped_source_regions']}  ({s['unmapped_pages']} pages)", "```", "",
        s["confirmed_storyboard_production_units_outside_pl06_note"], "",
        "## A count that was wrong, and what it actually was", "",
        _tbl(["field", "value"],
             [["was", r0["was"]], ["was read as", r0["was_read_as"]],
              ["actually", r0["actually"]], ["now", r0["now"]],
              ["outside-PL06 equivalent", r0["outside_pl06_equivalent"]]]), "",
        "Three different sevens sit in this data, which is why the contradiction was easy "
        "to miss: seven PL06 Topik, seven non-PL06 Pakej Latihan, and seven Topik in the "
        "frozen segmentation. Each now carries its own named roll.", "",
        "## Named member rolls", "",
        _tbl(["count", "value", "members"],
             [["confirmed storyboard production units outside PL06",
               s["confirmed_storyboard_production_units_outside_pl06"],
               "*(none)*"],
              ["candidate structures", s["candidate_structures"],
               ", ".join(f"`{x}`" for x in s["candidate_structures_roll"])],
              ["clean candidates", s["clean_candidates"],
               ", ".join(f"`{x}`" for x in s["clean_candidates_roll"])],
              ["amber candidates", s["amber_candidates"],
               ", ".join(f"`{x}`" for x in s["amber_candidates_roll"])],
              ["unmapped source regions", s["unmapped_source_regions"],
               ", ".join(f"`{x}`" for x in s["unmapped_source_regions_roll"])]]), "",
        f"*Unmapped source region.* {s['unmapped_source_regions_definition']}", "",
        "## PL06's own rows — reported separately, NOT an outside-PL06 count", "",
        s["pl06_topik_note"], "",
        _tbl(["Topik", "sub-modul heading", "source pages", "Bahagian", "storyboard "
              "production unit?"],
             [[t2["topik_id"], t2["sub_modul_heading"],
               f"{t2['source_page_span'][0]}–{t2['source_page_span'][1]}",
               t2["bahagian_in_this_topik"],
               "no — a Topik is a source structure"]
              for t2 in s["pl06_topik"]]), "",
        f"PL06's storyboard production units are the "
        f"**{s['pl06_storyboard_production_units']}** Bahagian entries beneath these "
        f"seven Topik, not the Topik themselves.", "",
        "## Confirmed Topic/Bahagian segmentation", "",
        f"Source: {t['source']}.", "",
        _tbl(["Topik", "Bahagian", "segmentation", "D4 treatment"],
             [[k, v["bahagian"], v["segmentation"],
               "no label, closes 'Tamat Topik'" if v["segmentation"]
               == "TOPIK_WITHOUT_BAHAGIAN"
               else "per-Bahagian storyboard/Rumusan/Kuiz; only the last closes "
                    "'Tamat Topik'"]
              for k, v in t["topics"].items()]), "",
        "## Structures affected by D4", "",
        f"Resolved: {', '.join(s['structures_affected_by_d4']['resolved'])} "
        f"({s['structures_affected_by_d4']['resolved_scope']}).", "",
        f"Unresolved: {s['structures_affected_by_d4']['unresolved_count']}. "
        f"{s['structures_affected_by_d4']['unresolved_note']}", "",
        "## Candidate structures", "",
        _tbl(["candidate", "PL", "topic", "record type", "status", "granularity",
              "D4 resolvable"],
             [[r["candidate_id"], r["pl"], (r["topic"] or "")[:34], r["record_type"],
               r["status"], r["granularity"], "no"] for r in s["rows"]]), "",
        "## Still not confirmed production units", "",
        f"{len(s['still_not_confirmed_production_units'])} of "
        f"{len(s['rows'])} — every candidate structure outside PL06 remains a candidate. "
        f"D4 cannot promote any of them, because D4 keys on a segmentation none of them "
        f"has.", ""])


def _forecast_md(f):
    L = [BANNER, "", "# K5 completion forecast", "", "```",
         f"STATUS = {f['status']}", "```", "", f["status_note"], "", f["basis"], "",
         "## Section B is resolved", "",
         _tbl(["field", "value"],
              [["decision date", f["section_b_resolved"]["date"]],
               ["deadline", f["section_b_resolved"]["deadline"]],
               ["met deadline", f["section_b_resolved"]["met_deadline"]],
               ["status", f["section_b_resolved"]["status"]]]), "",
         "Unblocked: " + "; ".join(f["section_b_resolved"]["what_it_unblocked"]) + ".", "",
         "Still not unblocked: "
         + "; ".join(f["section_b_resolved"]["what_it_did_not_unblock"]) + ".", "",
         "## The real review constraint", "",
         _tbl(["field", "value"],
              [[k.replace("_", " "), v] for k, v in f["review_constraint"].items()
               if k != "note"]), "",
         f["review_constraint"]["note"], "",
         "## What is still open", "",
         _tbl(["variable", "state"],
              [["slots per available day", f["open_variables"][
                  "slots_per_available_day"]],
               ["available dates", f["open_variables"]["available_dates"]],
               ["B2 density outcome", f["open_variables"]["b2_density_outcome"]]]), "",
         f["open_variables"]["consequence"], "",
         "## Fixed inputs", "",
         _tbl(["input", "value"], [[k.replace("_", " "), v]
                                   for k, v in f["fixed_inputs"].items()]), "",
         "## Conditional assumptions", ""]
    L += [f"- **{a.split(' — ')[0]}** — {a.split(' — ', 1)[1]}"
          if " — " in a else f"- {a}" for a in f["assumptions"]]
    L += ["", "## Scenarios at a glance", "",
          _tbl(["", "scenario", "slots/day (conditional)", "9 Aug target", "confidence"],
               [[s["id"], s["name"], s["slots_per_day_assumed"], s["target_9_aug"],
                 s["confidence"]] for s in f["scenarios"]]), ""]
    for s in f["scenarios"]:
        L += [f"## Scenario {s['id']} — {s['name']}", "",
              _tbl(["stage", "range"],
                   [["Section B decision date", s["section_b_decision_date"]],
                    ["slots per day (conditional)", s["slots_per_day_assumed"]],
                    ["calibration completion", s["calibration_completion_range"]],
                    ["batch generation start", s["batch_generation_start_range"]],
                    ["engineering generation completion",
                     s["engineering_generation_completion_range"]],
                    ["Bariah review / freeze completion",
                     s["bariah_review_freeze_completion_range"]],
                    ["full-K5 package completion",
                     s["full_k5_package_completion_range"]]]), "",
              "**Assumptions:** " + ", ".join(s["assumptions"]) + ".", "",
              "**Principal blockers:**", ""]
        L += [f"- {b}" for b in s["principal_blockers"]]
        if s.get("mitigation"):
            L += ["", f"**Mitigation.** {s['mitigation']}"]
        L += [""]
    L += ["## Deliberately not forecast", ""]
    L += [f"- {x}" for x in f["what_is_not_forecast"]]
    L += [""]
    return "\n".join(L)


def _qa_md(s):
    return "\n".join([
        BANNER, "", "# K5 Bariah-policy QA report", "", "```",
        f"SUITE_ID = {s['suite_id']}",
        f"GATES    = {s['total']}",
        f"PASSED   = {s['passed']}",
        f"FAILED   = {len(s['failed'])}",
        f"ORACLE_SEPARATION_STRUCTURAL = {s['oracle_separation_structural']}", "```", "",
        "Own identity and own total. No sibling suite is merged in or edited.", "",
        _tbl(["area", "gates"], [[k, v] for k, v in s["by_type"].items() if v]), "",
        _tbl(["oracle basis", "gates"],
             [[k, v] for k, v in s["by_oracle_basis"].items()]), "",
        "## Every gate", "",
        _tbl(["gate", "area", "basis", "population", "ok"],
             [[g["gate_id"], g["gate_type"], g["oracle_basis"], g["population"],
               "yes" if g["ok"] else "**NO**"] for g in s["gates"]]), "",
        "## Not checked", "",
        "\n".join(f"- {n}" for n in s["not_checked"]), ""])


def _mut_md(r):
    return "\n".join([
        BANNER, "", "# K5 Bariah-policy mutation report", "", "```",
        f"SUITE_ID = {r['suite_id']}",
        f"FIXTURES = {r['fixture_count']}",
        f"DETECTED = {r['detected']}",
        f"MISSED   = {len(r['missed'])}",
        f"BASELINE = {r['baseline_pass']}/{r['baseline_total']}", "```", "",
        _tbl(["fixture", "what it breaks", "target", "gates that fired"],
             [[f["fixture_id"], f["title"], f["target"],
               ", ".join(f"`{g}`" for g in f["fired"]) or "**NONE — MISSED**"]
              for f in r["fixtures"]]), ""])


def emit_all():
    rec = P.ingestion_record()
    m = AP.impact_matrix()
    c = AP.calibration_units()
    s = AP.outside_pl06()
    qa = QA.summary()
    mu = MU.main()
    return [
        _j("K5_BARIAH_DECISION_INGESTION_v1.json", rec),
        _w("K5_BARIAH_DECISION_INGESTION_v1.md", _ingestion_md(rec)),
        _j("K5_DECISION_IMPACT_MATRIX_v1.json", m),
        _w("K5_DECISION_IMPACT_MATRIX_v1.md", _matrix_md(m)),
        _j("K5_CALIBRATION_REEVALUATION_v1.json", c),
        _w("K5_CALIBRATION_REEVALUATION_v1.md", _calibration_md(c)),
        _j("K5_STRUCTURES_OUTSIDE_PL06_v1.json", s),
        _w("K5_STRUCTURES_OUTSIDE_PL06_v1.md", _structures_md(s)),
        _j("K5_COMPLETION_FORECAST_v1.json", AP.FORECAST),
        _w("K5_COMPLETION_FORECAST_v1.md", _forecast_md(AP.FORECAST)),
        _j("K5_POLICY_QA_REPORT_v1.json", qa),
        _w("K5_POLICY_QA_REPORT_v1.md", _qa_md(qa)),
        _w("K5_POLICY_MUTATION_REPORT_v1.md", _mut_md(mu)),
    ]


if __name__ == "__main__":
    for n in emit_all():
        print("wrote", n)
