# -*- coding: utf-8 -*-
"""Stage 4.2F-D — emit the eight remaining PL06 extractions and provisional models."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PL06 = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import pl06_extract_v1 as EX       # noqa: E402
import pl06_extract_rest_v1 as R   # noqa: E402

OUT = R.OUT_DIR
BANNER = ("<!-- GENERATED by docs/pl06/tools/pl06_rest_emit_v1.py — "
          f"Stage {R.STAGE}. Edit the model, not this file. -->")


def _tbl(h, rows):
    o = ["| " + " | ".join(h) + " |", "|" + "|".join("---" for _ in h) + "|"]
    for r in rows:
        o.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                   for c in r) + " |")
    return "\n".join(o)


def emit_all():
    os.makedirs(OUT, exist_ok=True)
    models, ex = R.all_models()
    units = R.remaining_units()
    made = []
    for uid, e in ex.items():
        n = f"{uid.replace('-', '_')}_SOURCE_EXTRACT_v1.json"
        with open(os.path.join(OUT, n), "w", encoding="utf-8") as f:
            json.dump(e, f, ensure_ascii=False, indent=1)
            f.write("\n")
        made.append(n)
    for uid, m in models.items():
        n = f"{uid.replace('-', '_')}_PROVISIONAL_MODEL_v1.json"
        with open(os.path.join(OUT, n), "w", encoding="utf-8") as f:
            json.dump(m, f, ensure_ascii=False, indent=1)
            f.write("\n")
        made.append(n)

    leak = EX.leak_report(ex, units)
    eq = EX.t04_equivalence()
    summary = dict(
        stage=R.STAGE, authority=R.AUTHORITY,
        derived_from="frozen PL06 boundary map",
        total_mapped_units=14, already_represented=R.ALREADY_REPRESENTED,
        remaining_count=len(units),
        remaining_unit_ids=[u["unit_id"] for u in units],
        derivation_rule=R.DERIVATION_RULE,
        units=[dict(unit_id=uid,
                    lesson_title=ex[uid]["lesson_title"],
                    module_pages=ex[uid]["boundary"]["module_pages"],
                    page_range_matches_frozen=ex[uid]["page_attribution"]
                    ["matches_frozen_map"],
                    shared_start=ex[uid]["boundary"]["shared_start"],
                    shared_end=ex[uid]["boundary"]["shared_end"],
                    rows=ex[uid]["totals"]["content_rows"],
                    tables=ex[uid]["totals"]["tables"],
                    images=ex[uid]["totals"]["raster_images"],
                    diagrams=ex[uid]["totals"]["diagrams"],
                    groups=len(m["grouping"]["groups"]),
                    grouping_basis=m["grouping"]["basis"],
                    minimum_screens=m["screen_sequence"]["arithmetic"][
                        "minimum_total_screens"],
                    obligations=m["mandatory_propositions"]["count"],
                    definitions=m["definitional_statements"]["count"],
                    visual_subjects=m["visual_obligations"]["count"],
                    source_attested=m["visual_obligations"]["source_attested"],
                    terminology=m["terminology"]["count"],
                    extraction_qa=m["extraction_qa"])
               for uid, m in models.items()],
        totals=dict(units=len(units),
                    rows=sum(e["totals"]["content_rows"] for e in ex.values()),
                    tables=sum(e["totals"]["tables"] for e in ex.values()),
                    images=sum(e["totals"]["raster_images"] for e in ex.values()),
                    obligations=sum(m["mandatory_propositions"]["count"]
                                    for m in models.values()),
                    definitions=sum(m["definitional_statements"]["count"]
                                    for m in models.values()),
                    visual_subjects=sum(m["visual_obligations"]["count"]
                                        for m in models.values())),
        leak_report=leak, t04_equivalence_still_holds=eq.get("equivalent"))
    n = "PL06_REST_EXTRACTION_SUMMARY_v1.json"
    with open(os.path.join(OUT, n), "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=1)
        f.write("\n")
    made.append(n)

    t = summary["totals"]
    md = [BANNER, "", "# PL06 — the eight remaining units", "", "```",
          f"STAGE            = {R.STAGE}",
          f"AUTHORITY        = {R.AUTHORITY}",
          "MAPPED_UNITS     = 14",
          f"ALREADY_REPRESENTED = {len(R.ALREADY_REPRESENTED)}",
          f"REMAINING        = {summary['remaining_count']}",
          f"CONTROLLED_ROWS  = {t['rows']}", "```", "",
          "The unit list is derived from the frozen boundary map, not typed. Fourteen units "
          "are mapped and six are already represented — the delivered B02 proof, T04, and the "
          "four batch 1 units — so eight remain.", "",
          _tbl(["unit", "lesson", "pages", "shared", "rows", "tbl", "img", "groups",
                "min screens", "obligations", "definitions", "visuals"],
               [[u["unit_id"], u["lesson_title"][:34],
                 f"{u['module_pages'][0]}–{u['module_pages'][1]}",
                 ("start" if u["shared_start"] else "")
                 + ("+end" if u["shared_end"] else "") or "clean",
                 u["rows"], u["tables"], u["images"], u["groups"], u["minimum_screens"],
                 u["obligations"], u["definitions"],
                 f"{u['visual_subjects']} ({u['source_attested']} attested)"]
                for u in summary["units"]]), "",
          "## What this layer claims", "", R.DERIVATION_RULE, "",
          "Batch 1's propositions and stems were hand-authored after reading every unit. "
          "These eight are derived by the published rule above, quoting rows verbatim. The "
          "rows are the same quality; the analysis over them is shallower, and the models say "
          "so in `model_depth`. Rumusan beats, dialogue verdicts and assessment items are "
          "`PENDING_UNIT_EXCEPTION_REVIEW`, not guessed.", "",
          "## Boundary integrity", "", "```",
          f"all units clean        = {str(leak['all_clean']).lower()}",
          f"adjacent pairs checked = {leak['adjacency']['pairs_checked']}",
          f"all contiguous         = {str(leak['adjacency']['all_contiguous']).lower()}",
          f"T04 equivalence holds  = {str(eq.get('equivalent')).lower()}", "```", "",
          _tbl(["adjacent pair", "first ends", "second begins", "gap"],
               [[p["pair"], p["first_last_included"], p["second_first_included"], p["gap"]]
                for p in leak["adjacency"]["pairs"]]), "",
          "The two non-zero gaps are exactly where the already-extracted units sit — "
          "T03-B02/B03/B04 between T03-B01 and T03-B05, and T04/T05-B01/T06-B01 between "
          "T03-B05 and T07-B01. A gap between units that are not adjacent in the frozen map "
          "is expected and is reported rather than hidden.", ""]
    n = "PL06_REST_EXTRACTION_AND_MODELS_v1.md"
    with open(os.path.join(OUT, n), "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    made.append(n)
    return made, summary


if __name__ == "__main__":
    made, s = emit_all()
    print(f"emitted {len(made)} artifacts; {s['totals']['rows']} rows across "
          f"{s['remaining_count']} units")
