# -*- coding: utf-8 -*-
"""Stage 4.2F-B2 — project the batch model into the review DOCX, the Markdown and the
traceability artifacts.

    python3 docs/pl06/tools/pl06_batch1_emit_v1.py

ONE block list feeds both the DOCX and the Markdown, so the two cannot disagree. Every
string comes from pl06_batch1_data_v1; nothing is typed here.
"""
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PL06 = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(PL06))
sys.path.insert(0, HERE)
import pl06_batch1_data_v1 as B   # noqa: E402
import pl06_docx_v1 as D          # noqa: E402

OUT = PL06
DOCX_DIR = os.path.join(REPO, "reviews", "storyboard-bariah", "pl06_harvest_batch1")
DOCX_NAME = "PL06_Pakej_Keputusan_Bariah_Kelompok1_v1_0.docx"
PREVIEW_DIR = os.path.join(PL06, "harvest_batch1_preview")
MD_NAME = "PL06_HARVEST_BATCH1_PACKAGE_v1.md"

BANNER = (f"<!-- GENERATED by {B.GENERATED_BY} — Stage {B.STAGE}. "
          "Edit the model, not this file. -->")

DOC_TITLE_MS = "Pakej Keputusan Bariah — Kelompok Tuaian Kuasa 1"
DOC_SUBTITLE_MS = "Empat unit PL06 · sempadan beku, kandungan belum diekstrak"

ARTIFACTS = [
    MD_NAME,
    "PL06_HARVEST_BATCH1_MODEL_v1.json",
    "PL06_HARVEST_BATCH1_TRACEABILITY_v1.json",
    "PL06_HARVEST_BATCH1_TRACEABILITY_v1.md",
    "PL06_HARVEST_BATCH1_DECISION_INDEX_v1.json",
    "PL06_HARVEST_BATCH1_DECISION_INDEX_v1.md",
]

_LABEL = {p["code"]: p["label"] for p in B.PROVENANCE_CLASSES}


def _prov(code):
    return D.p(f"[{_LABEL[code]}]", role="provenance")


# ==========================================================================================
# THE BLOCK LIST
# ==========================================================================================
def blocks():
    out = []
    a, h, p, bl, fld, tbl, br = (out.append, D.h, D.p, D.bullet, D.field, D.table,
                                 D.pagebreak)

    # ---------- cover ----------
    a(h(0, DOC_TITLE_MS, role="cover_title"))
    a(p(DOC_SUBTITLE_MS, role="cover_subtitle"))
    a(p(" · ".join(B.BATCH_UNITS), role="cover_unit"))
    a(p(f"Kelompok {B.BATCH_ID} · Peringkat {B.STAGE} · Status {B.BATCH_STATUS}",
        role="cover_unit"))
    a(p("Pakej ini mencadangkan. Ia tidak meluluskan apa-apa. Setiap baris membawa label "
        "asalnya, dan setiap keputusan mempunyai ruang jawapan.", role="emphasis"))
    a(p(B.LANGUAGE_POLICY["statement_ms"]))
    a(br())

    # ---------- A. overview ----------
    a(h(1, "A. Gambaran keseluruhan kelompok"))
    a(_prov("SRC"))
    a(p("Empat unit PL06. Sempadan keempat-empatnya beku dan disahkan dengan cincangan "
        "SHA-256; kandungan keempat-empatnya belum diekstrak."))
    a(tbl(["Unit", "Topik", "Muka surat modul", "Perenggan", "Subtopik", "Skrin minimum",
           "Sempadan dikongsi"],
          [[u["unit_id"], u["display_title"],
            u["points"]["boundary"]["module_page_range"],
            u["points"]["boundary"]["paragraph_span"],
            len(u["points"]["mandatory_content"]["named_subtopics"]),
            u["points"]["screen_sequence"]["arithmetic"]["minimum_total_screens"],
            ("mula" if u["points"]["shared_page_risk"]["shared_start"] else "")
            + ("+akhir" if u["points"]["shared_page_risk"]["shared_end"] else "")
            or "tiada"]
           for u in B.units()],
          widths=[20, 18, 10, 8, 8, 9, 11]))

    a(h(2, "Apa yang pakej ini boleh dan tidak boleh tanya"))
    a(_prov("OPEN"))
    a(p("DOCX modul disimpan di luar repositori ini melalui identiti "
        f"({B.MODULE_DOCX_BYTES:,} bait, SHA-256 {B.MODULE_DOCX_SHA256[:16]}…). Tiada unit "
        "dalam kelompok ini mempunyai kandungan, visual atau sumber kuiz yang diekstrak."))
    a(tbl(["Syarat henti", "Keadaan", "Daftar"],
          [[s["stop_id"], s["condition"], s["register"]] for s in B.BLOCKING_STOPS],
          widths=[14, 46, 40]))
    a(p("Oleh itu setiap kad diisi sepenuhnya di mana bukti beku sampai — sempadan, risiko "
        "muka surat dikongsi, pengumpulan pada aras tajuk, aritmetik bilangan skrin, "
        "perbendaharaan rawatan, guna semula — dan merekodkan PENDING_EXTRACTION di mana "
        "ia tidak sampai. Tiada batang soalan kuiz, hasil pembelajaran atau subjek visual "
        "ditulis untuk unit yang teksnya belum dibaca sesiapa.", role="risk"))

    a(h(2, "Yang mesti dilihat sebelum apa-apa kelulusan"))
    for e in B.exposures():
        a(p(f"{e['exposure_id']} · {e['subject']}", role="item_label"))
        a(p(e["statement"]))
    a(br())

    # ---------- B. rules ----------
    a(h(1, "B. Peraturan seluruh kursus yang boleh diguna semula"))
    a(_prov("AUTO"))
    a(p("Digunakan tanpa bertanya, kerana peraturan ini seluruh kursus atau generik — bukan "
        "keputusan instruksi khusus T04."))
    a(tbl(["ID", "Peraturan", "Skop", "Bukti"],
          [[r["rule_id"], r["rule"], r["scope"], r["evidence"]] for r in B.AUTO_APPLIED_RULES],
          widths=[7, 34, 16, 43]))
    a(p("Amaran yang tidak digugurkan senyap:", role="item_label"))
    for r in B.AUTO_APPLIED_RULES:
        if r["caveat"] != "None." and r["caveat"] != "None":
            a(bl(f"{r['rule_id']} — {r['caveat']}"))
    a(p("Frasa yang tidak boleh muncul di hadapan pelajar: "
        + ", ".join(f"“{x}”" for x in B.BANNED_LEARNER_PHRASES) + " (AR-03)."))

    a(h(2, "Yang TIDAK diguna semula daripada T04"))
    a(_prov("BARIAH"))
    a(tbl(["ID", "Perkara T04", "Sebab", "Yang mudah alih"],
          [[n["item_id"], n["item"], n["reason"], n["what_is_portable"]] for n in B.NO_REUSE],
          widths=[7, 20, 38, 35]))
    a(br())

    # ---------- C to F. unit cards ----------
    for u in B.units():
        letter = B._section_letter(u["unit_id"])
        a(h(1, f"{letter}. Kad keputusan — {u['unit_id']}"))
        a(p(u["display_title"], role="emphasis"))
        out.extend(_card_blocks(u, letter))
        a(br())

    # ---------- G. cross-unit exceptions ----------
    a(h(1, "G. Pengecualian merentas unit"))
    for x in B.cross_unit_exceptions():
        a(p(f"{x['exception_id']} · {x['subject']}", role="item_label"))
        a(p("Unit: " + ", ".join(x["applies_to"])))
        a(p(x["statement"]))
    a(br())

    # ---------- H. decision sheet ----------
    a(h(1, "H. Helaian keputusan Bariah"))
    a(_prov("BARIAH"))
    a(p("Pilihan jawapan:", role="item_label"))
    for o in B.RESPONSE_OPTIONS:
        a(bl(f"{o['option']} — {o['meaning']}"
             + (f"  ({B.GABUNG_TARGET_FIELD}: WAJIB)" if o["requires_target_id"] else "")))
    dec = B.decisions()
    a(p(f"{len(dec)} keputusan diminta. Setiap satu mempunyai ruang jawapan di bawah.",
        role="emphasis"))
    for d in dec:
        a(p(f"{d['decision_id']} · {d['unit_display']} — {d['question']}", role="question"))
        a(_prov(d["provenance"]))
        if d.get("why"):
            a(p(d["why"]))
        a(fld("Pilihan: " + " / ".join(d["options"])
              + (f"     {B.GABUNG_TARGET_FIELD}: ______________"
                 if d["requires_target_id"] else "")))
        a(fld("Catatan: ______________________________________________________________"))
    return out


def _card_blocks(u, letter):
    out, pt = [], u["points"]
    a, p, bl, tbl, h = out.append, D.p, D.bullet, D.table, D.h

    def point(no, key, code):
        title = next(c["title"] for c in B.CARD_POINTS if c["no"] == no)
        a(h(2, f"{letter}.{key} — {no}. {title}"))
        a(_prov(code))

    b = pt["boundary"]
    point(1, "boundary", b["provenance"])
    a(tbl(["Medan", "Nilai"],
          [["Julat muka surat modul", f"{b['module_page_range']} ({b['module_pages']} m/s)"],
           ["Julat muka surat PDF", b["pdf_page_range"]],
           ["Sauh mula", b["start_anchor"]],
           ["Berhenti sebelum", b["end_before"]],
           ["Perenggan DOCX", f"{b['docx_para_start']} → sebelum {b['docx_para_end_before']}"
                              f" ({b['paragraph_span']} perenggan)"],
           ["Status peta", b["map_status"]],
           ["Imej sempadan", f"{b['boundary_image']} — {b['boundary_image_custody']}"]],
          widths=[26, 74]))

    s = pt["shared_page_risk"]
    point(2, "shared_page_risk", s["provenance"])
    a(p(s["note"]))
    a(p(s["risk"], role="risk" if (s["shared_start"] or s["shared_end"]) else None))

    c = pt["controlled_rows"]
    point(3, "controlled_rows", c["provenance"])
    a(p(f"Status: {c['status']} · bilangan baris: {c['row_count']} · "
        f"penghalang: {c['blocking_stop']}"))
    a(p(c["note"]))

    m = pt["mandatory_content"]
    point(4, "mandatory_content", m["provenance"])
    for x in m["named_subtopics"]:
        a(bl(x))
    a(p(m["note"]))

    g = pt["grouping"]
    point(5, "grouping", g["provenance"])
    a(tbl(["Kumpulan", "Merangkumi"], [[x["group_id"], x["covers"]] for x in g["proposal"]],
          widths=[18, 82]))
    a(p(g["note"]))

    q = pt["screen_sequence"]
    point(6, "screen_sequence", q["provenance"])
    for x in q["sequence"]:
        a(bl(x))
    ar = q["arithmetic"]
    a(p("Aritmetik bilangan skrin, dedah sepenuhnya:", role="item_label"))
    a(tbl(["Sebutan", "Nilai", "Asas"],
          [["Skrin rangka", ar["shell_screens"], ar["shell_basis"]],
           ["Skrin kandungan (lantai)", ar["content_screens_floor"], ar["floor_basis"]],
           ["Skrin kandungan (siling)", ar["content_screens_ceiling"],
            ar["why_no_single_number"]],
           ["Skrin penutup", ar["closing_screens"], "Rumusan, Kuiz, Tamat"],
           ["JUMLAH MINIMUM", ar["minimum_total_screens"], "jumlah tiga sebutan pertama"],
           ["JUMLAH MAKSIMUM", ar["maximum_total_screens"], "tidak diteka"]],
          widths=[24, 14, 62]))

    t = pt["treatment"]
    point(7, "treatment", t["provenance"])
    a(p(f"Cadangan: {t['proposal']} · keyakinan: {t['confidence']}"))
    a(p(t["reason"]))
    a(p("Perbendaharaan yang disokong: " + "; ".join(t["vocabulary"]) + " (AR-06)."))

    r = pt["runtime_states"]
    point(8, "runtime_states", "OPEN")
    a(tbl(["Ukuran", "Nilai"],
          [["Keadaan asas (lantai)", r["base_states_floor"]],
           ["Keadaan tercetus", r["triggered_states"]],
           ["Jumlah keadaan runtime", r["total_runtime_states"]]], widths=[40, 60]))
    a(p("Kaedah: " + r["method"]))
    a(p(r["why"]))

    d = pt["dialogue"]
    point(9, "dialogue", d["provenance"])
    a(p(f"Cadangan: {d['proposal']}"))
    a(p(d["reason"]))
    a(p(d["constraint"], role="risk"))

    ru = pt["rumusan"]
    point(10, "rumusan", ru["provenance"])
    a(p(ru["treatment"]))
    a(p(f"Bilangan beat: {ru['beat_count']} — {ru['note']}", role="risk"))

    qz = pt["quiz_stems"]
    point(11, "quiz_stems", qz["provenance"])
    a(p(qz["composition"]))
    a(tbl(["Slot", "Jenis", "Subtopik", "Batang soalan"],
          [[x["slot"], x["kind"], x["draws_from"], x["stem"]] for x in qz["slots"]],
          widths=[8, 22, 42, 28]))
    a(p(qz["note"], role="risk"))

    ak = pt["answer_keys"]
    point(12, "answer_keys", ak["provenance"])
    a(p(f"Status: {ak['status']} · kuasa: {ak['authority']} · "
        f"sokongan sumber: {ak['source_support']}"))
    a(p(ak["note"]))

    v = pt["visual_obligations"]
    point(13, "visual_obligations", v["provenance"])
    a(p(f"Bilangan: {v['count']} · status: {v['status']} · penghalang: {v['blocking_stop']}"))
    a(p(v["rule"]))
    a(p(v["note"], role="risk"))

    re = pt["reuse"]
    point(14, "reuse", re["provenance"])
    for x in re["candidates"]:
        a(bl(x))

    nr = pt["no_reuse"]
    point(15, "no_reuse", nr["provenance"])
    a(p("Pengecualian sejagat: " + ", ".join(nr["exceptions"]) + " (lihat bahagian B)."))
    a(p(nr["unit_specific"], role="risk"))

    oq = pt["open_questions"]
    point(16, "open_questions", oq["provenance"])
    for x in oq["items"]:
        a(bl(x))
    return out


# ==========================================================================================
# EMIT
# ==========================================================================================
def _w(name, text):
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1) + "\n")


def _tbl_md(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|") for c in r) + " |")
    return "\n".join(out)


def traceability():
    rows = []
    for u in B.units():
        b = u["points"]["boundary"]
        rows.append(dict(
            unit_id=u["unit_id"],
            claim="source boundary and page range",
            evidence="PL06_LESSON_BOUNDARY_MAP_v1.json",
            evidence_sha256=B.BOUNDARY_MAP_SHA256,
            evidence_class="FROZEN_HASH_VERIFIED",
            value=f"{b['module_page_range']} · {b['start_anchor']} → {b['end_before']}"))
        rows.append(dict(
            unit_id=u["unit_id"], claim="boundary page image",
            evidence=f"source-freeze/boundary_pages/{b['boundary_image']}.png",
            evidence_sha256=(_sha_of_image(b["boundary_image"])
                             if b["boundary_image"] in B.BOUNDARY_IMAGES_INGESTED else None),
            evidence_class=b["boundary_image_custody"],
            value=b["boundary_image"]))
        rows.append(dict(
            unit_id=u["unit_id"], claim="named subtopics",
            evidence="PL06_LESSON_BOUNDARY_MAP_v1.json · subtopics field",
            evidence_sha256=B.BOUNDARY_MAP_SHA256, evidence_class="FROZEN_HASH_VERIFIED",
            value="; ".join(u["points"]["mandatory_content"]["named_subtopics"])))
        for claim, key in (("controlled source rows", "controlled_rows"),
                           ("quiz stems", "quiz_stems"),
                           ("answer keys", "answer_keys"),
                           ("visual obligations", "visual_obligations")):
            rows.append(dict(
                unit_id=u["unit_id"], claim=claim,
                evidence="PL06_OPEN_AUTHORITY_ITEMS_v1 · "
                         + u["points"][key].get("blocking_stop", "STOP-004"),
                evidence_sha256=None, evidence_class="BLOCKED_NOT_EXTRACTED",
                value=B.NOT_EXTRACTED))
    for r in B.AUTO_APPLIED_RULES:
        rows.append(dict(unit_id="ALL", claim=f"auto-applied rule {r['rule_id']}",
                         evidence=r["evidence"], evidence_sha256=None,
                         evidence_class="COURSE_WIDE_RULE", value=r["rule"]))
    for n in B.NO_REUSE:
        rows.append(dict(unit_id="ALL", claim=f"no-reuse {n['item_id']}",
                         evidence=n["reason"], evidence_sha256=None,
                         evidence_class="EXPLICIT_NO_REUSE", value=n["item"]))
    return dict(stage=B.STAGE, batch_id=B.BATCH_ID, rows=rows,
                module_docx=dict(name=B.MODULE_DOCX_NAME, bytes=B.MODULE_DOCX_BYTES,
                                 sha256=B.MODULE_DOCX_SHA256,
                                 custody=B.MODULE_DOCX_CUSTODY,
                                 in_this_repository=B.MODULE_DOCX_IN_THIS_REPOSITORY),
                totals=dict(rows=len(rows),
                            frozen_hash_verified=len([r for r in rows if r["evidence_class"]
                                                      == "FROZEN_HASH_VERIFIED"]),
                            blocked_not_extracted=len([r for r in rows
                                                       if r["evidence_class"]
                                                       == "BLOCKED_NOT_EXTRACTED"])))


def _sha_of_image(stem):
    path = os.path.join(B.BOUNDARY_IMAGE_DIR, stem + ".png")
    if not os.path.exists(path):
        return None
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def emit_all():
    made = []
    blks = blocks()

    made.append(_w(MD_NAME, BANNER + "\n" + D.render_markdown(blks)))
    made.append(_j("PL06_HARVEST_BATCH1_MODEL_v1.json",
                   dict(stage=B.STAGE, lane=B.LANE, batch_id=B.BATCH_ID,
                        suite_id=B.SUITE_ID, status=B.BATCH_STATUS,
                        forbidden_status_claims=B.FORBIDDEN_STATUS_CLAIMS,
                        units=B.units(), sections=B.SECTIONS,
                        auto_applied_rules=B.AUTO_APPLIED_RULES, no_reuse=B.NO_REUSE,
                        provenance_classes=B.PROVENANCE_CLASSES,
                        response_options=B.RESPONSE_OPTIONS,
                        card_points=B.CARD_POINTS, exposures=B.exposures(),
                        cross_unit_exceptions=B.cross_unit_exceptions(),
                        blocking_stops=B.BLOCKING_STOPS)))

    tr = traceability()
    made.append(_j("PL06_HARVEST_BATCH1_TRACEABILITY_v1.json", tr))
    made.append(_w("PL06_HARVEST_BATCH1_TRACEABILITY_v1.md", "\n".join([
        BANNER, "", "# PL06 harvest batch 1 — source and authority traceability", "",
        "```",
        f"BATCH_ID              = {B.BATCH_ID}",
        f"ROWS                  = {tr['totals']['rows']}",
        f"FROZEN_HASH_VERIFIED  = {tr['totals']['frozen_hash_verified']}",
        f"BLOCKED_NOT_EXTRACTED = {tr['totals']['blocked_not_extracted']}",
        "```", "",
        "Every claim in the package points at an artifact. A claim that could point at "
        "nothing is recorded as blocked rather than dropped, which is why a third of these "
        "rows say NOT_EXTRACTED — the package is honest about its own holes.", "",
        _tbl_md(["Unit", "Claim", "Evidence", "Class", "Value"],
                [[r["unit_id"], r["claim"], r["evidence"], r["evidence_class"], r["value"]]
                 for r in tr["rows"]]), ""])))

    dec = B.decisions()
    made.append(_j("PL06_HARVEST_BATCH1_DECISION_INDEX_v1.json",
                   dict(stage=B.STAGE, batch_id=B.BATCH_ID, total=len(dec),
                        by_scope={s: len([d for d in dec if d["scope"] == s])
                                  for s in sorted({d["scope"] for d in dec})},
                        by_unit={u: len([d for d in dec if d["unit_id"] == u])
                                 for u in B.BATCH_UNITS},
                        gabung_decisions=[d["decision_id"] for d in dec
                                          if d["requires_target_id"]],
                        decisions=dec)))
    made.append(_w("PL06_HARVEST_BATCH1_DECISION_INDEX_v1.md", "\n".join([
        BANNER, "", "# PL06 harvest batch 1 — decision index", "",
        f"**{len(dec)} decisions requested.** Each one is bounded, numbered, and has a "
        "response location in the DOCX.", "",
        _tbl_md(["ID", "Scope", "Unit", "Point", "Options", "Target ID", "Answer at",
                 "Evidence at"],
                [[d["decision_id"], d["scope"], d["unit_id"] or "—", d["point_key"],
                  " / ".join(d["options"]),
                  "WAJIB" if d["requires_target_id"] else "—",
                  d["response_location"], d["card_reference"]] for d in dec]), ""])))

    docx = D.render_docx(blks, os.path.join(DOCX_DIR, DOCX_NAME),
                         f"{DOC_TITLE_MS} — {DOC_SUBTITLE_MS}")
    previews = D.render_preview(blks, PREVIEW_DIR, prefix="B1P")
    return dict(artifacts=made, docx=docx, docx_bytes=os.path.getsize(docx),
                previews=previews, blocks=len(blks))


if __name__ == "__main__":
    r = emit_all()
    for m in r["artifacts"]:
        print("emitted  :", m)
    print("docx     :", r["docx"], f"({r['docx_bytes']} bytes)")
    print("previews :", len(r["previews"]))
    print("blocks   :", r["blocks"])
