# -*- coding: utf-8 -*-
"""Stage 4.2F-C — emit the batch 1 extractions, provisional models and extraction QA.

    python3 docs/pl06/tools/pl06_batch1_model_emit_v1.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PL06 = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import pl06_extract_v1 as EX      # noqa: E402
import pl06_unit_model_v1 as UM   # noqa: E402

OUT = os.path.join(PL06, "batch1_extract")
BANNER = ("<!-- GENERATED by docs/pl06/tools/pl06_batch1_model_emit_v1.py — "
          f"Stage {UM.STAGE}. Edit the model, not this file. -->")


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def emit_all():
    os.makedirs(OUT, exist_ok=True)
    models, extracts = UM.all_models()
    made = []

    for uid, ex in extracts.items():
        p = os.path.join(OUT, f"{uid.replace('-', '_')}_SOURCE_EXTRACT_v1.json")
        with open(p, "w", encoding="utf-8") as f:
            json.dump(ex, f, ensure_ascii=False, indent=1)
            f.write("\n")
        made.append(os.path.basename(p))

    for uid, m in models.items():
        p = os.path.join(OUT, f"{uid.replace('-', '_')}_PROVISIONAL_MODEL_v1.json")
        with open(p, "w", encoding="utf-8") as f:
            json.dump(m, f, ensure_ascii=False, indent=1)
            f.write("\n")
        made.append(os.path.basename(p))

    leak = EX.leak_report(extracts)
    eq = EX.t04_equivalence()
    summary = dict(stage=UM.STAGE, authority=UM.AUTHORITY,
                   pending_pattern_package=UM.PENDING_PACKAGE,
                   classifications=UM.CLASSES, frozen_nothing=UM.FROZEN_NOTHING,
                   units=[dict(
                       unit_id=uid,
                       rows=extracts[uid]["totals"]["content_rows"],
                       module_pages=extracts[uid]["boundary"]["module_pages"],
                       shared_start=extracts[uid]["boundary"]["shared_start"],
                       shared_end=extracts[uid]["boundary"]["shared_end"],
                       groups=len(m["grouping"]["groups"]),
                       minimum_screens=m["screen_sequence"]["arithmetic"][
                           "minimum_total_screens"],
                       propositions=m["mandatory_propositions"]["count"],
                       quiz_items=len(m["assessment"]["items"]),
                       visual_subjects=m["visual_obligations"]["count"],
                       source_attested_visuals=m["visual_obligations"]["source_attested"],
                       dialogue=m["dialogue"]["verdict"],
                       ambiguities=m["ambiguity_register"]["count"],
                       missing_source=len(m["missing_source_register"]["items"]),
                       extraction_qa=m["extraction_qa"])
                       for uid, m in models.items()],
                   leak_report=leak, t04_equivalence=eq)
    p = os.path.join(OUT, "PL06_BATCH1_EXTRACTION_SUMMARY_v1.json")
    with open(p, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=1)
        f.write("\n")
    made.append(os.path.basename(p))

    # ---- Markdown ----
    md = [BANNER, "", "# PL06 batch 1 — controlled extraction and provisional models", "",
          "```",
          f"STAGE      = {UM.STAGE}",
          f"AUTHORITY  = {UM.AUTHORITY}",
          f"UNITS      = {len(models)}",
          f"PENDING    = {UM.PENDING_PACKAGE} (PENDING_BARIAH_REVIEW, not authority)",
          "```", "",
          "Nothing here is frozen: " + ", ".join(UM.FROZEN_NOTHING)
          + ". Every claim carries one of five classifications.", "",
          _tbl(["unit", "rows", "pages", "shared", "groups", "min screens", "props",
                "quiz", "visuals", "dialogue"],
               [[u["unit_id"], u["rows"],
                 f"{u['module_pages'][0]}–{u['module_pages'][1]}",
                 ("start" if u["shared_start"] else "")
                 + ("+end" if u["shared_end"] else "") or "clean",
                 u["groups"], u["minimum_screens"], u["propositions"], u["quiz_items"],
                 f"{u['visual_subjects']} ({u['source_attested_visuals']} attested)",
                 u["dialogue"]] for u in summary["units"]]), "",
          "## Boundary integrity", "",
          "Extraction never used a page range. Every unit was sliced between named heading "
          "anchors resolved in the binary, and the records left on each side are emitted by "
          "name so that 'nothing leaked' is a checkable claim.", "", "```",
          f"all units clean           = {str(leak['all_clean']).lower()}",
          f"T03-B03 last paragraph    = {leak['adjacency']['b03_last_included']}",
          f"T03-B04 first paragraph   = {leak['adjacency']['b04_first_included']}",
          f"contiguous, gap           = {str(leak['adjacency']['contiguous']).lower()}, "
          f"{leak['adjacency']['gap']}",
          "```", "", leak["adjacency"]["note"], "",
          _tbl(["unit", "shared", "span", "rows outside own span",
                "rows in another unit's span", "last record before", "first record after"],
               [[u["unit_id"],
                 ("start" if u["shared_start"] else "")
                 + ("+end" if u["shared_end"] else "") or "clean",
                 f"{u['span'][0]}–{u['span'][1]}",
                 len(u["paragraph_indices_outside_own_span"]),
                 len(u["rows_landing_in_another_units_span"]),
                 (u["first_excluded_before"] or "—")[:40],
                 (u["first_excluded_after"] or "—")[:40]]
                for u in leak["units"]]), "",
          "## The reader was checked against the reader it generalises", "", "```",
          f"ran               = {str(eq.get('ran')).lower()}",
          f"equivalent to T04 = {str(eq.get('equivalent')).lower()}",
          f"frozen rows       = {eq.get('frozen_row_count')}",
          f"this reader rows  = {eq.get('got_row_count')}",
          f"text mismatches   = {len(eq.get('text_mismatches', []))}",
          f"type mismatches   = {len(eq.get('type_mismatches', []))}",
          f"index mismatches  = {len(eq.get('paragraph_index_mismatches', []))}",
          "```", "", eq.get("note", ""), "",
          "## Page attribution", "",
          "The T04 extractor attributed pages by counting Word's cached "
          "`<w:lastRenderedPageBreak>`. On T04 that happened to land on the frozen range. On "
          "all four of these units it does not — it under-counts the last page of T03-B03, "
          "T03-B04 and T05-B01 by one and over-counts T06-B01 by one. Trusting it would have "
          "published a wrong page range for every unit in this batch while the frozen map "
          "was right all along.", "",
          "Page attribution now comes from the rendered PDF, which is hash-verified and "
          "prints its own module page number in the footer. The cached-layout number is still "
          "computed and still reported, as the weaker second opinion it always was.", "",
          _tbl(["unit", "cached layout", "typeset PDF", "frozen map", "cached agrees",
                "typeset agrees"],
               [[uid,
                 f"{extracts[uid]['page_attribution_divergence']['cached_layout_range'][0]}–"
                 f"{extracts[uid]['page_attribution_divergence']['cached_layout_range'][1]}",
                 f"{extracts[uid]['page_attribution_divergence']['typeset_range'][0]}–"
                 f"{extracts[uid]['page_attribution_divergence']['typeset_range'][1]}",
                 f"{extracts[uid]['page_attribution_divergence']['frozen_map_range'][0]}–"
                 f"{extracts[uid]['page_attribution_divergence']['frozen_map_range'][1]}",
                 "yes" if extracts[uid]["page_attribution_divergence"][
                     "cached_layout_agrees_with_frozen"] else "**no**",
                 "yes" if extracts[uid]["page_attribution_divergence"][
                     "typeset_agrees_with_frozen"] else "**no**"]
                for uid in extracts]), ""]

    for uid, m in models.items():
        ex = extracts[uid]
        a = m["screen_sequence"]["arithmetic"]
        md += [f"## {uid} — {m['lesson_title']}", "", "```",
               f"module pages        = {ex['boundary']['module_pages'][0]}–"
               f"{ex['boundary']['module_pages'][1]}",
               f"controlled rows     = {ex['totals']['content_rows']}",
               f"structural headings = {m['heading_tree']['structural_headings']}",
               f"prose styled as H3  = {m['prose_styled_as_heading']['count']}",
               f"tables / figures    = {ex['totals']['tables']} / "
               f"{ex['totals']['raster_images']}",
               f"minimum screens     = {a['minimum_total_screens']} "
               f"(shell {a['shell_screens']} + groups {a['content_groups']} + "
               f"closing {a['closing_screens']})",
               f"maximum screens     = {a['maximum_total_screens']}",
               f"dialogue            = {m['dialogue']['verdict']}",
               f"pattern candidates  = {m['pattern_family']['primary_candidate']} / "
               f"{m['pattern_family']['secondary_candidate']}",
               "```", "",
               "**Proposed grouping** (" + m["grouping"]["basis"] + "): "
               + ", ".join(g["covers"] for g in m["grouping"]["groups"]) + ".",
               ""]
        if m["grouping"]["override_declared"]:
            md += [f"> Grouping override declared — {m['grouping']['override_reason']}. "
                   f"The automatic detector found: "
                   f"{', '.join(m['grouping']['automatic_component_detection']) or 'nothing'}.",
                   ""]
        md += ["**Mandatory content propositions** — every one cites its rows.", "",
               _tbl(["proposition", "rows"],
                    [[p["proposition"], ", ".join(p["rows"])]
                     for p in m["mandatory_propositions"]["propositions"]]), "",
               "**Assessment** — "
               f"{m['assessment']['composition']}, key status "
               f"**{m['assessment']['key_status']}**, authority "
               f"{m['assessment']['key_authority']}.", "",
               _tbl(["slot", "kind", "stem", "correct response", "source rows"],
                    [[q["slot"], q["kind"], q["stem"],
                      "; ".join(q["correct"]) if isinstance(q["correct"], list)
                      else q["correct"], ", ".join(q["correct_rows"])]
                     for q in m["assessment"]["items"]]), "",
               "**Candidate visual subjects** — "
               f"{m['visual_obligations']['count']} proposed, "
               f"{m['visual_obligations']['source_attested']} with a figure actually in the "
               "source.", "",
               _tbl(["subject", "rows", "source figure"],
                    [[v["subject"], ", ".join(v["rows"]),
                      "yes" if v["has_source_figure"] else "no"]
                     for v in m["visual_obligations"]["subjects"]]), "",
               "**Compliance-sensitive statements**", "",
               _tbl(["statement", "why", "rows"],
                    [[c["statement"], c["why"], ", ".join(c["rows"])]
                     for c in m["compliance_sensitive"]["statements"]]), "",
               "**Ambiguity register**", ""]
        md += [f"- {x['item']} → `{x.get('resolution', '—')}`"
               for x in m["ambiguity_register"]["items"]]
        md += ["", "**Missing-source register**", ""]
        md += [f"- **{x['severity']}** — {x['item']} {x['consequence']}"
               for x in m["missing_source_register"]["items"]] or ["- none"]
        q = m["extraction_qa"]
        md += ["", "**Extraction QA**", "", "```",
               f"row ids unique               = {str(q['row_ids_unique']).lower()}",
               f"sequence contiguous          = {str(q['sequence_is_contiguous']).lower()}",
               f"pages monotonic              = {str(q['pages_monotonic']).lower()}",
               f"page range matches frozen    = "
               f"{str(q['page_range_matches_frozen']).lower()}",
               f"paragraphs inside own span   = "
               f"{str(q['paragraph_indices_inside_span']).lower()}",
               f"typeset-attributed rows      = {q['typeset_attributed_rows']}",
               f"carried-forward rows         = {q['carried_forward_rows']}",
               "```", ""]

    p = os.path.join(OUT, "PL06_BATCH1_EXTRACTION_AND_MODELS_v1.md")
    with open(p, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    made.append(os.path.basename(p))
    return made, summary


if __name__ == "__main__":
    made, s = emit_all()
    for m in made:
        print("emitted  :", m)
