# -*- coding: utf-8 -*-
"""Stage 4.2F-I — emit the 14 PL06 working packets and one consolidated exception report."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import pl06_packet_model_v1 as PM   # noqa: E402

BANNER = (f"<!-- GENERATED by {PM.GENERATED_BY} — Stage {PM.STAGE}. "
          "Edit the model, not this file. -->")


def _w(name, text):
    os.makedirs(PM.OUT_DIR, exist_ok=True)
    with open(os.path.join(PM.OUT_DIR, name), "w", encoding="utf-8") as f:
        f.write(text if text.endswith("\n") else text + "\n")
    return name


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def _packet_md(p):
    r, d, rm, q = p["roles"], p["dialogue"], p["rumusan"], p["quiz"]
    v, it, c = p["visual_direction"], p["interaction"], p["completion"]
    L = [BANNER, "", f"# {p['unit_id']} — {p['title']}", "",
         "```", f"STAGE            = {p['stage']}",
         f"TOPIK            = {p['topik']}   BAHAGIAN = {p['bahagian']}",
         f"GENERATION_SCOPE = {p['generation_scope']}",
         f"EVIDENCE_TIER    = {p['evidence_tier']}",
         f"STATUS           = {' · '.join(p['status_marks'])}", "```", "",
         "## Completion — schema is not copy", "",
         _tbl(["Metric", "State"], [(k, v_) for k, v_ in c.items()]), "",
         "## Declared subtopics", "",
         (p["subtopics"].get("declared") or "—"), "",
         "## Controlled source rows", "",
         _tbl(["Field", "Value"],
              [("rows", p["controlled_source_rows"]["count"]),
               ("structural headings", p["controlled_source_rows"]["structural_headings"]),
               ("range", f"{p['controlled_source_rows']['first_row']} … "
                         f"{p['controlled_source_rows']['last_row']}")]), "",
         "## Character role audit", "",
         f"Narrator: **{r['narrator']['name']}** (reused, {r['narrator']['authority']})"
         if r.get("narrator") else "Narrator: —", "",
         _tbl(["Role", "Needs to speak", "Family", "Classification", "Character", "Reason"],
              [(a_["role_id"], "yes" if a_["needs_to_speak"] else "no",
                a_["role_family"] or "—", a_["classification"],
                a_["reused_character"] or a_["name"] or "—", (a_["reason"] or "")[:90])
               for a_ in r["audit"]]) if r["audit"] else "No role markers in source.", "",
         "## Draft S02 scenario", "",
         f"`{d.get('status')}` · tension: `{d.get('tension_kind', '—')}`", ""]
    if d.get("turns"):
        L += [_tbl(["#", "Speaker", "Kind", "Text", "Rows"],
                   [(t["seq"], t["speaker"], t["kind"], t["text"],
                     ", ".join(t.get("rows") or [])) for t in d["turns"]]), ""]
    else:
        L += [f"`{d.get('status')}` — {d.get('reason', '')}", ""]
    L += ["## Draft Rumusan — exactly three internal beats", "",
          "Beat labels are production metadata and are **not learner-facing**. All declared "
          "subtopics sit INSIDE the scope beat; none becomes a beat of its own.", "",
          _tbl(["Beat", "Learner-facing label", "Subtopics", "Text"],
               [(b["beat"], "none", ", ".join(b.get("subtopics") or []) or "—",
                 b.get("text") or "—") for b in rm["beats"]]), "",
          f"## Quiz — {q.get('composition', '—')} · pass {q.get('pass_percent', '—')}%", "",
          f"drafted: {q.get('drafted', 0)} · anchored slots: {q.get('anchored', 0)}", ""]
    if q.get("items"):
        L += [_tbl(["Slot", "Kind", "State", "Stem", "Correct", "Key status", "Rows"],
                   [(i["slot"], i["kind"], i["state"], (i["stem"] or "—")[:60],
                     (i["correct"] or "—")[:60], i["key_status"],
                     ", ".join(i.get("correct_rows") or [])) for i in q["items"]]), ""]
    L += ["## Visual direction", "",
          f"subjects: {v.get('count', 0)} · source-attested: {v.get('source_attested', 0)}",
          ""]
    if v.get("subjects"):
        L += [_tbl(["Subject", "Rows", "Source figure"],
                   [(s_["subject"], ", ".join(s_["rows"]),
                     "yes" if s_["has_source_figure"] else "**no**")
                    for s_ in v["subjects"]]), ""]
    L += ["## Interaction treatment", "",
          _tbl(["Field", "Value"],
               [("primary", it.get("primary") or "—"),
                ("secondary", it.get("secondary") or "—"),
                ("repeated components", it.get("repeated_components", "—")),
                ("reason", it.get("reason", "—"))]), "",
          "## Analysis record — why these choices", "",
          _tbl(["Aspect", "Rationale"],
               [("dialogue tension", p["analysis"]["dialogue_tension"]),
                ("treatment", p["analysis"]["treatment"]),
                ("role mapping", p["analysis"]["role_mapping"])]), "",
          "## Production readiness", "",
          f"`production_ready = {p['production_ready']}`", "",
          _tbl(["Blocker"], [(b,) for b in p["production_blockers"]])
          if p["production_blockers"] else "No blockers.", ""]
    return "\n".join(L)


def _legacy_md(ls):
    L = [BANNER, "", "# PL06 — retained legacy artifacts", "",
         "These units are NOT regeneration targets. They are verified by artifact path and "
         "hash, never by production-packet refusal.", ""]
    for l in ls:
        L += [f"## {l['unit_id']} — {l['title']}", "",
              _tbl(["Field", "Value"],
                   [("generation_scope", l["generation_scope"]),
                    ("artifact_profile", l["artifact_profile"]),
                    ("named_exception", l["named_exception"] or "none"),
                    ("basis", l["basis"])]), "",
              _tbl(["Kind", "Path", "Bytes", "Slides", "SHA-256"],
                   [(a["kind"], a["path"], f"{a['bytes']:,}", a["slides"], a["sha256"])
                    for a in l["declared_artifacts"]]), ""]
    return "\n".join(L)


def emit_all():
    ps = PM.packets()
    ls = PM.legacy_entries()
    files = [_w("PL06_LEGACY_RETAINED_v0_1.md", _legacy_md(ls)),
             _w("PL06_LEGACY_RETAINED_v0_1.json",
                json.dumps(dict(stage=PM.STAGE, legacy=ls), ensure_ascii=False, indent=1))]
    for p in ps:
        stem = p["unit_id"].replace("-", "_")
        files.append(_w(f"PACKET_{stem}_v0_1.md", _packet_md(p)))
        files.append(_w(f"PACKET_{stem}_v0_1.json",
                        json.dumps(p, ensure_ascii=False, indent=1)))

    t = PM.totals()
    files.append(_w("PL06_PACKET_INDEX_v0_1.json",
                    json.dumps(dict(stage=PM.STAGE, totals=t,
                                    package_shape=PM.A.package_shape(),
                                    approved_cast=PM.A.approved_characters(),
                                    legacy=ls,
                                    units=[dict(unit_id=p["unit_id"], title=p["title"],
                                                tier=p["evidence_tier"],
                                                rows=p["controlled_source_rows"]["count"],
                                                completion=p["completion"],
                                                blockers=p["production_blockers"])
                                           for p in ps]),
                               ensure_ascii=False, indent=1)))

    # ---------------------------------------------------------- consolidated exceptions ----
    authoring, owner, bariah = [], [], []
    for p in ps:
        u = p["unit_id"]
        for i in p["quiz"].get("items", []):
            if i["state"] == "QUIZ_ANCHORED_SLOT":
                authoring.append((f"AUTH-QUIZ-{u}-{i['slot']}", u,
                                  f"Quiz {i['slot']} is an anchored slot: stem and options "
                                  f"must be written against {i.get('anchor_row')}."))
        if not p["completion"]["SOURCE_ANALYSIS_COMPLETE"]:
            authoring.append((f"AUTH-ANALYSIS-{u}", u,
                              "Rows extracted but no committed unit analysis; the drafted "
                              "copy is derived and needs an editorial pass."))
        if p["dialogue"].get("status") == PM.JUDGMENT:
            bariah.append((f"BARIAH-DIALOGUE-{u}", u,
                           "No defensible tension found in the controlled rows; a human "
                           "judgment call on whether a scenario is warranted."))
        if p["visual_direction"].get("source_attested", 0) == 0:
            owner.append((f"OWNER-VISUAL-{u}", u,
                          "No source-attested figure. RP-104 default is a lockable owner "
                          "decision unless Bariah wants each one reviewed."))
        for r in p["roles"]["new_required"]:
            bariah.append((f"BARIAH-ROLE-{u}-{r['role_id']}", u,
                           f"Genuinely new speaking role: {r['role_description']}"))
    owner.append(("OWNER-TREATMENT-DEFAULT", "ALL",
                  "Interaction treatment defaults were read from each module's own repeated "
                  "structure. Lockable by Firdaus for fast-track production."))
    bariah.append(("BARIAH-RETURN-DOC", "ALL",
                   "The returned K5_Pengesahan_ID_Watak_Dialog_Rumusan itself: every drafted "
                   "item is DRAFTED_NOT_APPROVED until it lands."))

    L = [BANNER, "", "# PL06 — reclassified exception report", "",
         "```", f"STAGE = {PM.STAGE}",
         f"AUTHORING_TODO         = {len(authoring)}",
         f"OWNER_DEFAULT_DECISION = {len(owner)}",
         f"BARIAH_EXCEPTION       = {len(bariah)}", "```", "",
         "Incomplete writing tasks are NOT sent to Bariah as instructional exceptions.", "",
         "## AUTHORING_TODO — CC / SME Cloud can complete without Bariah", "",
         _tbl(["ID", "Unit", "Detail"], authoring) if authoring else "None.", "",
         "## OWNER_DEFAULT_DECISION — Firdaus can lock for fast-track production", "",
         _tbl(["ID", "Unit", "Detail"], owner) if owner else "None.", "",
         "## BARIAH_EXCEPTION — genuinely needs her judgment", "",
         _tbl(["ID", "Unit", "Detail"], bariah) if bariah else "None.", "",
         "## Human-judgment checks — deliberately NOT automated", "",
         _tbl(["Check", "Why a gate cannot decide it"],
              [(c["check"], c["why"]) for c in HUMAN_JUDGMENT]), ""]
    files.append(_w("PL06_EXCEPTION_REPORT_v0_1.md", "\n".join(L)))
    return files


HUMAN_JUDGMENT = [
    dict(check="Does the S02 scenario carry meaningful tension?",
         why="A gate can confirm a question mark and a source-backed answer. It cannot "
             "judge whether the problem is one a contractor would actually face."),
    dict(check="Does the dialogue read as natural Malay speech?",
         why="Register, idiom and rhythm are editorial judgments; no assertion available "
             "here distinguishes fluent dialogue from stilted dialogue."),
    dict(check="Is the visual direction right for this topic?",
         why="RP-104 can be checked (a direction must come from a source figure). Whether "
             "the resulting image teaches the point is a design judgment."),
    dict(check="Are the quiz distractors plausible but wrong?",
         why="A gate can check counts, kinds and row citations. Plausibility is subject "
             "expertise."),
    dict(check="Is the chosen interaction treatment the best one?",
         why="The packet proposes a treatment from the module's repeated structure. "
             "Whether a different pattern teaches better is Bariah's call."),
]


if __name__ == "__main__":
    for f in emit_all():
        print("emitted", f)
