# -*- coding: utf-8 -*-
"""Stage 4.2F-B0.9.1 — emit the custody, exchange-reading, AG-audit and predicate artifacts."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import t04_supplementary_evidence_v1 as S   # noqa: E402
import t04_predicate_audit_v1 as P          # noqa: E402
import t04_ooxml_v1 as X                    # noqa: E402

OUT = os.path.abspath(os.path.join(HERE, ".."))
BANNER = (f"<!-- GENERATED by {S.GENERATED_BY} — Stage {S.STAGE}. "
          "Edit the data module, not this file. -->")


def _w(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text if text.endswith("\n") else text + "\n")
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1))


def _hdr(title, extra=()):
    return "\n".join([BANNER, "", f"# {title}", "", "```",
                      f"STAGE      = {S.STAGE}",
                      f"SUITE_ID   = {S.SUITE_ID}",
                      f"PART_A     = {S.PART_A_RESULT}"] + list(extra) + ["```", ""])


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


# ==========================================================================================
def emit_custody():
    a = _j("T04_SUPPLEMENTARY_EVIDENCE_CUSTODY_v1.json",
           dict(stage=S.STAGE, generated_by=S.GENERATED_BY,
                custody_outcome=S.CUSTODY_OUTCOME,
                intended_custody_path=S.INTENDED_CUSTODY_PATH,
                search_locations=S.SEARCH_LOCATIONS,
                custody_fields=S.CUSTODY_FIELDS,
                timestamp_classes=S.TIMESTAMP_CLASSES,
                blocker=S.PART_A_BLOCKER,
                release_record_not_issued=S.RELEASE_RECORD_NOT_ISSUED))

    p = [_hdr("T04 — SUPPLEMENTARY SCREENSHOT CUSTODY",
              [f"CUSTODY_OUTCOME = {S.CUSTODY_OUTCOME}",
               f"CUSTODY_PATH    = NOT_CREATED"]),
         "The screenshot reached this run as a rendered image in the conversation. It is not "
         "a file. Every field below that can only be measured from a binary is recorded as "
         "unavailable — not estimated, not reconstructed, not inferred from the conversation "
         "label.", "",
         "# 1. Where the file was looked for", "",
         _tbl(["Location", "Result", "Note"],
              [(x["location"], x["result"], x["note"]) for x in S.SEARCH_LOCATIONS]), "",
         "# 2. Custody fields", "",
         _tbl(["Field", "Value", "Why"],
              [(x["field"], f"`{x['value']}`", x["why"]) for x in S.CUSTODY_FIELDS]), "",
         f"The intended custody path was `{S.INTENDED_CUSTODY_PATH}`. It was **not created**. "
         "Writing a placeholder there would put a file in the evidence directory that is not "
         "the evidence.", "",
         "# 3. Three kinds of timestamp, kept apart", "",
         "Only one of these exists, and it is the weakest of the three as file evidence.", ""]
    for t in S.TIMESTAMP_CLASSES:
        p += [f"**{t['timestamp_class']}** — "
              + ("available" if t["available"] else "**not available**"), "",
              f"- values: {t['values']}",
              f"- basis: {t['basis'] or '—'}",
              f"- {t['note']}", ""]

    b = S.PART_A_BLOCKER
    p += ["# 4. Blocker", "",
          _tbl(["Field", "Value"], [
              ("id", b["blocker_id"]), ("subject", b["subject"]),
              ("required", b["required"]), ("observed", b["observed"]),
              ("owner", b["owner"]),
          ]), "",
          f"**Consequence.** {b['consequence']}", "",
          f"**What would unblock it.** {b['what_would_unblock']}", "",
          "# 5. The release record that was not issued", "",
          _tbl(["Field", "Value"], [
              ("would-be verdict", S.RELEASE_RECORD_NOT_ISSUED["would_be_verdict"]),
              ("issued", "**no**"),
              ("why not", S.RELEASE_RECORD_NOT_ISSUED["why_not_issued"]),
              ("prior record still standing",
               S.RELEASE_RECORD_NOT_ISSUED["prior_release_record_stands"]),
          ]), ""]
    return [a, _w("T04_SUPPLEMENTARY_EVIDENCE_CUSTODY_v1.md", "\n".join(p))]


# ==========================================================================================
def emit_reading():
    a = _j("T04_AUTHORITY_EXCHANGE_READING_v1.json",
           dict(stage=S.STAGE, generated_by=S.GENERATED_BY,
                reading_method=S.READING_METHOD,
                evidence_class=S.EVIDENCE_CLASS,
                blocked_evidence_class=S.BLOCKED_EVIDENCE_CLASS,
                confirmation_modes=S.CONFIRMATION_MODES,
                messages=S.MESSAGES,
                attribution_corrections=S.ATTRIBUTION_CORRECTIONS,
                confirmation_id_mapping=S.CONFIRMATION_ID_MAPPING,
                confirmation_readings=S.CONFIRMATION_READINGS,
                q5_divergence=S.Q5_DIVERGENCE,
                new_open_items=S.NEW_OPEN_ITEMS))

    m = S.READING_METHOD
    p = [_hdr("T04 — AUTHORITY EXCHANGE READING",
              [f"METHOD         = {m['method']}",
               f"OCR_USED       = {m['ocr_used']}",
               f"EVIDENCE_CLASS = {S.EVIDENCE_CLASS}",
               f"MESSAGES_READ  = {len(S.MESSAGES)}"]),
         "The exchange was read by looking at the rendered image. OCR was not used, and no "
         "prior transcript was treated as sufficient on its own — which matters, because the "
         "transcript-only reading in the previous stage got a speaker wrong.", "",
         f"**Speaker attribution.** {m['speaker_attribution_basis']}", "",
         "**Limitations of this reading.**", ""]
    p += [f"- {x}" for x in m["limitations"]]

    p += ["", "# 1. Every visible message", "",
          _tbl(["#", "Time", "Sender", "Direction", "Content"],
               [(x["position"], x["time_shown"], f"**{x['sender']}**", x["direction"],
                 " / ".join(x["verbatim_fragments"])[:180]) for x in S.MESSAGES]), ""]
    for x in S.MESSAGES:
        p += [f"## {x['msg_id']} — {x['sender']}, {x['time_shown']}", "",
              f"*{x['bubble']}*", "", x["summary"], ""]
        p += [f"> {f}" for f in x["verbatim_fragments"]]
        p += [""]

    p += ["# 2. Corrections this reading forces", ""]
    for c in S.ATTRIBUTION_CORRECTIONS:
        p += [f"## {c['correction_id']} — {c['subject']}", "",
              _tbl(["Field", "Value"], [
                  ("recorded in", c["recorded_in_stage"]),
                  ("recorded as", c["recorded_as"]),
                  ("actually", c["actually"]),
                  ("severity", c["severity"]),
                  ("status", c["status"]),
              ]), "",
              f"**Basis.** {c['basis']}", "",
              f"**Consequence.** {c['consequence']}", ""]

    mp = S.CONFIRMATION_ID_MAPPING
    p += ["# 3. Confirmation ID re-scoping — proposed, not applied", "",
          f"Status `{mp['status']}`, blocked by `{mp['blocked_by']}`. The stage brief "
          "re-scopes these three IDs onto different subjects from the ones already committed "
          "under them. Renumbering live governance records while the premise for the "
          "renumbering is blocked would be worse than the collision, so nothing is "
          "renumbered and the mapping is published instead.", "",
          _tbl(["Proposed ID", "Proposed subject", "B0.9 ID", "B0.9 subject", "Relationship"],
               [(r["proposed_id"] or "— none —", r["proposed_subject"] or "—",
                 r["b09_id"], r["b09_subject"], r["relationship"]) for r in mp["rows"]]), "",
          "# 4. What the exchange confirms, and at what precision", ""]

    for r in S.CONFIRMATION_READINGS:
        p += [f"## {r['confirmation_id']} — {r['subject']}", "",
              f"**Put by {r['proposition_put_by']}** ({r['proposition_msg']}):", "",
              f"> {r['proposition_verbatim']}", "",
              f"**Authority response** ({r['authority_response_msg']}):", "",
              f"> {r['authority_response_verbatim']}", "",
              _tbl(["Field", "Value"], [
                  ("confirmation mode", r["confirmation_mode"]),
                  ("status if custody had passed",
                   f"`{r['would_be_status_if_custody_passed']}`"),
                  ("**actual status**", f"**`{r['actual_status']}`**"),
                  ("evidence class", f"`{r['evidence_class']}`"),
                  ("upgrade blocked by", r["upgrade_blocked_by"]),
              ]), "",
              f"**Not claimed.** {r['not_claimed']}", ""]
        if r.get("does_not_confirm"):
            p += ["**This does not by itself confirm:**", ""]
            p += [f"- {x}" for x in r["does_not_confirm"]]
            p += [""]
        if r.get("mutability"):
            p += [f"**Mutability.** {r['mutability']}", ""]

    d = S.Q5_DIVERGENCE
    p += ["# 5. A divergence the screenshot exposes", "",
          f"## {d['finding_id']} — {d['subject']}", "",
          f"Severity `{d['severity']}`.", "",
          "**Stems**", "",
          _tbl(["Where", "Stem"],
               [("put to the authority in WhatsApp", d["stem_put_to_authority"]),
                ("frozen in the content model", d["stem_in_frozen_model"])]), "",
          f"The frozen stem's source is {d['stem_source_of_frozen_model']} — Bariah's own "
          "written replacement. Firdaus's WhatsApp wording is different.", "",
          "**Options**", "",
          _tbl(["#", "Put to the authority", "Frozen in the model", "Same?"],
               [(i + 1, a_, b_, "yes" if a_ == b_ else "**NO**")
                for i, (a_, b_) in enumerate(zip(d["options_put_to_authority"],
                                                 d["options_in_frozen_model"]))]), "",
          f"**What this means.** {d['what_this_means']}", "",
          f"**Why it is not resolved here.** {d['why_it_is_not_resolved_here']}", "",
          _tbl(["Field", "Value"], [
              ("frozen model changed", "no" if d["frozen_model_unchanged"] else "yes"),
              ("resolution required from", d["resolution_required_from"]),
              ("tracked as", d["tracked_as"]),
              ("blocks storyboard layout",
               "no" if not d["blocking_storyboard_layout"] else "yes"),
              ("blocks a scored quiz", "yes" if d["blocking_scored_quiz"] else "no"),
          ]), "",
          "# 6. New open items", "",
          _tbl(["ID", "Subject", "Owner", "Raised by"],
               [(o["open_id"], o["subject"], o["owner"], o["raised_by"])
                for o in S.NEW_OPEN_ITEMS]), ""]
    return [a, _w("T04_AUTHORITY_EXCHANGE_READING_v1.md", "\n".join(p))]


# ==========================================================================================
def emit_ag_audit():
    rows = S.ag_register_audit()
    a = _j("T04_AG_REGISTER_AUDIT_v1.json",
           dict(stage=S.STAGE, generated_by=S.GENERATED_BY,
                set_status=S.AG_SET_STATUS,
                authority_basis=S.AG_AUTHORITY_BASIS,
                individual_card_status=S.AG_INDIVIDUAL_CARD_STATUS,
                forbidden_representations=S.AG_FORBIDDEN_REPRESENTATIONS,
                distinction_layers=S.AG_DISTINCTION_LAYERS,
                section_level_narrative_contents=S.SECTION_LEVEL_NARRATIVE_CONTENTS,
                no_reuse_closed=S.NO_REUSE_CLOSED,
                no_reuse_decision_basis=S.NO_REUSE_DECISION_BASIS,
                no_reuse_evidence_precision=S.NO_REUSE_EVIDENCE_PRECISION,
                no_reuse_not_claimed=S.NO_REUSE_NOT_CLAIMED,
                groups=rows))

    p = [_hdr("T04 — AG-01 … AG-08 REGISTER AUDIT",
              [f"SET_STATUS       = {S.AG_SET_STATUS}",
               f"AUTHORITY_BASIS  = {S.AG_AUTHORITY_BASIS}",
               f"INDIVIDUAL_CARDS = {S.AG_INDIVIDUAL_CARD_STATUS}",
               f"GROUPS           = {len(rows)}"]),
         "The authority DOCX contains eight per-group decision cards and **every one of them "
         "is blank**. Its Section B narrative nevertheless accepts conditional sharing across "
         "AG-01 to AG-08 as a set and accepts the 46 → 41 calculation. Both facts are true at "
         "once, and the register has to hold both without collapsing them.", "",
         "# 1. Four layers, kept apart", "",
         _tbl(["Layer", "What", "Value", "Basis"],
              [(x["layer"], x["name"], f"`{x['value']}`", x["basis"])
               for x in S.AG_DISTINCTION_LAYERS]), ""]
    for x in S.AG_DISTINCTION_LAYERS:
        p += [f"**{x['layer']}. {x['name']}** — source: {x['source']}"]
        if x["quote"]:
            p += ["", f"> {x['quote']}"]
        p += [""]

    p += ["# 2. How the groups must NOT be represented", ""]
    p += [f"- not as {x}" for x in S.AG_FORBIDDEN_REPRESENTATIONS]
    p += ["", "Each of those three is a different way of losing information. *Eight "
          "individual acceptances* invents ticks that are not on the page. *Eight unanswered "
          "decisions* discards a set-level acceptance she did write. *Eight pending-human "
          "blockers* would stall a build over a question the authority has already answered.",
          "", "# 3. The register as committed", "",
          _tbl(["Group", "Label", "Set status", "Card", "Reuse in register",
                "Item restrictions", "Whole-group?"],
               [(g["asset_group_id"], g["label"], g["set_level_status"],
                 g["individual_card_status"], g["reuse_decision_in_register"],
                 ", ".join(g["item_level_restrictions"]) or "none",
                 "yes" if g["restriction_applies_to_whole_group"] else "no")
                for g in rows]), "",
          "# 4. What the section-level narrative actually says", ""]
    p += [f"- {x}" for x in S.SECTION_LEVEL_NARRATIVE_CONTENTS]
    p += ["", "# 5. The three no-reuse decisions remain closed", "",
          _tbl(["Obligation", "Item", "Group", "Decision basis", "Evidence precision"],
               [(x["obligation_id"], x["label"], x["asset_group_id"],
                 S.NO_REUSE_DECISION_BASIS, S.NO_REUSE_EVIDENCE_PRECISION)
                for x in S.NO_REUSE_CLOSED]), "",
          f"**Not claimed.** {S.NO_REUSE_NOT_CLAIMED}", ""]
    return [a, _w("T04_AG_REGISTER_AUDIT_v1.md", "\n".join(p))]


# ==========================================================================================
def emit_predicate_and_xml():
    audit = P.summary()
    proofs = X.proofs()
    a = _j("T04_PREDICATE_AND_XML_AUDIT_v1.json",
           dict(stage=S.STAGE, generated_by=S.GENERATED_BY,
                predicate_audit=audit, xml_proofs=proofs))

    p = [_hdr("T04 — FILTERED-POPULATION AND XML ELEMENT AUDIT",
              [f"CLOSED_POPULATIONS   = {audit['closed_populations']}",
               f"EXCLUDED_POPULATIONS = {audit['excluded_populations']}",
               f"FAILING              = {audit['failing'] or 'none'}",
               f"XML_PROOF_CASES      = {len(proofs)}"]),
         "# 1. Why this audit exists", "",
         "Fixture `C-05` got past the Stage 4.2F-B0.9 suite. A gate selected its population "
         "by a mutable property and then checked that property — so when the mutation made a "
         "record leave the population, the gate saw a smaller, still-correct population and "
         "passed. **A filter cannot observe its own departures.**", "",
         "Every gate whose population is selected by a mutable property now carries three "
         "assertions rather than one: the property check, a named-membership assertion, and a "
         "population-count delta.", "",
         "# 2. Closed populations", "",
         _tbl(["ID", "Selector", "Mutable property", "Expected", "Observed", "+", "−",
               "Guarded by"],
              [(r["population_id"], f"`{r['selector']}`", r["mutable_property"],
                r["expected_count"], r["observed_count"],
                len(r["unexpected_additions"]), len(r["unexpected_removals"]),
                ", ".join(r["guarded_by"])) for r in audit["rows"]]), "",
         "Named members, in full:", ""]
    for r in audit["rows"]:
        p += [f"- **{r['population_id']}** `{r['selector']}` → "
              + ", ".join(r["observed_members"])
              + (f"  (origin fixture {r['origin_fixture']})")]

    p += ["", "# 3. Documented exclusions", "",
          "Naming members is only meaningful for a population whose membership is itself a "
          "governed fact. For open-ended populations a named list would have to be edited on "
          "every unrelated change, which trains the reader to ignore it. These five are "
          "excluded on purpose, each with the delta guard that covers it instead.", "",
          _tbl(["ID", "Selector", "Used by", "Why excluded", "Delta guard"],
               [(x["exclusion_id"], x["selector"], ", ".join(x["used_by"]), x["why"],
                 x["delta_guard"]) for x in audit["exclusions"]]), "",
          "# 4. XML element identity", "",
          "Substring matching on OOXML is wrong in a way that reads as right. `<w:insideH>` "
          "starts with `<w:ins`; `<w:tcPr>` starts with `<w:t`. The first of those nearly "
          "produced a false claim that the authority document contained twelve tracked "
          "insertions. Element checks now match namespace plus local name exactly.", "",
          _tbl(["Case", "Kind", "What it proves", "Exact match", "Naive substring",
                "Naive would have been wrong"],
               [(c["case_id"], c["kind"], c["description"], c["exact_match_count"],
                 c["naive_substring_count"],
                 "yes" if c["naive_would_have_been_wrong"] else "n/a — positive control")
                for c in proofs]), "",
          "`XML-04` is a positive control: it exists so the helper cannot pass by returning "
          "zero for everything.", ""]
    return [a, _w("T04_PREDICATE_AND_XML_AUDIT_v1.md", "\n".join(p))]


def emit_all():
    files = []
    for fn in (emit_custody, emit_reading, emit_ag_audit, emit_predicate_and_xml):
        files += fn()
    return files


if __name__ == "__main__":
    for n in emit_all():
        print(n)
