# -*- coding: utf-8 -*-
"""Stage 4.2F-B0.9 — emit every authority-ingestion artifact from one data source.

Every string in every emitted file is projected from t04_authority_data_v1. Nothing is typed
here that does not exist as a record there, so a claim cannot appear in a Markdown file
without also existing in the controlled model.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import t04_authority_data_v1 as D   # noqa: E402

OUT = os.path.abspath(os.path.join(HERE, ".."))
BANNER = (f"<!-- GENERATED by {D.GENERATED_BY} — Stage {D.STAGE}. "
          "Edit the data module, not this file. -->")


def _w(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text if text.endswith("\n") else text + "\n")
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1))


def _hdr(title, extra=()):
    lines = [BANNER, "", f"# {title}", "", "```",
             f"STAGE                = {D.STAGE}",
             f"SUITE_ID             = {D.SUITE_ID}",
             f"INTERNAL_UNIT_ID     = {D.INTERNAL_UNIT_ID}",
             f"LEARNER_DISPLAY_UNIT = {D.LEARNER_DISPLAY_UNIT} — "
             f"{D.LEARNER_DISPLAY_UNIT_TITLE}",
             f"INSTRUCTIONAL_AUTHORITY = BARIAH_AHMAD"]
    lines += list(extra) + ["```", ""]
    return "\n".join(lines)


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def _q(s):
    return f"“{s}”" if s else "—"


# ==========================================================================================
# PART 1 — EVIDENCE REGISTER
# ==========================================================================================
def emit_evidence():
    obj = dict(
        stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
        evidence_classes=D.EVIDENCE_CLASSES,
        evidence_dir=D.EVIDENCE_DIR,
        records=D.EVIDENCE,
        primary_artifact_mechanism=D.PRIMARY_ARTIFACT_MECHANISM,
        unit_label_ruling=D.UNIT_LABEL_RULING)
    a = _j("T04_AUTHORITY_EVIDENCE_REGISTER_v1.json", obj)

    p = [_hdr("T04 — AUTHORITY EVIDENCE REGISTER",
              [f"EVIDENCE_RECORDS     = {len(D.EVIDENCE)}",
               f"PRIMARY_SHA256       = {D.PRIMARY_DOCX_SHA256}",
               f"PRIMARY_BYTES        = {D.PRIMARY_DOCX_BYTES}"]),
         "The hierarchy runs top to bottom. Anything lower may only restate what something "
         "higher decided.", ""]

    p.append(_tbl(["Level", "Evidence", "ID", "Supplied to this run", "SHA-256"],
                  [(r["evidence_class"], r["filename"], r["evidence_id"],
                    "yes" if r["supplied_in_this_run"] else "**NO**",
                    r["sha256"]) for r in D.EVIDENCE]))
    p.append("")

    for r in D.EVIDENCE:
        p += [f"## {r['evidence_id']} — {r['evidence_class']}", "",
              _tbl(["Field", "Value"], [
                  ("filename", r["filename"]),
                  ("frozen path", r["frozen_path"] or "—"),
                  ("supplied in this run", "yes" if r["supplied_in_this_run"] else "NO"),
                  ("byte size", r["byte_size"]),
                  ("SHA-256", r["sha256"]),
                  ("extent", r["dimensions_or_extent"]),
                  ("authority", r["authority"]),
                  ("authored with", r["authored_with"]),
                  ("date recorded", r["date_authority_recorded"]),
                  ("scope", r["scope"]),
              ]), "",
              f"**Authority wording.** {_q(r['authority_quote'])}", "",
              f"**Interpretation.** {r['interpretation']}", "",
              f"**Limitations.** {r['limitations']}", "",
              f"**Provenance.** {r['provenance_chain']}", ""]

    m = D.PRIMARY_ARTIFACT_MECHANISM
    p += ["## How the authority recorded her decisions", "",
          _tbl(["Check", "Observed"], [
              ("tracked changes present", str(m["tracked_changes_present"])),
              ("tracked change elements", str(m["tracked_change_element_count"])),
              ("Word comments present", str(m["word_comments_present"])),
              ("Word comments", str(m["word_comment_count"])),
              ("comments part in package", str(m["comments_part_present"])),
              ("decision mechanism", m["decision_mechanism"]),
          ]), "",
          m["note"], "",
          f"*Counting note.* {m['counting_trap']}", "",
          "## Unit labelling ruling", "",
          _tbl(["Field", "Value"], [
              ("ruling", D.UNIT_LABEL_RULING["ruling_id"]),
              ("internal unit ID", D.UNIT_LABEL_RULING["internal_unit_id"]),
              ("learner display unit", D.UNIT_LABEL_RULING["learner_display_unit"]),
              ("scope", D.UNIT_LABEL_RULING["scope"]),
          ]), "",
          f"**Authority wording.** {_q(D.UNIT_LABEL_RULING['authority_quote'])}", "",
          D.UNIT_LABEL_RULING["interpretation"], ""]

    b = _w("T04_AUTHORITY_EVIDENCE_REGISTER_v1.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 2 — CONFIRMATIONS
# ==========================================================================================
def emit_confirmations():
    a = _j("T04_AUTHORITY_CONFIRMATIONS_v1.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                statuses=D.CONFIRMATION_STATUSES, records=D.CONFIRMATIONS))

    p = [_hdr("T04 — WHATSAPP AUTHORITY CONFIRMATIONS",
              [f"CONFIRMATION_RECORDS = {len(D.CONFIRMATIONS)}",
               "SUPPLEMENTARY_IMAGE  = NOT_SUPPLIED_TO_THIS_RUN",
               "EVIDENCE_GRADE       = DEGRADED_TRANSCRIBED_NOT_IMAGE_VERIFIED"]),
         "The WhatsApp screenshot itself was not supplied to this run. Its byte size, "
         "SHA-256, pixel dimensions and visible timestamps are recorded as `NOT_SUPPLIED` "
         "and are not estimated. What follows rests on wording transcribed into the stage "
         "brief, which is a weaker evidence grade than the DOCX and is labelled as such.", ""]

    p.append(_tbl(["ID", "Quoted wording", "Status", "Changes content?"],
                  [(c["confirmation_id"], _q(c["authority_quote"]), c["status"],
                    "yes" if c["applied_to_content"] else "no")
                   for c in D.CONFIRMATIONS]))
    p.append("")

    for c in D.CONFIRMATIONS:
        p += [f"## {c['confirmation_id']} — {c['subject']}", "",
              f"**Authority wording.** {_q(c['authority_quote'])}", "",
              _tbl(["Field", "Value"], [
                  ("evidence", c["evidence_id"]),
                  ("status", c["status"]),
                  ("evidence grade", c["evidence_grade"]),
                  ("applied to content", "yes" if c["applied_to_content"] else "no"),
                  ("blocking", "yes" if c["blocking"] else "no"),
              ]), "",
              f"**Interpretation.** {c['interpretation']}", "",
              f"**What this does not establish.** {c['what_this_does_not_establish']}", ""]
        if c.get("ambiguous_label_as_written"):
            p += ["**The label is not used as an identifier.** "
                  f"Bariah wrote *{c['ambiguous_label_as_written']}*. That string is recorded "
                  "as written and is not used as a decision ID. "
                  + c["why_the_raw_label_is_not_an_id"], "",
                  "Candidate referents, neither selected:", ""]
            p += [f"- {x}" for x in c["candidate_referents"]]
            p += ["", f"**Resolution required from.** {c['resolution_required_from']}", ""]

    b = _w("T04_AUTHORITY_CONFIRMATIONS_v1.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 3 — DECISION REGISTER
# ==========================================================================================
def emit_decisions():
    reg = D._decision_register()
    a = _j("T04_AUTHORITY_DECISION_REGISTER_v1.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                decision_classes=D.DECISION_CLASSES,
                decision_class_meaning=D.DECISION_CLASS_MEANING,
                decisions_by_class=D.decisions_by_class(),
                course_wide_decisions=D.course_wide_decisions(),
                unsettled_decisions=D.unsettled_decisions(),
                authority_wording_corrections=D.AUTHORITY_WORDING_CORRECTIONS,
                supersessions=D.SUPERSESSIONS,
                records=reg))

    by_class = D.decisions_by_class()
    p = [_hdr("T04 — AUTHORITY DECISION REGISTER",
              [f"DECISION_RECORDS = {len(reg)}",
               f"DECISION_CLASSES = {len(D.DECISION_CLASSES)}",
               f"COURSE_WIDE      = {len(D.course_wide_decisions())}",
               f"UNSETTLED        = {len(D.unsettled_decisions())}"]),
         "Every decision is typed. A single `ACCEPTED` bucket would erase the difference "
         "between wording Bariah wrote herself and wording CAIR chose after she asked for a "
         "change — those are different decisions and they carry different weight downstream.",
         "", "# 1. Decision classes", "",
         _tbl(["Class", "Count", "What it means"],
              [(c, len(by_class[c]), D.DECISION_CLASS_MEANING[c])
               for c in D.DECISION_CLASSES]), "",
         "# 2. Every decision", "",
         _tbl(["ID", "Class", "Subject", "Applies to", "Scope", "Source"],
              [(d["decision_id"], d["decision_class"], d["subject"],
                ", ".join(d["applies_to"]), d["scope"], d["source_artifact"])
               for d in reg]), "",
         "# 3. Quoted authority wording, per decision", ""]

    for d in reg:
        p += [f"**{d['decision_id']}** — {d['subject']}", "",
              f"> {d['authority_quote']}", "",
              f"*Effect.* {d['effect']}", "",
              f"*Source.* {d['source_artifact']} §{d['source_section']} · evidence grade "
              f"{d['evidence_grade']} · authored by the authority: "
              f"{'yes' if d['authored_by_authority'] else 'no'}", ""]

    p += ["# 4. Course-wide decisions", "",
          "Two decisions state their own scope as the whole Kursus. They are recorded as "
          "course-wide because Bariah wrote *Global keseluruhan kursus*, not because their "
          "subject looks general.", "",
          _tbl(["ID", "Subject", "Scope"],
               [(d["decision_id"], d["subject"], d["scope"]) for d in reg
                if d["scope"] == "ALL_PLS_IN_KURSUS"]), "",
          "# 5. Wording corrections — applied, never silent", ""]

    for c in D.AUTHORITY_WORDING_CORRECTIONS:
        p += [f"## {c['correction_id']} — {c['field']}", "",
              _tbl(["Field", "Value"], [
                  ("decision", c["decision_id"]),
                  ("as written by the authority", c["as_written_by_authority"]),
                  ("as applied", c["as_applied"]),
                  ("correction type", c["correction_type"]),
                  ("confidence", c["confidence"]),
                  ("status", c["status"]),
                  ("reversible", "yes" if c["reversible"] else "no"),
              ]), "",
              f"**Basis.** {c['basis']}", "",
              f"**If this is wrong.** {c['what_happens_if_wrong']}", "",
              f"**Confirmation required from.** {c['confirmation_required_from']}", ""]

    p += ["# 6. Prior rulings this stage supersedes", ""]
    for s in D.SUPERSESSIONS:
        p += [f"## {s['supersession_id']}", "",
              _tbl(["Field", "Value"], [
                  ("superseded ruling", s["superseded_ruling"]),
                  ("first made in stage", s["superseded_in_stage"]),
                  ("superseded by", s["superseded_by"]),
                  ("new position", s["new_position"]),
                  ("risk owner", s["risk_owner"]),
              ]), "",
              f"**Authority wording.** {_q(s['authority_quote'])}", "",
              f"**Residual risk.** {s['residual_risk']}", ""]

    p += ["# 7. Not settled", "",
          _tbl(["ID", "Subject", "Why it is open"],
               [(d["decision_id"], d["subject"], d["effect"]) for d in reg
                if not d["settled"]]), ""]

    b = _w("T04_AUTHORITY_DECISION_REGISTER_v1.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 4 — FINAL SCREEN SEQUENCE v2
# ==========================================================================================
def emit_sequence():
    seq = D._final_sequence()
    a = _j("T04_FINAL_SCREEN_SEQUENCE_v2.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                internal_unit_id=D.INTERNAL_UNIT_ID,
                learner_display_unit=D.LEARNER_DISPLAY_UNIT,
                learner_display_unit_title=D.LEARNER_DISPLAY_UNIT_TITLE,
                unit_label_ruling=D.UNIT_LABEL_RULING,
                final_screen_count=D.final_screen_count(),
                superseded_screen_count=D.SUPERSEDED_SCREEN_COUNT,
                inserted_screens=D.inserted_screens(),
                renumbering_map=D.renumbering_map(),
                superseded_closing_label=D.SUPERSEDED_CLOSING_LABEL,
                final_closing_label=D.FINAL_CLOSING_LABEL,
                change_types=D.CHANGE_TYPES,
                named_reveal_items=D.NAMED_REVEAL_ITEMS,
                named_aspect_lists=D.NAMED_ASPECT_LISTS,
                authority_wording_corrections=D.AUTHORITY_WORDING_CORRECTIONS,
                supersessions=D.SUPERSESSIONS,
                screens=seq))

    p = [_hdr("T04 — FINAL SCREEN SEQUENCE v2",
              [f"FINAL_SCREEN_COUNT      = {D.final_screen_count()}",
               f"SUPERSEDED_SCREEN_COUNT = {D.SUPERSEDED_SCREEN_COUNT}",
               f"INSERTED                = {', '.join(D.inserted_screens())}",
               f"RENUMBERED              = {len(D.renumbering_map())}",
               f"CLOSING_LABEL           = {D.FINAL_CLOSING_LABEL}"]),
         "# 1. Unit identity", "",
         _tbl(["Field", "Value", "Why"], [
             ("INTERNAL_UNIT_ID", D.INTERNAL_UNIT_ID,
              "repository and build identifier — unchanged"),
             ("LEARNER_DISPLAY_UNIT", D.LEARNER_DISPLAY_UNIT,
              "what the learner is shown — Bariah ruled T04 has no Bahagian"),
         ]), "",
         f"> {D.UNIT_LABEL_RULING['authority_quote']}", "",
         D.UNIT_LABEL_RULING["interpretation"], "",
         "# 2. The sequence", "",
         _tbl(["#", "Screen", "Title", "Treatment", "Change", "Was", "Decisions"],
              [(s["position"], s["screen_id"], s["working_title"], s["treatment"],
                s["change_type"], s["previous_screen_id"] or "— new —",
                ", ".join(s["decision_ids"])) for s in seq]), "",
         "# 3. The insertion", "",
         "Bariah added one screen. Everything from the former T04-S14 onward shifts by one.",
         "",
         _tbl(["Was", "Now"],
              [(k, v) for k, v in sorted(D.renumbering_map().items())]), "",
         "# 4. Wording correction on the inserted screen", ""]

    for c in D.AUTHORITY_WORDING_CORRECTIONS:
        p += [_tbl(["Field", "Value"], [
                  ("correction", c["correction_id"]),
                  ("as written", c["as_written_by_authority"]),
                  ("as applied", c["as_applied"]),
                  ("status", c["status"]),
              ]), "", f"**Basis.** {c['basis']}", "",
              f"**If this is wrong.** {c['what_happens_if_wrong']}", ""]

    p += ["# 5. Treatment changes", "",
          _tbl(["Screen", "Was", "Now", "Authority instruction"],
               [(s["screen_id"], s["previous_treatment"] or "—", s["treatment"],
                 s["authority_note"]) for s in seq
                if "TREATMENT_CHANGED" in s["change_type"]]), "",
          "# 6. Named reveal items", "",
          "Bariah named the reveal items on two screens. They are held as data, not prose, so "
          "the sequence and the build read the same list.", ""]
    for sid, items in sorted(D.NAMED_REVEAL_ITEMS.items()):
        p += [f"- **{sid}** — " + " · ".join(items)]
    p += ["", "# 7. Aspect lists added to the three main-explanation screens", ""]
    for sid, items in sorted(D.NAMED_ASPECT_LISTS.items()):
        p += [f"- **{sid}** — " + " · ".join(items)]

    p += ["", "# 8. Superseded rulings", ""]
    for s in D.SUPERSESSIONS:
        p += [f"**{s['supersession_id']}** — {s['superseded_ruling']} "
              f"(stage {s['superseded_in_stage']}) is superseded by {s['superseded_by']}.", "",
              f"*New position.* {s['new_position']}", "",
              f"*Residual risk.* {s['residual_risk']}", ""]

    p += ["# 9. Every screen", ""]
    for s in seq:
        p += [f"## {s['screen_id']} — {s['working_title']}", "",
              _tbl(["Field", "Value"], [
                  ("position", s["position"]),
                  ("previously", s["previous_screen_id"] or "— did not exist —"),
                  ("treatment", s["treatment"]),
                  ("previous treatment", s["previous_treatment"] or "—"),
                  ("change", s["change_type"]),
                  ("interaction states", ", ".join(s["interaction_states"])),
                  ("named reveal items",
                   ", ".join(s["named_reveal_items"]) if s["named_reveal_items"] else "—"),
                  ("aspect list",
                   ", ".join(s["named_aspect_list"]) if s["named_aspect_list"] else "—"),
                  ("source rows",
                   ", ".join(s["source_row_ids"]) if s["source_row_ids"]
                   else "none — structural screen"),
                  ("decisions", ", ".join(s["decision_ids"])),
                  ("status", s["content_status"]),
              ]), "", s["authority_note"], ""]

    b = _w("T04_FINAL_SCREEN_SEQUENCE_v2.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 5 — FINAL DIALOGUE
# ==========================================================================================
def emit_dialogue():
    a = _j("T04_FINAL_DIALOGUE_v1.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                boundary_rules=D.DIALOGUE_BOUNDARY_RULES,
                dialogue=D.FINAL_DIALOGUE))

    d = D.FINAL_DIALOGUE
    p = [_hdr("T04 — FINAL SLIDE 2 DIALOGUE",
              [f"SCREEN        = {d['screen_id']}",
               f"LINE_COUNT    = {d['line_count']}",
               f"SUPERSEDED    = {d['superseded_line_count']} lines",
               f"AUTHORSHIP    = {d['authorship']}"]),
         "Bariah wrote these four lines herself. They are carried verbatim — CAIR did not "
         "edit, tighten or re-punctuate them.", "",
         "# 1. The dialogue", "",
         _tbl(["ID", "Speaker", "Line"],
              [(x["line_id"], x["speaker"], x["text_ms"]) for x in d["lines"]]), "",
         "# 2. Cast", "",
         _tbl(["Character", "Decision"],
              [(c, d["cast_decision_id"]) for c in d["characters"]]), "",
         "# 3. What the authority's critique asked for, and where it landed", ""]
    p += [f"- {x}" for x in d["authority_critique_addressed"]]
    p += ["", "# 4. Banned framing", "",
          f"> {d['banned_framing']['authority_quote']}", "",
          f"{d['banned_framing']['rule']} ({d['banned_framing']['decision_id']})", "",
          "# 5. Compliance boundary — still binding", "",
          "The Stage 4.2F-B0.6 exclusions were not lifted. The replacement dialogue is "
          "checked against each of them rather than assumed to comply.", ""]
    p += [f"- no {x} in character dialogue" for x in D.DIALOGUE_BOUNDARY_RULES]
    p += [""]
    b = _w("T04_FINAL_DIALOGUE_v1.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 6 — FINAL RUMUSAN
# ==========================================================================================
def emit_rumusan():
    a = _j("T04_FINAL_RUMUSAN_v1.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                rumusan=D.FINAL_RUMUSAN,
                archived_dependencies=D.ARCHIVED_DEPENDENCIES))

    r = D.FINAL_RUMUSAN
    p = [_hdr("T04 — FINAL RUMUSAN",
              [f"SCREEN      = {r['screen_id']}",
               f"STRUCTURE   = {r['structure']}",
               f"POINT_COUNT = {r['point_count']}",
               f"SUPERSEDED  = {r['superseded_point_count']} points",
               f"AUTHORSHIP  = {r['authorship']}"]),
         "Bariah wrote these three beats herself. They are carried verbatim.", "",
         "# 1. The Rumusan", "",
         _tbl(["ID", "Beat", "Text"],
              [(x["point_id"], x["beat"], x["text_ms"]) for x in r["points"]]), "",
         "# 2. What the critique asked for", ""]
    p += [f"- {x}" for x in r["authority_critique_addressed"]]

    s = r["scope_of_the_three_beat_structure"]
    p += ["", "# 3. Scope of the three-beat structure", "",
          _tbl(["Field", "Value"], [("applies to", s["applies_to"])]), "",
          s["why"], "",
          f"**What would extend it.** {s['what_would_be_needed']}", "",
          "# 4. Archived dependency", ""]
    for dep in D.ARCHIVED_DEPENDENCIES:
        p += [f"## {dep['dependency_id']} — {dep['status']}", "",
              f"*Raised in stage {dep['raised_in_stage']}:* {dep['original_statement']}", "",
              _tbl(["Field", "Value"], [
                  ("status", dep["status"]),
                  ("resolved by", ", ".join(dep["resolved_by"])),
              ]), "",
              f"**How it resolved.** {dep['how_resolved']}", "",
              f"**Residual.** {dep['residual']}", "",
              f"**Reopens if.** {dep['reopens_if']}", ""]
    b = _w("T04_FINAL_RUMUSAN_v1.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 7 — COURSE-WIDE QUIZ RULES
# ==========================================================================================
def emit_globals():
    a = _j("T04_QUIZ_GLOBAL_RULES_v1.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                rules=D.QUIZ_GLOBAL_RULES))

    p = [_hdr("KURSUS — GLOBAL QUIZ RULES ISSUED FROM T04",
              [f"RULES = {len(D.QUIZ_GLOBAL_RULES)}",
               "SCOPE = ALL_PLS_IN_KURSUS"]),
         "Bariah issued both of these while reviewing T04 and marked both *Global "
         "keseluruhan kursus*. They are recorded as course-wide because she said so — not "
         "because the subject looks general. Only their T04 application is executed here; no "
         "other unit is modified by this stage.", ""]

    for r in D.QUIZ_GLOBAL_RULES:
        p += [f"## {r['rule_id']} — {r['title_en']}", "",
              f"*{r['title_ms']}*", "",
              f"> {r['authority_quote']}", "",
              _tbl(["Field", "Value"], [
                  ("decision", r["decision_id"]),
                  ("scope", r["scope"]),
                  ("source", r["source_artifact"]),
                  ("applies beyond T04", "yes" if r["applies_beyond_t04"] else "no"),
                  ("applied to T04 items", ", ".join(r["applied_to_t04_items"])),
                  ("status", r["status"]),
              ]), "",
              f"**Rule.** {r['rule']}", ""]
        if r.get("banned_phrases"):
            p += ["**Banned phrasing.** " + ", ".join(f"`{x}`" for x in r["banned_phrases"]),
                  ""]
        if r.get("required_option_marker"):
            p += [f"**Required option marker.** {r['required_option_marker']} · "
                  f"**banned pattern** `{r['banned_option_marker_pattern']}`", ""]
        p += [f"**Enforcement.** {r['enforcement']}", ""]

    b = _w("T04_QUIZ_GLOBAL_RULES_v1.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 8 — FINAL QUIZ v2
# ==========================================================================================
def emit_quiz():
    a = _j("T04_FINAL_QUIZ_v2.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                global_rules=D.QUIZ_GLOBAL_RULES, quiz=D.FINAL_QUIZ))

    q = D.FINAL_QUIZ
    p = [_hdr("T04 — FINAL QUIZ v2",
              [f"SCREEN            = {q['screen_id']}",
               f"COMPOSITION       = {q['composition']}",
               f"PASS_MARK         = {q['pass_mark']}",
               f"SCOPE             = {q['scope']}",
               f"ANSWER_KEY_STATUS = {q['answer_key_status']}"]),
         "All five stems are Bariah's own replacement wording, carried verbatim. The Q5 "
         "option set is not: Bariah instructed that two options change and CAIR wrote the "
         "replacements, so they are marked pending her confirmation. No answer key is final.",
         "", "# 1. Items", ""]

    for it in q["items"]:
        marker = "checkbox" if it["option_marker_style"] == "CHECKBOX" else "letter"
        p += [f"## {it['question_id']} ({it['question_type']})", "",
              f"**{it['stem_ms']}**", "",
              _tbl(["Option", "Text", "Proposed key"],
                   [(("☐" if it["option_marker_style"] == "CHECKBOX"
                      else o["letter_label"] + "."),
                     o["text_ms"], "✓" if o["proposed_key"] else "")
                    for o in it["options"]]), "",
              _tbl(["Field", "Value"], [
                  ("stem authorship", it["stem_authorship"]),
                  ("stem decision", it["stem_decision_id"]),
                  ("options authorship", it["options_authorship"]),
                  ("option marker", marker),
                  ("answer key", it["answer_key_status"]),
                  ("global rules applied", ", ".join(it["global_rules_applied"])),
                  ("source rows", f"{len(it['source_row_ids'])} controlled rows"),
              ]), "",
              f"*Superseded stem.* {it['superseded_stem_ms']}", ""]

    p += ["# 2. Q5 option substitutions", "",
          "Bariah ordered options 5 and 6 changed because both were about fertiliser and "
          "therefore gave themselves away.", ""]
    for s in q["q5_option_substitutions"]:
        p += [_tbl(["Field", "Value"], [
                  ("position", f"{s['position']} (was labelled {s['previous_letter']})"),
                  ("superseded text", s["superseded_text"]),
                  ("replacement text", s["replacement_text"]),
                  ("authorship", s["authorship"]),
                  ("approval", s["approval_status"]),
              ]), "",
              f"*Why it was superseded.* {s['why_superseded']}", "",
              f"*Why the replacement works.* {s['why_the_replacement_works']}", ""]

    rc = q["q5_route_choice"]
    p += ["# 3. Which route was taken, and who chose", "",
          f"> {rc['authority_quote']}", "",
          _tbl(["Field", "Value"], [
              ("route taken", rc["route_taken"]),
              ("route not taken", rc["route_not_taken"]),
              ("chosen by", rc["chosen_by"]),
              ("approval", rc["approval_status"]),
          ]), "", rc["why"], "",
          "# 4. Answer key", "",
          f"`{q['answer_key_status']}` — {q['answer_key_status_reason']}", ""]

    b = _w("T04_FINAL_QUIZ_v2.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 9 — FINAL VISUAL SCOPE
# ==========================================================================================
def emit_visual_scope():
    a = _j("T04_FINAL_VISUAL_SCOPE_v1.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                decision_basis_values=D.DECISION_BASIS_VALUES,
                identifier_corrections=D.IDENTIFIER_CORRECTIONS,
                visual_scope=D.FINAL_VISUAL_SCOPE))

    v = D.FINAL_VISUAL_SCOPE
    p = [_hdr("T04 — FINAL VISUAL SCOPE",
              [f"GOVERNANCE_ID          = {v['governance_id']}",
               f"STATUS                 = {v['status']}",
               f"VISUAL_OBLIGATIONS     = {v['visual_obligation_count']}",
               f"ASSET_GROUPS           = {v['asset_group_count']}",
               f"PROPOSED_UNIQUE_ASSETS = {v['proposed_unique_assets']}",
               f"DO_NOT_REUSE_ITEMS     = {v['do_not_reuse_count']}"]),
         "# 1. What was accepted", "",
         f"> {v['accepted_production_scope_quote']}", "",
         v["obligations_are_not_assets"], "",
         "Bariah reviewed this section through two lenses and separated them explicitly.", "",
         _tbl(["Lens", "Verdict"],
              [("INSTRUCTIONAL",
                "Coverage sufficient; every operation has visual support."),
               ("MULTIMEDIA_PRODUCTION",
                "Conditional sharing reasonable; 46→41 accepted as production scope.")]), "",
         "# 2. Precedence when the two lenses conflict", "",
         f"> {v['precedence_rule']['authority_quote']}", "",
         f"**{v['precedence_rule']['rule_id']}** — {v['precedence_rule']['rule']} "
         f"Binding on {v['precedence_rule']['binding_on']}.", "",
         "# 3. Items that may not be reused", "",
         "Bariah confirmed all three and asked that each carry a decision-basis line. All "
         "three are `BOTH_INSTRUCTIONAL_AND_PRODUCTION` — she gave both grounds in the same "
         "comment.", "",
         _tbl(["Item", "Group", "Decision basis", "Why the visuals differ"],
              [(x["label"], x["asset_group_id"], x["decision_basis"], x["visual_difference"])
               for x in v["do_not_reuse_items"]]), ""]

    for x in v["do_not_reuse_items"]:
        p += [f"**{x['label']}** ({x['obligation_id']}, {x['asset_group_id']}) — "
              f"`{x['restriction']}`, scope `{x['restriction_scope']}`", "",
              f"- *Instructional ground.* {x['instructional_ground']}",
              f"- *Production ground.* {x['production_ground']}",
              f"- *Basis recorded as.* {x['decision_basis']} "
              f"(required by {x['decision_basis_requirement_decision']}, "
              f"confirmed by {x['decision_basis_source_decision']})", ""]

    p += ["# 4. Asset groups", "",
          "The restriction applies to the named item, never to the whole group.", "",
          _tbl(["Group", "Label", "Assets", "Screens", "Reuse", "Item restrictions"],
               [(g["asset_group_id"], g["label"], g["proposed_unique_assets"],
                 ", ".join(g["affected_screens"]), g["reuse_decision"],
                 ", ".join(g["item_level_restriction_labels"]) or "none")
                for g in v["asset_groups"]]), "",
          "# 5. The inserted screen adds no asset", ""]
    n = v["new_screen_asset_impact"]
    p += [_tbl(["Field", "Value"], [
              ("screen", n["screen_id"]),
              ("new unique assets", n["new_unique_assets"]),
              ("obligation", n["obligation_id"]),
              ("closure outcome changed",
               "no" if n["obligation_closure_outcome_unchanged"] else "yes"),
          ]), "", n["why"], "",
          "# 6. What is not approved", "", v["what_is_not_approved"], "",
          "# 7. Identifier corrections", ""]
    for c in D.IDENTIFIER_CORRECTIONS:
        p += [f"## {c['correction_id']} — {c['field']}", "",
              _tbl(["Field", "Value"], [
                  ("as recorded", c["as_recorded"]),
                  ("as corrected", c["as_corrected"]),
                  ("introduced in", c["introduced_in_stage"]),
                  ("found in", c["found_in_stage"]),
                  ("authority wording changed", "no"),
                  ("status", c["status"]),
              ]), "",
              f"**Basis.** {c['basis']}", "",
              f"**What it would have broken.** {c['what_it_would_have_broken']}", "",
              f"**How it was found.** {c['detection']}", "",
              f"**Recurrence.** {c['recurrence_note']}", ""]

    b = _w("T04_FINAL_VISUAL_SCOPE_v1.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 10 — SOURCE STATUS
# ==========================================================================================
def emit_source_status():
    a = _j("T04_SOURCE_STATUS_v1.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                status=D.SOURCE_STATUS, risk_token=D.SOURCE_RISK_TOKEN,
                detail=D.SOURCE_STATUS_DETAIL))

    d = D.SOURCE_STATUS_DETAIL
    p = [_hdr("T04 — SOURCE STATUS",
              [f"CONTROLLED_EXTRACT_SOURCE_BINDINGS     = "
               f"{D.SOURCE_STATUS['CONTROLLED_EXTRACT_SOURCE_BINDINGS']}",
               f"ORIGINAL_DOCX_ROUND_TRIP_REPRODUCIBILITY = "
               f"{D.SOURCE_STATUS['ORIGINAL_DOCX_ROUND_TRIP_REPRODUCIBILITY']}",
               f"SOURCE_DOCX_RETRIEVAL_AND_HASH_PROOF   = "
               f"{D.SOURCE_STATUS['SOURCE_DOCX_RETRIEVAL_AND_HASH_PROOF']}",
               f"RISK_TOKEN = {D.SOURCE_RISK_TOKEN}"]),
         "# 1. Bindings are present", "", d["bindings_present_evidence"], "",
         "# 2. What is open", "", d["what_is_open"], "",
         "# 3. Why it does not block the storyboard build", "", d["why_non_blocking"], "",
         f"**What would close it.** {d['what_would_close_it']}", "",
         "# 4. What this must not be recorded as", "",
         f"`{d['must_not_be_recorded_as']}` — {d['why_not']}", "",
         _tbl(["Field", "Value"],
              [("risk owner", d["risk_owner"]),
               ("blocking", "yes" if d["blocking"] else "no")]), ""]

    b = _w("T04_SOURCE_STATUS_v1.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 11 — FINAL CONTENT MODEL
# ==========================================================================================
def emit_final_model():
    states = D.final_states()
    a = _j("T04_FINAL_CONTENT_MODEL_v1.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                internal_unit_id=D.INTERNAL_UNIT_ID,
                learner_display_unit=D.LEARNER_DISPLAY_UNIT,
                final_state_values=D.FINAL_STATE_VALUES,
                final_states=states,
                course_wide_state=D.COURSE_WIDE_STATE,
                screens=D._final_sequence(),
                dialogue=D.FINAL_DIALOGUE,
                rumusan=D.FINAL_RUMUSAN,
                quiz=D.FINAL_QUIZ,
                quiz_global_rules=D.QUIZ_GLOBAL_RULES,
                visual_scope=D.FINAL_VISUAL_SCOPE,
                source_status=D.SOURCE_STATUS,
                source_risk_token=D.SOURCE_RISK_TOKEN,
                open_after_this_stage=D.OPEN_AFTER_THIS_STAGE,
                production_guards=dict(
                    pptx_generated=D.PPTX_GENERATED,
                    generator_touched=D.GENERATOR_TOUCHED,
                    mmd_production_started=D.MMD_PRODUCTION_STARTED,
                    react_or_scorm_started=D.REACT_OR_SCORM_STARTED,
                    authority_artifacts_modified=D.AUTHORITY_ARTIFACTS_MODIFIED)))

    p = [_hdr("T04 — FINAL CONTENT MODEL",
              [f"FINAL_STATES  = {len(states)} + 1 course-wide",
               f"SCREENS       = {D.final_screen_count()}",
               f"DIALOGUE      = {D.FINAL_DIALOGUE['line_count']} lines",
               f"RUMUSAN       = {D.FINAL_RUMUSAN['point_count']} beats",
               f"QUIZ          = {D.FINAL_QUIZ['item_count']} items",
               f"SETTLED       = {len([s for s in states if s['settled']])}/{len(states)}"]),
         "This is the build input. Each content class carries its own final state, because "
         "*frozen* and *approved* are not the same thing: two of these classes are frozen "
         "without being settled, and a third is settled while carrying an open risk.", "",
         "# 1. Final states", "",
         _tbl(["ID", "Content class", "Final state", "Settled", "Decisions"],
              [(s["state_id"], s["content_class"], s["final_state"],
                "yes" if s["settled"] else "**no**", ", ".join(s["decision_ids"]) or "—")
               for s in states]
              + [(D.COURSE_WIDE_STATE["state_id"], D.COURSE_WIDE_STATE["content_class"],
                  D.COURSE_WIDE_STATE["final_state"], "yes",
                  ", ".join(D.COURSE_WIDE_STATE["decision_ids"]))]), ""]

    for s in states:
        p += [f"- **{s['state_id']} {s['content_class']}** — {s['note']}"]
    p += [f"- **{D.COURSE_WIDE_STATE['state_id']} "
          f"{D.COURSE_WIDE_STATE['content_class']}** — {D.COURSE_WIDE_STATE['note']}", ""]

    p += ["# 2. Still open after this stage", "",
          _tbl(["ID", "Subject", "Owner", "Why"],
               [(o["open_id"], o["subject"], o["owner"], o["why_open"])
                for o in D.OPEN_AFTER_THIS_STAGE]), "",
          "# 3. Production guards", "",
          _tbl(["Guard", "Count"], [
              ("PPTX generated", D.PPTX_GENERATED),
              ("production generator touched", D.GENERATOR_TOUCHED),
              ("MMD production started", D.MMD_PRODUCTION_STARTED),
              ("React or SCORM started", D.REACT_OR_SCORM_STARTED),
              ("authority artifacts modified", D.AUTHORITY_ARTIFACTS_MODIFIED),
          ]), "",
          "# 4. Labels that must not be applied", "",
          D.FORBIDDEN_LABEL_DECLARATION, "",
          ", ".join(f"`{x}`" for x in D.FORBIDDEN_LABELS), ""]

    b = _w("T04_FINAL_CONTENT_MODEL_v1.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
# PART 12 — RECONCILIATION
# ==========================================================================================
def emit_reconciliation():
    a = _j("T04_AUTHORITY_RECONCILIATION_v1.json",
           dict(stage=D.STAGE, suite_id=D.SUITE_ID, generated_by=D.GENERATED_BY,
                superseded_facts=D.SUPERSEDED_FACTS,
                superseded_artifacts=D.SUPERSEDED_ARTIFACTS,
                new_artifacts=D.NEW_ARTIFACTS))

    p = [_hdr("T04 — CROSS-ARTIFACT RECONCILIATION",
              [f"SUPERSEDED_FACTS     = {len(D.SUPERSEDED_FACTS)}",
               f"SUPERSEDED_ARTIFACTS = {len(D.SUPERSEDED_ARTIFACTS)}",
               f"NEW_ARTIFACTS        = {len(D.NEW_ARTIFACTS)}"]),
         "Earlier artifacts are not rewritten — they record what was true when they were "
         "written. What matters is that nothing downstream reads a stale file as current, so "
         "every stale fact is named, and every artifact carrying one points at its "
         "replacement.", "",
         "# 1. Facts that are now false", "",
         _tbl(["ID", "No longer true", "Now", "Decision"],
              [(f["fact_id"], f["stale_claim"], f["now"], f["decision_id"])
               for f in D.SUPERSEDED_FACTS]), "",
         "# 2. Superseded artifacts", "",
         _tbl(["Artifact", "Superseded by", "Stale facts"],
              [(s["path"], s["superseded_by"], ", ".join(s["stale_facts"]))
               for s in D.SUPERSEDED_ARTIFACTS]), "",
         "# 3. Artifacts emitted by this stage", "",
         "Each of these is scanned for every stale fact above. A stale string may appear only "
         "inside an explicit supersession record — never as a current claim.", ""]
    p += [f"- `{n}`" for n in D.NEW_ARTIFACTS]
    p += [""]
    b = _w("T04_AUTHORITY_RECONCILIATION_v1.md", "\n".join(p))
    return [a, b]


# ==========================================================================================
def emit_all():
    files = []
    for fn in (emit_evidence, emit_confirmations, emit_decisions, emit_sequence,
               emit_dialogue, emit_rumusan, emit_globals, emit_quiz, emit_visual_scope,
               emit_source_status, emit_final_model, emit_reconciliation):
        files += fn()
    return files


if __name__ == "__main__":
    out = emit_all()
    for n in out:
        print(n)
    print(f"{len(out)} files")
