# -*- coding: utf-8 -*-
"""Stage 4.2F-B0.8A QA — the governed Bariah review artifact.

    SUITE_ID = T04_BARIAH_REVIEW_ARTIFACT_QA_v1
    python3 docs/pl06/t04/tools/t04_review_artifact_qa_v1.py

This suite is SEPARATE from T04_CONTENT_QA_v1 and its gate count must never be merged with
that suite's 138. Different suites govern different artifacts.

Harness rules carried forward: every gate declares the population it examined, and a
population of 0 fails unless the gate declares `empty_by_design` with a reason.
"""
import hashlib, json, os, re, subprocess, sys, zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
T04 = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(os.path.dirname(T04)))
sys.path.insert(0, HERE)
import t04_review_model_v1 as M
import t04_review_render_v1 as R
import t04_review_semantic_v1 as SEM

SUITE_ID = "T04_BARIAH_REVIEW_ARTIFACT_QA_v1"
SIBLING_SUITE_ID = "T04_CONTENT_QA_v1"
SIBLING_NOTE = ("This suite governs the review ARTIFACT. T04_CONTENT_QA_v1 governs the "
                "CONTENT. Their gate counts are not additive and must never be merged.")

ARTIFACT_AUTHORITY = "ARTIFACT_AUTHORITY"
SEMANTIC_PARITY = "SEMANTIC_PARITY"
MERGE_DISCIPLINE = "MERGE_DISCIPLINE"
VISUAL_REPORTING = "VISUAL_REPORTING"
CONTENT_BOUNDARY = "CONTENT_BOUNDARY"
LANGUAGE_PRESENTATION = "LANGUAGE_PRESENTATION"
DOCX_STRUCTURE = "DOCX_STRUCTURE"
RENDER_HONESTY = "RENDER_HONESTY"
PRODUCTION_GUARD = "PRODUCTION_GUARD"
REPORTING = "REPORTING"
ACCOUNTING = "ACCOUNTING"
SUPERSESSION_MARKER = "SUPERSESSION_MARKER"

GATE_TYPES = {ARTIFACT_AUTHORITY, SEMANTIC_PARITY, MERGE_DISCIPLINE, VISUAL_REPORTING,
              CONTENT_BOUNDARY, LANGUAGE_PRESENTATION, DOCX_STRUCTURE, RENDER_HONESTY,
              PRODUCTION_GUARD, REPORTING, ACCOUNTING, SUPERSESSION_MARKER}

# Rendering reality on this machine, established by probe, not assumed.
NATIVE_RENDER_STATUS = "NOT_CHECKED_RENDERER_UNAVAILABLE"
NATIVE_RENDER_EVIDENCE = ("LibreOffice 24.2.7.2 is installed but only libreoffice-core and "
                          "libreoffice-common are present — there is no libreoffice-writer "
                          "package and therefore no Writer import filter. `soffice "
                          "--convert-to pdf` and `--convert-to txt` both fail with 'source "
                          "file could not be loaded' on a known-good DOCX. Same shape as the "
                          "missing Impress filter recorded in earlier stages.")
DELIVERY_STATUS = "READY_FOR_FIRDAUS_VISUAL_CHECK"

NOT_CHECKED = [
    "how Microsoft Word paginates the document — no Writer-compatible renderer exists here",
    "whether the ☐ glyph (U+2610) resolves in Word's font fallback on the reviewer's machine",
    "whether any table overflows its page width once Word applies its own column fitting",
    "whether headings orphan at page boundaries in Word",
    "whether the document reads well to a native Malay speaker",
    "whether Bariah finds the decision fields usable in practice",
    "the real page count — the deterministic preview estimates it, Word decides it",
]

# The manual DOCX must never be treated as data or as deliverable.
MANUAL_DOCX_UPLOAD = ("/root/.claude/uploads/12837c42-b6ab-597b-8301-85c5b457471b/"
                      "4d8f3f25-T04_Pakej_Semakan_Bariah_v1.docx")

ENGLISH_DECISION_WORDS = ("ACCEPT", "EDIT", "REMOVE", "MERGE", "Decision", "Comment",
                          "Approve", "Reviewer name", "Signature")
TECH_LEAKS = ("docs/pl06", "reviews/storyboard-bariah", "GENERATED by", "sha256", "SHA-256",
              "gate", "mutation", "fixture", "SUITE_ID", "T04-ROW-", "T04-VO-", "python3")
COMPLIANCE_TERMS = ("akta", "berlesen", "lesen", "ppe", "sds", "stor berkunci", "pelupusan",
                    "papan tanda amaran", "perundangan")


def _sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(65536), b""):
            h.update(b)
    return h.hexdigest()


def _docx_text():
    z = zipfile.ZipFile(SEM.DOCX_PATH)
    xml = z.read("word/document.xml").decode("utf-8")
    t = "".join(re.findall(r"<w:t[^>]*>(.*?)</w:t>", xml, re.S))
    return (t.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">"))


def run():
    res = []

    def chk(gid, gtype, value, expected, population, empty_by_design=None):
        ok = value == expected
        vacuous = population == 0 and not empty_by_design
        res.append(dict(gate_id=gid, gate_type=gtype, value=value, expected=expected,
                        population=population, empty_by_design=empty_by_design,
                        vacuous=vacuous, ok=ok and not vacuous))

    m = M.MODEL
    P = SEM.parity()
    dtext = _docx_text()
    va = m["visual_asset_grouping"]
    t = va["totals"]
    dv = m["decision_vocabulary"]

    # ==================== 1. ARTIFACT AUTHORITY ====================
    ah = m["artifact_hierarchy"]
    chk("CONTROLLED_JSON_IS_SOURCE_OF_TRUTH", ARTIFACT_AUTHORITY,
        ah["CONTROLLED_CONTENT_SOURCE_OF_TRUTH"],
        "docs/pl06/t04/T04_BARIAH_REVIEW_MODEL_v1.json", 3)
    chk("DOCX_IS_HUMAN_APPROVAL_ARTIFACT", ARTIFACT_AUTHORITY,
        ah["HUMAN_APPROVAL_ARTIFACT"].endswith("T04_Pakej_Semakan_Bariah_v2.docx"), True, 3)
    chk("MARKDOWN_IS_REFERENCE_VIEW", ARTIFACT_AUTHORITY,
        ah["GENERATED_REFERENCE_VIEW"].endswith("T04_BARIAH_CONTENT_REVIEW_PACK_v2.md"),
        True, 3)
    e = m["external_manual_docx"]
    chk("MANUAL_DOCX_IS_NON_GOVERNED_REFERENCE", ARTIFACT_AUTHORITY,
        (e["status"], e["delivery_status"]),
        ("NON_GOVERNED_REFERENCE", "WITHDRAWN_NOT_FOR_BARIAH"), 1)
    chk("MANUAL_DOCX_NOT_USED_AS_AUTHORITY", ARTIFACT_AUTHORITY,
        (e["used_as_authority"], e["copied_into_evidence"]), (False, False), 2)
    chk("MANUAL_DOCX_NOT_IN_THE_REPOSITORY", ARTIFACT_AUTHORITY,
        [p for p in (os.path.join(R.DOCX_DIR, "T04_Pakej_Semakan_Bariah_v1.docx"),)
         if os.path.exists(p)], [], 1)
    chk("MANUAL_DOCX_DIVERGENCES_RECORDED", ARTIFACT_AUTHORITY,
        len(e["divergences_observed"]) >= 5, True, len(e["divergences_observed"]))
    chk("MODEL_FILE_ON_DISK_MATCHES_MODEL", ARTIFACT_AUTHORITY,
        json.load(open(SEM.MODEL_PATH, encoding="utf-8"))["model_version"],
        M.MODEL_VERSION, 1)

    # ==================== 2. SEMANTIC PARITY ====================
    chk("ALL_THREE_SEMANTIC_DIGESTS_AGREE", SEMANTIC_PARITY, P["all_three_agree"], True, 3)
    chk("NO_DOCX_ONLY_SUBSTANTIVE_CONTENT", SEMANTIC_PARITY,
        P["docx_only_substantive"], [], P["counts"]["docx"])
    chk("NO_MARKDOWN_ONLY_REVIEWABLE_CONTENT", SEMANTIC_PARITY,
        P["markdown_only_substantive"], [], P["counts"]["markdown"])
    chk("MODEL_FULLY_PRESENT_IN_DOCX", SEMANTIC_PARITY,
        P["model_missing_from_docx"], [], P["counts"]["model"])
    chk("MODEL_FULLY_PRESENT_IN_MARKDOWN", SEMANTIC_PARITY,
        P["model_missing_from_markdown"], [], P["counts"]["model"])
    chk("NO_FIELD_LEVEL_DIFFERENCES", SEMANTIC_PARITY,
        sorted(P["field_level_differences"]), [], P["counts"]["model"])
    sm, sd = SEM.semantic("markdown"), SEM.semantic("docx")
    # Expected count derived live from the model, never typed as a literal.
    _expected_ids = sorted({i for i in M.reviewable_item_ids()
                            if not re.fullmatch(r"Q[1-5]", i)})
    chk("ITEM_IDS_AGREE", SEMANTIC_PARITY,
        (sm["item_ids"] == sd["item_ids"], sd["item_ids"]), (True, _expected_ids),
        len(sd["item_ids"]))
    chk("SCREEN_COUNTS_AGREE", SEMANTIC_PARITY,
        (sm["screen_count"], sd["screen_count"],
         m["screen_sequence"]["proposed_learner_screen_count"]), (21, 21, 21), 3)
    chk("ASSET_GROUP_COUNTS_AGREE", SEMANTIC_PARITY,
        (sm["asset_group_count"], sd["asset_group_count"], t["asset_groups"]), (8, 8, 8), 3)
    chk("DIALOGUE_AGREES", SEMANTIC_PARITY, sm["dialogue"], sd["dialogue"],
        len(sd["dialogue"]))
    chk("DIALOGUE_LINE_COUNT", SEMANTIC_PARITY, len(sd["dialogue"]),
        len(m["slide_2_dialogue"]["lines"]), len(sd["dialogue"]))
    chk("RUMUSAN_POINT_COUNT_AGREES", SEMANTIC_PARITY,
        (sm["rumusan_point_count"], sd["rumusan_point_count"],
         len(m["rumusan"]["points"])), (4, 4, 4), 4)
    chk("QUIZ_IDS_AGREE", SEMANTIC_PARITY, (sm["quiz_ids"], sd["quiz_ids"]),
        (["Q1", "Q2", "Q3", "Q4", "Q5"], ["Q1", "Q2", "Q3", "Q4", "Q5"]), 5)
    chk("QUIZ_OPTIONS_AGREE", SEMANTIC_PARITY, sm["quiz_options"], sd["quiz_options"],
        len(sd["quiz_options"]))
    # The "[cadangan jawapan]" marker is substantive — it is how Bariah sees which option is
    # proposed as correct — so the expected set carries it too.
    # Normalised through the same collapse the extractor applies, so whitespace — a permitted
    # formatting difference — cannot fail a meaning check.
    model_opts = sorted({SEM._norm(f"{o['key']}. {o['text']}"
                                   + ("   [cadangan jawapan]" if o["proposed_correct"] else ""))
                         for i in m["quiz"]["items"] for o in i["options"]})
    chk("QUIZ_OPTIONS_MATCH_THE_MODEL", SEMANTIC_PARITY, sd["quiz_options"], model_opts,
        len(model_opts))
    chk("DECISION_VOCABULARY_AGREES", SEMANTIC_PARITY,
        (sm["decision_labels"], sd["decision_labels"]),
        (sorted(dv["labels_ms"].values()), sorted(dv["labels_ms"].values())), 4)
    chk("PROVENANCE_LABELS_AGREE", SEMANTIC_PARITY,
        sm["origin_labels"], sd["origin_labels"], len(sd["origin_labels"]))
    chk("REUSE_LABELS_AGREE", SEMANTIC_PARITY,
        sm["reuse_labels"], sd["reuse_labels"], len(sd["reuse_labels"]))
    chk("DEPENDENCY_NOTE_IN_BOTH", SEMANTIC_PARITY,
        (sm["dependency_note_present"], sd["dependency_note_present"]), (True, True), 2)
    chk("VERDICT_OPTIONS_AGREE", SEMANTIC_PARITY,
        (sm["verdict_options"], sd["verdict_options"]),
        (sorted(M.FINAL_VERDICT_OPTIONS_MS), sorted(M.FINAL_VERDICT_OPTIONS_MS)), 3)

    # ==================== 3. MERGE DISCIPLINE ====================
    mr = dv["merge_rule"]
    chk("MERGE_ALLOWED_ONLY_FOR_SCREENS_AND_ASSET_GROUPS", MERGE_DISCIPLINE,
        sorted(mr["applies_to"]), ["screen_sequence", "visual_asset_grouping"], 2)
    chk("MERGE_FORBIDDEN_FOR_CONTENT_ITEMS", MERGE_DISCIPLINE,
        sorted(mr["forbidden_for"]), ["quiz", "rumusan", "slide_2_dialogue"], 3)
    structural = m["screen_sequence"]["screens"] + va["groups"]
    chk("STRUCTURAL_ITEMS_OFFER_MERGE", MERGE_DISCIPLINE,
        [x["item_id"] for x in structural if "MERGE" not in x["allowed_decisions"]], [],
        len(structural))
    content_items = (m["slide_2_dialogue"]["lines"] + m["rumusan"]["points"]
                     + m["quiz"]["items"])
    chk("CONTENT_ITEMS_DO_NOT_OFFER_MERGE", MERGE_DISCIPLINE,
        [x["item_id"] for x in content_items if "MERGE" in x["allowed_decisions"]], [],
        len(content_items))
    chk("MERGE_REQUIRES_ALL_FOUR_FIELDS", MERGE_DISCIPLINE,
        sorted(mr["required_fields"]),
        sorted(["merge_source_id", "merge_target_id", "merge_reason",
                "proposed_resulting_title_or_group"]), 4)
    chk("EVERY_STRUCTURAL_ITEM_CARRIES_A_MERGE_RECORD", MERGE_DISCIPLINE,
        [x["item_id"] for x in structural
         if sorted(x["merge"]) != sorted(mr["required_fields"])], [], len(structural))
    # A MERGE that is set must carry a target, and the target must differ and resolve.
    all_ids = {x["item_id"] for x in structural}
    orphan = [x["item_id"] for x in structural
              if (x["merge"]["merge_source_id"] or x["decision"] == "MERGE")
              and not x["merge"]["merge_target_id"]]
    chk("NO_ORPHAN_MERGE_DECISION", MERGE_DISCIPLINE, orphan, [], len(structural))
    chk("MERGE_SOURCE_AND_TARGET_DIFFER", MERGE_DISCIPLINE,
        [x["item_id"] for x in structural
         if x["merge"]["merge_target_id"]
         and x["merge"]["merge_target_id"] == x["merge"]["merge_source_id"]], [],
        len(structural))
    chk("MERGE_TARGET_RESOLVES", MERGE_DISCIPLINE,
        [x["item_id"] for x in structural
         if x["merge"]["merge_target_id"] and x["merge"]["merge_target_id"] not in all_ids],
        [], len(structural))
    chk("MERGE_TARGET_FIELD_PRINTED_IN_DOCX", MERGE_DISCIPLINE,
        "GABUNG DENGAN ID" in dtext, True, 1)
    chk("MERGE_IS_NOT_REUSE", MERGE_DISCIPLINE,
        (bool(mr["not_the_same_as_reuse"]),
         sorted(dv["reuse"]) != sorted(dv["structural"])), (True, True), 2)
    chk("REUSE_IS_A_SEPARATE_FIELD", MERGE_DISCIPLINE,
        [g["item_id"] for g in va["groups"] if "allowed_reuse_decisions" not in g], [],
        len(va["groups"]))

    # ==================== 4. VISUAL REPORTING ====================
    chk("OBLIGATIONS_NOT_REPRESENTED_AS_ASSETS", VISUAL_REPORTING,
        t["visual_obligations"] == t["proposed_unique_assets"], False, 2)
    chk("ARITHMETIC_RECONCILES", VISUAL_REPORTING,
        va["arithmetic_check"], t["proposed_unique_assets"], 5)
    chk("PROPOSED_ASSETS_LABELLED_PROPOSED", VISUAL_REPORTING, t["status"],
        "PROPOSED_NOT_APPROVED", 1)
    chk("PROPOSED_ASSETS_NOT_CLAIMED_APPROVED_IN_DOCX", VISUAL_REPORTING,
        "belum diluluskan" in dtext, True, 1)
    chk("COMPOSITE_COUNT_DISCLOSED", VISUAL_REPORTING,
        (t["composite_covered"], len(va["composite_items"])), (5, 5), 5)
    chk("COMPOSITE_ITEMS_LISTED_IN_DOCX", VISUAL_REPORTING,
        [x for x in va["composite_items"] if x.split(" — ")[0] not in dtext], [],
        len(va["composite_items"]))
    chk("NO_SEPARATE_ASSET_COUNT_DISCLOSED", VISUAL_REPORTING,
        (t["no_separate_asset"], len(va["no_separate_asset_items"])), (3, 3), 3)
    chk("NO_SEPARATE_ASSET_ITEMS_LISTED_IN_DOCX", VISUAL_REPORTING,
        [x for x in va["no_separate_asset_items"] if x.split(" — ")[0] not in dtext], [],
        len(va["no_separate_asset_items"]))
    chk("ADDITIONAL_ASSETS_DISCLOSED", VISUAL_REPORTING, t["additional_assets"], 3, 3)
    ag1 = va["ag01_seventh_asset"]
    chk("AG01_SIX_VISUALS_ARE_BARIAH_REQUIREMENT", VISUAL_REPORTING,
        ag1["six_step_visuals_origin"], "KEPERLUAN_VISUAL_BARIAH", 1)
    chk("AG01_SEVENTH_ASSET_IS_A_CAIR_PROPOSAL", VISUAL_REPORTING,
        ag1["seventh_asset_origin"], "CADANGAN_PELAKSANAAN_CAIR_DARIPADA_D05", 1)
    chk("AG01_DISCLOSURE_IN_DOCX", VISUAL_REPORTING, ag1["disclosure_ms"] in dtext, True, 1)
    ag8 = va["ag08_scenario"]
    chk("AG08_IS_A_CAIR_SCENARIO_PROPOSAL", VISUAL_REPORTING,
        ag8["origin"], "CADANGAN_CAIR_UNTUK_SENARIO", 1)
    chk("AG08_EXCLUDED_FROM_THE_46", VISUAL_REPORTING,
        ag8["part_of_46_obligations"], False, 1)
    chk("AG08_DISCLOSURE_IN_DOCX", VISUAL_REPORTING, ag8["disclosure_ms"] in dtext, True, 1)
    chk("AG08_NOT_LABELLED_A_BARIAH_RULING", VISUAL_REPORTING,
        [g["item_id"] for g in va["groups"]
         if g["item_id"] == "AG-08" and g["origin_label"] == "KEPERLUAN_VISUAL_BARIAH"], [],
        len(va["groups"]))
    chk("AUTHORITY_STATEMENT_PRESENT", VISUAL_REPORTING,
        va["authority_statement_ms"] in dtext, True, 1)
    chk("DO_NOT_REUSE_GROUP_COUNT_DISCLOSED", VISUAL_REPORTING,
        t["do_not_reuse_groups"], 2, len(va["groups"]))
    chk("DO_NOT_REUSE_OBLIGATION_COUNT_DISCLOSED", VISUAL_REPORTING,
        (t["do_not_reuse_obligations"], len(va["do_not_reuse_items"])), (3, 3), 3)
    chk("DO_NOT_REUSE_ITEMS_SHOWN_IN_DOCX", VISUAL_REPORTING,
        [x["item"] for x in va["do_not_reuse_items"] if x["item"].split(" — ")[0] not in dtext],
        [], len(va["do_not_reuse_items"]))
    chk("REUSE_QUESTION_RESPECTS_CONSTRAINTS", VISUAL_REPORTING,
        (va["reuse_question_ms"].startswith("Selain visual yang telah ditandakan"),
         va["reuse_question_ms"] in dtext), (True, True), 1)
    chk("REUSE_QUESTION_NOT_UNRESTRICTED", VISUAL_REPORTING,
        bool(re.search(r"^Adakah visual tertentu boleh digunakan semula",
                       va["reuse_question_ms"])), False, 1)
    chk("EVERY_GROUP_HAS_REUSE_STATUS_AND_RESTRICTION", VISUAL_REPORTING,
        [g["item_id"] for g in va["groups"]
         if not (g["reuse_status"] and g["known_restriction_ms"])], [], len(va["groups"]))
    chk("EVERY_GROUP_HAS_AN_ALLOWED_ORIGIN_LABEL", VISUAL_REPORTING,
        [g["item_id"] for g in va["groups"]
         if g["origin_label"] not in va["origin_labels"]], [], len(va["groups"]))

    # ==================== 5. CONTENT BOUNDARY ====================
    d = m["slide_2_dialogue"]
    chk("SLIDE_2_BOUNDARIES_IN_MODEL", CONTENT_BOUNDARY,
        (d["boundaries"]["level"], len(d["boundaries"]["rules"])),
        ("PROCESS_OVERVIEW_ONLY", 4), 4)
    chk("SLIDE_2_BOUNDARIES_IN_DOCX", CONTENT_BOUNDARY,
        [r for r in d["boundaries"]["rules_ms"] if r not in dtext], [],
        len(d["boundaries"]["rules_ms"]))
    chk("NO_STATUTORY_DUTY_IN_DIALOGUE", CONTENT_BOUNDARY,
        sorted({term for term in COMPLIANCE_TERMS for L in d["lines"]
                if term in L["display_text"].lower()}), [], len(d["lines"]))
    chk("CAST_NOT_FINAL", CONTENT_BOUNDARY, d["cast_status"],
        "PROPOSED_SUBJECT_TO_BARIAH_APPROVAL", 1)
    chk("CAST_SCOPE_IS_SLIDE_2_ONLY", CONTENT_BOUNDARY,
        "Slide 2 sahaja" in d["contextual_fit_scope_ms"], True, 1)
    r = m["rumusan"]
    chk("RUMUSAN_04_RISK_FLAGGED", CONTENT_BOUNDARY,
        [p["item_id"] for p in r["points"] if p["risk_flag"] == "MEDIUM_FACTUAL_RISK"],
        ["T04-RUM2-04"], len(r["points"]))
    chk("RUMUSAN_04_SECOND_FLAG", CONTENT_BOUNDARY,
        [p["item_id"] for p in r["points"]
         if p["risk_flag_secondary"] == "GENERALISATION_REQUIRES_BARIAH_DECISION"],
        ["T04-RUM2-04"], len(r["points"]))
    chk("RUMUSAN_RISK_NOTE_IN_DOCX", CONTENT_BOUNDARY, r["risk_note_ms"] in dtext, True, 1)
    dep = m["cross_item_dependencies"]
    chk("DEP_RUM04_Q5_EXISTS", CONTENT_BOUNDARY,
        [x["dependency_id"] for x in dep], ["DEP-RUM04-Q5"], len(dep))
    chk("DEP_TRIGGER_AND_EFFECT", CONTENT_BOUNDARY,
        (dep[0]["trigger"], dep[0]["effect"]),
        ("RUMUSAN_04_EDITED_OR_REMOVED_DUE_TO_OVER_GENERALISATION",
         "Q5_REQUIRES_CONSISTENCY_REVIEW"), 2)
    chk("Q5_NOT_AUTOMATICALLY_INVALIDATED", CONTENT_BOUNDARY,
        dep[0]["automatic_invalidation"], False, 1)
    q = m["quiz"]
    chk("QUIZ_COMPOSITION_UNCHANGED", CONTENT_BOUNDARY,
        (len([i for i in q["items"] if i["question_type"] == "MCQ"]),
         len([i for i in q["items"] if i["question_type"] == "MULTIPLE_RESPONSE"])),
        (4, 1), len(q["items"]))
    chk("PASS_THRESHOLD_60", CONTENT_BOUNDARY, q["pass_threshold"], "60_PERCENT", 1)
    chk("SCOPE_ALL_PLS", CONTENT_BOUNDARY, q["scope"], "ALL_PLS_IN_KURSUS", 1)
    chk("ANSWER_KEY_NOT_FINAL", CONTENT_BOUNDARY,
        (q["answer_key_status"], q["answer_key_approval"]),
        ("PROPOSED_ANSWER_KEY", "PENDING_BARIAH_APPROVAL"), 2)
    chk("EVERY_QUIZ_ITEM_KEEPS_SOURCE_EVIDENCE_INTERNALLY", CONTENT_BOUNDARY,
        [i["item_id"] for i in q["items"]
         if not i.get("internal_answer_evidence") or not i.get("internal_provenance")], [],
        len(q["items"]))
    chk("QUIZ_SOURCE_STATUS_IS_SUPPORTED_NOT_UNSUPPORTED", CONTENT_BOUNDARY,
        (q["source_evidence_status"], q["source_evidence_caveat"]),
        ("SUPPORTED_BY_CONTROLLED_EXTRACT", "ORIGINAL_DOCX_ROUND_TRIP_NOT_REPROVEN"), 2)
    _live_projection = "\n".join(SEM.model_strings())
    chk("CUSTODY_CAVEAT_KEPT_OUT_OF_THE_BARIAH_DOCUMENT", CONTENT_BOUNDARY,
        (q["source_evidence_caveat"] in dtext,
         q["source_evidence_caveat"] in _live_projection), (False, False), 2)
    dr = q["distractor_review"]
    chk("Q5_DISTRACTOR_REVIEW_RECORDED", CONTENT_BOUNDARY,
        (bool(dr), dr["outcome"] if dr else None), (True, "REVISED"), 1)
    chk("Q5_OPTION_MAPPING_RECORDED", CONTENT_BOUNDARY,
        len(dr["option_mapping"]) if dr else 0, 6, 6)
    chk("Q5_CORRECT_ANSWER_COUNT_PRESERVED", CONTENT_BOUNDARY,
        (dr["correct_answer_count_before"], dr["correct_answer_count_after"]) if dr else None,
        (4, 4), 2)
    chk("EVERY_REVIEWABLE_ITEM_IS_A_DRAFT", CONTENT_BOUNDARY,
        [x["item_id"] for x in (m["screen_sequence"]["screens"] + va["groups"]
                                + d["lines"] + r["points"] + q["items"])
         if x["content_status"] != "CAIR_ASSISTED_DRAFT"
         or x["approval_status"] != "PENDING_BARIAH_REVIEW"
         or x["instructional_authority"] != "BARIAH"], [],
        len(m["screen_sequence"]["screens"]) + len(va["groups"]) + len(d["lines"])
        + len(r["points"]) + len(q["items"]))

    # ==================== 6. LANGUAGE AND PRESENTATION ====================
    chk("REVIEWER_INSTRUCTIONS_IN_MALAY", LANGUAGE_PRESENTATION,
        [s for s in m["reviewer_instructions"]["lines_ms"]
         if any(re.search(rf"\b{w}\b", s) for w in ENGLISH_DECISION_WORDS)], [],
        len(m["reviewer_instructions"]["lines_ms"]))
    chk("NO_ENGLISH_DECISION_WORDS_IN_DOCX", LANGUAGE_PRESENTATION,
        sorted({w for w in ENGLISH_DECISION_WORDS if re.search(rf"\b{w}\b", dtext)}), [],
        len(ENGLISH_DECISION_WORDS))
    chk("SECTION_F_IS_MALAY", LANGUAGE_PRESENTATION,
        [s["title_ms"] for s in m["sections"] if s["section_id"] == "F"],
        ["Keputusan dan pindaan Bariah"], 1)
    chk("PERMITTED_TECHNICAL_TERMS_ONLY", LANGUAGE_PRESENTATION,
        sorted({w for w in ("MCQ", "Multiple Response", "PPE", "SDS", "IPM")
                if w in dtext}) != [], True, 5)
    chk("NO_TECHNICAL_LEAK_IN_DOCX", LANGUAGE_PRESENTATION,
        sorted({w for w in TECH_LEAKS if w.lower() in dtext.lower()}), [], len(TECH_LEAKS))
    chk("NO_GENERATOR_BANNER_IN_DOCX", LANGUAGE_PRESENTATION,
        "GENERATED by" in dtext, False, 1)
    chk("OPENING_DISCLOSURE_PRESENT", LANGUAGE_PRESENTATION,
        m["document_metadata"]["opening_disclosure_ms"] in dtext, True, 1)
    chk("REVIEWER_BLOCK_PRESENT", LANGUAGE_PRESENTATION,
        ("Bariah" in dtext and "Tarikh semakan" in dtext), True, 2)
    chk("FINAL_VERDICT_BLOCK_PRESENT", LANGUAGE_PRESENTATION,
        [v for v in M.FINAL_VERDICT_OPTIONS_MS if v not in dtext], [],
        len(M.FINAL_VERDICT_OPTIONS_MS))
    chk("EXACTLY_ONE_VERDICT_VOCABULARY", LANGUAGE_PRESENTATION,
        (m["final_review_record"]["single_verdict_block"],
         dtext.count("LULUS TANPA PINDAAN")), (True, 1), 1)
    chk("SIGNATURE_FIELD_PRESENT", LANGUAGE_PRESENTATION,
        "Tandatangan / pengesahan bertulis" in dtext, True, 1)
    chk("NO_OVERCLAIM_THAT_PPTX_OR_MMD_EXISTS", LANGUAGE_PRESENTATION,
        ("belum dijana" in dtext and "belum dihasilkan" in dtext), True, 2)
    chk("ALL_SIX_SECTIONS_PRESENT", LANGUAGE_PRESENTATION,
        [s["section_id"] for s in m["sections"]], ["A", "B", "C", "D", "E", "F"],
        len(m["sections"]))
    chk("SECTION_HEADINGS_IN_DOCX", LANGUAGE_PRESENTATION,
        [s["section_id"] for s in m["sections"]
         if f"{s['section_id']}. {s['title_ms']}" not in dtext], [], len(m["sections"]))

    # ==================== 7. DOCX STRUCTURE ====================
    z = zipfile.ZipFile(SEM.DOCX_PATH)
    names = z.namelist()
    chk("DOCX_IS_A_VALID_ZIP", DOCX_STRUCTURE, z.testzip(), None, len(names))
    import xml.dom.minidom as MD
    bad = []
    for n in names:
        if n.endswith(".xml") or n.endswith(".rels"):
            try:
                MD.parseString(z.read(n))
            except Exception:
                bad.append(n)
    chk("ALL_XML_PARTS_PARSE", DOCX_STRUCTURE, bad, [],
        len([n for n in names if n.endswith((".xml", ".rels"))]))
    rel_ids, missing = [], []
    for rn in [n for n in names if n.endswith(".rels")]:
        x = z.read(rn).decode()
        rel_ids += re.findall(r'Id="([^"]+)"', x)
        base = "" if rn == "_rels/.rels" else rn.split("_rels/")[0]
        for tgt in re.findall(r'Target="([^"]+)"', x):
            if tgt.startswith("http"):
                continue
            if (base + tgt) not in names:
                missing.append(base + tgt)
    chk("ALL_RELATIONSHIPS_RESOLVE", DOCX_STRUCTURE, missing, [], len(rel_ids))
    chk("NO_DUPLICATE_RELATIONSHIP_IDS_PER_PART", DOCX_STRUCTURE,
        sorted({i for rn in [n for n in names if n.endswith(".rels")]
                for ids in [re.findall(r'Id="([^"]+)"', z.read(rn).decode())]
                for i in ids if ids.count(i) > 1}), [], len(rel_ids))
    doc = z.read("word/document.xml").decode()
    chk("NO_BROKEN_MEDIA_LINKS", DOCX_STRUCTURE,
        re.findall(r'r:(?:embed|link)="([^"]+)"', doc), [], 1,
        empty_by_design="the governed document embeds no media — it is text and tables only")
    chk("NO_UNEXPECTED_EXTERNAL_LINKS", DOCX_STRUCTURE,
        re.findall(r'TargetMode="External"', "".join(
            z.read(n).decode() for n in names if n.endswith(".rels"))), [], len(rel_ids))
    _live_blocks = R.blocks()
    chk("PAGE_BREAKS_AT_SECTION_BOUNDARIES", DOCX_STRUCTURE,
        doc.count('w:type="page"'),
        len([b for b in _live_blocks if b["kind"] == "pagebreak"]),
        len([b for b in _live_blocks if b["kind"] == "pagebreak"]))
    chk("TABLES_FIT_THE_CONTENT_WIDTH", DOCX_STRUCTURE,
        [w for w in re.findall(r'<w:tblW w:w="(\d+)"', doc) if int(w) > R.CONTENT_W], [],
        doc.count("<w:tbl>"))
    chk("EVERY_TABLE_GRID_SUMS_TO_TABLE_WIDTH", DOCX_STRUCTURE,
        [g for g in re.findall(r"<w:tblGrid>(.*?)</w:tblGrid>", doc, re.S)
         if sum(int(x) for x in re.findall(r'w:w="(\d+)"', g)) != R.CONTENT_W], [],
        doc.count("<w:tblGrid>"))
    chk("SECTION_PAGE_SIZE_IS_A4", DOCX_STRUCTURE,
        re.search(r'<w:pgSz w:w="(\d+)" w:h="(\d+)"/>', doc).groups(),
        (str(R.PAGE_W), str(R.PAGE_H)), 1)
    chk("DOCUMENT_ENDS_WITH_CONTENT_NOT_A_BLANK_PAGE", DOCX_STRUCTURE,
        _live_blocks[-1]["kind"], "field", 1)
    chk("MODEL_PROJECTION_DERIVED_LIVE", DOCX_STRUCTURE,
        len(_live_blocks) == len(R.blocks()) and len(SEM.model_strings()) > 0, True,
        len(_live_blocks))
    chk("EVERY_REVIEWABLE_ITEM_HAS_DECISION_FIELDS_IN_DOCX", DOCX_STRUCTURE,
        [x for x in M.reviewable_item_ids() if x not in dtext], [],
        len(M.reviewable_item_ids()))
    chk("CHECKBOX_COUNT_MATCHES_THE_MODEL", DOCX_STRUCTURE,
        dtext.count(R.BOX) > 0, True, dtext.count(R.BOX))

    # ==================== 8. RENDER HONESTY ====================
    chk("NATIVE_RENDER_STATUS_DECLARED", RENDER_HONESTY,
        NATIVE_RENDER_STATUS, "NOT_CHECKED_RENDERER_UNAVAILABLE", 1)
    chk("NATIVE_RENDER_NOT_CLAIMED_PASSED", RENDER_HONESTY,
        NATIVE_RENDER_STATUS.startswith("NOT_CHECKED"), True, 1)
    chk("DELIVERY_STATUS_MATCHES_RENDER_STATUS", RENDER_HONESTY,
        DELIVERY_STATUS,
        "READY_FOR_FIRDAUS_VISUAL_CHECK"
        if NATIVE_RENDER_STATUS.startswith("NOT_CHECKED") else "READY_FOR_BARIAH_DELIVERY", 1)
    chk("RENDER_UNAVAILABILITY_EVIDENCED", RENDER_HONESTY,
        len(NATIVE_RENDER_EVIDENCE) > 100, True, 1)
    prev = sorted(os.listdir(os.path.join(T04, "preview")))
    chk("FALLBACK_PREVIEW_GENERATED", RENDER_HONESTY,
        len([p for p in prev if p.endswith(".png")]) > 0, True, len(prev))
    chk("PREVIEW_DERIVED_FROM_THE_SAME_MODEL", RENDER_HONESTY,
        all(p.startswith("T04_Pakej_Semakan_Bariah_v2_p") for p in prev if p.endswith(".png")),
        True, len(prev))

    # ==================== 9. PRODUCTION GUARD ====================
    pg = m["production_guards"]
    chk("NO_PPTX_GENERATED", PRODUCTION_GUARD, pg["PPTX_GENERATED"], 0, 1)
    chk("NO_MMD_PRODUCTION_STARTED", PRODUCTION_GUARD, pg["MMD_PRODUCTION_STARTED"], 0, 1)
    try:
        gen = subprocess.run(["git", "status", "--porcelain", "reviews/source-completion"],
                             cwd=REPO, capture_output=True, text=True,
                             timeout=60).stdout.strip()
    except Exception:
        gen = ""
    chk("NO_PRODUCTION_GENERATOR_MODIFIED", PRODUCTION_GUARD,
        (gen, pg["GENERATOR_TOUCHED"]), ("", 0), 1)
    try:
        tracked = subprocess.run(["git", "ls-files"], cwd=REPO, capture_output=True,
                                 text=True, timeout=60).stdout.split()
    except Exception:
        tracked = []
    chk("NO_PPTX_IN_THE_PL06_TREE", PRODUCTION_GUARD,
        [x for x in tracked if x.lower().endswith(".pptx") and "/pl06/" in x], [],
        len(tracked) or 1)
    chk("MANUAL_V1_DOCX_NOT_TRACKED", PRODUCTION_GUARD,
        [x for x in tracked if x.endswith("T04_Pakej_Semakan_Bariah_v1.docx")], [],
        len(tracked) or 1)

    # ==================== 10. REPORTING ====================
    chk("SUITE_ID_PRESENT", REPORTING, SUITE_ID, "T04_BARIAH_REVIEW_ARTIFACT_QA_v1", 1)
    chk("SUITE_NOT_MERGED_WITH_CONTENT_SUITE", REPORTING,
        (SUITE_ID != SIBLING_SUITE_ID, len(SIBLING_NOTE) > 50), (True, True), 2)
    chk("NOT_CHECKED_PUBLISHED", REPORTING, len(NOT_CHECKED) >= 5, True, len(NOT_CHECKED))
    chk("EVERY_GATE_REPORTS_A_POPULATION", REPORTING,
        [r["gate_id"] for r in res if not isinstance(r.get("population"), int)], [], len(res))
    chk("NO_UNDECLARED_EMPTY_POPULATION", REPORTING,
        [r["gate_id"] for r in res if r["population"] == 0 and not r["empty_by_design"]], [],
        len(res))
    # Totals recomputed live from the artifacts, never trusted from a stored field.
    live_screens = len(m["screen_sequence"]["screens"])
    live_groups = len(va["groups"])
    live_assets = sum(g["proposed_unique_assets"] for g in va["groups"])
    chk("SEMANTIC_TOTALS_DERIVED_LIVE", REPORTING,
        (m["screen_sequence"]["proposed_learner_screen_count"] == live_screens,
         t["asset_groups"] == live_groups,
         t["proposed_unique_assets"] == live_assets), (True, True, True), 3)

    # ==================== 11. ACCOUNTING ====================
    g_ids = [r["gate_id"] for r in res]
    chk("DUPLICATE_GATE_IDS", ACCOUNTING,
        sorted({x for x in g_ids if g_ids.count(x) > 1}), [], len(g_ids))
    chk("EVERY_GATE_CARRIES_A_TYPE", ACCOUNTING,
        [r["gate_id"] for r in res if r["gate_type"] not in GATE_TYPES], [], len(res))
    return res


def accounting(rows):
    a = [r for r in rows if r["gate_type"] != SUPERSESSION_MARKER]
    by = {}
    for r in a:
        by[r["gate_type"]] = by.get(r["gate_type"], 0) + 1
    return dict(SUITE_ID=SUITE_ID, SIBLING_SUITE_ID=SIBLING_SUITE_ID,
                SIBLING_NOTE=SIBLING_NOTE,
                TOTAL_EMITTED_GATE_RECORDS=len(rows),
                ACTIVE_GATE_COUNT=len(a),
                ACTIVE_GATES_PASSING=sum(1 for r in a if r["ok"]),
                SUPERSESSION_MARKERS_PRESENT=len(rows) - len(a),
                VACUOUS_GATES=[r["gate_id"] for r in rows if r["vacuous"]],
                DECLARED_EMPTY_GATES=[r["gate_id"] for r in rows if r["empty_by_design"]],
                POPULATION_TOTALS={r["gate_id"]: r["population"] for r in rows},
                BY_TYPE=dict(sorted(by.items())),
                NATIVE_RENDER=NATIVE_RENDER_STATUS,
                DELIVERY_STATUS=DELIVERY_STATUS,
                NOT_CHECKED=NOT_CHECKED,
                FAILING=[r["gate_id"] for r in rows if not r["ok"]])


if __name__ == "__main__":
    rows = run()
    a = accounting(rows)
    w = max(len(r["gate_id"]) for r in rows)
    t = max(len(r["gate_type"]) for r in rows)
    for r in rows:
        flag = "VACU" if r["vacuous"] else ("PASS" if r["ok"] else "FAIL")
        print(f"{flag}  {r['gate_type']:<{t}}  {r['gate_id']:<{w}}  n={r['population']:<5} "
              f"{r['value']!r}"[:200] + ("" if r["ok"] else f"   expected {r['expected']!r}"))
    print()
    print(f"SUITE_ID = {a['SUITE_ID']}   ({a['SIBLING_NOTE']})")
    print(f"{a['ACTIVE_GATES_PASSING']}/{a['ACTIVE_GATE_COUNT']} active gates PASS  ·  "
          f"{a['TOTAL_EMITTED_GATE_RECORDS']} emitted records")
    print(f"VACUOUS_GATES = {a['VACUOUS_GATES']}")
    print(f"DECLARED_EMPTY_GATES = {a['DECLARED_EMPTY_GATES']}")
    print(f"NATIVE_RENDER = {a['NATIVE_RENDER']}")
    print(f"DELIVERY_STATUS = {a['DELIVERY_STATUS']}")
    for k, v in a["BY_TYPE"].items():
        print(f"    {k:<22} {v}")
    sys.exit(1 if a["FAILING"] else 0)
