# -*- coding: utf-8 -*-
"""Stage 4.2F-B0.6 — emit every Bariah-rulings artifact from the one controlled data source.

Markdown, CSV and JSON all come from t04_rulings_data_v1, so they cannot disagree.
"""
import csv, io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import t04_rulings_data_v1 as D

OUT = os.path.abspath(os.path.join(HERE, ".."))
BANNER = (f"<!-- GENERATED by {D.GENERATED_BY} — Stage {D.STAGE}. "
          "Edit the data module, not this file. -->")


def _w(name, text):
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text if text.endswith("\n") else text + "\n")
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1))


def _hdr(title, extra=()):
    lines = [BANNER, "", f"# {title}", "",
             "```",
             f"STAGE                   = {D.STAGE}",
             f"UNIT                    = {D.UNIT_ID} — {D.LESSON_TITLE}",
             f"CONTENT_STATUS          = {D.CONTENT_STATUS}",
             f"APPROVAL_STATUS         = {D.APPROVAL_STATUS}",
             f"INSTRUCTIONAL_AUTHORITY = {D.INSTRUCTIONAL_AUTHORITY}"]
    lines += list(extra)
    lines += ["```", ""]
    return "\n".join(lines)


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


# ==========================================================================================
def emit_rulings():
    ev_rows = [(e["evidence_id"], e["frozen_filename"], f'{e["byte_size"]:,}',
                e["sha256"][:16] + "…", e["dimensions_px"], e["evidence_class"])
               for e in D.EVIDENCE]
    dec_rows = [(d["decision_id"], d["title"], f'**{d["status"]}**',
                 d["ruling"] or "—", ", ".join(d["evidence"]) or "—") for d in D.DECISIONS]

    parts = [_hdr("T04 — BARIAH PARTIAL RULINGS",
                  [f"EVIDENCE_ITEMS          = {len(D.EVIDENCE)}",
                   f"RULING_LOCATORS         = {len(D.RULING_LOCATORS)}",
                   f"DECISIONS_REGISTERED    = {len(D.DECISIONS)}",
                   f"APPROVED_ITEMS          = {D.APPROVED_ITEMS}"]),
             "# 1. Frozen evidence", "",
             _tbl(["ID", "Frozen filename", "Bytes", "SHA-256", "Dimensions", "Class"],
                  ev_rows), ""]
    for e in D.EVIDENCE:
        parts += [f"## {e['evidence_id']}", "",
                  "```",
                  f"frozen_path                = {e['frozen_path']}",
                  f"original_uploaded_filename = {e['original_uploaded_filename']}",
                  f"byte_size                  = {e['byte_size']}",
                  f"sha256                     = {e['sha256']}",
                  f"media_type                 = {e['media_type']}",
                  f"dimensions_px              = {e['dimensions_px']}",
                  f"colour_mode                = {e['colour_mode']}",
                  f"evidence_date              = {e['evidence_date']}",
                  f"received_utc               = {e['received_utc']}",
                  f"reviewer                   = {e['reviewer']}",
                  f"evidence_class             = {e['evidence_class']}",
                  f"scope                      = {e['scope']}",
                  f"modification               = {e['modification']}",
                  "```", "", e["description"], ""]
    parts += ["**Filename limitation, stated rather than hidden.** The original uploaded "
              "filenames are not recoverable — the images arrived as inline image blocks on "
              "the instruction message rather than as named files, and no filename is carried "
              "anywhere in the session record. The frozen names were assigned by CAIR "
              "following the B02 evidence naming pattern already in the same directory. The "
              "bytes are the evidence; the names are not.", "",
              "# 2. Rulings, verbatim", ""]
    for r in D.RULING_LOCATORS:
        parts += [f"### {r['locator']} · {r['evidence_id']}", "",
                  f"*{r['position']}*", "",
                  f"> {r['verbatim']}", "",
                  r["reading"], ""]
    parts += ["# 3. Decision status", "",
              _tbl(["Decision", "Title", "Status", "Ruling", "Evidence"], dec_rows), ""]
    for d in D.DECISIONS:
        parts += [f"## {d['decision_id']} — {d['title']}", "",
                  f"**Status: `{d['status']}`**", ""]
        if d["ruling"]:
            parts += [f"Ruling: `{d['ruling']}`", ""]
        if d["superseded_recommendation"]:
            parts += [f"Superseded recommendation: `{d['superseded_recommendation']}`", ""]
        parts += [d["supersession_note"], ""]
        if d["what_bariah_required"]:
            parts += ["**What Bariah required**", ""]
            parts += [f"- {x}" for x in d["what_bariah_required"]] + [""]
        parts += [f"**What Bariah did not specify.** {d['what_bariah_did_not_specify']}", "",
                  f"Scope: `{d['scope']}`", "", "**Still open**", ""]
        parts += [f"- {x}" for x in d["open_points"]] + [""]
    parts += ["# 4. Scope asymmetry, recorded", "",
              D.SCOPE_ASYMMETRY["observation"], "", D.SCOPE_ASYMMETRY["handling"], "",
              f"Status: `{D.SCOPE_ASYMMETRY['status']}` — {D.SCOPE_ASYMMETRY['reason']}", "",
              "Rows not covered by any obligation: " +
              ", ".join(f"`{r}`" for r in D.SCOPE_ASYMMETRY["kejur_sub_items_not_covered"]),
              ""]
    return _w("T04_BARIAH_PARTIAL_RULINGS_v1.md", "\n".join(parts))


def emit_rulings_json():
    return _j("T04_BARIAH_PARTIAL_RULINGS_v1.json", dict(
        pack="T04_BARIAH_PARTIAL_RULINGS", version="v1", stage=D.STAGE, unit_id=D.UNIT_ID,
        content_status=D.CONTENT_STATUS, approval_status=D.APPROVAL_STATUS,
        instructional_authority=D.INSTRUCTIONAL_AUTHORITY,
        approved_items=D.APPROVED_ITEMS,
        evidence_dir=D.EVIDENCE_DIR, evidence=D.EVIDENCE,
        ruling_locators=D.RULING_LOCATORS, decision_statuses=D.DECISION_STATUSES,
        decisions=D.DECISIONS, scope_asymmetry=D.SCOPE_ASYMMETRY))


# ==========================================================================================
def emit_inventory_md():
    t = D.VISUAL_TOTALS
    parts = [_hdr("T04 — VISUAL DIRECTION INVENTORY",
                  [f"TOTAL_VISUAL_OBLIGATIONS = {t['total_obligations']}",
                   f"EXISTING_SOURCE_ASSETS   = {t['existing_source_assets']} (SmartArt)",
                   f"RASTER_SOURCE_IMAGES     = {t['existing_raster_source_images']}",
                   f"NEW_MMD_ASSETS_REQUIRED  = {t['new_assets_required']}",
                   f"PENDING_HUMAN            = {t['pending_human']}",
                   "TREATMENT_AUTHORITY      = " + D.TREATMENT_AUTHORITY,
                   "SUBJECT_AUTHORITY        = " + D.SUBJECT_AUTHORITY]),
             "# 1. Where the population comes from", "",
             "Bariah ruled that a visual is required. She did not say what any visual should "
             "show. Those are two different authorities and this inventory keeps them apart "
             "on every row:", "",
             "```",
             f"treatment_authority  {D.TREATMENT_AUTHORITY}",
             "                     Bariah required a visual here — the frozen screenshots",
             f"subject_authority    {D.SUBJECT_AUTHORITY}",
             "                     WHAT it shows comes from the module, never from Bariah",
             "```", "",
             "The population is derived from the controlled extract, not typed by hand, so "
             "the counts below are checkable against the source rather than asserted.", "",
             _tbl(["Group", "Ruling", "Count"], [
                 ("A — six-step process nodes", "BR-L1", t["process_nodes"]),
                 ("B — Landskap Lembut main explanation", "BR-L2", t["lembut_main"]),
                 ("B — Siram / Baja / Racun main explanations", "BR-L3", t["operation_mains"]),
                 ("B — descendants of the three operations", "BR-L4",
                  t["operation_descendants"]),
                 ("C — Landskap Kejur main explanation", "BR-L5", t["kejur_main"]),
                 ("C — the four named Kejur groups", "BR-L6", t["kejur_groups"]),
                 ("**TOTAL**", "", f"**{t['total_obligations']}**")]), "",
             "The BR-L4 descendants, enumerated rather than left as *their subtopics*:", "",
             _tbl(["Operation", "Descendant source headings"], [
                 ("Siram", t["siram_descendants"]), ("Baja", t["baja_descendants"]),
                 ("Racun", t["racun_descendants"])]), "",
             "# 2. What does not exist", "",
             "The module contains **zero raster images**. One visual asset exists — the "
             "SmartArt process diagram `T04-DGM-01` — and it carries the six node *labels*, "
             "not six step illustrations. Every obligation below is "
             f"`{D.NEW_ASSET}`. No row claims an image that is not in the source.", "",
             D.VOCABULARY_NOTE, "",
             "# 3. The obligations", ""]
    for v in D.VISUAL_OBLIGATIONS:
        parts += [f"## {v['visual_obligation_id']} — {v['governed_display_heading']}", "",
                  "```",
                  f"bariah_ruling_locator          = {v['bariah_ruling_locator']}",
                  f"source_row_ids                 = {', '.join(v['source_row_ids'])}",
                  f"raw_source_heading             = {v['raw_source_heading']}",
                  f"governed_display_heading       = {v['governed_display_heading']}",
                  f"proposed_visual_class          = {v['proposed_visual_class']}",
                  f"existing_source_asset_available= {v['existing_source_asset_available']}",
                  f"source_asset_id                = {v['source_asset_id'] or '—'}",
                  f"production_requirement         = {v['production_requirement']}",
                  f"source_authority               = {v['source_authority']}",
                  f"treatment_authority            = {v['treatment_authority']}",
                  f"subject_authority              = {v['subject_authority']}",
                  f"mmd_dependency                 = {v['mmd_dependency']}",
                  f"approval_status                = {v['approval_status']}",
                  "```", "",
                  f"**Learner-facing subject.** {v['learner_facing_subject']}", "",
                  f"**Purpose.** {v['visual_purpose']}", ""]
        if v["unresolved_issue"]:
            parts += [f"**Unresolved.** {v['unresolved_issue']}", ""]
    parts += ["# 4. Scope asymmetry", "", D.SCOPE_ASYMMETRY["observation"], "",
              D.SCOPE_ASYMMETRY["handling"], ""]
    return _w("T04_VISUAL_DIRECTION_INVENTORY_v1.md", "\n".join(parts))


def emit_inventory_csv():
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(D.VISUAL_OBLIGATION_FIELDS)
    for v in D.VISUAL_OBLIGATIONS:
        w.writerow([";".join(v[f]) if isinstance(v[f], list) else ("" if v[f] is None else v[f])
                    for f in D.VISUAL_OBLIGATION_FIELDS])
    return _w("T04_VISUAL_DIRECTION_INVENTORY_v1.csv", buf.getvalue())


def emit_inventory_json():
    return _j("T04_VISUAL_DIRECTION_INVENTORY_v1.json", dict(
        pack="T04_VISUAL_DIRECTION_INVENTORY", version="v1", stage=D.STAGE,
        unit_id=D.UNIT_ID, content_status=D.CONTENT_STATUS,
        approval_status=D.APPROVAL_STATUS,
        instructional_authority=D.INSTRUCTIONAL_AUTHORITY,
        allowed_visual_classes=D.ALLOWED_VISUAL_CLASSES,
        vocabulary_note=D.VOCABULARY_NOTE,
        fields=D.VISUAL_OBLIGATION_FIELDS,
        totals=D.VISUAL_TOTALS,
        siram_descendant_rows=D.SIRAM_DESCENDANTS,
        baja_descendant_rows=D.BAJA_DESCENDANTS,
        racun_descendant_rows=D.RACUN_DESCENDANTS,
        kejur_groups=D.KEJUR_GROUPS,
        process_nodes=D.PROCESS_NODES,
        scope_asymmetry=D.SCOPE_ASYMMETRY,
        obligations=D.VISUAL_OBLIGATIONS))


# ==========================================================================================
def emit_mapping_md():
    i = D.MAPPING_IMPACT
    parts = [_hdr("T04 — SOURCE-TO-SCREEN MAPPING v2",
                  [f"FINAL_SCREEN_COUNT       = {D.FINAL_SCREEN_COUNT}",
                   f"B02_FAMILIES_PROPAGATED  = {i['b02_families_propagated']}",
                   f"VISUAL_OBLIGATIONS       = {i['obligations_total']}",
                   f"MAPPED_TO_A_CANDIDATE    = {i['obligations_mapped_to_existing_candidates']}",
                   f"NO_SCREEN_AT_ALL         = {i['obligations_with_no_home']}"]),
             "# 1. The headline", "", i["headline"], "",
             f"**`FINAL_SCREEN_COUNT = {D.FINAL_SCREEN_COUNT}`.** {i['reason']}", "",
             "# 2. How much more visual-intensive", "",
             _tbl(["", "Stage 4.2F-B0.5", "Stage 4.2F-B0.6"], [
                 ("Source visuals", "1", "1 — unchanged"),
                 ("Required visuals", "not counted", f"**{i['obligations_total']}**"),
                 ("Screens with a visual treatment", "1 of 6", "5 of 6"),
                 ("Obligations with no screen", "—", f"**{i['obligations_with_no_home']}**")]),
             "", i["revised_visual_count_claim"], "",
             "# 3. Per-candidate revision", ""]
    for m in D.MAPPING_V2:
        parts += [f"## {m['screen_candidate_id']} — {m['working_title']}", "",
                  _tbl(["Field", "Value"], [
                      ("previous visual assumption", m["previous_visual_assumption"]),
                      ("new Bariah visual obligation", m["new_bariah_visual_obligation"]),
                      ("visual obligation IDs",
                       ", ".join(m["visual_obligation_ids"]) or "none"),
                      ("required visual states", m["required_visual_states"]),
                      ("available source visual", m["available_source_visual"]),
                      ("missing production asset", m["missing_production_asset"]),
                      ("possible screen expansion", m["possible_screen_expansion"]),
                      ("popup / reveal implications", m["popup_reveal_implications"]),
                      ("learner-screen count impact", m["learner_screen_count_impact"]),
                      ("runtime-state count impact", m["runtime_state_count_impact"]),
                      ("decision still required", m["decision_still_required"])]), ""]
    parts += ["# 4. The obligations with no screen", "",
              f"{i['obligations_with_no_home']} of {i['obligations_total']} obligations do "
              "not land on any of the six candidates. They are the Siram, Baja and Racun "
              "subtopics — the material the v1 map compressed into three reveals on one "
              "screen. They are listed here rather than quietly absorbed:", "",
              _tbl(["Obligation", "Heading", "Ruling"],
                   [(v["visual_obligation_id"], v["governed_display_heading"],
                     v["bariah_ruling_locator"])
                    for v in D.VISUAL_OBLIGATIONS
                    if v["visual_obligation_id"] in i["unmapped_obligation_ids"]]), "",
              "# 5. B02 structure not propagated", "", i["b02_family_note"], ""]
    return _w("T04_SOURCE_TO_SCREEN_MAPPING_v2.md", "\n".join(parts))


def emit_mapping_json():
    return _j("T04_SOURCE_TO_SCREEN_MAPPING_v2.json", dict(
        pack="T04_SOURCE_TO_SCREEN_MAPPING", version="v2", stage=D.STAGE, unit_id=D.UNIT_ID,
        content_status=D.CONTENT_STATUS, approval_status=D.APPROVAL_STATUS,
        instructional_authority=D.INSTRUCTIONAL_AUTHORITY,
        final_screen_count=D.FINAL_SCREEN_COUNT,
        impact=D.MAPPING_IMPACT, screens=D.MAPPING_V2))


def emit_contracts_md():
    parts = [_hdr("T04 — SCREEN CONTRACTS DRAFT v2",
                  [f"CONTRACTS                = {len(D.CONTRACTS_V2)}",
                   f"FINAL_SCREEN_COUNT       = {D.FINAL_SCREEN_COUNT}",
                   f"APPROVED_ITEMS           = {D.APPROVED_ITEMS}"]),
             "Every contract carries its Stage 4.2F-B0.5 visual treatment as "
             "`superseded_visual_treatment` so the change Bariah's ruling forced is visible "
             "rather than overwritten.", ""]
    for c in D.CONTRACTS_V2:
        parts += [f"## {c['contract_id']} — {c['candidate_type']}", "",
                  "```",
                  f"revision                 = {c['revision']}",
                  f"source_rows              = {len(c['source_rows'])}",
                  f"visual_obligation_ids    = {', '.join(c['visual_obligation_ids']) or '—'}",
                  f"required_visual_states   = {c['required_visual_states']}",
                  f"missing_production_asset = {c['missing_production_asset']}",
                  f"visual_ruling_authority  = {c['visual_ruling_authority']}",
                  f"visual_subject_authority = {c['visual_subject_authority']}",
                  f"open_decision            = {c['open_decision']}",
                  f"bariah_approval          = {c['bariah_approval']['status']}",
                  "```", "",
                  f"**Learner-facing purpose.** {c['learner_facing_purpose']}", "",
                  f"**Base state.** {c['base_state']}", "",
                  "**Interaction states.** " + "; ".join(c["interaction_states"]), "",
                  f"**Completion.** {c['completion_condition']}", "",
                  f"**Visual treatment (v2).** {c['visual_treatment']}", "",
                  f"**Superseded visual treatment (v1).** {c['superseded_visual_treatment']}",
                  "",
                  f"**Text treatment.** {c['text_treatment']}", "",
                  f"**VO proposal.** {c['vo_proposal']}", "",
                  f"**Speaker Notes proposal.** {c['speaker_notes_proposal']}", "",
                  f"**Accessibility.** {c['accessibility_consideration']}", "",
                  f"**Fallback.** {c['fallback_behaviour']}", "",
                  f"**Source authority.** {c['source_authority']}", ""]
        if c.get("hidden_content_classification"):
            parts += [f"**Hidden content.** `{c['hidden_content_classification']}` — "
                      f"{c['hidden_content_justification']}", ""]
        if c.get("options"):
            parts += ["**Options, none chosen.**", ""]
            for o in c["options"]:
                parts += [f"- **{o['option']} — {o['label']}.** {o['grounding']} "
                          f"*Trade-off:* {o['tradeoff']}"]
            parts += [""]
    return _w("T04_SCREEN_CONTRACTS_DRAFT_v2.md", "\n".join(parts))


def emit_contracts_json():
    return _j("T04_SCREEN_CONTRACTS_DRAFT_v2.json", dict(
        pack="T04_SCREEN_CONTRACTS_DRAFT", version="v2", stage=D.STAGE, unit_id=D.UNIT_ID,
        content_status=D.CONTENT_STATUS, approval_status=D.APPROVAL_STATUS,
        instructional_authority=D.INSTRUCTIONAL_AUTHORITY,
        final_screen_count=D.FINAL_SCREEN_COUNT,
        approved_items=D.APPROVED_ITEMS, contracts=D.CONTRACTS_V2))


# ==========================================================================================
def emit_rumusan():
    r = D.RUMUSAN_V2
    parts = [_hdr("T04 — RUMUSAN, CAIR-ASSISTED DRAFT v2",
                  [f"STATEMENTS               = {len(r['statements'])}",
                   f"MEDIUM_RISK_STATEMENT    = {r['medium_risk_statement_id']}",
                   "STYLE_INSTRUCTION        = BR-W3 (Topik 3 Bahagian 2)",
                   "DRAFTING_AUTHORISED_BY   = BR-W1"]),
             "# 1. What Bariah instructed", "",
             "> Kuiz & Rumusan - Yes. please draft. I will check.", "",
             "> Rumusan - Follow writing style Topik 3 Bahagian 2", "",
             "A **style** instruction. It governs how the Rumusan is written, not what it "
             "says. Every fact below comes from T04 source rows.", "",
             "```",
             f"style_source     = {D.RUMUSAN_STYLE_SOURCE['unit']}",
             f"artifact         = {D.RUMUSAN_STYLE_SOURCE['artifact']}",
             f"authority        = {D.RUMUSAN_STYLE_SOURCE['authority']}",
             "```", "",
             f"**{D.RUMUSAN_STYLE_SOURCE['prohibition']}**", "",
             "# 2. Style characteristics extracted", "",
             _tbl(["Rule", "Characteristic", "Observed in Topik 3 Bahagian 2", "Applied to T04"],
                  [(s["rule_id"], s["characteristic"], s["observed"], s["applied_as"])
                   for s in D.RUMUSAN_STYLE_RULES]), "",
             "# 3. The draft", "",
             f"**{r['heading']}**", ""]
    for s in r["statements"]:
        parts += [f"## {s['statement_id']}", "",
                  f"> {s['draft_text']}", "",
                  "```",
                  f"source_row_ids      = {', '.join(s['source_row_ids'])}",
                  f"source_heading      = {s['source_heading']}",
                  f"style_rule_applied  = {', '.join(s['style_rule_applied'])}",
                  f"style_deviation     = {s['style_deviation'] or 'none'}",
                  "```", "",
                  f"**Factual risk.** {s['factual_risk_status']}", "",
                  "**Bariah review:** accept ☐  edit ☐  remove ☐  comment: "
                  "________________", ""]
    parts += ["# 4. Provenance", "", r["provenance"], "",
              "# 5. Five statements became four", "", D.RUMUSAN_CONSOLIDATION_NOTE, "",
              _tbl(["v1", "Topic", "v2", "Change"],
                   [(m["v1"], m["v1_topic"], m["v2"], m["change"])
                    for m in D.RUMUSAN_V1_TO_V2]), "",
              "# 6. The flagged generalisation", "",
              f"`{r['medium_risk_statement_id']}` carries a **MEDIUM** factual-risk flag. It "
              "is preserved deliberately, not smuggled through:", "",
              [s for s in r["statements"]
               if s["statement_id"] == r["medium_risk_statement_id"]][0]
              ["factual_risk_status"], ""]
    return _w("T04_RUMUSAN_CAIR_ASSISTED_DRAFT_v2.md", "\n".join(parts))


def emit_quiz():
    q = D.QUIZ_V2
    c = q["consolidation"]
    parts = [_hdr("T04 — QUIZ BLUEPRINT v2",
                  [f"QUIZ_COMPOSITION            = {q['quiz_composition']}",
                   f"COMPOSITION_RULE            = {q['composition_rule']}",
                   f"SCOPE                       = {q['scope']}",
                   f"PASS_THRESHOLD              = {q['pass_threshold']}",
                   f"QUIZ_CONTENT                = {q['quiz_content']}",
                   f"FINAL_INSTRUCTIONAL_AUTHORITY = {q['final_instructional_authority']}"]),
             "# 1. What is settled and what is not", "",
             "> Kuiz - 4 MCQ, 1 Multiple Response - Apply to ALL PLs in Kursus", "",
             f"Composition is `{q['quiz_composition']}` with scope `{q['scope']}` — not T04, "
             "not PL06, the whole Kursus.", "",
             f"The pass threshold is `{q['pass_threshold']}`. {q['threshold_note']}", "",
             "**Not produced:** " + ", ".join(q["not_produced"]) + ".", "",
             "# 2. The five slots", "",
             _tbl(["Slot", "Type", "Learning point", "Demand", "From"],
                  [(s["slot"], s["item_type"], s["source_learning_point"][:60],
                    s["cognitive_demand"], ", ".join(s["from_blueprint"]))
                   for s in q["slots"]]), ""]
    for s in q["slots"]:
        parts += [f"## {s['slot']} — {s['item_type']}", "",
                  "```",
                  f"source_learning_point = {s['source_learning_point']}",
                  f"source_row_ids        = {', '.join(s['source_row_ids'])}",
                  f"cognitive_demand      = {s['cognitive_demand']}",
                  f"from_blueprint        = {', '.join(s['from_blueprint'])}",
                  "```", "",
                  f"**Misconception assessed.** {s['misconception_to_assess']}", "",
                  f"**Correct-answer evidence.** {s['correct_answer_evidence']}", "",
                  f"**Visual dependency.** {s['visual_dependency']}", "",
                  f"**Why {s['item_type']}.** {s['why_this_type']}", "",
                  f"**Overlap.** {s['content_overlap']}", "",
                  f"**Bariah decision required.** {s['bariah_decision_required']}", ""]
    parts += ["# 3. Six coverage points into five slots", "", c["situation"], "",
              f"**{c['rule']}**", "",
              _tbl(["Coverage point", "Slot"],
                   [(u["point"], u["slot"]) for u in c["unmerged"]] +
                   [(", ".join(c["merged"]["from_points"]) + " — **merged**",
                     c["merged"]["into"])]), "",
              f"**The merge.** {c['merged']['justification']}", "",
              f"**What it costs.** {c['merged']['cost']}", "",
              f"`{c['accounting']}`", ""]
    return _w("T04_QUIZ_BLUEPRINT_v2.md", "\n".join(parts))


# ==========================================================================================
def emit_legal():
    L = D.LEGAL_CLARIFICATION
    t = D.LEGAL_TOTALS
    parts = [_hdr("T04 — LEGAL AND COMPLIANCE CONTENT CLARIFICATION (D-04)",
                  [f"STATUS                   = {L['status']}",
                   f"GROUPS                   = {t['groups']}",
                   f"ROWS                     = {t['rows']}",
                   f"MANDATORY                = {t['mandatory']}",
                   f"SUPPLEMENTARY_PROPOSED   = {t['supplementary']}",
                   f"APPLIED_TO_A_CONTRACT    = {L['applied_to_a_contract']}"]),
             "# 1. Bariah's question", ""]
    for qq in L["bariah_question"]:
        parts += [f"> {qq}", ""]
    parts += ["# 2. The answer", "", L["answer_to_bariah"], "",
              _tbl(["Group", "Rows"],
                   [(g["group"], len(g["rows"])) for g in L["groups"]] +
                   [("**TOTAL**", f"**{t['rows']}**")]), "",
              t["growth_note"], "",
              "# 3. Every row, individually", ""]
    for g in L["groups"]:
        parts += [f"## {g['group_id']} — {g['group']}", ""]
        for r in g["rows"]:
            parts += [f"### `{r['source_row_id']}` — {r['mandatory_or_supplementary']}", "",
                      f"> {r['source_wording']}", "",
                      _tbl(["Field", "Value"], [
                          ("proposed base-screen treatment",
                           r["proposed_base_screen_treatment"]),
                          ("proposed optional-reveal treatment",
                           r["proposed_optional_reveal_treatment"]),
                          ("mandatory or supplementary", r["mandatory_or_supplementary"]),
                          ("why", r["why"]),
                          ("visual requirement", r["visual_requirement"]),
                          ("Bariah confirmation", "☐ confirm  ☐ amend  comment: ______")]),
                      ""]
    parts += ["# 4. Recommendation", "", L["recommended_option"], "",
              f"Status: `{L['recommendation_status']}`.", "",
              L["supplementary_note"], "",
              "Reveal candidates: " +
              ", ".join(f"`{r}`" for r in L["supplementary_candidates"]) + ".", "",
              f"**Not applied.** {L['application_note']}", ""]
    return _w("T04_LEGAL_CONTENT_CLARIFICATION_v1.md", "\n".join(parts))


def emit_remaining():
    d3, d5 = D.D03_FOLLOWUP, D.D05_FOLLOWUP
    parts = [_hdr("T04 — REMAINING BARIAH DECISIONS",
                  [f"UNRESOLVED_ITEMS         = {len(D.REMAINING)}",
                   f"APPROVED_ITEMS           = {D.APPROVED_ITEMS}"]),
             "# 1. What is still open", "",
             _tbl(["#", "Decision", "Title", "Status", "Ask"],
                  [(r["item"], r["decision_id"], r["title"], r["status"], r["ask"])
                   for r in D.REMAINING]), ""]
    for r in D.REMAINING:
        parts += [f"### {r['item']}. {r['decision_id']} — {r['title']}", "",
                  f"**Status:** `{r['status']}`", "",
                  f"**Ask:** {r['ask']}", "",
                  f"**Why it is open:** {r['why_unresolved']}", ""]
    parts += ["# 2. Not asked again", "",
              "These were given clearly and are not re-opened:", ""]
    parts += [f"- {x}" for x in D.NOT_ASKED_AGAIN] + [""]
    parts += ["# 3. D-03 — T04 cast", "",
              f"**Status:** `{d3['status']}` · **Scope:** `{d3['scope']}`", "",
              f"*{d3['scope_guard']}*", "", d3["question"], ""]
    for o in d3["options"]:
        parts += [f"- **{o['option']}. {o['label']}** — {o['note']}"]
    parts += ["", f"**Prior recommendation:** `{d3['prior_recommendation_status']}`. "
                  f"{d3['prior_recommendation']}", "",
              "# 4. D-05 — SmartArt review and MMD treatment", "",
              f"**Status:** `{d5['status']}`", "",
              f"**Already confirmed:** `{d5['confirmed']['ruling']}` "
              f"({d5['confirmed']['evidence']}) — a visual is required for every step.", "",
              "**Three confirmations still needed:**", ""]
    for cc in d5["confirmations_required"]:
        parts += [f"### {cc['item']}. {cc['ask']}", "",
                  f"`{cc['status']}` — {cc['why']}", ""]
    parts += ["## The six source nodes, in order", "",
              _tbl(["#", "Node label"],
                   [(n["position"], n["label"]) for n in d5["six_nodes_in_order"]]), "",
              "```",
              f"asset_id   = {d5['node_evidence']['asset_id']}",
              f"part       = {d5['node_evidence']['part']}",
              f"sha256     = {d5['node_evidence']['sha256']}",
              f"layout     = {d5['node_evidence']['layout']}",
              f"hierarchy  = {d5['node_evidence']['hierarchy']}",
              f"node_count = {d5['node_evidence']['node_count']}",
              f"production = {d5['production_status']}",
              "```", ""]
    return _w("T04_REMAINING_BARIAH_DECISIONS_v1.md", "\n".join(parts))


def emit_whatsapp():
    w = D.WHATSAPP
    parts = [_hdr("T04 — BARIAH WHATSAPP FOLLOW-UP DRAFT",
                  [f"STATUS                   = {w['status']}",
                   f"LANGUAGE                 = {w['language']}",
                   f"SENDING_AUTHORITY        = {w['sending_authority']}"]),
             f"**`{w['status']}`.** Sending is {w['sending_authority']}'s call, not CAIR's. "
             "This file is the text only.", "",
             "# Message", "", "```", w["text"], "```", "",
             "# Constraints honoured", ""]
    parts += [f"- {x}" for x in w["constraints_honoured"]] + [""]
    parts += ["# Not asked again", ""]
    parts += [f"- {x}" for x in D.NOT_ASKED_AGAIN] + [""]
    return _w("T04_BARIAH_WHATSAPP_FOLLOWUP_DRAFT_v1.md", "\n".join(parts))


EMITTERS = [emit_rulings, emit_rulings_json, emit_inventory_md, emit_inventory_csv,
            emit_inventory_json, emit_mapping_md, emit_mapping_json, emit_contracts_md,
            emit_contracts_json, emit_rumusan, emit_quiz, emit_legal, emit_remaining,
            emit_whatsapp]

if __name__ == "__main__":
    written = [e() for e in EMITTERS]
    for n in written:
        print("wrote", n)
    print(f"{len(written)} files")
