# -*- coding: utf-8 -*-
"""Stage 4.2F-B1.1 Lane A — build the state-review appendix PPTX and emit the registers.

The appendix is a SEPARATE deck. The B1 layout storyboard is not hand-edited and not
regenerated with different content: it still answers "what does each screen look like", and
the appendix answers "what does each runtime state do". Two questions, two artifacts.

Two state panels per page, never mixing screens. Each panel answers all five coverage
criteria on its face — trigger, content, difference from base, return behaviour, bindings —
because a state recorded only in Notes or JSON is not review-visible by this stage's own
definition.
"""
import json
import os
import sys

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.util import Emu, Pt

HERE = os.path.dirname(os.path.abspath(__file__))
T04 = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(os.path.dirname(T04)))
sys.path.insert(0, HERE)
import t04_state_model_v1 as SM       # noqa: E402
import t04_state_coverage_v1 as CV    # noqa: E402
import t04_storyboard_model_v1 as SB  # noqa: E402
import t04_storyboard_build_v1 as BB  # noqa: E402

OUT = os.path.abspath(os.path.join(HERE, ".."))
BANNER = (f"<!-- GENERATED by {SM.GENERATED_BY} — Stage {SM.STAGE}. "
          "Edit the model, not this file. -->")
PREVIEW_DIR = os.path.join(OUT, "state_appendix_preview")

SLIDE_W, SLIDE_H, MARGIN = BB.SLIDE_W, BB.SLIDE_H, BB.MARGIN
INK, MUTED, RULE = BB.INK, BB.MUTED, BB.RULE
AUTH, SRC, PLACEHOLDER = BB.AUTH, BB.SRC, BB.PLACEHOLDER
BASECOL = RGBColor(0x37, 0x47, 0x4F)

KIND_LABEL_MS = {
    "BASE": "Keadaan asas",
    "REVEAL": "Panel pendedahan",
    "STEP": "Langkah proses",
    "QUIZ_ITEM": "Item kuiz",
    "QUIZ_RESULT": "Keputusan kuiz",
    "COMPLETION": "Penanda selesai",
}
FIELD_LABEL_MS = {
    "trigger": "Pencetus",
    "content": "Apa yang dipaparkan",
    "diff": "Beza daripada keadaan asas",
    "return": "Cara pelajar kembali / meneruskan",
    "bind": "Sumber dan kuasa",
}


def _tf(slide, x, y, w, h):
    box = slide.shapes.add_textbox(x, y, w, h)
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = Emu(0)
    tf.margin_top = tf.margin_bottom = Emu(0)
    return tf


def _panel_bg(slide, x, y, w, h):
    sh = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, x, y, w, h)
    sh.fill.solid()
    sh.fill.fore_color.rgb = RGBColor(0xF7, 0xF7, 0xF7)
    sh.line.color.rgb = RULE
    sh.shadow.inherit = False
    return sh


def _state_panel(slide, st, x, y, w, h):
    _panel_bg(slide, x, y, w, h)
    pad = Emu(180000)
    tf = _tf(slide, Emu(x + pad), Emu(y + pad), Emu(w - 2 * pad), Emu(h - 2 * pad))
    colour = AUTH if st["state_kind"] == "BASE" else BASECOL

    BB._p(tf, f"{st['state_id']}   ·   {KIND_LABEL_MS[st['state_kind']]}", 11, MUTED,
          bold=True, first=True)
    BB._p(tf, f"{FIELD_LABEL_MS['trigger']}: {st['trigger_label']}"
              + (f"  [{st['trigger_id']}]" if st["trigger_id"] else ""), 12, colour,
          bold=True)

    BB._p(tf, FIELD_LABEL_MS["content"], 10, MUTED, bold=True)
    if st["content_block_texts"]:
        for t in st["content_block_texts"][:7]:
            BB._p(tf, f"· {t}", 10, INK, indent=1)
        if len(st["content_block_texts"]) > 7:
            BB._p(tf, f"· … {len(st['content_block_texts']) - 7} rekod lagi", 9, MUTED,
                  indent=1)
    else:
        BB._p(tf, "Tiada kandungan dipaparkan — penanda sahaja.", 10, MUTED, indent=1,
              italic=True)

    BB._p(tf, FIELD_LABEL_MS["diff"], 10, MUTED, bold=True)
    BB._p(tf, st["differs_from_base_ms"], 10, INK, indent=1)

    BB._p(tf, FIELD_LABEL_MS["return"], 10, MUTED, bold=True)
    BB._p(tf, st["return_behaviour_ms"], 10, INK, indent=1)

    BB._p(tf, FIELD_LABEL_MS["bind"], 10, MUTED, bold=True)
    BB._p(tf, ("Baris: " + ", ".join(st["source_row_ids"])) if st["source_row_ids"]
          else "Tiada baris modul — keadaan struktur", 9, SRC, indent=1)
    BB._p(tf, "Keputusan: " + (", ".join(st["decision_ids"]) or "—"), 9, MUTED, indent=1)
    if st.get("binding_limitation"):
        BB._p(tf, "HAD: " + st["binding_limitation_ms"], 9, PLACEHOLDER, indent=1)


# ==========================================================================================
# MEASURED RENDERER CAPACITY
#
# How many panels a page can actually hold is a property of the geometry and of the real
# panel content, not of CV.PANELS_PER_PAGE. This lays out every state's panel at each
# candidate width and reports the widest arrangement in which nothing overflows its box.
# It is the independent oracle for the panel budget, the same way RENDERER_LINE_CAPACITY is
# the independent oracle for the storyboard page budget.
PANEL_CAPACITY_PROBE_MAX = 6


def _panel_wrapped_height(draw, font, st, content_width):
    """Panel height in preview pixels, wrapped with the font the previews actually use."""
    y = 130

    def line(txt, f, indent=0):
        nonlocal y
        words, cur = txt.split(), ""
        for w in words:
            probe = (cur + " " + w).strip()
            if draw.textlength(probe, font=f) > content_width - indent:
                y += 15
                cur = w
            else:
                cur = probe
        if cur:
            y += 16

    line(f"{st['state_id']}  ·  {KIND_LABEL_MS[st['state_kind']]}", font(11, True))
    line(f"Pencetus: {st['trigger_label']}", font(12, True))
    line(FIELD_LABEL_MS["content"], font(10, True))
    for t in st["content_block_texts"][:6]:
        line("· " + t, font(10), 8)
    if len(st["content_block_texts"]) > 6:
        line(f"· … {len(st['content_block_texts']) - 6} rekod lagi", font(9), 8)
    if not st["content_block_texts"]:
        line("Tiada kandungan — penanda sahaja.", font(10), 8)
    line(FIELD_LABEL_MS["diff"], font(10, True))
    line(st["differs_from_base_ms"], font(10), 8)
    line(FIELD_LABEL_MS["return"], font(10, True))
    line(st["return_behaviour_ms"], font(10), 8)
    line(FIELD_LABEL_MS["bind"], font(10, True))
    line(("Baris: " + ", ".join(st["source_row_ids"])) if st["source_row_ids"]
         else "Tiada baris modul", font(9), 8)
    if st.get("binding_limitation"):
        line("HAD: " + st["binding_limitation_ms"], font(9), 8)
    return y


def renderer_panel_capacity():
    """Widest panels-per-page arrangement in which no state's panel overflows its box.

    Recomputed on every call on purpose: a cached module constant would stop reflecting the
    inventory it is measured from, which is exactly the live-derivation defect this suite
    already guards against elsewhere.
    """
    from PIL import Image, ImageDraw, ImageFont

    def font(sz, bold=False):
        base = "/usr/share/fonts/truetype/liberation/"
        nm = "LiberationSans-Bold.ttf" if bold else "LiberationSans-Regular.ttf"
        return ImageFont.truetype(base + nm, sz)

    W, H = 1280, 720
    draw = ImageDraw.Draw(Image.new("RGB", (W, H), (255, 255, 255)))
    states = SM.states()
    best = 0
    for n in range(1, PANEL_CAPACITY_PROBE_MAX + 1):
        pw = (W - 96 - (n - 1) * 20) // n
        if any(_panel_wrapped_height(draw, font, st, pw - 24) > H - 84 for st in states):
            break
        best = n
    return best


def build_appendix():
    prs = Presentation()
    prs.slide_width, prs.slide_height = SLIDE_W, SLIDE_H

    # Cover
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    tf = _tf(slide, MARGIN, Emu(1600200), Emu(SLIDE_W - 2 * MARGIN), Emu(2600000))
    BB._p(tf, "LAMPIRAN SEMAKAN KEADAAN RUNTIME", 16, MUTED, bold=True, first=True)
    BB._p(tf, f"{SB.LEARNER_DISPLAY_UNIT}: {SB.LEARNER_DISPLAY_UNIT_TITLE}", 32, INK,
          bold=True)
    t = SM.totals()
    BB._p(tf, f"{t['total_runtime_states']} keadaan runtime merentas "
              f"{t['learner_screens']} skrin", 16, MUTED)
    BB._p(tf, "", 10)
    BB._p(tf, "Lampiran ini melengkapkan storyboard susun atur. Storyboard menunjukkan rupa "
              "setiap skrin; lampiran ini menunjukkan apa yang berlaku dalam setiap keadaan.",
          11, MUTED, italic=True)
    BB._p(tf, "Setiap panel menjawab lima perkara: pencetus, kandungan, beza daripada "
              "keadaan asas, cara kembali, dan sumber serta kuasa.", 11, MUTED, italic=True)
    BB._p(tf, f"Rujukan dalaman: {SB.INTERNAL_UNIT_ID}", 10, MUTED, italic=True)

    for page in CV.appendix_pages():
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        sc = next(s for s in SB.screens() if s["screen_id"] == page["screen_id"])
        tf = _tf(slide, MARGIN, Emu(320000), Emu(SLIDE_W - 2 * MARGIN), Emu(700000))
        BB._p(tf, f"{sc['screen_id']}   ·   {sc['treatment']}", 11, MUTED, bold=True,
              first=True)
        BB._p(tf, sc["title_ms"], 22, INK, bold=True)
        BB._rule(slide, Emu(1120000))

        n = len(page["states"])
        gap = Emu(200000)
        pw = Emu(int((SLIDE_W - 2 * MARGIN - (n - 1) * gap) / n))
        for i, st in enumerate(page["states"]):
            _state_panel(slide, st, Emu(int(MARGIN + i * (pw + gap))), Emu(1280000),
                         pw, Emu(4700000))

        tf = _tf(slide, MARGIN, Emu(6150000), Emu(SLIDE_W - 2 * MARGIN), Emu(400000))
        BB._p(tf, f"Lampiran keadaan · halaman {page['page_no']} daripada "
                  f"{len(CV.appendix_pages())}", 9, MUTED, first=True)

    os.makedirs(CV.APPENDIX_DIR, exist_ok=True)
    path = os.path.join(CV.APPENDIX_DIR, CV.APPENDIX_NAME)
    prs.save(path)
    return path


# ==========================================================================================
def render_appendix_previews():
    from PIL import Image, ImageDraw, ImageFont

    def font(sz, bold=False):
        base = "/usr/share/fonts/truetype/liberation/"
        nm = "LiberationSans-Bold.ttf" if bold else "LiberationSans-Regular.ttf"
        try:
            return ImageFont.truetype(base + nm, sz)
        except Exception:
            return ImageFont.load_default()

    os.makedirs(PREVIEW_DIR, exist_ok=True)
    for f in os.listdir(PREVIEW_DIR):
        if f.endswith(".png"):
            os.remove(os.path.join(PREVIEW_DIR, f))

    W, H = 1280, 720
    made = []
    pages = CV.appendix_pages()
    for page in pages:
        sc = next(s for s in SB.screens() if s["screen_id"] == page["screen_id"])
        img = Image.new("RGB", (W, H), (255, 255, 255))
        d = ImageDraw.Draw(img)
        d.text((48, 34), f"{sc['screen_id']}  ·  {sc['treatment']}", font=font(14, True),
               fill=(107, 107, 107))
        d.text((48, 56), sc["title_ms"], font=font(24, True), fill=(26, 26, 26))
        d.line([(48, 100), (W - 48, 100)], fill=(216, 216, 216), width=2)

        n = len(page["states"])
        pw = (W - 96 - (n - 1) * 20) // n
        overflow = False
        for i, st in enumerate(page["states"]):
            px = 48 + i * (pw + 20)
            d.rectangle([px, 116, px + pw, H - 70], fill=(247, 247, 247),
                        outline=(216, 216, 216))
            y = 130
            cx = px + 12
            cw = pw - 24

            def line(txt, f, fill, indent=0):
                nonlocal y, overflow
                words, cur = txt.split(), ""
                for w in words:
                    probe = (cur + " " + w).strip()
                    if d.textlength(probe, font=f) > cw - indent:
                        d.text((cx + indent, y), cur, font=f, fill=fill)
                        y += 15
                        cur = w
                    else:
                        cur = probe
                if cur:
                    d.text((cx + indent, y), cur, font=f, fill=fill)
                    y += 16
                if y > H - 84:
                    overflow = True

            line(f"{st['state_id']}  ·  {KIND_LABEL_MS[st['state_kind']]}", font(11, True),
                 (107, 107, 107))
            line(f"Pencetus: {st['trigger_label']}", font(12, True), (55, 71, 79))
            line("Apa yang dipaparkan", font(10, True), (107, 107, 107))
            for t in st["content_block_texts"][:6]:
                line("· " + t, font(10), (26, 26, 26), 8)
            if len(st["content_block_texts"]) > 6:
                line(f"· … {len(st['content_block_texts']) - 6} rekod lagi", font(9),
                     (107, 107, 107), 8)
            if not st["content_block_texts"]:
                line("Tiada kandungan — penanda sahaja.", font(10), (107, 107, 107), 8)
            line("Beza daripada keadaan asas", font(10, True), (107, 107, 107))
            line(st["differs_from_base_ms"], font(10), (26, 26, 26), 8)
            line("Cara kembali / meneruskan", font(10, True), (107, 107, 107))
            line(st["return_behaviour_ms"], font(10), (26, 26, 26), 8)
            line("Sumber dan kuasa", font(10, True), (107, 107, 107))
            line(("Baris: " + ", ".join(st["source_row_ids"])) if st["source_row_ids"]
                 else "Tiada baris modul", font(9), (13, 71, 161), 8)
            if st.get("binding_limitation"):
                line("HAD: " + st["binding_limitation_ms"], font(9), (183, 28, 28), 8)

        d.line([(48, H - 60), (W - 48, H - 60)], fill=(216, 216, 216), width=1)
        d.text((48, H - 48),
               f"Lampiran keadaan · halaman {page['page_no']} daripada {len(pages)}",
               font=font(11), fill=(107, 107, 107))
        p = os.path.join(PREVIEW_DIR, f"A{page['page_no']:02d}.png")
        img.save(p)
        made.append(dict(path=p, page_no=page["page_no"], overflowed=overflow))
    return made


# ==========================================================================================
def _w(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text if text.endswith("\n") else text + "\n")
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1))


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def _hdr(title, extra=()):
    return "\n".join([BANNER, "", f"# {title}", "", "```",
                      f"STAGE    = {SM.STAGE}",
                      f"SUITE_ID = {SM.SUITE_ID}",
                      f"STATUS   = {SM.CURRENT_STATUS}"] + list(extra) + ["```", ""])


NEW_ARTIFACTS = [
    "T04_RUNTIME_STATE_INVENTORY_v1.json", "T04_RUNTIME_STATE_INVENTORY_v1.md",
    "T04_STATE_REVIEW_COVERAGE_v1.json", "T04_STATE_REVIEW_COVERAGE_v1.md",
    "T04_SOURCE_ROW_AUDIT_v1.json", "T04_SOURCE_ROW_AUDIT_v1.md",
    "T04_LIVE_NAMESPACE_ALIAS_MAP_v1.json", "T04_LIVE_NAMESPACE_ALIAS_MAP_v1.md",
    "T04_ORACLE_INDEPENDENCE_AUDIT_v1.json", "T04_ORACLE_INDEPENDENCE_AUDIT_v1.md",
    "T04_STATE_ROLL_AUDIT_v1.json", "T04_STATE_ROLL_AUDIT_v1.md",
    "T04_NATIVE_POWERPOINT_INSPECTION_PACKAGE_v1.json",
    "T04_NATIVE_POWERPOINT_INSPECTION_PACKAGE_v1.md",
]


def emit_all():
    files = []
    st = SM.states()
    t = SM.totals()

    files.append(_j("T04_RUNTIME_STATE_INVENTORY_v1.json",
                    dict(stage=SM.STAGE, status=SM.CURRENT_STATUS,
                         forbidden_status_claims=SM.FORBIDDEN_STATUS_CLAIMS,
                         totals=t, verification=SM.verification(), states=st)))
    p = [_hdr("T04 — RUNTIME STATE INVENTORY",
              [f"LEARNER_SCREENS      = {t['learner_screens']}",
               f"BASE_STATES          = {t['base_states']}",
               f"TRIGGERED_STATES     = {t['triggered_states']}",
               f"COMPLETION_FLAGS     = {t['completion_flags']}",
               f"TOTAL_RUNTIME_STATES = {t['total_runtime_states']}",
               f"INTERACTIONS         = {t['interactions']}",
               f"REVIEW_PAGES_B1      = {t['review_pages_b1']}"]),
         "Derived from the controlled model, never from the deck's page count. Reveal targets "
         "are declared per screen and then verified against that screen's own controlled "
         "rows.", "",
         _tbl(["Screen", "State", "Kind", "Trigger", "Records", "Bindings"],
              [(x["screen_id"], x["state_id"], x["state_kind"], x["trigger_label"],
                x["content_record_count"],
                ", ".join(x["source_row_ids"]) or "structural") for x in st]), "",
         "# Verification of declared reveal targets", "",
         _tbl(["Screen", "Declared states", "Declared targets", "Agree", "Rows outside"],
              [(v["screen_id"], v["declared_reveal_states"], v["declared_targets"],
                "yes" if v["counts_agree"] else "**NO**",
                ", ".join(v["rows_outside_the_screen"]) or "none")
               for v in SM.verification()]), ""]
    files.append(_w("T04_RUNTIME_STATE_INVENTORY_v1.md", "\n".join(p)))

    roll = SM.roll_audit()
    plan = CV.frozen_plan_audit()
    cap = renderer_panel_capacity()
    files.append(_j("T04_STATE_ROLL_AUDIT_v1.json",
                    dict(stage=SM.STAGE,
                         why=("The frozen roll is the independent anchor for every state "
                              "count. Plan-versus-deck gates cannot see a state leave the "
                              "model, because both sides are projected from it."),
                         declared_total=SM.DECLARED_TOTAL_RUNTIME_STATES,
                         frozen_state_ids=SM.DECLARED_STATE_IDS,
                         frozen_panel_state_ids=CV.DECLARED_PANEL_STATE_IDS,
                         frozen_full_page_state_ids=CV.DECLARED_FULL_PAGE_STATE_IDS,
                         roll_audit=roll, plan_audit=plan,
                         panel_budget=dict(
                             declared=CV.PANELS_PER_PAGE,
                             literal=CV.PANEL_BUDGET_LITERAL,
                             basis=CV.PANEL_BUDGET_BASIS,
                             measured_renderer_capacity=cap,
                             probe_max=PANEL_CAPACITY_PROBE_MAX))))
    p = [_hdr("T04 — FROZEN STATE ROLL AUDIT",
              [f"DECLARED_TOTAL_RUNTIME_STATES = {SM.DECLARED_TOTAL_RUNTIME_STATES}",
               f"LIVE_STATE_COUNT              = {roll['live_count']}",
               f"FROZEN_PANEL_STATES           = {plan['frozen_panel_count']}",
               f"FROZEN_FULL_PAGE_STATES       = {plan['frozen_full_page_count']}",
               f"PAGES_FROM_THE_FROZEN_ROLL    = "
               f"{plan['pages_expected_from_the_frozen_roll']}",
               f"PANEL_BUDGET                  = {CV.PANEL_BUDGET_LITERAL}",
               f"MEASURED_RENDERER_CAPACITY    = {cap}"]),
         "Mutation fixture A-03 deleted one runtime state and rebuilt the appendix. Every "
         "appendix gate still passed: the page plan and the deck were both projected from "
         "the mutated inventory, so they agreed with each other about a state that no longer "
         "existed. The roll below is the reviewed inventory written down by hand and never "
         "derived from `states()`, so a state that leaves the model now fails a gate.", "",
         "Fixture A-01 exposed the same shape in the panel budget: the gate compared pages "
         "built from `PANELS_PER_PAGE` against `PANELS_PER_PAGE`. The budget is now checked "
         "against a literal, and separately against a capacity measured by laying every "
         f"panel out at each candidate width — {cap} panels fit before anything overflows, "
         "so the two-panel rule is a review-legibility policy, stricter than the renderer.",
         "",
         _tbl(["Check", "Result"],
              [("Live inventory equals the frozen roll", "yes" if roll["agrees"] else "**NO**"),
               ("Missing from live", ", ".join(roll["missing_from_live"]) or "none"),
               ("Added to live", ", ".join(roll["added_to_live"]) or "none"),
               ("Duplicate live IDs", ", ".join(roll["duplicate_live_ids"]) or "none"),
               ("Frozen panel states missing from the plan",
                ", ".join(plan["missing_from_the_plan"]) or "none"),
               ("Planned states not on the frozen roll",
                ", ".join(plan["added_to_the_plan"]) or "none"),
               ("The two rolls are disjoint",
                "yes" if plan["rolls_are_disjoint"] else "**NO**"),
               ("The two rolls cover the state roll",
                "yes" if plan["rolls_cover_the_state_roll"] else "**NO**")]), ""]
    files.append(_w("T04_STATE_ROLL_AUDIT_v1.md", "\n".join(p)))

    before = CV.coverage_report(False)
    after = CV.coverage_report(True)
    files.append(_j("T04_STATE_REVIEW_COVERAGE_v1.json",
                    dict(stage=SM.STAGE, criteria=CV.COVERAGE_CRITERIA,
                         before_appendix=before, after_appendix=after,
                         decision_before=CV.decision(False),
                         decision_after=CV.decision(True),
                         appendix=dict(name=CV.APPENDIX_NAME,
                                       pages=len(CV.appendix_pages()),
                                       panels_per_page=CV.PANELS_PER_PAGE),
                         matrix=CV.matrix(True))))
    p = [_hdr("T04 — STATE REVIEW COVERAGE MATRIX",
              [f"TOTAL_STATES        = {after['total_states']}",
               f"BEFORE_APPENDIX     = {before['represented_states']} covered, "
               f"{before['unrepresented_count']} not",
               f"AFTER_APPENDIX      = {after['represented_states']} covered, "
               f"{after['unrepresented_count']} not",
               f"DECISION            = {CV.decision(True)}"]),
         "A state is review-covered only if the artifact answers all five of these:", ""]
    p += [f"{i + 1}. {c}" for i, c in enumerate(CV.COVERAGE_CRITERIA)]
    p += ["", "Text being present somewhere on the page satisfies none of 1, 3 or 4, and a "
          "state name in a list satisfies none of them at all.", "",
          "# Before the appendix", "",
          _tbl(["Class", "States"], list(before["by_class"].items())), "",
          "# After the appendix", "",
          _tbl(["Class", "States"], list(after["by_class"].items())), "",
          _tbl(["Check", "Result"], [
              ("duplicate representations", after["duplicate_representations"] or "none"),
              ("orphan review panels", after["orphan_review_panels"] or "none"),
              ("pages with no state mapping", after["review_pages_with_no_state_mapping"]),
              ("cover page, declared", after["cover_page_declared"]),
              ("unmapped excluding cover",
               after["unmapped_pages_excluding_cover"] or "none"),
              ("every state uniquely mapped", after["every_state_uniquely_mapped"]),
          ]), "",
          "# The matrix", "",
          _tbl(["State", "Screen", "Trigger", "B1 page", "Appendix", "Representation"],
               [(r["state_id"], r["screen_id"], r["trigger_label"], r["b1_review_page"],
                 r["appendix_page"] or "—", r["representation"])
                for r in CV.matrix(True)]), ""]
    files.append(_w("T04_STATE_REVIEW_COVERAGE_v1.md", "\n".join(p)))

    aud = CV.source_row_audit()
    files.append(_j("T04_SOURCE_ROW_AUDIT_v1.json",
                    dict(stage=SM.STAGE, audited=CV.AUDITED_ROW_IDS,
                         not_found_token=CV.NOT_FOUND_TOKEN, rows=aud)))
    p = [_hdr("T04 — BRIEF-REFERENCED SOURCE ROW AUDIT",
              [f"AUDITED   = {len(aud)}",
               f"FOUND     = {len([r for r in aud if r['exists']])}",
               f"NOT_FOUND = {len([r for r in aud if not r['exists']])}"]),
         "Each ID checked directly against the controlled extract. A missing ID would be "
         "recorded as `" + CV.NOT_FOUND_TOKEN + "` and no replacement binding would be "
         "manufactured.", ""]
    for r in aud:
        if not r["exists"]:
            p += [f"## {r['row_id']} — `{r['status']}`", "",
                  "Not present in the controlled extract. No replacement was manufactured.",
                  ""]
            continue
        sp = r["source_position"]
        p += [f"## {r['row_id']}", "",
              f"> {r['controlled_source_text']}", "",
              _tbl(["Field", "Value"], [
                  ("exists", "yes"),
                  ("module page", sp and r["module_page"]),
                  ("sequence", sp["sequence"]),
                  ("paragraph range", f"{sp['paragraph_start']}–{sp['paragraph_end']}"),
                  ("content type", sp["content_type"]),
                  ("heading path", " › ".join(sp["heading_path"])),
                  ("used in states", ", ".join(r["used_in_states"])),
                  ("semantic binding", f"**{r['semantic_binding']}**"),
              ]), "",
              _tbl(["Option set", "#", "Relation", "Proposed key", "Option text"],
                   [(l["option_set"], l["position"], l["relation"],
                     "yes" if l["is_proposed_key"] else "no", l["option_text"])
                    for l in r["q5_links"]] or [("—", "—", "—", "—",
                                                 "no Q5 option links to this row")]), "",
              r["semantic_binding_note"], ""]
    files.append(_w("T04_SOURCE_ROW_AUDIT_v1.md", "\n".join(p)))

    al = CV.alias_map_report()
    files.append(_j("T04_LIVE_NAMESPACE_ALIAS_MAP_v1.json", dict(stage=SM.STAGE, **al)))
    p = [_hdr("T04 — LIVE NAMESPACE ALIAS MAP",
              [f"REGISTERS   = {', '.join(al['registers'])}",
               f"LIVE_ITEMS  = {al['live_count']}",
               f"COLLISIONS  = {al['unqualified_collisions'] or 'none'}"]),
         "Historical `E-*` identifiers were one flat series covering two different kinds of "
         "thing. The historical records are **not** rewritten — this is an alias map, not a "
         "migration.", "",
         _tbl(["Historical", "Live", "Register", "Subject", "Disposition"],
              [(a["historical_id"], a["live_id"] or "—", a["register"] or "—",
                a["subject"], a["disposition"]) for a in al["alias_rows"]]), "",
         "# Raised by this stage", "",
         _tbl(["Live ID", "Register", "Subject", "Owner", "Blocks"],
              [(n["live_id"], n["register"], n["subject"], n["owner"], n["blocking"])
               for n in al["new_items"]]), "",
         _tbl(["Check", "Result"], [
             ("every historical E-* accounted for",
              al["every_historical_id_accounted"]),
             ("unqualified identifier collisions",
              al["unqualified_collisions"] or "none"),
             ("historical records rewritten", al["historical_records_rewritten"]),
         ]), ""]
    files.append(_w("T04_LIVE_NAMESPACE_ALIAS_MAP_v1.md", "\n".join(p)))

    oa = CV.oracle_audit()
    files.append(_j("T04_ORACLE_INDEPENDENCE_AUDIT_v1.json", dict(stage=SM.STAGE, **oa)))
    p = [_hdr("T04 — ORACLE INDEPENDENCE AUDIT",
              [f"RELEASE_CRITICAL_GATES = {oa['release_critical_gates']}",
               f"ORACLE_INDEPENDENT     = {oa['oracle_independent']}",
               f"SHARED_GENERATOR       = {len(oa['shared_generator'])}"]),
         "A check is only worth what its reference point is worth. Two gates in this project "
         "passed while validating a value against its own source, and both were caught by "
         "fixtures rather than by review.", "",
         _tbl(["Gate", "Suite", "Expected from", "Observed from", "Shares helper",
               "Independent"],
              [(r["gate_id"], r["suite"], r["expected_value_source"],
                r["observed_value_source"],
                "yes" if r["expected_and_observed_share_a_generator_helper"] else "no",
                "yes" if r["oracle_independent"] else "**no**") for r in oa["rows"]]), "",
         "# The two that were fixed after a fixture found them", ""]
    for r in oa["rows"]:
        if r["history"]:
            p += [f"**{r['gate_id']}** — {r['history']}", ""]
    p += ["# The one that shares a helper, and why that is acceptable here", ""]
    for r in oa["rows"]:
        if r["expected_and_observed_share_a_generator_helper"]:
            p += [f"**{r['gate_id']}** — {r['justification']}", ""]
    p += ["# Protections preserved", ""]
    p += [f"- {x}" for x in oa["preserved_protections"]]
    p += [""]
    files.append(_w("T04_ORACLE_INDEPENDENCE_AUDIT_v1.md", "\n".join(p)))

    files += emit_inspection_package()
    return files


def emit_inspection_package():
    import hashlib
    b1 = os.path.join(SB.PPTX_DIR, SB.PPTX_NAME)
    ap = os.path.join(CV.APPENDIX_DIR, CV.APPENDIX_NAME)
    pkg = dict(
        stage=SM.STAGE,
        purpose=("A compact brief for opening these decks in real Microsoft PowerPoint or "
                 "the Claude PowerPoint plugin, and for recording what is found."),
        artifacts=[
            dict(role="layout storyboard", path=os.path.relpath(b1, REPO),
                 bytes=os.path.getsize(b1),
                 sha256=hashlib.sha256(open(b1, "rb").read()).hexdigest(),
                 slides=len(SB.slides()) + 1),
            dict(role="state review appendix", path=os.path.relpath(ap, REPO),
                 bytes=os.path.getsize(ap),
                 sha256=hashlib.sha256(open(ap, "rb").read()).hexdigest(),
                 slides=len(CV.appendix_pages()) + 1),
        ],
        learner_screen_to_review_page={
            s["screen_id"]: [f"p{i + 2}" for i, sl in enumerate(SB.slides())
                             if sl["screen_id"] == s["screen_id"]]
            for s in SB.screens()},
        runtime_state_to_review_page={r["state_id"]: dict(
            b1=r["b1_review_page"], appendix=r["appendix_page"]) for r in CV.matrix(True)},
        continuation_pages=[dict(screen_id=sl["screen_id"], page=f"p{i + 2}",
                                 page_index=sl["page_index"], page_count=sl["page_count"])
                            for i, sl in enumerate(SB.slides()) if sl["is_continuation"]],
        font_inventory=dict(b1=CV.font_inventory(b1), appendix=CV.font_inventory(ap)),
        master_and_layout_usage=dict(b1=CV.layout_usage(b1), appendix=CV.layout_usage(ap)),
        notes_and_metadata=dict(b1=CV.notes_inventory(b1), appendix=CV.notes_inventory(ap)),
        interaction_ids=sorted({s["trigger_id"] for s in SM.states() if s["trigger_id"]}),
        visual_obligation_mapping={s["screen_id"]: s["visual"]["visual_obligations_served"]
                                   for s in SB.screens()},
        known_open_statuses=CV.alias_map_report()["by_register"],
        native_render_status=BB.RENDER_STATUS,
        correction_intake_template=dict(fields=CV.CORRECTION_INTAKE_FIELDS,
                                        policy=CV.CORRECTION_POLICY),
    )
    a = _j("T04_NATIVE_POWERPOINT_INSPECTION_PACKAGE_v1.json", pkg)
    p = [_hdr("T04 — NATIVE POWERPOINT INSPECTION PACKAGE",
              [f"ARTIFACTS = {len(pkg['artifacts'])}",
               f"RENDER    = {pkg['native_render_status']}"]),
         pkg["purpose"], "",
         "# 1. Artifacts", "",
         _tbl(["Role", "Path", "Bytes", "Slides", "SHA-256"],
              [(x["role"], f"`{x['path']}`", x["bytes"], x["slides"], x["sha256"][:16] + "…")
               for x in pkg["artifacts"]]), "",
         "# 2. Fonts", "",
         _tbl(["Deck", "Typefaces"],
              [("layout storyboard", ", ".join(pkg["font_inventory"]["b1"])),
               ("state appendix", ", ".join(pkg["font_inventory"]["appendix"]))]), "",
         "Arial is requested throughout. It is **not** embedded — PowerPoint will substitute "
         "if the machine lacks it, and that substitution is one of the things this inspection "
         "is for.", "",
         "# 3. Masters and layouts", "",
         _tbl(["Deck", "Layouts in package", "Masters", "Layouts used"],
              [("layout storyboard", pkg["master_and_layout_usage"]["b1"]
                ["layouts_in_package"],
                pkg["master_and_layout_usage"]["b1"]["masters_in_package"],
                pkg["master_and_layout_usage"]["b1"]["layouts_actually_used"]),
               ("state appendix", pkg["master_and_layout_usage"]["appendix"]
                ["layouts_in_package"],
                pkg["master_and_layout_usage"]["appendix"]["masters_in_package"],
                pkg["master_and_layout_usage"]["appendix"]["layouts_actually_used"])]), "",
         "# 4. Notes and metadata", "",
         pkg["notes_and_metadata"]["b1"]["note"], "",
         "# 5. Continuation pages", "",
         _tbl(["Screen", "Page", "Index"],
              [(c["screen_id"], c["page"], f"{c['page_index']}/{c['page_count']}")
               for c in pkg["continuation_pages"]]), "",
         "# 6. Interaction IDs", "",
         f"{len(pkg['interaction_ids'])} triggers: "
         + ", ".join(pkg["interaction_ids"][:12]) + " …", "",
         "# 7. Open statuses", "",
         _tbl(["Register", "Live IDs"],
              [(k, ", ".join(v)) for k, v in pkg["known_open_statuses"].items()]), "",
         "# 8. Correction intake", "",
         _tbl(["Field"], [(f,) for f in pkg["correction_intake_template"]["fields"]]), "",
         f"**Policy.** {pkg['correction_intake_template']['policy']}", ""]
    b = _w("T04_NATIVE_POWERPOINT_INSPECTION_PACKAGE_v1.md", "\n".join(p))
    return [a, b]


def build_all():
    path = build_appendix()
    previews = render_appendix_previews()
    files = emit_all()
    return dict(appendix=path, previews=previews, files=files)


if __name__ == "__main__":
    r = build_all()
    print(f"appendix : {r['appendix']} ({os.path.getsize(r['appendix'])} bytes)")
    print(f"previews : {len(r['previews'])} "
          f"(overflowed: {len([x for x in r['previews'] if x['overflowed']])})")
    for f in r["files"]:
        print(f"emitted  : {f}")
