# -*- coding: utf-8 -*-
"""Stage 4.2F-B0.7 — emit every final-structural-rulings artifact from the one data source."""
import csv, io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import t04_final_rulings_data_v1 as D

OUT = os.path.abspath(os.path.join(HERE, ".."))
BANNER = (f"<!-- GENERATED by {D.GENERATED_BY} — Stage {D.STAGE}. "
          "Edit the data module, not this file. -->")


def _w(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text if text.endswith("\n") else text + "\n")
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1))


def _hdr(title, extra=()):
    lines = [BANNER, "", f"# {title}", "", "```",
             f"STAGE                   = {D.STAGE}",
             f"UNIT                    = {D.UNIT_ID} — {D.LESSON_TITLE}",
             f"CONTENT_STATUS          = {D.CONTENT_STATUS}",
             f"APPROVAL_STATUS         = {D.APPROVAL_STATUS}",
             f"INSTRUCTIONAL_AUTHORITY = {D.INSTRUCTIONAL_AUTHORITY}"]
    lines += list(extra) + ["```", ""]
    return "\n".join(lines)


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def _totals_block():
    t = D.APPROVAL_TOTALS
    return ["```",
            f"CONFIRMED_POLICY_DECISIONS                 = {t['CONFIRMED_POLICY_DECISIONS']}"
            f"   {', '.join(t['confirmed_policy_decision_ids'])}",
            f"CONDITIONALLY_CONFIRMED_DECISIONS          = "
            f"{t['CONDITIONALLY_CONFIRMED_DECISIONS']}   "
            f"{', '.join(t['conditionally_confirmed_decision_ids'])}",
            f"APPROVED_FINAL_INSTRUCTIONAL_CONTENT_ITEMS = "
            f"{t['APPROVED_FINAL_INSTRUCTIONAL_CONTENT_ITEMS']}",
            f"PENDING_BARIAH_CONTENT_REVIEWS             = "
            f"{t['PENDING_BARIAH_CONTENT_REVIEWS']}",
            "```"]


# ==========================================================================================
def emit_rulings_md():
    p = [_hdr("T04 — BARIAH FINAL STRUCTURAL RULINGS",
              [f"EVIDENCE_ITEMS_TOTAL    = {len(D.EVIDENCE_ALL)}",
               f"NEW_THIS_STAGE          = {len(D.EVIDENCE_NEW)}",
               f"RULING_LOCATORS_TOTAL   = {len(D.RULING_LOCATORS_ALL)}",
               f"STRUCTURAL_DECISIONS    = {D.READINESS['structural_decisions_status']}"]),
         "# 1. Approval accounting"]
    p += _totals_block()
    p += ["", D.APPROVAL_TOTALS["supersession_note"], "",
          "# 2. New evidence", ""]
    d = D.EVIDENCE_DELIVERY
    p += [f"**Delivery discrepancy.** The stage instruction says "
          f"**{d['expected_by_instruction']} screenshots** are attached. "
          f"**{d['actually_received']}** arrived. {d['consequence']}", "",
          "Checked: " + "; ".join(d["checked"]) + ".", ""]
    for e in D.EVIDENCE_NEW:
        p += [f"## {e['evidence_id']}", "", "```",
              f"frozen_path                = {e['frozen_path']}",
              f"original_uploaded_filename = {e['original_uploaded_filename']}",
              f"byte_size                  = {e['byte_size']}",
              f"sha256                     = {e['sha256']}",
              f"media_type                 = {e['media_type']}",
              f"dimensions_px              = {e['dimensions_px']}",
              f"evidence_date              = {e['evidence_date']}",
              f"received_utc               = {e['received_utc']}",
              f"reviewer                   = {e['reviewer']}",
              f"evidence_class             = {e['evidence_class']}",
              f"scope                      = {e['scope']}",
              f"modification               = {e['modification']}",
              "```", "", e["description"], ""]
    p += ["## What is not legible", ""]
    for L in D.EVIDENCE_LEGIBILITY:
        p += [f"**{L['item']}** — not legible in the screenshot.", "",
              L["what_is_legible"], "",
              f"`authority = {L['authority']}`", "", L["basis"], "", L["note"], ""]
    p += ["# 3. Rulings, verbatim", ""]
    for r in D.RULING_LOCATORS_NEW:
        p += [f"### {r['locator']} · {r['evidence_id']} · {r['decision']}", "",
              f"*{r['position']}*", "",
              f"Replying to: *{r['replying_to']}*", "",
              f"> {r['verbatim']}", "", r["reading"], ""]
    p += ["# 4. Decision state", "",
          _tbl(["Decision", "Title", "Status", "Structural", "Changed here"],
               [(x["decision_id"], x["title"], f'`{x["status"]}`',
                 x["structural_status"], "**yes**" if x["changed_this_stage"] else "no")
                for x in D.DECISIONS]), ""]
    for x in D.DECISIONS:
        if not x["changed_this_stage"]:
            continue
        p += [f"## {x['decision_id']} — {x['title']}", "",
              f"`{x.get('previous_status')}` → **`{x['status']}`**", "",
              f"Ruling: `{x['ruling']}`", "",
              f"Evidence: {', '.join(x['evidence'])}", "",
              x["change_note"], ""]
    p += ["# 5. D-02B — passing threshold", "", "```"]
    p += [f"{k:<16} = {v}" for k, v in D.D02B.items()]
    p += ["```", "", "# 6. D-04 — the confirmed split", ""]
    s = D.D04_SPLIT
    p += [f"`status = {s['status']}` · `applied_to_contracts = {s['applied_to_contracts']}` · "
          f"`scope = {s['scope']}`", "",
          "**Base screen must show:**", ""]
    p += [f"- **{i['item']}** — {', '.join(i['rows'])} · *{i['legibility']}*"
          for i in s["base_screen_must_show"]] + [""]
    p += ["**Click-to-reveal may contain:**", ""]
    p += [f"- {i['item']} — {', '.join(i['rows'])}" for i in s["reveal_may_contain"]] + [""]
    p += [f"*{s['reveal_is_permissive']}*", "",
          "## Delta from the CAIR proposal", "",
          _tbl(["", "Rows"], [
              ("CAIR proposed as reveal", ", ".join(s["delta_from_cair_proposal"]["cair_proposed_reveal"])),
              ("Bariah confirmed as reveal", ", ".join(s["delta_from_cair_proposal"]["bariah_confirmed_reveal"])),
              ("Moved TO base", ", ".join(s["delta_from_cair_proposal"]["moved_to_base"])),
              ("Newly reveal-eligible", ", ".join(s["delta_from_cair_proposal"]["newly_reveal_eligible"]))]),
          "", s["delta_from_cair_proposal"]["note"], "",
          f"**Residual risk.** {s['residual_risk']}", "",
          "Out of scope, unchanged and still base-visible: " +
          ", ".join(f"`{r}`" for r in s["out_of_scope_rows_unchanged"]) +
          " — the Baja-section compliance rows, which were not part of the question Bariah "
          "was asked.", "",
          "# 7. D-05 — SmartArt, fully confirmed", "", "```"]
    p += [f"{k:<22} = {v}" for k, v in D.D05.items() if not isinstance(v, list)]
    p += ["```", "",
          _tbl(["#", "Node label"],
               [(i + 1, n) for i, n in enumerate(D.D05["six_nodes_in_order"])]), "",
          "D-05 is removed from every unresolved list.", "",
          "# 8. D-03 — cast policy", "", "```"]
    p += [f"{k:<28} = {v}" for k, v in D.D03_POLICY.items()
          if isinstance(v, (str, int)) or (isinstance(v, list) and all(
              isinstance(z, str) for z in v))]
    p += ["```", "", f"**Prior B02 policy.** *{D.D03_POLICY['prior_b02_policy']['verbatim']}* "
          f"— {D.D03_POLICY['prior_b02_policy']['consistency']}", ""]
    return _w("T04_BARIAH_FINAL_STRUCTURAL_RULINGS_v1.md", "\n".join(p))


def emit_rulings_json():
    return _j("T04_BARIAH_FINAL_STRUCTURAL_RULINGS_v1.json", dict(
        pack="T04_BARIAH_FINAL_STRUCTURAL_RULINGS", version="v1", stage=D.STAGE,
        unit_id=D.UNIT_ID, content_status=D.CONTENT_STATUS,
        approval_status=D.APPROVAL_STATUS,
        instructional_authority=D.INSTRUCTIONAL_AUTHORITY,
        approval_totals=D.APPROVAL_TOTALS,
        evidence_delivery=D.EVIDENCE_DELIVERY,
        evidence_dir=D.EVIDENCE_DIR, evidence_new=D.EVIDENCE_NEW,
        evidence_all=D.EVIDENCE_ALL, evidence_legibility=D.EVIDENCE_LEGIBILITY,
        ruling_locators_new=D.RULING_LOCATORS_NEW,
        ruling_locators_all=D.RULING_LOCATORS_ALL,
        decision_statuses=D.DECISION_STATUSES, decisions=D.DECISIONS,
        d02b=D.D02B, d03_policy=D.D03_POLICY, d04_split=D.D04_SPLIT, d05=D.D05,
        readiness=D.READINESS))


# ==========================================================================================
def emit_fit():
    f = D.CONTEXTUAL_FIT
    p = [_hdr("T04 — CHARACTER CONTEXTUAL FIT ASSESSMENT",
              [f"ASSESSMENT_ID           = {f['assessment_id']}",
               f"SLIDE                   = {f['slide']}",
               f"RESULT                  = {f['recommendation']}",
               f"AUTHORITY               = {f['authority']}",
               f"STATUS                  = {f['status']}"]),
         "# 1. What Bariah ruled", "",
         "> 2. Guna watak tambahan di Slide 2 (perbualan dialog senario)", "",
         "> jika Alya & Encik Rahman, sesuai, boleh guna semula. Jika tidak, guna watak baru",
         "",
         "The condition is the ruling. Naming the pair without assessing whether they suit "
         "would implement half of what she wrote. This document is that assessment.", "",
         f"Allowed results: {' · '.join(f'`{r}`' for r in D.ALLOWED_FIT_RESULTS)}", "",
         "# 2. Dialogue purpose", "", f["dialogue_purpose"], "",
         "Source rows: " + ", ".join(f"`{r}`" for r in f["source_row_bindings"]), "",
         "# 3. Roles required", ""]
    for r in f["roles_required"]:
        p += [f"### {r['role']}", "", r["function"], "", f"*Source basis.* {r['source_basis']}",
              ""]
    p += ["# 4. Does each character fit?", ""]
    for key, blk in (("Alya", f["alya_fit"]), ("Encik Rahman", f["encik_rahman_fit"])):
        p += [f"## {blk['character']} — {blk['established_role']}", "",
              f"**Fits: {'YES' if blk['fits'] else 'NO'}** · risk `{blk['risk']}`", ""]
        if blk.get("conditional_on"):
            p += [f"Conditional on: {blk['conditional_on']}", ""]
        p += [blk["reasoning"], ""]
    p += ["Roles as established in B02: " +
          "; ".join(f"**{n}** — {r}" for n, r in D.D03_POLICY["roles_as_established_in_b02"]),
          "", f"Source: `{D.D03_POLICY['roles_source']}`", "",
          "# 5. Specialist expertise", "",
          _tbl(["Question", "Answer"],
               [("Required for Slide 2?", f["specialist_expertise_required"]["for_slide_2"]),
                ("Required anywhere in the unit?",
                 f["specialist_expertise_required"]["for_the_unit"])]), "",
          f["specialist_expertise_required"]["detail"], "",
          "# 6. Risk of unsupported expertise", "",
          f"**Level: `{f['unsupported_expertise_risk']['level']}`**", "",
          f["unsupported_expertise_risk"]["description"], "",
          f"**Mitigation.** {f['unsupported_expertise_risk']['mitigation']}", "",
          f"Residual after mitigation: `{f['unsupported_expertise_risk']['residual_after_mitigation']}`",
          "", "# 7. Recommendation", "",
          f"**`{f['recommendation']}`**", "", f["recommendation_condition"], "",
          f"A new character would be required if: {f['new_character_would_be_required_if']}",
          "", f"`{f['authority']}` · `{f['status']}` — this is CAIR's assessment, offered so "
          "Bariah can confirm or overturn it. It is not a ruling.", ""]
    return _w("T04_CHARACTER_CONTEXTUAL_FIT_ASSESSMENT_v1.md", "\n".join(p))


def emit_dialogue():
    s = D.SLIDE2_DIALOGUE
    p = [_hdr("T04 — SLIDE 2 DIALOGUE CONTRACT DRAFT",
              [f"CONTRACT_ID             = {s['contract_id']}",
               f"SCREEN_CANDIDATE_ID     = {s['screen_candidate_id']}",
               f"SLIDE_POSITION          = {s['slide_position']}",
               f"CANDIDATE_TYPE          = {s['candidate_type']}",
               f"CAST_STATUS             = {s['cast_status']}",
               f"BARIAH_APPROVAL         = {s['bariah_approval']['status']}"]),
         "# 1. Contract", "",
         _tbl(["Field", "Value"], [
             ("source rows", ", ".join(s["source_rows"])),
             ("cast", "; ".join(f"{n} — {r}" for n, r in s["cast"])),
             ("learner-facing purpose", s["learner_facing_purpose"]),
             ("base state", s["base_state"]),
             ("interaction states", "; ".join(s["interaction_states"])),
             ("completion", s["completion_condition"]),
             ("visual treatment", s["visual_treatment"]),
             ("VO", s["vo_proposal"]),
             ("Speaker Notes", s["speaker_notes_proposal"]),
             ("accessibility", s["accessibility_consideration"]),
             ("fallback", s["fallback_behaviour"]),
             ("source authority", s["source_authority"])]), "",
         "# 2. The compliance-exclusion rule", "",
         f"`compliance_content_excluded = {s['compliance_content_excluded']}`", "",
         s["compliance_exclusion_rule"], "",
         "This is not stylistic caution. The source states that pesticide spraying must be "
         "done by a licensed operator — a competence the character bank does not give Encik "
         "Rahman. A mentor character stating a statutory duty converts a source citation into "
         "a character's word. A gate holds this rule.", "",
         "# 3. Dialogue beats", "", f"*{s['drafting_basis']}*", ""]
    for b in s["beats"]:
        p += [f"### Beat {b['beat']} — {b['speaker']}", "",
              f"**Intent.** {b['intent']}", "",
              f"**Source rows.** {', '.join(b['source_row_ids'])}", "",
              f"> {b['draft_line']}", ""]
    p += ["# 4. Bariah review", "",
          _tbl(["Beat", "accept", "edit", "replace", "comment"],
               [(b["beat"], "☐", "☐", "☐", "________________") for b in s["beats"]]), "",
          f"`content_status = {s['content_status']}` · "
          f"`approval_status = {s['approval_status']}` · "
          f"`instructional_authority = {s['instructional_authority']}`", ""]
    return _w("T04_SLIDE_2_DIALOGUE_CONTRACT_DRAFT_v1.md", "\n".join(p))


# ==========================================================================================
def emit_assets_md():
    t = D.ASSET_TOTALS
    p = [_hdr("T04 — VISUAL ASSET GROUPING PLAN",
              [f"VISUAL_OBLIGATIONS      = {t['VISUAL_OBLIGATIONS']}",
               f"UNIQUE_ASSET_COUNT      = {t['UNIQUE_ASSET_COUNT']}",
               f"VISUAL_COVERAGE_STATUS  = {t['VISUAL_COVERAGE_STATUS']}",
               f"ASSET_GROUPS            = {t['asset_groups']}",
               f"PRODUCTION_STARTED      = {t['production_started']}"]),
         "# 1. Obligations are not assets", "", D.OBLIGATIONS_ARE_NOT_ASSETS, "",
         f"`UNIQUE_ASSET_COUNT = {t['UNIQUE_ASSET_COUNT']}` until the grouping is decided. "
         f"`{t['VISUAL_COVERAGE_STATUS']}` records what is true today: coverage has to be "
         "produced, and how many files that means is not yet known.", "",
         f"**{t['slide_2_visual_note']}**", "",
         "# 2. Asset groups", "",
         _tbl(["Group", "Label", "Parent", "Obligations"],
              [(g["group_id"], g["label"], g["parent"],
                len([r for r in D.ASSET_PLAN
                     if r["proposed_asset_group_id"] == g["group_id"]]))
               for g in D.ASSET_GROUPS]), ""]
    for g in D.ASSET_GROUPS:
        p += [f"**{g['group_id']}** — {g['composite_rationale']}"]
    p += ["", "# 3. Planning status", "",
          _tbl(["", "Count"], [
              ("composite candidates the source itself presents as a set", t["composite_candidates"]),
              ("undetermined, pending Bariah", t["undetermined"]),
              ("marked DO NOT REUSE", t["do_not_reuse"]),
              ("production started", t["production_started"])]), "",
          "Only obligations whose SOURCE presents a set are marked as composite candidates. "
          "Everything else stays `UNDETERMINED_PENDING_BARIAH` — a guess dressed as a plan "
          "would be worse than an open field.", "",
          "## Subjects that look reusable and are not", ""]
    for r in D.ASSET_PLAN:
        if r["reuse_allowed"] == "SIMILAR_SUBJECT_DO_NOT_REUSE":
            p += [f"- **{r['obligation_id']}** — {r['reuse_note']}"]
    p += ["", "# 4. The plan", "",
          _tbl(["Obligation", "Group", "Unique asset", "Composite?", "Reuse", "Serves",
                "Production", "Bariah"],
               [(r["obligation_id"], r["proposed_asset_group_id"],
                 r["unique_asset_candidate_id"], r["composite_or_individual"],
                 r["reuse_allowed"], r["screens_or_states_served"], r["production_status"],
                 r["bariah_approval_requirement"]) for r in D.ASSET_PLAN]), ""]
    return _w("T04_VISUAL_ASSET_GROUPING_PLAN_v1.md", "\n".join(p))


def emit_assets_csv():
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(D.ASSET_PLAN_FIELDS)
    for r in D.ASSET_PLAN:
        w.writerow([r[f] for f in D.ASSET_PLAN_FIELDS])
    return _w("T04_VISUAL_ASSET_GROUPING_PLAN_v1.csv", buf.getvalue())


def emit_assets_json():
    return _j("T04_VISUAL_ASSET_GROUPING_PLAN_v1.json", dict(
        pack="T04_VISUAL_ASSET_GROUPING_PLAN", version="v1", stage=D.STAGE,
        unit_id=D.UNIT_ID,
        visual_obligations=D.VISUAL_OBLIGATION_COUNT,
        unique_asset_count=D.UNIQUE_ASSET_COUNT,
        visual_coverage_status=D.VISUAL_COVERAGE_STATUS,
        obligations_are_not_assets=D.OBLIGATIONS_ARE_NOT_ASSETS,
        totals=D.ASSET_TOTALS, fields=D.ASSET_PLAN_FIELDS,
        asset_groups=D.ASSET_GROUPS, plan=D.ASSET_PLAN))


# ==========================================================================================
def emit_mapping_md():
    i = D.MAPPING_IMPACT_V3
    p = [_hdr("T04 — SOURCE-TO-SCREEN MAPPING v3",
              [f"CANDIDATES              = {i['candidates']}",
               f"NEW_THIS_STAGE          = {i['new_candidate_this_stage']}",
               f"FINAL_SCREEN_COUNT      = {D.FINAL_SCREEN_COUNT}",
               f"VISUAL_OBLIGATIONS      = {i['obligations_total']}",
               f"NO_SCREEN_AT_ALL        = {i['obligations_with_no_home']}",
               f"B02_FAMILIES_PROPAGATED = {i['b02_families_propagated']}"]),
         "# 1. What changed", "", i["headline"], "",
         f"**`FINAL_SCREEN_COUNT = {D.FINAL_SCREEN_COUNT}`.** {i['reason']}", "",
         "# 2. Candidates", "",
         _tbl(["Candidate", "Slide", "Working title", "Visual states", "D-04 split",
               "Still required"],
              [(m["screen_candidate_id"], m["slide_position"], m["working_title"],
                m["required_visual_states"], "**applied**" if m["d04_split_applied"] else "—",
                m["decision_still_required"]) for m in D.MAPPING_V3]), ""]
    for m in D.MAPPING_V3:
        p += [f"## {m['screen_candidate_id']} — {m['working_title']}", "",
              _tbl(["Field", "Value"], [
                  ("slide position", m["slide_position"]),
                  ("previous visual assumption", m["previous_visual_assumption"]),
                  ("new Bariah visual obligation", m["new_bariah_visual_obligation"]),
                  ("visual obligation IDs", ", ".join(m["visual_obligation_ids"]) or "none"),
                  ("required visual states", m["required_visual_states"]),
                  ("available source visual", m["available_source_visual"]),
                  ("missing production asset", m["missing_production_asset"]),
                  ("possible screen expansion", m["possible_screen_expansion"]),
                  ("popup / reveal implications", m["popup_reveal_implications"]),
                  ("learner-screen count impact", m["learner_screen_count_impact"]),
                  ("runtime-state count impact", m["runtime_state_count_impact"]),
                  ("D-04 split applied", m["d04_split_applied"]),
                  ("decision still required", m["decision_still_required"])]), ""]
    p += ["# 3. Unchanged from v2", "",
          f"{i['obligations_with_no_home']} of {i['obligations_total']} visual obligations "
          "still have no screen. Closing the structural decisions did not give them one — "
          "they are the Siram, Baja and Racun subtopics, and where they land is a mapping "
          "decision nobody has taken yet.", "",
          f"`B02_FAMILIES_PROPAGATED = {i['b02_families_propagated']}`. {i['b02_family_note']}",
          ""]
    return _w("T04_SOURCE_TO_SCREEN_MAPPING_v3.md", "\n".join(p))


def emit_mapping_json():
    return _j("T04_SOURCE_TO_SCREEN_MAPPING_v3.json", dict(
        pack="T04_SOURCE_TO_SCREEN_MAPPING", version="v3", stage=D.STAGE, unit_id=D.UNIT_ID,
        content_status=D.CONTENT_STATUS, approval_status=D.APPROVAL_STATUS,
        instructional_authority=D.INSTRUCTIONAL_AUTHORITY,
        final_screen_count=D.FINAL_SCREEN_COUNT,
        impact=D.MAPPING_IMPACT_V3, screens=D.MAPPING_V3))


def emit_contracts_md():
    p = [_hdr("T04 — SCREEN CONTRACTS DRAFT v3",
              [f"CONTRACTS               = {len(D.CONTRACTS_V3)}",
               f"NEW_THIS_STAGE          = {D.SLIDE2_DIALOGUE['contract_id']}",
               f"D04_SPLIT_APPLIED_TO    = T04-CT-04",
               f"FINAL_SCREEN_COUNT      = {D.FINAL_SCREEN_COUNT}"]),
         "Bariah's D-04 split is APPLIED here, not merely proposed. `T04-CT-04` carries its "
         "Stage 4.2F-B0.6 base state as `superseded_base_state` so the change is visible.", ""]
    for c in D.CONTRACTS_V3:
        p += [f"## {c['contract_id']} — {c['candidate_type']}", "", "```",
              f"revision                 = {c['revision']}",
              f"source_rows              = {len(c['source_rows'])}",
              f"visual_obligation_ids    = {', '.join(c['visual_obligation_ids']) or '—'}",
              f"required_visual_states   = {c['required_visual_states']}",
              f"missing_production_asset = {c['missing_production_asset']}",
              f"open_decision            = {c['open_decision']}",
              f"bariah_approval          = {c['bariah_approval']['status']}",
              "```", "",
              f"**Learner-facing purpose.** {c['learner_facing_purpose']}", "",
              f"**Base state.** {c['base_state']}", ""]
        if c.get("superseded_base_state"):
            p += [f"**Superseded base state (v2).** {c['superseded_base_state']}", ""]
        p += ["**Interaction states.** " + "; ".join(c["interaction_states"]), "",
              f"**Completion.** {c['completion_condition']}", "",
              f"**Visual treatment.** {c['visual_treatment']}", "",
              f"**Text treatment.** {c['text_treatment']}", "",
              f"**Accessibility.** {c['accessibility_consideration']}", "",
              f"**Fallback.** {c['fallback_behaviour']}", "",
              f"**Source authority.** {c['source_authority']}", ""]
        if c.get("base_visible_rows"):
            p += ["**D-04 split, applied.**", "",
                  _tbl(["", "Rows"],
                       [("base-visible, may not be hidden", ", ".join(c["base_visible_rows"])),
                        ("reveal-eligible", ", ".join(c["reveal_eligible_rows"]))]), ""]
        if c.get("hidden_content_classification"):
            p += [f"**Hidden content.** `{c['hidden_content_classification']}` — "
                  f"{c['hidden_content_justification']}", ""]
    return _w("T04_SCREEN_CONTRACTS_DRAFT_v3.md", "\n".join(p))


def emit_contracts_json():
    return _j("T04_SCREEN_CONTRACTS_DRAFT_v3.json", dict(
        pack="T04_SCREEN_CONTRACTS_DRAFT", version="v3", stage=D.STAGE, unit_id=D.UNIT_ID,
        content_status=D.CONTENT_STATUS, approval_status=D.APPROVAL_STATUS,
        instructional_authority=D.INSTRUCTIONAL_AUTHORITY,
        final_screen_count=D.FINAL_SCREEN_COUNT,
        approval_totals=D.APPROVAL_TOTALS,
        d04_split=D.D04_SPLIT, slide_2_dialogue=D.SLIDE2_DIALOGUE,
        contracts=D.CONTRACTS_V3))


# ==========================================================================================
def emit_remaining():
    p = [_hdr("T04 — REMAINING BARIAH CONTENT REVIEWS",
              [f"STRUCTURAL_DECISIONS    = {D.READINESS['structural_decisions_status']}",
               f"PENDING_CONTENT_REVIEWS = {len(D.PENDING_CONTENT_REVIEWS)}"]),
         "# 1. Approval accounting"]
    p += _totals_block()
    p += ["", "# 2. Structure is closed", "",
          _tbl(["Decision", "Title", "Status", "Structural"],
               [(d["decision_id"], d["title"], f'`{d["status"]}`', d["structural_status"])
                for d in D.READINESS["structural_decisions"]]), "",
          "# 3. What is left — content only", "",
          _tbl(["#", "Review", "Decision", "What Bariah must do"],
               [(r["review_id"], r["title"], r["decision"], r["what"])
                for r in D.PENDING_CONTENT_REVIEWS]), ""]
    for r in D.PENDING_CONTENT_REVIEWS:
        p += [f"### {r['review_id']} — {r['title']}", "",
              f"**Decision:** `{r['decision']}` · **Status:** `{r['status']}`", "",
              f"**What Bariah must do.** {r['what']}", "",
              f"**Where CAIR has got to.** {r['cair_position']}", ""]
    p += ["# 4. What is not claimed", ""]
    p += [f"- {x}" for x in D.READINESS["what_is_not_claimed"]] + [""]
    p += ["```",
          f"storyboard_status   = {D.READINESS['storyboard_status']}",
          f"storyboard_approval = {D.READINESS['storyboard_approval']}",
          f"mmd_status          = {D.READINESS['mmd_status']}",
          "```", ""]
    return _w("T04_REMAINING_BARIAH_CONTENT_REVIEWS_v1.md", "\n".join(p))


def emit_whatsapp():
    w = D.WHATSAPP
    p = [_hdr("T04 — BARIAH WHATSAPP CONTENT REVIEW DRAFT",
              [f"STATUS                  = {w['status']}",
               f"LANGUAGE                = {w['language']}",
               f"SENDING_AUTHORITY       = {w['sending_authority']}"]),
         f"**`{w['status']}`.** Sending is {w['sending_authority']}'s call.", "",
         "# Message", "", "```", w["text"], "```", "",
         "# Constraints honoured", ""]
    p += [f"- {x}" for x in w["constraints_honoured"]] + ["", "# Not asked again", ""]
    p += [f"- {x}" for x in w["not_asked_again"]] + [""]
    return _w("T04_BARIAH_WHATSAPP_CONTENT_REVIEW_DRAFT_v1.md", "\n".join(p))


EMITTERS = [emit_rulings_md, emit_rulings_json, emit_fit, emit_dialogue, emit_assets_md,
            emit_assets_csv, emit_assets_json, emit_mapping_md, emit_mapping_json,
            emit_contracts_md, emit_contracts_json, emit_remaining, emit_whatsapp]

if __name__ == "__main__":
    written = [e() for e in EMITTERS]
    for n in written:
        print("wrote", n)
    print(f"{len(written)} files")
