# -*- coding: utf-8 -*-
"""Stage 4.2F-B1 — build the T04 review PPTX and the registers, from the controlled model.

The deck is generated, never hand-edited. Every text frame on every slide is placed from
`t04_storyboard_model_v1`, so a sentence cannot appear in the PPTX without existing in the
model, and the QA suite re-reads the built file from disk rather than trusting this builder.

Two things this stage does NOT claim:

  * that the deck looks right in Microsoft PowerPoint — no Impress filter exists here, so no
    native render was performed and none is asserted;
  * that any visual exists — every visual slot is a labelled placeholder naming the asset
    group and obligations it stands for.
"""
import json
import os
import sys

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Emu, Pt

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import t04_storyboard_model_v1 as M        # noqa: E402
import t04_authority_data_v1 as A          # noqa: E402
import t04_supplementary_evidence_v1 as S  # noqa: E402

OUT = os.path.abspath(os.path.join(HERE, ".."))
BANNER = (f"<!-- GENERATED by {M.GENERATED_BY} — Stage {M.STAGE}. "
          "Edit the model, not this file. -->")

# 16:9 at 13.333in × 7.5in
SLIDE_W = Emu(12192000)
SLIDE_H = Emu(6858000)
MARGIN = Emu(457200)

INK = RGBColor(0x1A, 0x1A, 0x1A)
MUTED = RGBColor(0x6B, 0x6B, 0x6B)
RULE = RGBColor(0xD8, 0xD8, 0xD8)
AUTH = RGBColor(0x1B, 0x5E, 0x20)      # authority-supplied or selected
SRC = RGBColor(0x0D, 0x47, 0xA1)       # controlled source
UI = RGBColor(0x6B, 0x6B, 0x6B)        # structural furniture
PLACEHOLDER = RGBColor(0xB7, 0x1C, 0x1C)

DRAFT = RGBColor(0x6A, 0x1B, 0x9A)     # CAIR-drafted assessment option

PROV_COLOUR = {"AUTHORITY_SUPPLIED": AUTH, "AUTHORITY_SELECTED": AUTH,
               "SOURCE_CONTROLLED": SRC, "CAIR_DRAFTED_ASSESSMENT_OPTION": DRAFT,
               "CAIR_STRUCTURAL": UI}
PROV_TAG = {"AUTHORITY_SUPPLIED": "A", "AUTHORITY_SELECTED": "A*",
            "SOURCE_CONTROLLED": "S", "CAIR_DRAFTED_ASSESSMENT_OPTION": "d",
            "CAIR_STRUCTURAL": "u"}

LEGEND = ("Warna teks: biru = kandungan modul terkawal · hijau = kandungan Bariah "
          "(A = ditulis, A* = dipilih) · ungu = pilihan kuiz draf CAIR · "
          "kelabu = elemen antara muka")


def _tf(slide, x, y, w, h, wrap=True):
    box = slide.shapes.add_textbox(x, y, w, h)
    tf = box.text_frame
    tf.word_wrap = wrap
    tf.margin_left = tf.margin_right = Emu(0)
    tf.margin_top = tf.margin_bottom = Emu(0)
    return tf


def _p(tf, text, size=14, colour=INK, bold=False, italic=False, first=False, indent=0,
       align=PP_ALIGN.LEFT):
    para = tf.paragraphs[0] if first else tf.add_paragraph()
    para.alignment = align
    para.level = min(int(indent or 0), 4)
    run = para.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = colour
    run.font.name = "Arial"
    return para


def _rule(slide, y):
    from pptx.enum.shapes import MSO_SHAPE
    ln = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, MARGIN, y,
                                Emu(SLIDE_W - 2 * MARGIN), Emu(9525))
    ln.fill.solid()
    ln.fill.fore_color.rgb = RULE
    ln.line.fill.background()
    ln.shadow.inherit = False
    return ln


# ==========================================================================================
def _title_slide(prs):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    tf = _tf(slide, MARGIN, Emu(1600200), Emu(SLIDE_W - 2 * MARGIN), Emu(2400000))
    _p(tf, "STORYBOARD UNTUK SEMAKAN BARIAH", 16, MUTED, bold=True, first=True)
    _p(tf, f"{M.LEARNER_DISPLAY_UNIT}: {M.LEARNER_DISPLAY_UNIT_TITLE}", 34, INK, bold=True)
    _p(tf, f"{M.SCREEN_COUNT_EXPECTED} skrin pembelajaran", 18, MUTED)
    _p(tf, "", 10)
    _p(tf, f"Rujukan dalaman: {M.INTERNAL_UNIT_ID}", 11, MUTED, italic=True)
    _p(tf, "Storyboard sahaja. Aset visual MMD belum dihasilkan.", 11, PLACEHOLDER,
       italic=True)
    _p(tf, LEGEND, 10, MUTED, italic=True)
    return slide


def _screen_slide(prs, sl):
    sc = sl["screen"]
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # Header: screen id + title. The screen ID is production metadata, kept visually distinct
    # from the learner-facing title beside it.
    tf = _tf(slide, MARGIN, Emu(320000), Emu(SLIDE_W - 2 * MARGIN), Emu(700000))
    _p(tf, f"{sc['screen_id']}   ·   {sc['treatment']}", 11, MUTED, bold=True, first=True)
    _p(tf, sc["title_ms"] + sl["title_suffix"], 24, INK, bold=True)
    _rule(slide, Emu(1150000))

    # Learner content column.
    col_w = Emu(int((SLIDE_W - 2 * MARGIN) * 0.60))
    tf = _tf(slide, MARGIN, Emu(1320000), col_w, Emu(4600000))
    _p(tf, "KANDUNGAN SKRIN" + (" (sambungan)" if sl["is_continuation"] else ""),
       10, MUTED, bold=True, first=True)
    for b in sl["blocks"]:
        colour = PROV_COLOUR[b["provenance"]]
        tag = PROV_TAG[b["provenance"]]
        size = 11 if b["provenance"] == "CAIR_STRUCTURAL" else 13
        _p(tf, f"{tag} · {b['text']}", size, colour, indent=b.get("list_level") or 0)

    # Right column: interaction, visual, traceability.
    rx = Emu(int(MARGIN + col_w + 300000))
    rw = Emu(int(SLIDE_W - MARGIN - rx))
    tf = _tf(slide, rx, Emu(1320000), rw, Emu(4600000))
    _p(tf, "INTERAKSI", 10, MUTED, bold=True, first=True)
    for st in sc["interaction_states"]:
        _p(tf, f"· {st}", 10, INK)
    if sc["named_reveal_items"]:
        _p(tf, "Item pendedahan:", 10, MUTED, bold=True)
        for r in sc["named_reveal_items"]:
            _p(tf, f"· {r}", 10, INK)

    v = sc["visual"]
    _p(tf, "", 8)
    _p(tf, "VISUAL", 10, MUTED, bold=True)
    if v["asset_group_ids"]:
        _p(tf, "· ".join(v["asset_group_ids"]), 11, INK, bold=True)
        for lbl in v["asset_group_labels"]:
            _p(tf, lbl, 10, INK)
        _p(tf, f"Dasar guna semula: {v['reuse_policy']}", 9, MUTED)
        if v["do_not_reuse_obligations"]:
            _p(tf, "TIDAK BOLEH DIKONGSI: " + ", ".join(v["do_not_reuse_obligations"]),
               9, PLACEHOLDER, bold=True)
        _p(tf, "ASET BELUM DIHASILKAN", 10, PLACEHOLDER, bold=True)
    else:
        _p(tf, "Tiada visual khusus", 10, MUTED, italic=True)

    _p(tf, "", 8)
    _p(tf, "SUMBER DAN KEPUTUSAN", 10, MUTED, bold=True)
    _p(tf, ("Baris modul: " + ", ".join(sc["source_row_ids"])) if sc["source_row_ids"]
       else "Skrin struktur — tiada baris modul", 8, MUTED)
    _p(tf, "Keputusan: " + ", ".join(sc["decision_ids"]), 8, MUTED)

    # Footer.
    tf = _tf(slide, MARGIN, Emu(6150000), Emu(SLIDE_W - 2 * MARGIN), Emu(500000))
    _p(tf, f"{M.LEARNER_DISPLAY_UNIT} · skrin {sc['position']} daripada "
           f"{M.SCREEN_COUNT_EXPECTED}", 9, MUTED, first=True)
    # The per-screen authority note stays in the registers and off the slide. It is English
    # production prose, and on two screens it quoted the retired label "Tamat Bahagian" onto
    # a deck whose whole point is that T04 has no Bahagian.
    return slide


def build_pptx():
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H
    _title_slide(prs)
    for sl in M.slides():
        _screen_slide(prs, sl)
    os.makedirs(M.PPTX_DIR, exist_ok=True)
    path = os.path.join(M.PPTX_DIR, M.PPTX_NAME)
    prs.save(path)
    return path


# ==========================================================================================
# DETERMINISTIC PREVIEW — a layout approximation, not a PowerPoint render
# ==========================================================================================
def render_previews():
    from PIL import Image, ImageDraw, ImageFont

    def font(sz, bold=False):
        base = "/usr/share/fonts/truetype/liberation/"
        name = "LiberationSans-Bold.ttf" if bold else "LiberationSans-Regular.ttf"
        try:
            return ImageFont.truetype(base + name, sz)
        except Exception:
            return ImageFont.load_default()

    W, H = 1280, 720
    outdir = os.path.join(OUT, "storyboard_preview")
    os.makedirs(outdir, exist_ok=True)
    # Clear first. A previous run's pages survive a re-render otherwise, and a reviewer
    # opening the folder cannot tell a stale page from a current one — the first pass here
    # left four orphans behind when pagination changed the filenames.
    for f in os.listdir(outdir):
        if f.endswith(".png"):
            os.remove(os.path.join(outdir, f))
    made = []
    rgb = {k: tuple(int(str(v)[i:i + 2], 16) for i in (0, 2, 4))
           for k, v in PROV_COLOUR.items()}

    for sl in M.slides():
        sc = sl["screen"]
        img = Image.new("RGB", (W, H), (255, 255, 255))
        d = ImageDraw.Draw(img)
        d.text((48, 34), f"{sc['screen_id']}  ·  {sc['treatment']}", font=font(15, True),
               fill=(107, 107, 107))
        d.text((48, 58), sc["title_ms"] + sl["title_suffix"], font=font(28, True),
               fill=(26, 26, 26))
        d.line([(48, 108), (W - 48, 108)], fill=(216, 216, 216), width=2)

        y = 130
        d.text((48, y), "KANDUNGAN SKRIN" + (" (sambungan)" if sl["is_continuation"]
                                             else ""),
               font=font(12, True), fill=(107, 107, 107))
        y += 24
        overflowed = False
        for b in sl["blocks"]:
            colour = rgb[b["provenance"]]
            tag = PROV_TAG[b["provenance"]]
            txt = f"{tag} · {b['text']}"
            f = font(14 if b["provenance"] != "CAIR_STRUCTURAL" else 12)
            # naive wrap at the column width
            words, line = txt.split(), ""
            for w in words:
                probe = (line + " " + w).strip()
                if d.textlength(probe, font=f) > 700:
                    d.text((48 + 14 * b.get("list_level", 0), y), line, font=f, fill=colour)
                    y += 20
                    line = w
                else:
                    line = probe
            if line:
                d.text((48 + 14 * b.get("list_level", 0), y), line, font=f, fill=colour)
                y += 22
            if y > H - 90:
                # Should be unreachable: pagination exists so nothing is ever cut off. If it
                # fires, the preview says so loudly rather than quietly eliding content.
                overflowed = True
                d.text((48, y), "TRUNCATED — PAGINATION FAILED", font=font(13, True),
                       fill=(183, 28, 28))
                break

        rx, ry = 810, 130
        d.text((rx, ry), "INTERAKSI", font=font(12, True), fill=(107, 107, 107))
        ry += 22
        for st in sc["interaction_states"]:
            d.text((rx, ry), f"· {st}", font=font(12), fill=(26, 26, 26))
            ry += 18
        v = sc["visual"]
        ry += 12
        d.text((rx, ry), "VISUAL", font=font(12, True), fill=(107, 107, 107))
        ry += 22
        if v["asset_group_ids"]:
            d.text((rx, ry), " · ".join(v["asset_group_ids"]), font=font(13, True),
                   fill=(26, 26, 26))
            ry += 20
            if v["do_not_reuse_obligations"]:
                d.text((rx, ry), "TIDAK BOLEH DIKONGSI", font=font(11, True),
                       fill=(183, 28, 28))
                ry += 18
            d.text((rx, ry), "ASET BELUM DIHASILKAN", font=font(11, True),
                   fill=(183, 28, 28))
        else:
            d.text((rx, ry), "Tiada visual khusus", font=font(12), fill=(107, 107, 107))

        d.line([(48, H - 60), (W - 48, H - 60)], fill=(216, 216, 216), width=1)
        d.text((48, H - 48),
               f"{M.LEARNER_DISPLAY_UNIT} · skrin {sc['position']} daripada "
               f"{M.SCREEN_COUNT_EXPECTED}"
               + ("" if sl["page_count"] == 1
                  else f"  ·  halaman {sl['page_index']}/{sl['page_count']}"),
               font=font(11), fill=(107, 107, 107))

        suffix = "" if sl["page_count"] == 1 else f"_p{sl['page_index']}"
        p = os.path.join(outdir, f"{sc['screen_id']}{suffix}.png")
        img.save(p)
        made.append(dict(path=p, screen_id=sc["screen_id"], page=sl["page_index"],
                         overflowed=overflowed))
    return made


RENDER_STATUS = "NOT_CHECKED_POWERPOINT_RENDERER_UNAVAILABLE"
RENDER_NOTE = (
    "LibreOffice has no Impress filter in this environment, so the deck was not opened by any "
    "presentation application and no native render was produced. What exists is a "
    "deterministic preview drawn from the same model at 1280x720 with real font metrics. It "
    "is a layout approximation: it does not prove PowerPoint pagination, autofit behaviour, "
    "font fallback or shape overflow.")


# ==========================================================================================
# REGISTERS
# ==========================================================================================
def _w(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text if text.endswith("\n") else text + "\n")
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1))


def _hdr(title, extra=()):
    return "\n".join([BANNER, "", f"# {title}", "", "```",
                      f"STAGE                = {M.STAGE}",
                      f"SUITE_ID             = {M.SUITE_ID}",
                      f"INTERNAL_UNIT_ID     = {M.INTERNAL_UNIT_ID}",
                      f"LEARNER_DISPLAY_UNIT = {M.LEARNER_DISPLAY_UNIT}"]
                     + list(extra) + ["```", ""])


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def emit_registers():
    files = []
    scs = M.screens()

    files.append(_j("T04_STORYBOARD_MODEL_v1.json", dict(
        stage=M.STAGE, generated_by=M.GENERATED_BY,
        internal_unit_id=M.INTERNAL_UNIT_ID,
        learner_display_unit=M.LEARNER_DISPLAY_UNIT,
        pptx=dict(name=M.PPTX_NAME, dir=os.path.relpath(M.PPTX_DIR, os.path.dirname(OUT))),
        provenance_vocabulary=M.PROVENANCE,
        forbidden_provenance=M.FORBIDDEN_PROVENANCE,
        screen_count=len(scs),
        renumbering_applied=M.renumbering_applied(),
        screens=scs)))
    p = [_hdr("T04 — STORYBOARD MODEL",
              [f"SCREENS = {len(scs)}", f"PPTX    = {M.PPTX_NAME}"]),
         "Every learner-facing string carries a provenance label. There is no category for "
         "CAIR-written teaching content, because none is permitted.", "",
         _tbl(["#", "Screen", "Title", "Treatment", "Blocks", "Visual", "Decisions"],
              [(s["position"], s["screen_id"], s["title_ms"], s["treatment"],
                s["learner_text_count"],
                ", ".join(s["visual"]["asset_group_ids"]) or "—",
                ", ".join(s["decision_ids"])) for s in scs]), ""]
    r = M.renumbering_applied()
    p += ["# The B0.8 → B0.9 numbering translation", "",
          "The obligation closure and the asset-group plan were written against the "
          "21-screen sequence. Reading them against the current 22-screen IDs without "
          "translating is silently wrong for ten screens.", "",
          _tbl(["Register", "Rows translated"],
               [("visual obligations", r["obligations_translated"]),
                ("asset groups", r["asset_groups_translated"])]), "",
          _tbl(["Asset group", "B0.8 screens", "Current screens"],
               [(x["asset_group_id"], ", ".join(x["b08_screens"]),
                 ", ".join(x["current_screens"])) for x in r["asset_group_rows"]]), ""]
    for s in scs:
        p += [f"## {s['screen_id']} — {s['title_ms']}", "",
              _tbl(["Field", "Value"], [
                  ("treatment", s["treatment"]),
                  ("states", ", ".join(s["interaction_states"])),
                  ("visual", ", ".join(s["visual"]["asset_group_ids"]) or "none"),
                  ("source rows", ", ".join(s["source_row_ids"]) or "structural screen"),
                  ("decisions", ", ".join(s["decision_ids"])),
              ]), "",
              _tbl(["Provenance", "Text"],
                   [(b["provenance"], b["text"]) for b in s["content_blocks"]]), ""]
    files.append(_w("T04_STORYBOARD_MODEL_v1.md", "\n".join(p)))

    st = M.source_traceability()
    files.append(_j("T04_STORYBOARD_SOURCE_TRACEABILITY_v1.json",
                    dict(stage=M.STAGE, rows=st, row_count=len(st),
                         non_verbatim=[x for x in st if not x["verbatim"]])))
    files.append(_w("T04_STORYBOARD_SOURCE_TRACEABILITY_v1.md", "\n".join([
        _hdr("T04 — SCREEN TO SOURCE TRACEABILITY",
             [f"BOUND_STRINGS = {len(st)}",
              f"NON_VERBATIM  = {len([x for x in st if not x['verbatim']])}"]),
        "Every source-derived string on every screen, with the controlled row it came from "
        "and whether it is carried verbatim.", "",
        _tbl(["Screen", "Row", "Page", "Verbatim", "Text"],
             [(x["screen_id"], x["row_id"], x["module_page"],
               "yes" if x["verbatim"] else "**NO**", x["learner_text"]) for x in st]), ""])))

    at = M.authority_traceability()
    files.append(_j("T04_STORYBOARD_AUTHORITY_TRACEABILITY_v1.json",
                    dict(stage=M.STAGE, rows=at, row_count=len(at))))
    files.append(_w("T04_STORYBOARD_AUTHORITY_TRACEABILITY_v1.md", "\n".join([
        _hdr("T04 — SCREEN TO AUTHORITY TRACEABILITY", [f"BINDINGS = {len(at)}"]),
        "Every screen, every decision that governs it, and the authority wording behind it.",
        "",
        _tbl(["Screen", "Decision", "Class", "Authority", "Grade", "Quoted wording"],
             [(x["screen_id"], x["decision_id"], x["decision_class"], x["authority"],
               x["evidence_grade"], x["authority_quote"][:110]) for x in at]), ""])))

    im = M.interaction_model()
    files.append(_j("T04_STORYBOARD_INTERACTION_MODEL_v1.json",
                    dict(stage=M.STAGE, screens=im)))
    files.append(_w("T04_STORYBOARD_INTERACTION_MODEL_v1.md", "\n".join([
        _hdr("T04 — INTERACTION AND STATE MODEL",
             [f"SCREENS = {len(im)}",
              f"INTERACTIVE = {len([x for x in im if x['state_count'] > 1])}"]),
        _tbl(["Screen", "Treatment", "States", "Reveals", "Completion", "Residual risk"],
             [(x["screen_id"], x["treatment"], x["state_count"], x["reveal_count"],
               x["completion_condition"], x["residual_risk"] or "—") for x in im]), ""])))

    vm = M.visual_mapping()
    vt = M.visual_totals()
    files.append(_j("T04_STORYBOARD_VISUAL_MAPPING_v1.json",
                    dict(stage=M.STAGE, totals=vt, screens=vm)))
    files.append(_w("T04_STORYBOARD_VISUAL_MAPPING_v1.md", "\n".join([
        _hdr("T04 — VISUAL OBLIGATION AND ASSET MAPPING",
             [f"VISUAL_OBLIGATIONS     = {vt['visual_obligations']}",
              f"ASSET_GROUPS           = {vt['asset_groups']}",
              f"PROPOSED_UNIQUE_ASSETS = {vt['proposed_unique_assets']}",
              f"ARTWORK_PRODUCED       = {vt['artwork_produced']}"]),
        "46 obligations, 8 groups, 41 proposed unique assets, 0 produced. The inserted "
        "T04-S14 reuses AG-06 and adds none.", "",
        _tbl(["Screen", "Groups", "Obligations", "Reuse policy", "Do not reuse", "Artwork"],
             [(x["screen_id"], ", ".join(x["asset_group_ids"]) or "—",
               len(x["visual_obligations_served"]), x["reuse_policy"],
               ", ".join(x["do_not_reuse_obligations"]) or "—", x["artwork_status"])
              for x in vm]), ""])))

    asx = M.assessment_status()
    files.append(_j("T04_STORYBOARD_ASSESSMENT_STATUS_v1.json", dict(stage=M.STAGE, **asx)))
    files.append(_w("T04_STORYBOARD_ASSESSMENT_STATUS_v1.md", "\n".join([
        _hdr("T04 — ASSESSMENT STATUS REGISTER",
             [f"COMPOSITION       = {asx['composition']}",
              f"PASS_MARK         = {asx['pass_mark']}",
              f"ANSWER_KEY_STATUS = {asx['answer_key_status']}",
              f"E07               = {asx['e07_status']} ({asx['e07_selected_set']})"]),
        "The stems are the authority's. The two Q5 distractors were **selected** by her from "
        "an enumerated pair, which is not the same as her having written them. No answer key "
        "is final, and B1 produces no runtime assessment packet.", "",
        _tbl(["Item", "Type", "Stem provenance", "Authority-authored stem", "Options",
              "Marker", "Proposed key", "Key status"],
             [(x["question_id"], x["question_type"], x["stem_provenance"],
               "yes" if x["stem_is_authority_authored"] else "**no**", x["option_count"],
               x["option_marker_style"], x["proposed_key_positions"], x["key_status"])
              for x in asx["items"]]), "",
        "**Not final:**", ""] + [f"- {x}" for x in asx["what_is_not_final"]] + [
        "", f"*{asx['runtime_packet_note']}*", ""])))

    ev = M.evidence_status()
    files.append(_j("T04_STORYBOARD_EVIDENCE_STATUS_v1.json", dict(stage=M.STAGE, **ev)))
    files.append(_w("T04_STORYBOARD_EVIDENCE_STATUS_v1.md", "\n".join([
        _hdr("T04 — EVIDENCE STATUS REGISTER",
             [f"RELEASE = {' · '.join(ev['release_decision'])}"]),
        _tbl(["Evidence", "ID", "SHA-256", "Custody", "Verified"],
             [(ev["primary_authority_evidence"]["filename"],
               ev["primary_authority_evidence"]["evidence_id"],
               ev["primary_authority_evidence"]["sha256"][:16] + "…",
               ev["primary_authority_evidence"]["custody"], "yes"),
              (ev["supplementary_authority_evidence"]["filename"],
               ev["supplementary_authority_evidence"]["evidence_id"],
               ev["supplementary_authority_evidence"]["sha256"],
               ev["supplementary_authority_evidence"]["custody"], "**no**")]), "",
        f"E-07 is `{ev['e07_closure']['status']}` by `{ev['e07_closure']['authority']}`, at "
        f"evidence class `{ev['e07_closure']['evidence_class']}` with custody "
        f"`{ev['e07_closure']['custody_status']}`.", "",
        "# Open items", "",
        _tbl(["ID", "Subject", "Owner"],
             [(o["open_id"], o["subject"], o["owner"]) for o in ev["open_items"]]), "",
        "# Source status", "",
        _tbl(["Field", "Value"], list(ev["source_status"].items())), "",
        f"`{ev['source_risk_token']}`", ""])))
    return files


def build_all():
    pptx = build_pptx()
    previews = render_previews()
    files = emit_registers()
    return dict(pptx=pptx, previews=previews, registers=files)


if __name__ == "__main__":
    r = build_all()
    print(f"PPTX      : {r['pptx']}  ({os.path.getsize(r['pptx'])} bytes)")
    print(f"previews  : {len(r['previews'])}  "
          f"(overflowed: {len([x for x in r['previews'] if x['overflowed']])})")
    for f in r["registers"]:
        print(f"register  : {f}")
