# -*- coding: utf-8 -*-
"""Stage 4.2F-B0.8 — emit every content and instance-mapping artifact from one data source."""
import csv, io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import t04_content_data_v1 as D

OUT = os.path.abspath(os.path.join(HERE, ".."))
BANNER = (f"<!-- GENERATED by {D.GENERATED_BY} — Stage {D.STAGE}. "
          "Edit the data module, not this file. -->")


def _w(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text if text.endswith("\n") else text + "\n")
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1))


def _hdr(title, extra=()):
    lines = [BANNER, "", f"# {title}", "", "```",
             f"STAGE                   = {D.STAGE}",
             f"UNIT                    = {D.UNIT_ID} — {D.LESSON_TITLE}",
             f"CONTENT_STATUS          = {D.CONTENT_STATUS}",
             f"APPROVAL_STATUS         = {D.APPROVAL_STATUS}",
             f"INSTRUCTIONAL_AUTHORITY = {D.INSTRUCTIONAL_AUTHORITY}"]
    lines += list(extra) + ["```", ""]
    return "\n".join(lines)


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def _rev():
    return "ACCEPT ☐   EDIT ☐   REMOVE ☐   COMMENT: ______________________"


# ==========================================================================================
def emit_closure_md():
    p = [_hdr("T04 — VISUAL OBLIGATION CLOSURE",
              [f"VISUAL_OBLIGATIONS_TOTAL  = {D.VISUAL_OBLIGATIONS_TOTAL}",
               f"VISUAL_OBLIGATIONS_CLOSED = {D.VISUAL_OBLIGATIONS_CLOSED}",
               f"ORPHAN_OBLIGATIONS        = {D.ORPHAN_OBLIGATIONS}",
               f"POLICY_RULE               = {D.VISUAL_POLICY_RULE}"]),
         "# 1. Three authorities, kept apart", "",
         _tbl(["Authority", "Value", "What it decides"], [
             ("requirement", D.REQUIREMENT_AUTHORITY,
              "that a visual is required at all — Bariah's ruling"),
             ("population derivation", D.POPULATION_DERIVATION_AUTHORITY,
              "WHICH descendants exist — the module's heading structure"),
             ("subject", D.SUBJECT_AUTHORITY,
              "WHAT each visual shows — the module's text")]), "",
         f"**The policy rule was renamed.** `{D.SUPERSEDED_POLICY_RULE}` → "
         f"`{D.VISUAL_POLICY_RULE}`.", "", D.POLICY_RENAME_REASON, "",
         "# 2. Closure accounting", "",
         _tbl(["Outcome", "Count"],
              [(k, v) for k, v in D.CLOSURE_BY_OUTCOME.items()] +
              [("**TOTAL**", f"**{D.VISUAL_OBLIGATIONS_TOTAL}**")]), "",
         f"`ORPHAN_OBLIGATIONS = {D.ORPHAN_OBLIGATIONS}`. The outcome "
         f"`{D.FORBIDDEN_OUTCOME}` appears nowhere.", "",
         "The five `COVERED_BY_COMPOSITE_ASSET_GROUP` obligations still receive a visual — a "
         "labelled panel inside a composite another obligation already pays for. Splitting "
         "them out would destroy the comparison the source teaches. The three "
         "`NOT_A_SEPARATE_ASSET_WITH_REASON` obligations are the *Aspek Pengurusan untuk "
         "Kontraktor* headings, which have no body text and therefore no subject to draw.", "",
         "# 3. The 46 obligations", ""]
    for r in D.OBLIGATION_CLOSURE:
        p += [f"## {r['obligation_id']} — {r['source_heading']}", "", "```",
              f"closure_outcome                = {r['closure_outcome']}",
              f"source_row_ids                 = {', '.join(r['source_row_ids'])}",
              f"proposed_learner_screen_id     = {r['proposed_learner_screen_id'] or '—'}",
              f"proposed_runtime_state_id      = {r['proposed_runtime_state_id'] or '—'}",
              f"proposed_asset_group_id        = {r['proposed_asset_group_id']}",
              f"unique_asset_candidate_id      = {r['unique_asset_candidate_id'] or '—'}",
              f"composite_or_individual        = {r['composite_or_individual']}",
              f"reuse_policy                   = {r['reuse_policy']}",
              f"screens_or_states_served       = {r['screens_or_states_served']}",
              f"visual_class                   = {r['visual_class']}",
              f"complexity_tier                = {r['complexity_tier']}",
              f"production_complexity          = {r['production_complexity']}",
              f"requirement_authority          = {r['requirement_authority']}",
              f"population_derivation_authority= {r['population_derivation_authority']}",
              f"subject_authority              = {r['subject_authority']}",
              f"mmd_dependency                 = {r['mmd_dependency']}",
              f"approval_status                = {r['approval_status']}",
              "```", "",
              f"**Visual subject.** {r['visual_subject']}", "",
              f"**Rationale.** {r['rationale']}", ""]
        if r["reuse_note"]:
            p += [f"**Reuse.** {r['reuse_note']}", ""]
    return _w("T04_VISUAL_OBLIGATION_CLOSURE_v1.md", "\n".join(p))


def emit_closure_csv():
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(D.CLOSURE_FIELDS)
    for r in D.OBLIGATION_CLOSURE:
        w.writerow([";".join(r[f]) if isinstance(r[f], list) else
                    ("" if r[f] is None else r[f]) for f in D.CLOSURE_FIELDS])
    return _w("T04_VISUAL_OBLIGATION_CLOSURE_v1.csv", buf.getvalue())


def emit_closure_json():
    return _j("T04_VISUAL_OBLIGATION_CLOSURE_v1.json", dict(
        pack="T04_VISUAL_OBLIGATION_CLOSURE", version="v1", stage=D.STAGE,
        suite_id=D.SUITE_ID, unit_id=D.UNIT_ID,
        content_status=D.CONTENT_STATUS, approval_status=D.APPROVAL_STATUS,
        instructional_authority=D.INSTRUCTIONAL_AUTHORITY,
        policy_rule=D.VISUAL_POLICY_RULE,
        superseded_policy_rule=D.SUPERSEDED_POLICY_RULE,
        policy_rename_reason=D.POLICY_RENAME_REASON,
        requirement_authority=D.REQUIREMENT_AUTHORITY,
        population_derivation_authority=D.POPULATION_DERIVATION_AUTHORITY,
        subject_authority=D.SUBJECT_AUTHORITY,
        closure_outcomes=D.CLOSURE_OUTCOMES, forbidden_outcome=D.FORBIDDEN_OUTCOME,
        totals=dict(VISUAL_OBLIGATIONS_TOTAL=D.VISUAL_OBLIGATIONS_TOTAL,
                    VISUAL_OBLIGATIONS_CLOSED=D.VISUAL_OBLIGATIONS_CLOSED,
                    ORPHAN_OBLIGATIONS=D.ORPHAN_OBLIGATIONS,
                    by_outcome=D.CLOSURE_BY_OUTCOME),
        decisions=D.DECISIONS, d04_provenance=D.D04_PROVENANCE,
        fields=D.CLOSURE_FIELDS, obligations=D.OBLIGATION_CLOSURE))


# ==========================================================================================
def emit_assets_md():
    t = D.ASSET_TOTALS
    p = [_hdr("T04 — VISUAL ASSET GROUPING PLAN v2",
              [f"VISUAL_OBLIGATION_COUNT   = {t['visual_obligation_count']}",
               f"ASSET_GROUP_COUNT         = {t['asset_group_count']}",
               f"PROPOSED_UNIQUE_ASSETS    = {t['proposed_unique_assets']}",
               f"UNIQUE_ASSET_COUNT        = {D.UNIQUE_ASSET_COUNT}",
               f"MMD_PRODUCTION            = NOT_STARTED"]),
         "# 1. Obligations are not assets", "", t["obligations_are_not_assets"], "",
         _tbl(["Reported separately", "Count"], [
             ("visual obligation count", t["visual_obligation_count"]),
             ("asset group count", t["asset_group_count"]),
             ("composite asset candidates", t["composite_asset_candidate_count"]),
             ("individual asset candidates", t["individual_asset_candidate_count"]),
             ("unique asset count **confirmed**", t["unique_asset_count_confirmed"]),
             ("unique asset count **undetermined**", t["unique_asset_count_undetermined"]),
             ("do-not-reuse **groups**", t["do_not_reuse_group_count"]),
             ("do-not-reuse **obligations**", t["do_not_reuse_obligation_count"])]), "",
         f"`UNIQUE_ASSET_COUNT = {D.UNIQUE_ASSET_COUNT}`. The 41 is a proposal, not a "
         "production volume.", "",
         "# 2. Asset groups", ""]
    for g in D.ASSET_GROUPS:
        p += [f"## {g['asset_group_id']} — {g['label']}", "", "```",
              f"obligations_covered         = {len(g['obligations_covered'])}",
              f"proposed_unique_assets      = {g['proposed_unique_assets']}"
              f"  ({g['assets_from_obligations']} from obligations"
              f" + {g['additional_assets']} additional)",
              f"composite_or_individual     = {g['composite_or_individual']}",
              f"complexity_tier             = {g['complexity_tier']}",
              f"affected_screens            = {', '.join(g['affected_screens'])}",
              f"source_reference_available  = {g['source_reference_available']}",
              f"mmd_production_status       = {g['mmd_production_status']}",
              f"bariah_approval_requirement = {g['bariah_approval_requirement']}",
              f"effort_band                 = {g['effort_band']}",
              "```", "",
              f"**Visual concept.** {g['visual_concept']}", "",
              f"**Source grounding.** {g['source_grounding']}", "",
              f"**Reuse.** {g['reuse_conditions']}", ""]
        if g["obligations_covered"]:
            p += ["Obligations: " + ", ".join(f"`{o}`" for o in g["obligations_covered"]), ""]
        else:
            p += [f"**Obligations covered: none, by design.** {g['empty_reason']}", ""]
        if g.get("additional_assets_reason"):
            p += [f"**Additional assets.** {g['additional_assets_reason']}", ""]
    return _w("T04_VISUAL_ASSET_GROUPING_PLAN_v2.md", "\n".join(p))


def emit_assets_csv():
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(D.ASSET_GROUP_FIELDS)
    for g in D.ASSET_GROUPS:
        w.writerow([";".join(g[f]) if isinstance(g[f], list) else g[f]
                    for f in D.ASSET_GROUP_FIELDS])
    return _w("T04_VISUAL_ASSET_GROUPING_PLAN_v2.csv", buf.getvalue())


def emit_assets_json():
    return _j("T04_VISUAL_ASSET_GROUPING_PLAN_v2.json", dict(
        pack="T04_VISUAL_ASSET_GROUPING_PLAN", version="v2", stage=D.STAGE,
        unit_id=D.UNIT_ID, unique_asset_count=D.UNIQUE_ASSET_COUNT,
        complexity_tiers=D.COMPLEXITY_TIERS, totals=D.ASSET_TOTALS,
        fields=D.ASSET_GROUP_FIELDS, asset_groups=D.ASSET_GROUPS))


# ==========================================================================================
def emit_sequence_md():
    p = [_hdr("T04 — PROPOSED LEARNER-SCREEN SEQUENCE",
              [f"PROPOSED_LEARNER_SCREEN_COUNT = {D.PROPOSED_LEARNER_SCREEN_COUNT}",
               f"FINAL_LEARNER_SCREEN_COUNT    = {D.FINAL_LEARNER_SCREEN_COUNT}",
               f"SOURCE_ROWS_COVERED           = "
               f"{D.SOURCE_ROW_COVERAGE['rows_on_at_least_one_screen']} / "
               f"{D.SOURCE_ROW_COVERAGE['total_rows']}",
               f"B02_SCREEN_COUNT_INHERITED    = {D.B02_SCREEN_COUNT_INHERITED}",
               f"B02_FAMILIES_PROPAGATED       = {D.B02_FAMILIES_PROPAGATED}"]),
         "# 1. The count", "", D.SCREEN_COUNT_NOTE, "",
         f"**`FINAL_LEARNER_SCREEN_COUNT = {D.FINAL_LEARNER_SCREEN_COUNT}`** — the proposed "
         "count is CAIR's arithmetic over the source; the final count is Bariah's decision.",
         "", "# 2. Populations accounted for", "",
         _tbl(["Population", "Screens"],
              [(r["population"], ", ".join(r["screens"])) for r in D.REQUIRED_POPULATIONS]),
         "",
         f"All {D.SOURCE_ROW_COVERAGE['total_rows']} controlled source rows appear on at "
         "least one screen. Uncovered rows: " +
         (", ".join(D.SOURCE_ROW_COVERAGE["uncovered_rows"]) or "**none**") + ".", "",
         "# 3. The sequence", "",
         _tbl(["Screen", "Title", "Treatment", "Rows", "Obligations", "States"],
              [(s["screen_id"], s["working_title"], s["treatment"],
                len(s["source_row_ids"]), len(s["visual_obligations_served"]),
                len(s["interaction_states"])) for s in D.SCREEN_SEQUENCE]), ""]
    for s in D.SCREEN_SEQUENCE:
        p += [f"## {s['screen_id']} — {s['working_title']}", "", "```",
              f"treatment                  = {s['treatment']}",
              f"source_row_ids             = {', '.join(s['source_row_ids']) or '—'}",
              f"visual_obligations_served  = "
              f"{', '.join(s['visual_obligations_served']) or '—'}",
              f"asset_groups_used          = {', '.join(s['asset_groups_used']) or '—'}",
              f"completion_condition       = {s['completion_condition']}",
              f"bariah_review_status       = {s['bariah_review_status']}",
              "```", "",
              f"**Instructional purpose.** {s['instructional_purpose']}", "",
              f"**Learner outcome.** {s['learner_outcome']}", "",
              f"**Base state.** {s['base_state']}", "",
              "**Interaction states.** " + "; ".join(s["interaction_states"]), "",
              f"**Narration.** {s['narration_treatment']}", "",
              f"**Speaker Notes.** {s['speaker_notes_treatment']}", "",
              f"**Accessibility.** {s['accessibility_treatment']}", "",
              f"**Technical-claim dependency.** {s['technical_claim_dependency']}", "",
              _rev(), ""]
    return _w("T04_PROPOSED_SCREEN_SEQUENCE_v1.md", "\n".join(p))


def emit_sequence_json():
    return _j("T04_PROPOSED_SCREEN_SEQUENCE_v1.json", dict(
        pack="T04_PROPOSED_SCREEN_SEQUENCE", version="v1", stage=D.STAGE, unit_id=D.UNIT_ID,
        content_status=D.CONTENT_STATUS, approval_status=D.APPROVAL_STATUS,
        instructional_authority=D.INSTRUCTIONAL_AUTHORITY,
        proposed_learner_screen_count=D.PROPOSED_LEARNER_SCREEN_COUNT,
        final_learner_screen_count=D.FINAL_LEARNER_SCREEN_COUNT,
        b02_screen_count_inherited=D.B02_SCREEN_COUNT_INHERITED,
        b02_families_propagated=D.B02_FAMILIES_PROPAGATED,
        screen_count_note=D.SCREEN_COUNT_NOTE,
        required_populations=D.REQUIRED_POPULATIONS,
        source_row_coverage=D.SOURCE_ROW_COVERAGE,
        fields=D.SCREEN_FIELDS, screens=D.SCREEN_SEQUENCE))


# ==========================================================================================
def emit_fit():
    f = D.CONTEXTUAL_FIT
    p = [_hdr("T04 — CHARACTER CONTEXTUAL FIT ASSESSMENT v2",
              [f"ASSESSMENT_ID           = {f['assessment_id']}",
               f"SUPERSEDES              = {f['supersedes']}",
               f"RESULT                  = {f['recommendation']}",
               f"AUTHORITY               = {f['authority']}",
               f"INSTANCE_MAPPING        = {f['instance_mapping_status']}"]),
         "# 1. Dialogue purpose", "",
         "The Slide 2 dialogue must remain at:", ""]
    p += [f"- {x}" for x in f["dialogue_purpose"]] + [""]
    p += [f"**It must not carry:** {f['dialogue_purpose_excludes']}", "",
          "Source rows: " + ", ".join(f"`{r}`" for r in f["source_row_bindings"]), "",
          "# 2. Do the characters fit?", ""]
    for blk in (f["alya"], f["encik_rahman"]):
        p += [f"## {blk['character']} — {blk['established_role']}", "",
              f"**Role in dialogue.** {blk['role_in_dialogue']}", "",
              f"**Fits: {'YES' if blk['fits'] else 'NO'}** · risk `{blk['risk']}`", ""]
        if blk.get("conditional_on"):
            p += [f"Conditional on: {blk['conditional_on']}", ""]
        p += [blk["reasoning"], ""]
    p += [f"Role source: `{f['roles_source']}`", "",
          "# 3. Specialist expertise", "",
          _tbl(["Question", "Answer"], [
              ("Required for Slide 2?", f["specialist_expertise_required_for_slide_2"]),
              ("Required anywhere in the unit?", f["specialist_expertise_required_in_unit"])]),
          "", f["specialist_expertise_detail"], "",
          "# 4. Risk of unsupported expertise", "",
          f"**Level `{f['unsupported_expertise_risk']['level']}`**", "",
          f["unsupported_expertise_risk"]["description"], "",
          f"**Mitigation.** {f['unsupported_expertise_risk']['mitigation']}", "",
          f"Residual: `{f['unsupported_expertise_risk']['residual_after_mitigation']}`", "",
          "# 5. Recommendation", "",
          f"**`{f['recommendation']}`**", "", f["recommendation_condition"], "",
          f"A new character would be required if: {f['new_character_would_be_required_if']}",
          "",
          f"`{f['authority']}` · `{f['status']}`. Instance mapping is "
          f"`{f['instance_mapping_status']}` — proposed by CAIR, not approved by Bariah.", "",
          _rev(), ""]
    return _w("T04_CHARACTER_CONTEXTUAL_FIT_ASSESSMENT_v2.md", "\n".join(p))


def emit_dialogue_md():
    g = D.DIALOGUE
    p = [_hdr("T04 — SLIDE 2 DIALOGUE, CAIR-ASSISTED DRAFT",
              [f"SCREEN                  = {g['screen_id']}",
               f"CONTRACT                = {g['contract_id']}",
               f"LEVEL                   = {g['level']}",
               f"CAST_STATUS             = {g['cast_status']}",
               f"FIT_ASSESSMENT          = {g['fit_assessment_id']} → {g['fit_result']}"]),
         "# 1. Cast", "",
         _tbl(["Character", "Role"], list(g["cast"])), "",
         "# 2. The exclusion rule", "", g["compliance_exclusion_rule"], "",
         "Nothing in the dialogue may state any of:", ""]
    p += [f"- {x}" for x in g["compliance_exclusions"]] + [""]
    p += ["This is not stylistic caution. The module states that pesticide spraying must be "
          "done by a licensed operator, and Encik Rahman is a senior contractor, not a "
          "licensed operator. A mentor character stating a statutory duty converts a source "
          "citation into a character's word. A gate scans every line and fails on a hit.", "",
          "# 3. The dialogue", ""]
    for L in g["lines"]:
        p += [f"### {L['dialogue_line_id']} — {L['speaker']}", "",
              f"> {L['text']}", "", "```",
              f"source_row_ids       = {', '.join(L['source_row_ids'])}",
              f"instructional_function = {L['instructional_function']}",
              f"factual_risk_status  = {L['factual_risk_status']}",
              f"vo_status            = {L['vo_status']}",
              "```", "", _rev(), ""]
    p += ["# 4. Status", "", "```",
          f"content_status          = {g['content_status']}",
          f"instructional_authority = {g['instructional_authority']}",
          f"approval_status         = {g['approval_status']}",
          "```", "", g["drafting_basis"], "", g["length_note"], ""]
    return _w("T04_SLIDE_2_DIALOGUE_CAIR_DRAFT_v1.md", "\n".join(p))


def emit_dialogue_json():
    return _j("T04_SLIDE_2_DIALOGUE_CAIR_DRAFT_v1.json", dict(
        pack="T04_SLIDE_2_DIALOGUE", version="v1", stage=D.STAGE, unit_id=D.UNIT_ID,
        contextual_fit=D.CONTEXTUAL_FIT, dialogue=D.DIALOGUE))


# ==========================================================================================
def emit_rumusan_md():
    r = D.RUMUSAN
    p = [_hdr("T04 — RUMUSAN, CAIR-ASSISTED DRAFT v3",
              [f"POINTS                  = {len(r['points'])}",
               f"MEDIUM_RISK_POINT       = {r['medium_risk_point_id']}",
               f"SUPERSEDES              = {r['supersedes']}",
               "STYLE_INSTRUCTION       = BR-W3 (Topik 3 Bahagian 2)"]),
         "# 1. What changed from v2", "", r["change_from_v2"], "",
         "# 2. Style, taken from the approved Topik 3 Bahagian 2 treatment", "",
         f"**{D.RUMUSAN_STYLE_SOURCE['prohibition']}**", "",
         _tbl(["Rule", "Characteristic", "Observed", "Applied to T04"],
              [(s["rule_id"], s["characteristic"], s["observed"], s["applied_as"])
               for s in D.RUMUSAN_STYLE_RULES]), "",
         "# 3. The draft", "", f"**{r['heading']}**", ""]
    for s in r["points"]:
        p += [f"## {s['point_id']}", "", f"> {s['draft_text']}", "", "```",
              f"source_row_ids     = {', '.join(s['source_row_ids'])}",
              f"source_heading     = {s['source_heading']}",
              f"style_rule_applied = {', '.join(s['style_rule_applied'])}",
              f"style_deviation    = {s['style_deviation'] or 'none'}",
              "```", "",
              f"**Factual risk.** {s['factual_risk_status']}", "", _rev(), ""]
    p += ["# 4. Provenance", "", r["provenance"], "",
          "# 5. Why four points and not five", "", r["consolidation_note"], "",
          _tbl(["v1", "Topic", "v2/v3", "Change"],
               [(m["v1"], m["v1_topic"], m["v2"], m["change"])
                for m in r["v1_to_v2_mapping"]]), ""]
    return _w("T04_RUMUSAN_CAIR_ASSISTED_DRAFT_v3.md", "\n".join(p))


def emit_rumusan_json():
    return _j("T04_RUMUSAN_CAIR_ASSISTED_DRAFT_v3.json", dict(
        pack="T04_RUMUSAN", version="v3", stage=D.STAGE, unit_id=D.UNIT_ID,
        style_rules=D.RUMUSAN_STYLE_RULES, style_source=D.RUMUSAN_STYLE_SOURCE,
        rumusan=D.RUMUSAN))


# ==========================================================================================
def emit_quiz_md():
    q = D.QUIZ
    c = q["coverage_accounting"]
    p = [_hdr("T04 — QUIZ, CAIR-ASSISTED DRAFT",
              [f"COMPOSITION             = {q['composition']}",
               f"PASS_THRESHOLD          = {q['pass_threshold']}",
               f"SCOPE                   = {q['scope']}",
               f"ANSWER_KEY              = {q['answer_key_status']}",
               f"ANSWER_KEY_APPROVAL     = {q['answer_key_approval']}"]),
         "# 1. These are drafts", "",
         f"Five items with stems, options and a **`{q['answer_key_status']}`**. Nothing here "
         "is a final question and nothing here is a final key. Bariah authors or approves the "
         "assessment; this is material for her to work from.", "",
         "# 2. Coverage accounting", "",
         _tbl(["", "Value"], [
             ("blueprint coverage points", len(c["blueprint_points"])),
             ("slots", c["slots"]),
             ("discarded", f"**{c['discarded']}**"),
             ("merged into", c["merged"]["into"]),
             ("merged from", ", ".join(c["merged"]["from_points"]))]), "",
         f"**The merge.** {c['merged']['disclosure']}", "",
         f"**What it costs.** {c['merged']['cost']}", "",
         "# 3. The five items", ""]
    for it in q["items"]:
        p += [f"## {it['question_id']} — {it['question_type']}", "",
              f"**{it['draft_stem']}**", ""]
        for k, v in it["draft_options"]:
            mark = " ←" if k in it["proposed_correct_answer"] else ""
            p += [f"- **{k}.** {v}{mark}"]
        p += ["", "```",
              f"proposed_correct_answer = {', '.join(it['proposed_correct_answer'])}"
              f"   ({q['answer_key_status']} · {q['answer_key_approval']})",
              f"source_row_ids          = {', '.join(it['source_row_ids'])}",
              f"cognitive_demand        = {it['cognitive_demand']}",
              f"visual_dependency       = {it['visual_dependency']}",
              f"factual_risk_status     = {it['factual_risk_status']}",
              "```", "",
              f"**Correct-answer evidence.** {it['correct_answer_evidence']}", "",
              f"**Distractor rationale.** {it['distractor_rationale']}", "",
              f"**Misconception assessed.** {it['misconception_assessed']}", "",
              f"**Overlap check.** {it['overlap_check']}", "",
              f"**Feedback.** correct: *{it['feedback_proposal']['correct']}* · "
              f"incorrect: *{it['feedback_proposal']['incorrect']}*", "",
              _rev(), ""]
    p += ["# 4. Status", "", "```",
          f"content_status              = {q['content_status']}",
          f"final_instructional_authority = {q['final_instructional_authority']}",
          f"approval_status            = {q['approval_status']}",
          f"pass_threshold             = {q['pass_threshold']}",
          f"scope                      = {q['scope']}",
          "```", ""]
    return _w("T04_QUIZ_CAIR_ASSISTED_DRAFT_v1.md", "\n".join(p))


def emit_quiz_json():
    return _j("T04_QUIZ_CAIR_ASSISTED_DRAFT_v1.json", dict(
        pack="T04_QUIZ", version="v1", stage=D.STAGE, unit_id=D.UNIT_ID,
        fields=D.QUIZ_ITEM_FIELDS, quiz=D.QUIZ))


# ==========================================================================================
def emit_mmd():
    f, t = D.MMD_FORECAST, D.MMD_TOTALS
    p = [_hdr("T04 — PRELIMINARY MMD DEMAND FORECAST",
              [f"STATUS                  = {f['status']}",
               f"COMMITMENT              = {f['commitment']}",
               f"GATE                    = {f['gate']}",
               f"PRODUCTION_STATUS       = {f['production_status']}"]),
         f"**`{f['commitment']}`.** {f['hours_note']}", "",
         "# 1. Totals", "",
         _tbl(["", "Count"], [
             ("total proposed asset groups", t["total_proposed_asset_groups"]),
             ("total proposed unique assets", t["total_proposed_unique_assets"]),
             ("composite assets", t["composite_assets"]),
             ("individual assets", t["individual_assets"]),
             ("high-complexity groups", t["high_complexity_groups"]),
             ("reusable groups", t["reusable_groups"]),
             ("non-reusable groups", t["non_reusable_groups"]),
             ("unresolved groups", t["unresolved_groups"])]), "",
         "# 2. Per group", "",
         _tbl(["Group", "Tier", "Assets", "Screens", "Source ref", "Illustration/photo",
               "Effort", "Production"],
              [(g["asset_group_id"], g["complexity_tier"], g["proposed_asset_count"],
                ", ".join(g["affected_screens"]), g["source_reference_available"],
                g["illustration_or_photo_direction"], f"**{g['estimated_mmd_effort_band']}**",
                g["mmd_production_status"]) for g in f["groups"]]), "",
         "# 3. What this is not", "",
         "This forecast is arithmetic over a proposed screen sequence Bariah has not "
         "approved. If she regroups the screens, the asset groups change and so does every "
         "number above. No production hours appear anywhere, because no measured MMD baseline "
         "exists for this toolchain — an hour figure would be invented.", "",
         f"`{f['gate']}`", ""]
    return _w("T04_MMD_DEMAND_FORECAST_PRELIMINARY_v1.md", "\n".join(p))


# ==========================================================================================
def emit_review_pack():
    q = D.QUIZ
    # No BANNER here: this pack is human-facing and the brief forbids repository paths in it.
    # Provenance for this file lives in the run manifest instead.
    p = ["# T04 — Pakej Semakan Bariah", "",
         "**Penjagaan dan Penyelenggaraan · Topik 4**", "",
         "Semua kandungan di bawah adalah **draf**. Papan cerita belum dijana dan tiada aset "
         "visual dihasilkan. Mohon Bariah tandakan ACCEPT, EDIT atau REMOVE bagi setiap "
         "item, dan tulis komen di mana perlu.", "",
         "---", "", "## A. Cadangan susunan skrin", "",
         f"Kami cadangkan **{D.PROPOSED_LEARNER_SCREEN_COUNT} skrin**. Jumlah akhir menunggu "
         "kelulusan Bariah.", "",
         _tbl(["Skrin", "Tajuk", "Layanan"],
              [(s["screen_id"], s["working_title"], s["treatment"])
               for s in D.SCREEN_SEQUENCE]), "", _rev(), "",
         "---", "", "## B. Visual dan kumpulan aset", "",
         f"Bariah menetapkan visual bagi setiap langkah proses, setiap operasi dan setiap "
         f"sub-topik. Ini menghasilkan **{D.VISUAL_OBLIGATIONS_TOTAL} tempat yang memerlukan "
         f"visual**. Selepas dikumpulkan, ia menjadi **{D.ASSET_TOTALS['asset_group_count']} "
         f"kumpulan** dan cadangan **{D.ASSET_TOTALS['proposed_unique_assets']} visual "
         "berasingan** — bukan 46, kerana beberapa visual perbandingan berkongsi satu gambar.",
         "",
         _tbl(["Kumpulan", "Visual", "Cadangan bilangan", "Skrin"],
              [(g["asset_group_id"], g["label"], g["proposed_unique_assets"],
                ", ".join(g["affected_screens"])) for g in D.ASSET_GROUPS]), "", _rev(), "",
         "---", "", "## C. Perbualan Slide 2", "",
         "Watak: **Alya** (Kontraktor Junior) dan **Encik Rahman** (Mentor / Kontraktor "
         "Senior). Perbualan ini hanya mengenai aliran proses dan perbezaan landskap lembut "
         "dengan landskap kejur. Tiada kandungan racun, PPE atau undang-undang diletakkan "
         "dalam perbualan.", ""]
    for L in D.DIALOGUE["lines"]:
        p += [f"**{L['speaker']}:** {L['text']}", ""]
    p += [_rev(), "", "---", "", "## D. Rumusan — 4 ayat", "",
          f"**{D.RUMUSAN['heading']}**", ""]
    for s in D.RUMUSAN["points"]:
        p += [f"{s['point_id'][-2:]}. {s['draft_text']}", ""]
    p += ["> Nota: ayat keempat menyatakan tanggungjawab kontraktor sebagai satu peraturan "
          "am. Modul mengulang corak ini tiga kali tetapi tidak pernah menyatakannya sebagai "
          "peraturan am. Mohon Bariah sahkan sama ada ia boleh dikekalkan.", "", _rev(), "",
          "---", "", "## E. Kuiz — 5 soalan", "",
          f"4 MCQ + 1 Multiple Response · markah lulus {q['pass_threshold'].replace('_',' ')} "
          "· cadangan jawapan sahaja, belum muktamad.", ""]
    for it in q["items"]:
        p += [f"### {it['question_id']} ({it['question_type']})", "",
              it["draft_stem"], ""]
        for k, v in it["draft_options"]:
            mark = "  ← cadangan jawapan" if k in it["proposed_correct_answer"] else ""
            p += [f"- {k}. {v}{mark}"]
        p += ["", _rev(), ""]
    p += ["---", "", "## F. Keputusan yang masih diperlukan daripada Bariah", "",
          _tbl(["#", "Perkara", "Apa yang diperlukan"],
               [(a["approval_id"], a["item"], a["what"])
                for a in D.REMAINING_BARIAH_APPROVALS]), ""]
    return _w("T04_BARIAH_CONTENT_REVIEW_PACK_v1.md", "\n".join(p))


def emit_whatsapp():
    w = D.WHATSAPP
    p = [BANNER, "", "# T04 — BARIAH WHATSAPP CONTENT REVIEW DRAFT", "", "```",
         f"STATUS            = {w['status']}",
         f"LANGUAGE          = {w['language']}",
         f"SENDING_AUTHORITY = {w['sending_authority']}",
         "```", "",
         f"**`{w['status']}`.** Sending is {w['sending_authority']}'s call.", "",
         "# Message", "", "```", w["text"], "```", "", "# Constraints honoured", ""]
    p += [f"- {x}" for x in w["constraints_honoured"]] + [""]
    return _w("T04_BARIAH_WHATSAPP_CONTENT_REVIEW_DRAFT_v1.md", "\n".join(p))


EMITTERS = [emit_closure_md, emit_closure_csv, emit_closure_json,
            emit_assets_md, emit_assets_csv, emit_assets_json,
            emit_sequence_md, emit_sequence_json, emit_fit,
            emit_dialogue_md, emit_dialogue_json,
            emit_rumusan_md, emit_rumusan_json,
            emit_quiz_md, emit_quiz_json, emit_mmd,
            emit_review_pack, emit_whatsapp]

if __name__ == "__main__":
    written = [e() for e in EMITTERS]
    for n in written:
        print("wrote", n)
    print(f"{len(written)} files")
