# -*- coding: utf-8 -*-
"""Stage 4.2F-C — emit the SRC-AUTH-01 record and the cross-course source custody manifest.

    python3 docs/source/tools/src_emit_v1.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import src_authority_v1 as A   # noqa: E402

BANNER = (f"<!-- GENERATED by {A.GENERATED_BY} — Stage {A.STAGE}. "
          "Edit the model, not this file. -->")

ARTIFACTS = ["SRC_AUTH_01_v1.json", "SRC_AUTH_01_v1.md",
             "SOURCE_CUSTODY_MANIFEST_v1.json", "SOURCE_CUSTODY_MANIFEST_v1.md"]


def _w(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text)
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1) + "\n")


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|") for c in r) + " |")
    return "\n".join(out)


def emit_all():
    made = []
    au = A.AUTHORITY

    made.append(_j("SRC_AUTH_01_v1.json",
                   dict(stage=A.STAGE, lane=A.LANE, authority=au,
                        supersession=A.SUPERSESSION,
                        still_blocked_by_others=A.STILL_BLOCKED_BY_OTHERS,
                        pending_pattern_package=A.PENDING_PATTERN_PACKAGE)))
    md = [BANNER, "", "# SRC-AUTH-01 — project source-processing authority", "", "```",
          f"AUTHORITY_ID = {au['authority_id']}",
          f"OWNER        = {au['owner']}",
          f"STATUS       = {au['status']}",
          f"GRANULARITY  = {au['granularity']}",
          f"APPLIED_AT   = {au['applied_at']}", "```", "",
          "## Scope", "", au["scope"], "",
          "## Permitted operations", ""]
    md += [f"- {x}" for x in au["permitted_operations"]]
    md += ["", "## Explicit exclusions", "",
           "This is the half of the record that does the work. A processing permission that "
           "quietly reads as an instructional permission is worse than no record at all.", ""]
    md += [f"- **{x}**" for x in au["explicit_exclusions"]]

    s = A.SUPERSESSION
    md += ["", "## Relationship to the historical D-25", "", "```",
           f"{s['historical_id']}",
           f"{s['relationship']}",
           f"{s['live_id']}", "```", "",
           f"Historical record status: **{s['historical_record_status']}**. "
           f"It stays at `{s['historical_location']}` exactly as it was asked.", "",
           s["note"], "",
           "## What SRC-AUTH-01 does not unblock", "",
           _tbl(["id", "condition", "owner", "note"],
                [[b["stop_id"], b["condition"], b["owner"], b["note"]]
                 for b in A.STILL_BLOCKED_BY_OTHERS]), "",
           "## The pending pattern package", "", "```",
           f"FILE      = {A.PENDING_PATTERN_PACKAGE['filename']}",
           f"STATUS    = {A.PENDING_PATTERN_PACKAGE['status']}",
           f"AUTHORITY = {str(A.PENDING_PATTERN_PACKAGE['is_authority']).lower()}",
           "```", "", A.PENDING_PATTERN_PACKAGE["note"], ""]
    made.append(_w("SRC_AUTH_01_v1.md", "\n".join(md)))

    cm = A.custody_manifest()
    made.append(_j("SOURCE_CUSTODY_MANIFEST_v1.json", cm))

    t = cm["totals"]
    md = [BANNER, "", "# Source custody manifest — K5, K3, K2", "", "```",
          f"PACKAGES                    = {t['packages']}",
          f"LOCAL_BINARY_HASH_VERIFIED  = {t['local_binary_hash_verified']}",
          f"CONNECTOR_TEXT_READABLE     = {t['connector_text_readable']}",
          f"CONNECTOR_IDENTIFIED        = {t['connector_identified']}",
          f"SOURCE_BINARY_NOT_AVAILABLE = {t['not_available']}",
          f"SHA256_NOT_COMPUTED         = {t['sha256_not_computed']}",
          f"AUTHORITY_INHERITED         = {A.AUTHORITY['authority_id']}", "```", "",
          "A boundary map, a prior transcript or an extracted JSON is **not** proof that the "
          "original binary is readable. The evidence class on every row below says exactly "
          "how far the verification actually went.", "",
          _tbl(["class", "meaning"],
               [[e["code"], e["meaning"]] for e in A.EVIDENCE_CLASSES]), "",
          "## Packages", "",
          _tbl(["course", "package", "filename", "bytes", "SHA-256", "evidence class"],
               [[r["course"], r["package"], r.get("original_filename", "—"),
                 f"{r['bytes']:,}" if isinstance(r.get("bytes"), int) else r.get("bytes", "—"),
                 (r["sha256"][:16] + "…" if r.get("sha256") and r["sha256"] != A.NOT_COMPUTED
                  else r.get("sha256", "—")),
                 r["evidence_class"]] for r in cm["rows"]]), ""]

    k5 = cm["rows"][0]
    md += ["## K5 — the binary that was believed unavailable", "",
           "The PL06 harvest package recorded the module DOCX as held externally by identity "
           "and not present in this repository. That was true of the repository and false of "
           "this environment: the uploaded Stage 4.2F-A2 freeze package carries the source "
           "DOCX in full, and it hashes to the pinned identity exactly.", "", "```",
           f"runtime path       = {k5['runtime_path']}",
           f"zip member         = {k5['zip_member']}",
           f"bytes              = {k5['bytes']:,}  (match: "
           f"{str(k5['bytes_match']).lower()})",
           f"sha256             = {k5['sha256']}",
           f"sha256 match       = {str(k5['sha256_match']).lower()}",
           f"format             = {k5['format']}  valid: "
           f"{str(k5['format_valid']).lower()}",
           f"body paragraphs    = {k5['body_paragraphs']}",
           f"tables             = {k5['tables']}",
           f"media parts        = {k5['media_parts']}",
           f"package parts      = {k5['package_parts']}",
           f"embedded objects   = {str(k5['embedded_objects_readable']).lower()}",
           "```", "", k5["paragraph_index_basis"], "",
           "### Anchor probe — the boundary map checked against the binary", "",
           "Each frozen paragraph index was opened in the document and its text read. This is "
           "what proves the boundary map; the boundary map does not prove itself.", "",
           _tbl(["paragraph", "unit", "role", "frozen anchor", "observed text", "match"],
                [[p["paragraph_index"], p["unit"], p["role"], p["frozen_anchor"],
                  p["observed_text"], "yes" if p["matches"] else "**NO**"]
                 for p in k5["anchor_probes"]]), "",
           A.ANCHOR_NUMERAL_NOTE, "",
           "## K3 and K2 — reached through the connector, not through disk", "",
           "Both packages were located under the official source root "
           f"`{cm['drive_source_root']['folder_id']}`. "
           + cm["drive_source_root"]["course_mapping_basis"], "",
           "Byte sizes come from Drive metadata. **No SHA-256 was computed for any K3 or K2 "
           "file**, because computing one needs the binary on local disk and it is not there. "
           "The field says `SHA256_NOT_COMPUTED_NO_LOCAL_BINARY` rather than carrying a "
           "plausible-looking value.", "",
           "One readability probe was run against K3 PL03:", "", "```",
           f"outcome            = {cm['k3_readability_probe']['outcome']}",
           f"page markers       = {cm['k3_readability_probe']['observed']['page_markers_found']}"
           f"  (last: {cm['k3_readability_probe']['observed']['last_page_marker']})",
           f"LATIHAN present    = "
           f"{str(cm['k3_readability_probe']['observed']['latihan_present']).lower()}",
           f"SKEMA JAWAPAN      = "
           f"{str(cm['k3_readability_probe']['observed']['skema_jawapan_present']).lower()}",
           "```", "", cm["k3_readability_probe"]["note"], "",
           "### K2 size caveat", "", A.k2_custody()["size_note"], ""]
    made.append(_w("SOURCE_CUSTODY_MANIFEST_v1.md", "\n".join(md)))
    return made


if __name__ == "__main__":
    for m in emit_all():
        print("emitted  :", m)
