# -*- coding: utf-8 -*-
"""Stage 4.2F-F — emit the K2 targeted QA report.

    docs/source/.venv-k2/bin/python docs/source/tools/src_k2f_qa_emit_v1.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import src_k2f_qa_v1 as QA   # noqa: E402

BANNER = ("<!-- GENERATED by docs/source/tools/src_k2f_qa_emit_v1.py — "
          "Stage 4.2F-F. Edit the suite, not this file. -->")


def emit():
    s = QA.summary()
    md = [BANNER, "", "# Targeted QA report — Stage 4.2F-F K2 (binary-dependent)", "",
          "```",
          f"SUITE_ID                      = {s['suite_id']}",
          f"GATES                         = {s['total']}",
          f"PASSED                        = {s['passed']}",
          f"FAILED                        = {len(s['failed'])}",
          f"SKIPPED                       = {s['skipped']}",
          f"ORACLE_SEPARATION_STRUCTURAL  = {s['oracle_separation_structural']}",
          "```", "",
          "Its own identity and its own total; no sibling suite's gate count is merged in. "
          "Where 4.2F-E's suite asserted the binary was NOT read, this suite asserts it WAS "
          "read AND that nothing was over-claimed on the strength of it. A `RAW_BINARY` "
          "oracle basis is used for the first time — the suite re-hashes the local bytes "
          "independently of the model. If the git-ignored binary is absent that one gate is "
          "recorded SKIPPED, never silently passed.", "",
          "## Oracle bases", "", "| basis | gates |", "|---|---|"]
    md += [f"| `{b}` | {n} |" for b, n in s["by_oracle_basis"].items()]
    md += ["", "## Gates by area", "", "| area | gates |", "|---|---|"]
    md += [f"| {t} | {n} |" for t, n in s["by_type"].items() if n]
    md += ["", "## Every gate", "",
           "| gate | area | oracle basis | population | ok |",
           "|---|---|---|---|---|"]
    md += [f"| `{g['gate_id']}` | {g['gate_type']} | `{g['oracle_basis']}` | "
           f"{g['population']} | "
           f"{'skipped' if g['skipped'] else ('yes' if g['ok'] else '**NO**')} |"
           for g in s["gates"]]
    md += ["", "## Not checked", "",
           "Stated so the suite's scope is not mistaken for the whole problem.", ""]
    md += [f"- {n}" for n in s["not_checked"]]
    md += [""]
    p = os.path.join(SRC_DIR, "STAGE_4_2F_F_QA_REPORT_v1.md")
    with open(p, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    j = os.path.join(SRC_DIR, "STAGE_4_2F_F_QA_REPORT_v1.json")
    with open(j, "w", encoding="utf-8") as f:
        json.dump(s, f, ensure_ascii=False, indent=1)
    return p, j, s


if __name__ == "__main__":
    p, j, s = emit()
    print(f"{s['passed']}/{s['total']} passed ({s['skipped']} skipped)")
    print("wrote", os.path.basename(p))
    print("wrote", os.path.basename(j))
