# -*- coding: utf-8 -*-
"""Stage 4.2F-D — emit the targeted QA report.

    python3 docs/source/tools/src_run2_qa_emit_v1.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import src_run2_qa_v1 as QA   # noqa: E402

BANNER = ("<!-- GENERATED by docs/source/tools/src_run2_qa_emit_v1.py — "
          "Stage 4.2F-D. Edit the suite, not this file. -->")


def emit():
    s = QA.summary()
    md = [BANNER, "", "# Targeted QA report — Stage 4.2F-D release facts", "", "```",
          f"SUITE_ID                      = {s['suite_id']}",
          f"GATES                         = {s['total']}",
          f"PASSED                        = {s['passed']}",
          f"FAILED                        = {len(s['failed'])}",
          f"ORACLE_SEPARATION_STRUCTURAL  = {s['oracle_separation_structural']}",
          "```", "",
          "This suite has its own identity and its own total. No gate count from "
          "`PROJECT_SOURCE_CUSTODY_QA_v1`, `PL06_AUTHORITY_HARVEST_BATCH1_QA_v1` or any "
          "T04 suite is merged into it, and none of them was edited to agree with it.",
          "", "## Oracle separation", "", s["oracle_separation_note"], "",
          "| basis | gates | what it means |", "|---|---|---|",
          f"| `LITERAL` | {s['by_oracle_basis']['LITERAL']} | expected value typed by "
          f"hand from the source PDFs or the frozen map |",
          f"| `RAW_FILE` | {s['by_oracle_basis']['RAW_FILE']} | expected value re-read "
          f"from a file on disk, not from the module that consumes it |",
          f"| `INDEPENDENT_MEASURE` | {s['by_oracle_basis']['INDEPENDENT_MEASURE']} | "
          f"expected value computed a second, different way |", "",
          "## Gates by area", "", "| area | gates |", "|---|---|"]
    md += [f"| {t} | {n} |" for t, n in s["by_type"].items() if n]
    md += ["", "## Every gate", "",
           "| gate | area | oracle basis | population | source artifact | ok |",
           "|---|---|---|---|---|---|"]
    md += [f"| `{g['gate_id']}` | {g['gate_type']} | `{g['oracle_basis']}` | "
           f"{g['population']} | `{g['source_artifact']}` | "
           f"{'yes' if g['ok'] else '**NO**'} |" for g in s["gates"]]
    md += ["", "## Not checked", "",
           "Stated so that a reader does not mistake this suite's scope for the whole "
           "problem.", ""]
    md += [f"- {n}" for n in s["not_checked"]]
    md += [""]
    path = os.path.join(SRC_DIR, "STAGE_4_2F_D_QA_REPORT_v1.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    jpath = os.path.join(SRC_DIR, "STAGE_4_2F_D_QA_REPORT_v1.json")
    with open(jpath, "w", encoding="utf-8") as f:
        json.dump(s, f, ensure_ascii=False, indent=1)
    return path, jpath, s


if __name__ == "__main__":
    p, j, s = emit()
    print(f"{s['passed']}/{s['total']} passed")
    print("wrote", os.path.basename(p))
    print("wrote", os.path.basename(j))
