# -*- coding: utf-8 -*-
"""Stage 4.2F-F — read back and schema-check every emitted artifact.

    docs/source/.venv-k2/bin/python docs/source/tools/src_k2f_readback_v1.py

Closure requires that the artifacts on disk actually parse, carry their expected shape, and
agree with each other and with the frozen evidence — not that the emit step printed 'wrote'.
This checks all of them from disk, and exits non-zero if anything fails.

Coverage: all 22 physical files this stage generates are validated —
  * 10 JSON  — schema-checked (required top-level keys)
  * 10 MD    — generation-banner + non-trivial length
  *  1 CSV   — structurally validated against the JSON queue (header, row count, id set)
  *  1 MD    — the narrative run manifest, content-checked (hand-authored, so banner-exempt)
"""
import csv
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.dirname(HERE)

BRIEF_SHA = "0b2d81dda46eaf4fb018a20a78f7f9b2870129c61125768e4438937f3f405680"
GEN_BANNER = "GENERATED by"

# The two files outside the 10-JSON + 10-MD set, now covered here too.
CSV_ARTIFACT = "PRODUCTION_QUEUE_v5.csv"
NARRATIVE_MD = "STAGE_4_2F_F_RUN_MANIFEST.md"
# The run manifest must carry the exact amend-history wording; readback enforces it.
AMEND_SENTENCE = ("The Stage 4.2F-F feature-branch tip was amended and force-updated during "
                  "pre-PR review. No completed-stage commit, historical Stage-E evidence, or "
                  "mainline history was amended.")

# json artifact -> required top-level keys
JSON_SCHEMA = {
    "K2_EXTRACTION_EVIDENCE_v1.json": ["binary_identity", "pl_packages", "kt_papers",
                                       "region_accounting", "totals"],
    "K2_BINARY_CUSTODY_v2.json": ["record", "expected", "binding", "stage"],
    "K2_PAGE_BOUNDARY_MAP_v1.json": ["map_id", "regions", "accounting",
                                     "all_pl_spans_match_declared"],
    "K2_ASSESSMENT_INVENTORY_v1.json": ["inventory_id", "per_pl", "kt_papers",
                                        "kt_paper_count", "observations"],
    "K2_IMAGE_TABLE_INVENTORY_v1.json": ["inventory_id", "method", "per_pl", "totals"],
    "K2_COURSE_HIERARCHY_v2.json": ["rows", "modules", "pl_packages",
                                    "decomposition_completed", "source_ready_clean"],
    "K2_PROVISIONAL_MODELS_v1.json": ["models_id", "count", "models",
                                      "selection_criterion"],
    "K2_DECISION_REGISTER_v1.json": ["register_id", "decisions", "routed_to"],
    "PRODUCTION_QUEUE_v5.json": ["rows", "counts", "member_rolls", "invariants", "k2"],
    "STAGE_4_2F_F_QA_REPORT_v1.json": ["suite_id", "total", "passed", "gates"],
}

MD_ARTIFACTS = [
    "K2_BINARY_CUSTODY_v2.md", "K2_PAGE_BOUNDARY_MAP_v1.md",
    "K2_ASSESSMENT_INVENTORY_v1.md", "K2_IMAGE_TABLE_INVENTORY_v1.md",
    "K2_COURSE_HIERARCHY_v2.md", "K2_PROVISIONAL_MODELS_v1.md",
    "K2_DECISION_REGISTER_v1.md", "PRODUCTION_QUEUE_v5.md",
    "STAGE_4_2F_F_QA_REPORT_v1.md", "STAGE_4_2F_F_MUTATION_REPORT_v1.md",
]

PRESERVE_UNCHANGED = [  # Stage-E history must still be present and untouched
    "K2_BINARY_CUSTODY_v1.json", "K2_BINARY_CUSTODY_v1.md",
    "K2_COURSE_HIERARCHY_v1.json", "K2_COURSE_HIERARCHY_v1.md",
    "STAGE_4_2F_E_RUN_MANIFEST.md", "STAGE_4_2F_E_QA_REPORT_v1.json",
    "STAGE_4_2F_E_MUTATION_REPORT_v1.md",
]


def _load(name):
    with open(os.path.join(SRC_DIR, name), encoding="utf-8") as f:
        return json.load(f)


def check():
    fails = []

    def want(cond, msg):
        if not cond:
            fails.append(msg)

    # 1. JSON parse + schema
    data = {}
    for name, keys in JSON_SCHEMA.items():
        p = os.path.join(SRC_DIR, name)
        want(os.path.exists(p), f"{name} missing")
        if not os.path.exists(p):
            continue
        try:
            data[name] = _load(name)
        except Exception as e:  # noqa: BLE001
            fails.append(f"{name} does not parse: {e}")
            continue
        for k in keys:
            want(k in data[name], f"{name} missing key '{k}'")

    # 2. MD banner + non-trivial length
    for name in MD_ARTIFACTS:
        p = os.path.join(SRC_DIR, name)
        want(os.path.exists(p), f"{name} missing")
        if os.path.exists(p):
            txt = open(p, encoding="utf-8").read()
            want(GEN_BANNER in txt.splitlines()[0], f"{name} lacks generation banner")
            want(len(txt) > 300, f"{name} suspiciously short ({len(txt)} chars)")

    # 3. Stage-E history preserved
    for name in PRESERVE_UNCHANGED:
        want(os.path.exists(os.path.join(SRC_DIR, name)),
             f"Stage-E artifact {name} is missing (history must be preserved)")

    if not data:
        return fails  # nothing else checkable

    ev = data["K2_EXTRACTION_EVIDENCE_v1.json"]
    cust = data["K2_BINARY_CUSTODY_v2.json"]
    pm = data["K2_PAGE_BOUNDARY_MAP_v1.json"]
    hier = data["K2_COURSE_HIERARCHY_v2.json"]
    ai = data["K2_ASSESSMENT_INVENTORY_v1.json"]
    mods = data["K2_PROVISIONAL_MODELS_v1.json"]
    q = data["PRODUCTION_QUEUE_v5.json"]

    # 4. cross-artifact consistency
    want(ev["binary_identity"]["sha256_observed"] == BRIEF_SHA,
         "evidence sha256 != brief")
    want(cust["record"]["verified"]["sha256"]["observed"] == BRIEF_SHA,
         "custody observed sha256 != brief")
    want(cust["record"]["status"] == "BINARY_LOCAL_HASH_VERIFIED",
         "custody status not moved")

    ev_spans = {r["pl"]: (r["pdf_start_page"], r["pdf_end_page"]) for r in
                ev["pl_packages"]}
    hier_spans = {r["pl"]: (r["pdf_start_page"], r["pdf_end_page"]) for r in hier["rows"]}
    pm_spans = {r["region"]: (r["pdf_start_page"], r["pdf_end_page"])
                for r in pm["regions"] if r["region"].startswith("PL")}
    want(ev_spans == hier_spans, "evidence vs hierarchy PL spans disagree")
    want(ev_spans == pm_spans, "evidence vs page-map PL spans disagree")

    want(pm["accounting"]["clean_partition"] is True, "page map not a clean partition")
    want(ai["kt_paper_count"] == 9, f"KT paper count {ai['kt_paper_count']} != 9")
    want(mods["count"] == 2, f"model count {mods['count']} != 2")
    want(hier["decomposition_completed"] is True, "decomposition not complete")
    want(hier["confirmed_units"] == 0, "a unit was confirmed prematurely")

    # queue: K2 ids match hierarchy, invariants all hold, rolls match counts
    k2_ids = sorted(q["k2"]["ids"])
    hier_ids = sorted(f"K2-{r['module_code']}-{r['pl']}" for r in hier["rows"])
    want(k2_ids == hier_ids, "queue K2 ids != hierarchy ids")
    want(all(i["holds"] for i in q["invariants"]), "a queue invariant does not hold")
    for k, roll in q["member_rolls"].items():
        want(len(roll) == q["counts"][k], f"roll {k} != count")
    want(q["counts"]["immediately_executable_units"] == 13,
         "headline metric moved")
    want(q["k2"]["model_ready_units"] == 2, "K2 model-ready != 2")
    want(sorted(q["k2"]["kt06_exception_pls"]) == ["PL06", "PL08"],
         "KT06 exception PLs wrong")

    # 5. CSV projection — structurally validated against the JSON queue.
    csv_path = os.path.join(SRC_DIR, CSV_ARTIFACT)
    want(os.path.exists(csv_path), f"{CSV_ARTIFACT} missing")
    if os.path.exists(csv_path):
        with open(csv_path, encoding="utf-8", newline="") as f:
            csv_rows = list(csv.reader(f))
        want(csv_rows and csv_rows[0] == q["columns"],
             f"{CSV_ARTIFACT} header does not equal the queue columns")
        body = [r for r in csv_rows[1:] if r]
        want(len(body) == q["counts"]["total_rows"],
             f"{CSV_ARTIFACT} has {len(body)} rows, queue total_rows is "
             f"{q['counts']['total_rows']}")
        if csv_rows and csv_rows[0] == q["columns"]:
            idx = q["columns"].index("unit_or_candidate_id")
            want(sorted(r[idx] for r in body)
                 == sorted(r["unit_or_candidate_id"] for r in q["rows"]),
                 f"{CSV_ARTIFACT} id set does not match the JSON queue rows")

    # 6. Narrative run manifest — content-checked (hand-authored, banner-exempt).
    man_path = os.path.join(SRC_DIR, NARRATIVE_MD)
    want(os.path.exists(man_path), f"{NARRATIVE_MD} missing")
    if os.path.exists(man_path):
        mtxt = open(man_path, encoding="utf-8").read()
        norm = " ".join(mtxt.split())   # collapse wrapping so exact-phrase checks are robust
        want(len(mtxt) > 500, f"{NARRATIVE_MD} suspiciously short ({len(mtxt)} chars)")
        want("Stage 4.2F-F" in mtxt, f"{NARRATIVE_MD} missing stage id")
        want(".source-intake/K2" in mtxt, f"{NARRATIVE_MD} missing binary path")
        want(" ".join(AMEND_SENTENCE.split()) in norm,
             f"{NARRATIVE_MD} missing the exact required amend-history wording")

    return fails


if __name__ == "__main__":
    fails = check()
    n_json = len(JSON_SCHEMA)     # 10
    n_md = len(MD_ARTIFACTS)      # 10
    covered = n_json + n_md + 1 + 1   # + CSV + narrative manifest
    if fails:
        print(f"READBACK FAILED — {len(fails)} problem(s):")
        for f in fails:
            print("  -", f)
        sys.exit(1)
    print(f"READBACK OK — {covered}/22 physical files covered: {n_json} JSON "
          f"schema-checked, {n_md} MD banner-checked, 1 CSV structurally validated, "
          f"1 narrative MD content-checked; cross-consistency and Stage-E preservation "
          f"verified.")
