# -*- coding: utf-8 -*-
"""Stage 4.2F-F — publish PRODUCTION_QUEUE_v5: advance only K2, prove the result.

    docs/source/.venv-k2/bin/python docs/source/tools/src_k2f_queue_v1.py

v5 keeps every non-K2 row exactly as v4 had it and replaces the nine Stage-E K2 rows with
rows built by reading the emitted 4.2F-F artifacts (hierarchy v2, provisional models,
assessment inventory). Counts use run2's own definitions, copied verbatim and validated to
reproduce v4 on v4's own rows before anything is published.

Beyond the counts, v5 carries two things v4 did not:

  * member_rolls — the named id list behind every headline count, so no count is a bare
    number a reader has to trust;
  * invariants  — machine-checked proofs of PARTITION, UNIQUENESS, STATE_MONOTONICITY and
    AUTHORITY. If any invariant fails, the run aborts and publishes nothing.

record_type and processing state are kept strictly separate: all nine K2 rows remain
CANDIDATE_STRUCTURE (no storyboard granularity has been independently confirmed), while
each row's processing state advances only as far as its own artifacts support.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.dirname(HERE)
DOCS = os.path.dirname(SRC_DIR)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(DOCS, "pl06", "tools"))
import src_run2_v1 as R2   # noqa: E402  — the queue engine that produced v4
import src_k2f_v1 as F     # noqa: E402  — the Stage 4.2F-F K2 model

V4, V5 = "PRODUCTION_QUEUE_v4", "PRODUCTION_QUEUE_v5"
EXTS = (".json", ".md", ".csv")
BANNER = ("<!-- GENERATED by docs/source/tools/src_k2f_queue_v1.py — "
          f"Stage {F.STAGE}. Edit the model, not this file. -->")

# run2's exact metric definitions, copied verbatim so v5 speaks v4's language.
_SOURCE_ACCESS_NONE = ("NONE", "none — this is a source-access blocker, not an authority "
                       "one")
# The KT06 exception is recorded in the existing exact_blocker field, tagged with this
# stable code token so invariants and the k2 summary can identify the affected rows without
# a new schema field.
OBS03 = "K2-SOURCE-OBS-03"


def _is_kt06_held(r):
    return OBS03 in (r.get("exact_blocker") or "")


def _counts(rows):
    def n(pred):
        return len([r for r in rows if pred(r)])
    return dict(
        confirmed_production_units=n(lambda r: r["record_type"]
                                     == "CONFIRMED_PRODUCTION_UNIT"),
        candidate_structures=n(lambda r: r["record_type"] == "CANDIDATE_STRUCTURE"),
        unresolved_source_records=n(lambda r: r["record_type"] == "UNRESOLVED_SOURCE"),
        immediately_executable_units=n(lambda r: r["immediately_executable"]),
        extracted_units=n(lambda r: r["extraction_status"] == "EXTRACTED"),
        source_content_read_units=n(lambda r: r["extraction_status"]
                                    == "SOURCE_CONTENT_READ"),
        model_ready_units=n(lambda r: r["model_status"] in ("MODEL_READY", "PACKAGED")),
        waiting_authority_units=n(lambda r: r["authority_dependency"]
                                  not in _SOURCE_ACCESS_NONE),
        ready_to_emit_units=n(lambda r: r["ready_to_emit_pptx"]),
        total_rows=len(rows))


# count key -> predicate, for member rolls
_ROLL_PREDS = dict(
    confirmed_production_units=lambda r: r["record_type"] == "CONFIRMED_PRODUCTION_UNIT",
    candidate_structures=lambda r: r["record_type"] == "CANDIDATE_STRUCTURE",
    unresolved_source_records=lambda r: r["record_type"] == "UNRESOLVED_SOURCE",
    immediately_executable_units=lambda r: r["immediately_executable"],
    extracted_units=lambda r: r["extraction_status"] == "EXTRACTED",
    source_content_read_units=lambda r: r["extraction_status"] == "SOURCE_CONTENT_READ",
    model_ready_units=lambda r: r["model_status"] in ("MODEL_READY", "PACKAGED"),
    waiting_authority_units=lambda r: r["authority_dependency"] not in _SOURCE_ACCESS_NONE,
    ready_to_emit_units=lambda r: r["ready_to_emit_pptx"],
)


def _member_rolls(rows):
    return {k: sorted(r["unit_or_candidate_id"] for r in rows if pred(r))
            for k, pred in _ROLL_PREDS.items()}


def _invariants(rows, counts, rolls):
    checks = []

    def add(name, ok, detail):
        checks.append(dict(invariant=name, holds=bool(ok), detail=detail))

    # PARTITION — the three record types tile the queue with no gaps or overlaps.
    part = (counts["confirmed_production_units"] + counts["candidate_structures"]
            + counts["unresolved_source_records"])
    types = {r["record_type"] for r in rows}
    add("PARTITION_SUMS_TO_TOTAL", part == counts["total_rows"],
        f"{part} == {counts['total_rows']}")
    add("PARTITION_TYPES_ARE_THE_THREE_KNOWN",
        types <= {"CONFIRMED_PRODUCTION_UNIT", "CANDIDATE_STRUCTURE", "UNRESOLVED_SOURCE"},
        f"types present: {sorted(types)}")

    # UNIQUENESS — no id appears twice.
    ids = [r["unit_or_candidate_id"] for r in rows]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    add("IDS_ARE_UNIQUE", not dupes, f"duplicates: {dupes or 'none'}")

    # MEMBER ROLLS match their counts exactly.
    roll_ok = all(len(rolls[k]) == counts[k] for k in rolls)
    add("EVERY_ROLL_MATCHES_ITS_COUNT", roll_ok,
        {k: (len(rolls[k]), counts[k]) for k in rolls if len(rolls[k]) != counts[k]}
        or "all match")

    # STATE MONOTONICITY (whole queue) — a high state implies its prerequisites.
    extr_ok = all(r["content_read"] and r["boundary_confirmed"] and r["binary_readable"]
                  for r in rows if r["extraction_status"] == "EXTRACTED")
    add("EXTRACTED_IMPLIES_READ_AND_BOUNDARY_AND_READABLE", extr_ok,
        "every EXTRACTED row is content_read + boundary_confirmed + binary_readable")
    mr_ok = all(r["boundary_confirmed"] for r in rows
                if r["model_status"] in ("MODEL_READY", "PACKAGED"))
    add("MODEL_READY_IMPLIES_BOUNDARY_CONFIRMED", mr_ok,
        "every MODEL_READY/PACKAGED row is boundary_confirmed")
    exec_ok = all(r["binary_readable"] and r["boundary_confirmed"]
                  for r in rows if r["immediately_executable"])
    add("EXECUTABLE_IMPLIES_READABLE_AND_BOUNDARY", exec_ok,
        "every immediately_executable row is binary_readable + boundary_confirmed")

    # STATE MONOTONICITY (K2 clean ladder) — all nine sit on a strict ladder.
    k2 = [r for r in rows if r["course"] == "K2"]
    ladder_ok = all(r["source_located"] and r["binary_local"] and r["binary_readable"]
                    and r["content_read"] and r["boundary_confirmed"] for r in k2)
    add("K2_ROWS_ARE_FULLY_ON_THE_LADDER_TO_BOUNDARY_CONFIRMED", ladder_ok,
        "all nine: located+local+readable+read+boundary")
    k2_mr_extr = all(r["extraction_status"] == "EXTRACTED" for r in k2
                     if r["model_status"] == "MODEL_READY")
    add("K2_MODEL_READY_IMPLIES_EXTRACTED", k2_mr_extr,
        "K2 MODEL_READY rows are EXTRACTED")

    # AUTHORITY invariants.
    add("READY_TO_EMIT_IMPLIES_EXECUTABLE",
        all(r["immediately_executable"] for r in rows if r["ready_to_emit_pptx"]),
        "no row is ready-to-emit without being executable")
    add("NON_EXECUTABLE_ROWS_NAME_A_BLOCKER_OWNER",
        all(r["blocker_owner"] not in (None, "") for r in rows
            if not r["immediately_executable"]),
        "every blocked row names an owner")
    add("NO_K2_ROW_IS_EXECUTABLE",
        not any(r["immediately_executable"] for r in k2), "all nine K2 rows blocked")
    add("NO_K2_ROW_IS_READY_TO_EMIT",
        not any(r["ready_to_emit_pptx"] for r in k2), "all nine K2 ready_to_emit=false")
    add("NO_K2_ROW_IS_A_CONFIRMED_UNIT",
        all(r["record_type"] == "CANDIDATE_STRUCTURE" for r in k2),
        "all nine remain CANDIDATE_STRUCTURE")
    add("ONLY_TWO_K2_ROWS_ARE_MODEL_READY",
        len([r for r in k2 if r["model_status"] == "MODEL_READY"]) == 2,
        "exactly PL07 and PL09")
    held = sorted(r["pl"] for r in k2 if _is_kt06_held(r))
    add("KT06_EXCEPTION_PLS_ARE_HELD_AND_NOT_MODEL_READY",
        held == ["PL06", "PL08"]
        and all(r["model_status"] != "MODEL_READY" for r in k2 if _is_kt06_held(r)),
        f"held via exact_blocker: {held}; none model-ready")
    return checks


def build():
    """Derive v5 from the regenerated artifacts, not from the retired v4 file.

    Non-K2 rows come from the run2 engine (which reads the K3/K5/PL06 source artifacts), so
    v5 reproduces from a clean checkout even after v4 is retired. K2 rows come from the
    emitted 4.2F-F artifacts (F.queue_rows reads them back). The retired v4 file, if still
    present, is used only as an extra transition check.
    """
    orig_k2_model = R2.K2
    try:
        # baseline == v4's content, regenerated from source by the same engine.
        baseline = R2.queue_summary()

        # optional transition check against the retired file, if it is still on disk.
        v4_path = os.path.join(SRC_DIR, V4 + ".json")
        v4 = None
        if os.path.exists(v4_path):
            with open(v4_path, encoding="utf-8") as f:
                v4 = json.load(f)
            drift = {k: (baseline["counts"][k], v4["counts"][k]) for k in v4["counts"]
                     if baseline["counts"][k] != v4["counts"][k]}
            if drift:
                raise SystemExit(f"regenerated baseline does not match retired v4: {drift}")

        # advance only K2: point the engine's K2 model at the binary-measured 4.2F-F model.
        R2.K2 = F
        q = R2.queue_summary()
    finally:
        R2.K2 = orig_k2_model

    # guard: every non-K2 row is identical before and after the swap.
    base_non_k2 = [r for r in baseline["rows"] if r.get("course") != "K2"]
    adv_non_k2 = [r for r in q["rows"] if r.get("course") != "K2"]
    if base_non_k2 != adv_non_k2:
        raise SystemExit("non-K2 rows changed after the K2 swap; refusing to publish v5")

    rows = q["rows"]
    counts = q["counts"]                       # the engine's own definitions
    if _counts(rows) != counts:                # our copied predicates must agree with it
        raise SystemExit("copied count predicates disagree with the engine")
    rolls = _member_rolls(rows)
    inv = _invariants(rows, counts, rolls)
    failed = [c for c in inv if not c["holds"]]
    if failed:
        raise SystemExit(f"invariants failed, refusing to publish v5: {failed}")

    k2 = [r for r in rows if r.get("course") == "K2"]
    h = F.hierarchy()
    k2_block = dict(
        confirmed_production_units=0,
        candidate_structures=len(k2),
        source_ready_clean=h["source_ready_clean"],
        boundary_confirmed=len(k2),
        content_read=len(k2),
        extracted_units=len([r for r in k2 if r["extraction_status"] == "EXTRACTED"]),
        model_ready_units=len([r for r in k2 if r["model_status"] == "MODEL_READY"]),
        kt06_exception_pls=sorted(r["pl"] for r in k2 if _is_kt06_held(r)),
        immediately_executable_units=0,
        ready_to_emit_units=0,
        unmapped_source_regions=h["unmapped_source_regions"],
        authority_dependencies=sorted({r["authority_dependency"] for r in k2}),
        ids=sorted(r["unit_or_candidate_id"] for r in k2))

    blockers = {o: dict(count=len([r for r in rows if r["blocker_owner"] == o]),
                        ids=sorted(r["unit_or_candidate_id"] for r in rows
                                   if r["blocker_owner"] == o))
                for o in sorted({r["blocker_owner"] for r in rows})}

    out = dict(q)
    out["stage"] = F.STAGE
    out["supersedes"] = V4
    out["member_rolls"] = rolls
    out["invariants"] = inv
    out["k2"] = k2_block
    out["immediately_executable_ids"] = rolls["immediately_executable_units"]
    out["ready_to_emit_pptx_unit_ids"] = rolls["ready_to_emit_units"]
    out["blockers_by_owner"] = blockers
    out["derivation"] = ("v5 = the run2 engine with its K2 model advanced to the "
                         "binary-measured 4.2F-F model; K2 rows read back from the emitted "
                         "artifacts, non-K2 rows regenerated from source and proven "
                         "identical to the pre-advance baseline. Counts are the engine's "
                         "own. Member rolls and four invariant families (partition, "
                         "uniqueness, state-monotonicity, authority) are machine-checked "
                         "before publishing. Reproducibility scope: this queue reproduces "
                         "from the committed Stage-F artifacts alone, without the retired "
                         "PRODUCTION_QUEUE_v4 and without re-reading the binary; only "
                         "regenerating the raw extraction evidence from scratch requires the "
                         "verified K2 binary supplied locally at "
                         "'.source-intake/K2/2. PENGURUSAN PEMBINAAN LANDASAN.pdf'.")
    return out, (v4 or baseline)


def _tbl(h, rows):
    o = ["| " + " | ".join(h) + " |", "|" + "|".join("---" for _ in h) + "|"]
    for r in rows:
        o.append("| " + " | ".join(str(c).replace("|", "\\|") for c in r) + " |")
    return "\n".join(o)


def emit():
    q, v4 = build()
    with open(os.path.join(SRC_DIR, V5 + ".json"), "w", encoding="utf-8") as f:
        json.dump(q, f, ensure_ascii=False, indent=1)
        f.write("\n")

    cols = q["columns"]
    lines = [",".join(cols)]
    for r in q["rows"]:
        lines.append(",".join('"{}"'.format(str(r.get(c, "")).replace('"', '""'))
                              for c in cols))
    with open(os.path.join(SRC_DIR, V5 + ".csv"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    c, v4c, k2 = q["counts"], v4["counts"], q["k2"]
    md = [BANNER, "", "# Production queue v5 — K2 binary-dependent advance", "", "```",
          f"STAGE      = {q['stage']}",
          f"LIVE_QUEUE = {V5}  (supersedes {V4})",
          f"TOTAL_ROWS = {c['total_rows']}",
          f"INVARIANTS = {len([i for i in q['invariants'] if i['holds']])}/"
          f"{len(q['invariants'])} hold", "```", "",
          "Only K2 moved; every non-K2 row is identical to v4. record_type stays "
          "CANDIDATE_STRUCTURE for all nine — processing state advances separately.", "",
          "## Counts, v4 → v5", "",
          _tbl(["count", "v4", "v5"], [[k, v4c.get(k, "-"), c.get(k, "-")] for k in c]), "",
          "## Member rolls (named ids behind every count)", "",
          _tbl(["count", "n", "ids"],
               [[k, len(v), (", ".join(v) if v else "—")]
                for k, v in q["member_rolls"].items()]), "",
          "## Invariants proven", "",
          _tbl(["invariant", "holds"],
               [[i["invariant"], i["holds"]] for i in q["invariants"]]), "",
          "## K2 block", "", "```"]
    for k, v in k2.items():
        if k not in ("ids", "authority_dependencies"):
            md.append(f"{k:28}= {v}")
    md += ["```", "", "K2 ids: " + ", ".join(k2["ids"]), "", "## K2 rows", "",
           _tbl(["id", "record type", "extraction", "model", "exec?", "ready?",
                 "blocker owner"],
                [[r["unit_or_candidate_id"], r["record_type"],
                  r["extraction_status"], r["model_status"],
                  r["immediately_executable"], r["ready_to_emit_pptx"],
                  r["blocker_owner"]]
                 for r in q["rows"] if r.get("course") == "K2"]), ""]
    with open(os.path.join(SRC_DIR, V5 + ".md"), "w", encoding="utf-8") as f:
        f.write("\n".join(md))

    retired = []
    for ext in EXTS:
        p = os.path.join(SRC_DIR, V4 + ext)
        if os.path.exists(p):
            os.remove(p)
            retired.append(V4 + ext)
    live = sorted({f.rsplit(".", 1)[0] for f in os.listdir(SRC_DIR)
                   if f.startswith("PRODUCTION_QUEUE_")})
    return q, retired, live


if __name__ == "__main__":
    q, retired, live = emit()
    print("wrote", V5 + ".{json,md,csv}")
    print("counts:", json.dumps(q["counts"]))
    print("k2:", json.dumps({k: v for k, v in q["k2"].items() if k != "ids"}))
    print("invariants:", len([i for i in q["invariants"] if i["holds"]]), "/",
          len(q["invariants"]), "hold")
    print("retired:", retired, "| live:", live)
