# -*- coding: utf-8 -*-
"""Stage 4.2F-E — emit the K2 targeted QA report.

    python3 docs/source/tools/src_k2_qa_emit_v1.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import src_k2_qa_v1 as QA   # noqa: E402

BANNER = ("<!-- GENERATED by docs/source/tools/src_k2_qa_emit_v1.py — "
          "Stage 4.2F-E. Edit the suite, not this file. -->")


def emit():
    s = QA.summary()
    md = [BANNER, "", "# Targeted QA report — Stage 4.2F-E K2", "", "```",
          f"SUITE_ID                      = {s['suite_id']}",
          f"GATES                         = {s['total']}",
          f"PASSED                        = {s['passed']}",
          f"FAILED                        = {len(s['failed'])}",
          f"ORACLE_SEPARATION_STRUCTURAL  = {s['oracle_separation_structural']}",
          "```", "",
          "This suite has its own identity and its own total. No gate count from any "
          "sibling suite is merged into it.", "",
          "One sibling gate WAS changed, and it is named here rather than left implicit. "
          "`STAGE_4_2F_D_RELEASE_FACTS_QA_v1` carried "
          "`K2_REMAINS_AN_UNRESOLVED_SOURCE_RECORD_NOT_A_UNIT`, which asserted that every "
          "K2 queue row was `UNRESOLVED_SOURCE`. This run was explicitly required to end "
          "that condition. The gate's intent — K2 must not be promoted to a production "
          "unit on the strength of a missing binary — is unchanged, and it now reads "
          "`NO_K2_ROW_IS_A_CONFIRMED_PRODUCTION_UNIT`. The fact moved; the protection did "
          "not. Its fixture was repointed with it and the Stage 4.2F-D suite is still "
          "60/60 with 44/44 fixtures detected.",
          "", "## Oracle separation", "", "", 
          "| basis | gates | what it means |", "|---|---|---|"]
    md += [f"| `{b}` | {n} | see the suite docstring |"
           for b, n in s["by_oracle_basis"].items()]
    md += ["",
          "## Gates by area", "", "| area | gates |", "|---|---|"]
    md += [f"| {t} | {n} |" for t, n in s["by_type"].items() if n]
    md += ["", "## Every gate", "",
           "| gate | area | oracle basis | population | source artifact | ok |",
           "|---|---|---|---|---|---|"]
    md += [f"| `{g['gate_id']}` | {g['gate_type']} | `{g['oracle_basis']}` | "
           f"{g['population']} | `{g['source_artifact']}` | "
           f"{'yes' if g['ok'] else '**NO**'} |" for g in s["gates"]]
    md += ["", "## Not checked", "",
           "Stated so that a reader does not mistake this suite's scope for the whole "
           "problem.", ""]
    md += [f"- {n}" for n in s["not_checked"]]
    md += [""]
    path = os.path.join(SRC_DIR, "STAGE_4_2F_E_QA_REPORT_v1.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    jpath = os.path.join(SRC_DIR, "STAGE_4_2F_E_QA_REPORT_v1.json")
    with open(jpath, "w", encoding="utf-8") as f:
        json.dump(s, f, ensure_ascii=False, indent=1)
    return path, jpath, s


if __name__ == "__main__":
    p, j, s = emit()
    print(f"{s['passed']}/{s['total']} passed")
    print("wrote", os.path.basename(p))
    print("wrote", os.path.basename(j))
