# -*- coding: utf-8 -*-
"""Stage 4.2F-F — emit the binary-dependent K2 artifacts.

    docs/source/.venv-k2/bin/python docs/source/tools/src_k2f_emit_v1.py

Generates, from the Stage 4.2F-F model (src_k2f_v1), the seven artifacts 4.2F-E listed as
'not produced — needs the binary', plus the upgraded custody and hierarchy records.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import src_k2f_v1 as F   # noqa: E402

BANNER = ("<!-- GENERATED by docs/source/tools/src_k2f_emit_v1.py — "
          f"Stage {F.STAGE}. Edit the model, not this file. -->")


def _w(name, text):
    with open(os.path.join(SRC_DIR, name), "w", encoding="utf-8") as f:
        f.write(text)
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1) + "\n")


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def _custody_md(c):
    r = c["record"]
    v = r["verified"]
    L = [BANNER, "", "# K2 binary custody record — v2 (Stage 4.2F-F)", "", "```",
         f"STATUS           = {r['status']}",
         f"BINARY_LOCAL     = {r['binary_local']}",
         f"BINARY_READABLE  = {r['binary_readable']}",
         f"CONTENT_READ     = {r['content_read']}",
         f"EVIDENCE_CLASS   = {r['evidence_class']}",
         f"LOCAL_PATH       = {r['local_path']}", "```", "",
         "## The status moved because it is finally true", "",
         "Claimed now: " + ", ".join(f"`{s}`" for s in r["states_claimed"]), "",
         r["states_claimed_why"], "",
         "Still not claimed: " + ", ".join(f"`{s}`" for s in
                                           r["states_still_not_claimed"]), "",
         r["states_still_not_claimed_why"], "",
         "## Identity, verified from the bytes before anything was measured", "",
         _tbl(["field", "expected", "observed", "match"],
              [["bytes", v["bytes"]["expected"], v["bytes"]["observed"],
                v["bytes"]["match"]],
               ["sha256", v["sha256"]["expected"][:16] + "…",
                v["sha256"]["observed"][:16] + "…", v["sha256"]["match"]],
               ["pages", v["pages"]["expected"], v["pages"]["observed"],
                v["pages"]["match"]]]), "",
         _tbl(["check", "result"],
              [["PDF validity", v["pdf_validity"]],
               ["encryption", v["encryption_status"]],
               ["needs password", v["needs_password"]],
               ["PDF format", v["pdf_format"]],
               ["author", v["pdf_metadata"].get("author")],
               ["creator", v["pdf_metadata"].get("creator")]]), "",
         "## Binding", "",
         f"`{c['binding']['binding_id']}` supersedes `{c['binding']['supersedes']}`.", "",
         c["binding"]["conclusion"], "",
         "## Relationship to the earlier record", "",
         f"Supersedes: `{r['supersedes']}`", "", r["supersession_note"], ""]
    return "\n".join(L)


def _pagemap_md(m):
    a = m["accounting"]
    L = [BANNER, "", "# K2 page and boundary map — the 346-page decomposition", "", "```",
         f"MAP_ID          = {m['map_id']}",
         f"TOTAL_PAGES     = {m['total_pages']}",
         f"CLEAN_PARTITION = {a['clean_partition']}",
         f"UNASSIGNED      = {a['unassigned_pages'] or 'none'}",
         f"OVERLAPS        = {a['overlapping_pages'] or 'none'}",
         f"ALL_SPANS_MATCH_DECLARED = {m['all_pl_spans_match_declared']}", "```", "",
         m["note"], "", "## Regions", "",
         _tbl(["region", "start", "end", "pages", "contents", "boundary basis"],
              [[r["region"], r["pdf_start_page"], r["pdf_end_page"], r["pages"],
                r["contents"], r["boundary_basis"]] for r in m["regions"]]), ""]
    return "\n".join(L)


def _assess_md(a):
    L = [BANNER, "", "# K2 assessment and answer-scheme inventory", "", "```",
         f"INVENTORY_ID   = {a['inventory_id']}",
         f"KT_PAPER_COUNT = {a['kt_paper_count']}",
         f"ANSWER_SCHEMES = {len(a['answer_schemes_present'])}/9 packages", "```", "",
         "## Two assessment systems"] + ["", *[f"- {s}" for s in a["two_assessment_systems"]]]
    L += ["", "## Per-PL: LATIHAN and SKEMA JAWAPAN", "",
          _tbl(["PL", "module", "LATIHAN pages", "SKEMA JAWAPAN pages", "own scheme?"],
               [[r["pl"], r["module"], r["latihan_pages"], r["skema_jawapan_pages"],
                 r["has_own_answer_scheme"]] for r in a["per_pl"]]), "",
          "## Course-level competency task papers (KT / Kertas Tugasan)", "",
          _tbl(["KT code", "pages", "positional PL", "printed unit competency"],
               [[k["kt_code"], f"{k['pages'][0]}-{k['pages'][1]}", k["positional_pl"],
                 (k["printed_unit_competency"] or "?")[:48]] for k in a["kt_papers"]]), ""]
    for o in a["observations"]:
        L += [f"## {o['defect_id']} — {o['subject']}", "", o["finding"], "",
              f"Classification: **{o['classification']}**, routed to **{o['routed_to']}**.",
              ""]
        if "consequences" in o:
            L += ["Distinct consequence per package:", "",
                  _tbl(["PL", "consequence", "detail"],
                       [[c["pl"], c["consequence"], c["detail"]]
                        for c in o["consequences"]]), ""]
        if "production_impact" in o:
            L += [o["production_impact"], ""]
        if "not_resolved_here" in o:
            L += [o["not_resolved_here"], ""]
    return "\n".join(L)


def _imgtbl_md(it):
    L = [BANNER, "", "# K2 image and table inventory", "", "```",
         f"INVENTORY_ID  = {it['inventory_id']}",
         f"IMAGES_TOTAL  = {it['totals']['images_total']}", "```", "",
         "## Method", "", f"**Images.** {it['method']['images']}", "",
         f"**Tables.** {it['method']['tables']}", "",
         "## Per-PL", "",
         _tbl(["PL", "pages", "images", "tables (detector, upper bound)"],
              [[r["pl"], r["pages"], r["image_count"], r["table_detector_count"]]
               for r in it["per_pl"]]), "",
         "## Region image totals", "",
         _tbl(["region", "images"],
              [["front matter", it["totals"]["front_matter_images"]],
               ["teaching plans", it["totals"]["teaching_plan_images"]],
               ["KT assessment", it["totals"]["kt_region_images"]]]), "",
         it["honesty_note"], ""]
    return "\n".join(L)


def _hierarchy_md(h):
    L = [BANNER, "", "# K2 course hierarchy — v2 (decomposition complete)", "", "```",
         f"MODULES                 = {h['modules']}",
         f"PL_PACKAGES             = {h['pl_packages']}",
         f"SOURCE_READY_CLEAN      = {h['source_ready_clean']}",
         f"CONFIRMED_UNITS         = {h['confirmed_units']}",
         f"UNMAPPED_SOURCE_REGIONS = {h['unmapped_source_regions']}",
         f"DECOMPOSITION_COMPLETED = {h['decomposition_completed']}",
         f"PL_TO_MODULE_CONFIRMED  = "
         f"{h['pl_to_module_map_now_confirmed_from_each_package_header']}", "```", "",
         h["supersedes_4_2F_E_inference"], "", h["confirmed_units_why"], "",
         h["unmapped_note"], "", "## Packages", "",
         _tbl(["PL", "module", "official title", "span", "declared", "boundary OK",
               "LATIHAN", "SKEMA", "img", "tbl~", "record type"],
              [[r["pl"], r["module_code"], r["official_title"],
                f"{r['pdf_start_page']}-{r['pdf_end_page']}", r["declared_pages"],
                r["boundary_confirmed"], len(r["latihan_pages"]),
                r["skema_jawapan_pages"], r["image_count"], r["table_detector_count"],
                r["record_type"]] for r in h["rows"]]), "",
         "## Module map", "",
         _tbl(["module", "packages"],
              [[m, ", ".join(p)] for m, p in h["module_map"].items()]), ""]
    return "\n".join(L)


def _models_md(m):
    L = [BANNER, "", "# K2 first two clean controlled extractions and provisional models",
         "", "```", f"MODELS_ID = {m['models_id']}", f"COUNT     = {m['count']}", "```", "",
         "## Selection criterion", "", m["selection_criterion"], "",
         f"Not modelled this run: {m['not_modelled']}", ""]
    for mod in m["models"]:
        L += [f"## {mod['model_id']} — {mod['official_title']} ({mod['module']})", "",
              "```",
              f"PL      = {mod['pl']}",
              f"SPAN    = {mod['pdf_span'][0]}-{mod['pdf_span'][1]} ({mod['pages']} pages)",
              f"STATE   = {mod['model_state']}",
              f"IMAGES  = {mod['images']}   TABLES~ = {mod['tables_detector']}", "```", "",
              f"**Tajuk** (p{mod['tajuk_page']}): {mod['tajuk']}", "",
              f"**Objektif**: {mod['objektif']}", "",
              "**Penerangan topics**:"] + [f"- {t}" for t in mod["penerangan_topics"]]
        L += ["",
              f"**Latihan** (p{mod['latihan']['page']}): {mod['latihan']['item_count']} "
              f"items — " + "; ".join(mod["latihan"]["items_sample"]), "",
              f"**Skema jawapan** (p{mod['skema_jawapan']['page']}, "
              f"{mod['skema_jawapan']['audience']})", "",
              f"_{mod['confidence']}_", ""]
    return "\n".join(L)


def _decisions_md(d):
    L = [BANNER, "", "# K2 decision register", "", "```",
         f"REGISTER_ID = {d['register_id']}",
         f"ROUTED_TO   = {d['routed_to']}", "```", "", d["preamble"], "",
         "## Decisions", "",
         _tbl(["id", "owner", "question", "why answerable now"],
              [[x["decision_id"], x["owner"], x["question"], x["why_now"]]
               for x in d["decisions"]]), "", d["note"], ""]
    return "\n".join(L)


def emit_all():
    c = F.custody()
    made = [
        _j("K2_BINARY_CUSTODY_v2.json", c),
        _w("K2_BINARY_CUSTODY_v2.md", _custody_md(c)),
        _j("K2_PAGE_BOUNDARY_MAP_v1.json", F.page_boundary_map()),
        _w("K2_PAGE_BOUNDARY_MAP_v1.md", _pagemap_md(F.page_boundary_map())),
        _j("K2_ASSESSMENT_INVENTORY_v1.json", F.assessment_inventory()),
        _w("K2_ASSESSMENT_INVENTORY_v1.md", _assess_md(F.assessment_inventory())),
        _j("K2_IMAGE_TABLE_INVENTORY_v1.json", F.image_table_inventory()),
        _w("K2_IMAGE_TABLE_INVENTORY_v1.md", _imgtbl_md(F.image_table_inventory())),
        _j("K2_COURSE_HIERARCHY_v2.json", F.hierarchy()),
        _w("K2_COURSE_HIERARCHY_v2.md", _hierarchy_md(F.hierarchy())),
        _j("K2_PROVISIONAL_MODELS_v1.json", F.provisional_models()),
        _w("K2_PROVISIONAL_MODELS_v1.md", _models_md(F.provisional_models())),
        _j("K2_DECISION_REGISTER_v1.json", F.decision_register()),
        _w("K2_DECISION_REGISTER_v1.md", _decisions_md(F.decision_register())),
    ]
    return made


if __name__ == "__main__":
    for n in emit_all():
        print("wrote", n)
