# -*- coding: utf-8 -*-
"""Stage 4.2F-C — emit the K3/K2/K5 inventory and the artifact-derived production queue."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import src_inventory_v1 as INV   # noqa: E402
import src_queue_v1 as Q         # noqa: E402

BANNER = ("<!-- GENERATED by docs/source/tools/src_inventory_emit_v1.py — "
          f"Stage {INV.STAGE}. Edit the model, not this file. -->")

ARTIFACTS = ["K3_SOURCE_INVENTORY_v1.json", "K3_SOURCE_INVENTORY_v1.md",
             "K3_PROVISIONAL_MODELS_v1.json",
             "K2_MONOLITH_DECOMPOSITION_v1.json", "K2_MONOLITH_DECOMPOSITION_v1.md",
             "K5_REMAINING_INVENTORY_v1.json", "K5_REMAINING_INVENTORY_v1.md",
             "PRODUCTION_QUEUE_v1.json", "PRODUCTION_QUEUE_v1.md",
             "PRODUCTION_QUEUE_v1.csv"]


def _w(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text)
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1) + "\n")


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def emit_all():
    made = []
    inv = INV.inventory()
    k3, k2, k5 = inv["k3"], inv["k2"], inv["k5"]

    # ---------------- K3 ----------------
    made.append(_j("K3_SOURCE_INVENTORY_v1.json", dict(k3, models=inv["k3_models"])))
    md = [BANNER, "", "# K3 source inventory — Kerja Penstabilan Tanah", "", "```",
          f"FOLDER               = {k3['folder_id']}",
          f"PDFS                 = {k3['pdfs']}",
          f"READ_IN_FULL         = {k3['read_in_full']}",
          f"IDENTIFIED_NOT_READ  = {k3['identified_not_read']}",
          f"CANDIDATE_UNITS      = {k3['candidate_units_evidenced']} (evidenced)",
          f"FIELD / MODULE CODE  = {k3['field_code']} / {k3['module_code']}", "```", "",
          k3["read_in_full"] and k3["template_note"] or "", "",
          _tbl(["PL", "filename", "bytes", "read", "pages", "top sections", "tables",
                "figures", "LATIHAN", "SKEMA", "class"],
               [[r["pl"], r["filename"], f"{r['bytes']:,}",
                 "full" if r["read_status"] == "CONNECTOR_TEXT_READ_IN_FULL" else "**no**",
                 r["pages"],
                 len(r["top_sections"]) if isinstance(r["top_sections"], list)
                 else r["top_sections"],
                 r["tables"], r["figures"],
                 str(r["latihan"]).lower(), str(r["skema_jawapan"]).lower(),
                 r["classification"]] for r in k3["rows"]]), "",
          "## Why seven were not read", "", k3["rows"][1]["note"], "",
          "## One PDF is not assumed to be one unit", "",
          k3["one_pdf_equals_one_unit"]["finding"], "",
          "## Source conflict", "", "```",
          f"id     = {k3['header_conflict']['id']}",
          f"class  = {k3['header_conflict']['classification']}",
          f"owner  = {k3['header_conflict']['owner']}", "```", "",
          k3["header_conflict"]["finding"], "", k3["header_conflict"]["note"], "",
          "## Provisional models — the two SOURCE_READY_CLEAN units", ""]
    for m in inv["k3_models"]:
        a = m["screen_sequence"]["arithmetic"]
        md += [f"### {m['unit_id']} — {m['title']}", "", "```",
               f"pages              = {m['source']['pages']}",
               f"groups             = {len(m['grouping']['groups'])}",
               f"minimum screens    = {a['minimum_total_screens']}",
               f"maximum screens    = {a['maximum_total_screens']}",
               f"dialogue           = {m['dialogue']['verdict']}",
               f"pattern candidates = {m['pattern_family']['primary_candidate']} / "
               f"{m['pattern_family']['secondary_candidate']}",
               f"visual subjects    = {m['visual_obligations']['count']} "
               f"({m['visual_obligations']['source_attested']} source-attested)",
               "```", "",
               "Groups: " + ", ".join(g["covers"] for g in m["grouping"]["groups"]) + ".", "",
               "**Source-authored assessment** — status "
               f"`{m['source_assessment']['key_status']}`.", ""]
        md += [f"{i + 1}. {q}" for i, q in enumerate(m["source_assessment"]["questions"])]
        md += [""]
    md += ["## The assessment format conflict", "", "```",
           f"id    = {INV.K3_ASSESSMENT_FINDING['id']}",
           f"class = {INV.K3_ASSESSMENT_FINDING['classification']}", "```", "",
           INV.K3_ASSESSMENT_FINDING["finding"], "",
           "Options, none of them chosen here:", ""]
    md += [f"- {o}" for o in INV.K3_ASSESSMENT_FINDING["options_not_chosen"]]
    md += ["", INV.K3_ASSESSMENT_FINDING["note"], ""]
    made.append(_w("K3_SOURCE_INVENTORY_v1.md", "\n".join(md)))
    made.append(_j("K3_PROVISIONAL_MODELS_v1.json",
                   dict(stage=INV.STAGE, authority=INV.AUTHORITY,
                        assessment_finding=INV.K3_ASSESSMENT_FINDING,
                        models=inv["k3_models"])))

    # ---------------- K2 ----------------
    made.append(_j("K2_MONOLITH_DECOMPOSITION_v1.json", k2))
    mc = k2["missing_capability"]
    md = [BANNER, "", "# K2 monolith decomposition — Pengurusan Pembinaan Landasan", "",
          "```",
          f"OUTCOME    = {k2['outcome']}",
          f"FILE       = {k2['file']['filename']}",
          f"DRIVE ID   = {k2['file']['drive_id']}",
          f"BYTES      = {k2['file']['bytes']:,} (Drive metadata)",
          f"SHA-256    = {k2['file']['sha256']}", "```", "",
          "Every field this lane was asked to produce — page count, heading tree, module and "
          "PL hierarchy, descendant map, LATIHAN and SKEMA JAWAPAN locations, image and "
          "table inventory, candidate boundaries, shared-page risks, unit count — is "
          f"`{INV.UNKNOWN}`. None of them is estimated.", "",
          "## What is missing, exactly", "", "```",
          f"missing    = {mc['what_is_missing']}",
          f"identifier = {mc['exact_identifier']}",
          f"folder     = {mc['folder']}", "```", "", mc["why"], "",
          "What would unblock it:", ""]
    md += [f"- {x}" for x in mc["what_would_unblock_it"]]
    md += ["", "## Uncertainty register", "",
           _tbl(["item", "status", "note"],
                [[u["item"], u["status"], u["note"]] for u in k2["uncertainty_register"]]),
           "", k2["note"], ""]
    made.append(_w("K2_MONOLITH_DECOMPOSITION_v1.md", "\n".join(md)))

    # ---------------- K5 ----------------
    made.append(_j("K5_REMAINING_INVENTORY_v1.json", k5))
    t = k5["totals"]
    md = [BANNER, "", "# K5 remaining inventory — measured from the verified binary", "",
          "```",
          f"PAKEJ_LATIHAN_IN_MODULE  = {k5['pakej_latihan_in_module']}",
          f"SCOPE_REQUESTED          = {', '.join(k5['scope_requested'])}",
          f"CONFIRMED_UNIT           = {t['confirmed_units']}",
          f"CANDIDATE_UNIT           = {t['candidate_units']}",
          f"UNMAPPED_SOURCE_REGION   = {t['unmapped_source_regions']} "
          f"({t['unmapped_pages']} of {t['total_module_pages']} module pages)", "```", "",
          f"Prior estimate of {k5['prior_estimate']['prior_estimate']}: "
          f"**{k5['prior_estimate']['status']}**. {k5['prior_estimate']['reason']}", "",
          "Every page number below was located by finding the heading in the DOCX body and "
          "reading the module page off the typeset PDF footer. These are measurements.", "",
          _tbl(["PL", "title", "pages", "sub-modul", "confirmed", "candidate", "basis",
                "shared-page risk"],
               [[r["pl"], r["title"], f"{r['module_pages'][0]}–{r['module_pages'][1]} "
                                      f"({r['page_count']})",
                 r["sub_modul_count"], r["confirmed_units"], r["candidate_units"],
                 r["unit_basis"],
                 ", ".join(str(x) for x in r["shared_boundary_risk"]["shared_pages"])
                 or "none"] for r in k5["rows"]]), "",
          "## Findings", ""]
    for f in k5["findings"]:
        md += [f"**{f['id']} — {f['severity']}**", "", f["finding"], ""]
    md += ["## Quiz and answer-scheme availability", "", k5["rows"][0]["quiz_note"], ""]
    made.append(_w("K5_REMAINING_INVENTORY_v1.md", "\n".join(md)))

    # ---------------- queue ----------------
    q = Q.summary()
    made.append(_j("PRODUCTION_QUEUE_v1.json", q))
    hdr = Q.COLUMNS
    csv = [",".join(hdr)]
    for r in q["rows"]:
        csv.append(",".join('"' + str(r[c]).replace('"', '""') + '"' for c in hdr))
    made.append(_w("PRODUCTION_QUEUE_v1.csv", "\n".join(csv) + "\n"))

    md = [BANNER, "", "# Production queue", "", "```",
          f"ROWS                    = {q['total_rows']}",
          f"CONFIRMED_UNITS         = {q['total_confirmed_units']}",
          f"CANDIDATE_UNITS         = {q['total_candidate_units']}",
          f"SOURCE_READY            = {q['source_ready_count']} "
          f"({q['source_ready_percent']}%)",
          f"EXTRACTED               = {q['extracted_count']} ({q['extracted_percent']}%)",
          f"MODEL_READY             = {q['model_ready_count']} "
          f"({q['model_ready_percent']}%)",
          f"BLOCKED                 = {q['blocked_count']}", "```", "",
          q["derivation"], "", "## Blockers by owner", "",
          _tbl(["owner", "count", "units"],
               [[k, v["count"], ", ".join(v["units"][:6])
                 + (f" … +{len(v['units']) - 6}" if len(v["units"]) > 6 else "")]
                for k, v in q["blockers_by_owner"].items()]), "",
          "## Queue", "",
          _tbl(["course", "PL", "unit", "src", "boundary", "extraction", "model",
                "storyboard", "blocker", "next action"],
               [[r["course"], r["pl"], r["unit_id"],
                 "yes" if r["source_binary_verified"] else "no",
                 r["boundary_status"], r["extraction_status"], r["model_status"],
                 r["storyboard_readiness"], r["blocker"], r["next_executable_action"]]
                for r in q["rows"]]), ""]
    made.append(_w("PRODUCTION_QUEUE_v1.md", "\n".join(md)))
    return made


if __name__ == "__main__":
    for m in emit_all():
        print("emitted  :", m)
