# -*- coding: utf-8 -*-
"""Stage 4.2F-D Lane 3 — emit the completed K3 inventory and provisional models.

    python3 docs/source/tools/src_k3_emit_v1.py

v2 supersedes the Stage 4.2F-C v1 artifacts, which were written when two of nine packages
had been read. The v1 files are left on disk unchanged: they are the honest record of what
was known then, and rewriting them would erase the fact that the picture changed.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import src_k3_v1 as K   # noqa: E402

BANNER = ("<!-- GENERATED by docs/source/tools/src_k3_emit_v1.py — "
          f"Stage {K.STAGE}. Edit the model, not this file. -->")

ARTIFACTS = ["K3_SOURCE_INVENTORY_v2.json", "K3_SOURCE_INVENTORY_v2.md",
             "K3_PROVISIONAL_MODELS_v2.json", "K3_PROVISIONAL_MODELS_v2.md",
             "K3_COURSE_DECISION_v1.json", "K3_COURSE_DECISION_v1.md",
             "K3_SOURCE_OBSERVATIONS_v1.json", "K3_SOURCE_OBSERVATIONS_v1.md"]


def _w(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text)
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1) + "\n")


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def _inventory_md(inv):
    L = [BANNER, "", "# K3 source inventory v2", "",
         f"Course: **{inv['course_title']}**  |  field code: `{inv['field_code']}`  |  "
         f"folder: `{inv['folder_id']}`", "",
         f"- Packages: **{inv['pdfs']}**, read in full: **{inv['read_in_full']}**, "
         f"identified but not read: **{inv['identified_not_read']}**",
         f"- Modules evidenced: **{len(inv['modules_evidenced'])}** — "
         f"{', '.join(inv['modules_evidenced'])}",
         f"- Total source pages: **{inv['total_source_pages']}**",
         f"- Total source questions: **{inv['total_source_questions']}**",
         f"- Every read package has its own assessment: "
         f"**{inv['every_read_package_has_own_assessment']}**",
         f"- Question counts agree between the shape record and the package record: "
         f"**{inv['question_counts_all_agree']}**", "",
         "## Read status", "", inv["read_budget_note"], "",
         "## Module map", "",
         _tbl(["Module", "Packages"],
              [[m, ", ".join(pls)] for m, pls in inv["module_map"].items()]), "",
         inv["module_finding"], "",
         "## Packages", "",
         _tbl(["PL", "Module", "Pages", "Top", "Sub", "Tables", "Figures", "Q",
               "SKEMA shape", "Class"],
              [[r["pl"], r["module_code"], r["pages"], len(r["top_sections"]),
                r.get("sub_section_count", "-"), r["tables"], r["figures"],
                r["latihan_questions"], r["skema_shape"]["family"], r["classification"]]
               for r in inv["rows"]]), "",
         "## The K5 rule is not applied here", "",
         f"- Rule: {inv['k5_rule_not_applied']['rule']}",
         f"- Applies to: {inv['k5_rule_not_applied']['applies_to']}",
         f"- Applied to K3: **{inv['k5_rule_not_applied']['applied_to_k3']}**", "",
         inv["k5_rule_not_applied"]["why"], ""]
    return "\n".join(L)


def _models_md(models):
    L = [BANNER, "", "# K3 provisional unit models v2", "",
         f"{len(models)} models, one per package read in full. Every one classifies its "
         f"assessment as `{K.K3_ASSESSMENT_CLASS}`.", "",
         _tbl(["Unit", "PL", "Module", "Pages", "Groups", "Min screens", "Assessment",
               "Pattern family"],
              [[m["unit_id"], m["pl"], m["source"]["module_code"], m["source"]["pages"],
                m["screen_sequence"]["arithmetic"]["content_groups"],
                m["screen_sequence"]["arithmetic"]["minimum_total_screens"],
                m["source_assessment"]["cls"], m["pattern_family"]["cls"]]
               for m in models]), "",
         "## What is deliberately not frozen", "",
         "\n".join(f"- {n}" for n in models[0]["frozen_nothing"]), ""]
    return "\n".join(L)


def _decision_md(d):
    L = [BANNER, "", f"# {d['decision_id']} — {d['subject_en']}", "",
         f"**{d['subject_ms']}**", "", "## Konteks", "", d["context_ms"], "",
         d["evidence_note_ms"], "", "## Pilihan", "",
         _tbl(["Key", "Pilihan", "Kesan kepada pengeluaran", "Kos"],
              [[o["key"], o["label_ms"], o["consequence_ms"], o["production_cost_ms"]]
               for o in d["options"]]), "",
         "## Nota", "",
         f"- CAIR recommendation: **{d['cair_recommendation']}**",
         f"- {d['cair_note_ms']}",
         f"- Blocks: {', '.join(d['blocks'])}",
         f"- Does not block: {', '.join(d['does_not_block'])}", ""]
    return "\n".join(L)


def _observations_md(obs):
    L = [BANNER, "", "# K3 source observations v1", "",
         f"{len(obs)} observations raised by reading all nine packages. None of them is an "
         f"instructional decision; each is routed accordingly.", ""]
    for o in obs:
        # The title conflict is keyed `conflict_id`; the three observations are keyed
        # `observation_id`. Both are printed under their own identifier rather than
        # renaming either, so neither register loses its own name.
        oid = o.get("observation_id") or o["conflict_id"]
        L += [f"## {oid} — {o['subject']}", ""]
        for k, v in o.items():
            if k in ("observation_id", "conflict_id", "subject"):
                continue
            L.append(f"- **{k}**: {json.dumps(v, ensure_ascii=False) if isinstance(v, (list, dict)) else v}")
        L.append("")
    return "\n".join(L)


def emit_all():
    inv = K.k3_inventory()
    models = K.k3_models()
    d = K.K3_COURSE_DECISION
    obs = inv["observations"] + [inv["title_conflict"]]
    made = [
        _j("K3_SOURCE_INVENTORY_v2.json", inv),
        _w("K3_SOURCE_INVENTORY_v2.md", _inventory_md(inv)),
        _j("K3_PROVISIONAL_MODELS_v2.json", models),
        _w("K3_PROVISIONAL_MODELS_v2.md", _models_md(models)),
        _j("K3_COURSE_DECISION_v1.json", d),
        _w("K3_COURSE_DECISION_v1.md", _decision_md(d)),
        _j("K3_SOURCE_OBSERVATIONS_v1.json", obs),
        _w("K3_SOURCE_OBSERVATIONS_v1.md", _observations_md(obs)),
    ]
    return made


if __name__ == "__main__":
    for n in emit_all():
        print("wrote", n)
