# -*- coding: utf-8 -*-
"""Stage 4.2F-E — emit the K2 custody, conflict and hierarchy artifacts, and retire the
stale queue files.

    python3 docs/source/tools/src_k2_emit_v1.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import src_k2_v1 as K2   # noqa: E402

BANNER = ("<!-- GENERATED by docs/source/tools/src_k2_emit_v1.py — "
          f"Stage {K2.STAGE}. Edit the model, not this file. -->")

LIVE_QUEUE = "PRODUCTION_QUEUE_v4"
RETIRED_QUEUES = ["PRODUCTION_QUEUE_v1", "PRODUCTION_QUEUE_v2", "PRODUCTION_QUEUE_v3"]
QUEUE_EXTS = (".json", ".md", ".csv")


def _w(name, text):
    with open(os.path.join(SRC_DIR, name), "w", encoding="utf-8") as f:
        f.write(text)
    return name


def _j(name, obj):
    return _w(name, json.dumps(obj, ensure_ascii=False, indent=1) + "\n")


def _tbl(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                     for c in r) + " |")
    return "\n".join(out)


def _custody_md(c):
    r, b, cr = c["record"], c["binding"], c["connector_read"]
    L = [BANNER, "", "# K2 binary custody record", "", "```",
         f"STATUS           = {r['status']}",
         f"BINARY_LOCAL     = {r['binary_local']}",
         f"BINARY_READABLE  = {r['binary_readable']}",
         f"CONTENT_READ     = {r['content_read']}",
         f"EVIDENCE_CLASS   = {r['evidence_class']}", "```", "",
         "## What the brief expected", "",
         _tbl(["field", "expected value"],
              [[k, v] for k, v in c["expected"].items()]), "",
         "Every value above is **expected**, taken from the brief. None is observed: "
         "observing them requires the bytes.", "",
         "## What the Drive connector returned", "",
         _tbl(["field", "value"], [[k, v] for k, v in c["drive"].items()]), "",
         "## Binding between the identifier and the expected file", "",
         _tbl(["check", "result"],
              [["filename matches", b["filename_matches"]],
               ["bytes match", b["bytes_match"]],
               ["SHA-256 verified", b["sha256_verified"]],
               ["SHA-256 verifiable here", b["sha256_verifiable"]]]), "",
         b["why_not"], "", b["conclusion"], "",
         "## States claimed, and states deliberately not claimed", "",
         "Claimed: " + ", ".join(f"`{s}`" for s in r["states_claimed"]), "",
         "Not claimed: " + ", ".join(f"`{s}`" for s in r["states_not_claimed"]), "",
         r["states_not_claimed_why"], "",
         "## Locations searched", "",
         _tbl(["location", "method", "found", "note"],
              [[x["location"], x["method"], x["found"], x["note"]]
               for x in c["locations_searched"]]), "",
         "## Locations NOT searched", "",
         "Named so that the absence statement is scoped rather than absolute.", ""]
    L += [f"- {x}" for x in c["locations_not_searched"]]
    L += ["", "## Connector text coverage", "", "```",
          f"CHARS      = {cr['chars']:,}",
          f"PAGES      = {cr['document_pages_declared_by_brief']} (per the brief)",
          f"CHARS/PAGE = {cr['chars_per_page_if_complete']}",
          f"COMPLETE   = {cr['complete']}", "```", "",
          "### Evidence that the text is truncated", ""]
    L += [f"- {x}" for x in cr["truncation_evidence"]]
    L += ["", "### Covers", ""] + [f"- {x}" for x in cr["covers"]]
    L += ["", "### Does not cover", ""] + [f"- {x}" for x in cr["does_not_cover"]]
    L += ["", cr["consequence"], "",
          "## What could not be verified", "",
          _tbl(["check", "status"],
               [[k, v] for k, v in r["unverifiable"].items() if k != "note"]), "",
          r["unverifiable"]["note"], "",
          "## Relationship to the earlier record", "",
          f"Supersedes: `{r['supersedes']}`", "", r["supersession_note"], ""]
    return "\n".join(L)


def _conflict_md(cf):
    L = [BANNER, "", f"# {cf['conflict_id']} — {cf['subject']}", "", "```",
         f"CLASSIFICATION                 = {cf['classification']}",
         f"NARRATIVE_MODULE_COUNT         = {cf['narrative_module_count']}",
         f"SYLLABUS_TABLE_MODULE_COUNT    = {cf['syllabus_table_module_count']}",
         f"REQUIRES_INSTRUCTIONAL_DECISION= {cf['requires_instructional_decision']}",
         f"ROUTED_TO                      = {cf['routed_to']}",
         f"IN_BARIAH_REGISTER             = {cf['in_bariah_register']}",
         f"SILENTLY_CORRECTED             = {cf['silently_corrected']}", "```", "",
         "## Independent evidence", "",
         _tbl(["source", "kind", "modules", "packages", "exact value"],
              [[e["source"], e["kind"], e.get("asserts_module_count", "-"),
                e.get("asserts_package_count", "-"), e["exact_value"]]
               for e in cf["evidence"]]), "",
         "## Finding", "", cf["finding"], "",
         "## Codes present in the source", "",
         _tbl(["family", "codes"],
              [["module codes", ", ".join(cf["module_codes_present"])],
               ["PL codes", ", ".join(cf["pl_codes_present"])],
               ["teaching-plan codes", ", ".join(cf["pt_codes_present"])],
               ["LP codes in the silibus table",
                ", ".join(cf["lp_codes_present"])]]), "",
         "## Classification reasoning", "", cf["classification_reasoning"], "",
         "## Handling", "", cf["correction_note"], ""]
    sd = cf["secondary_defect"]
    L += ["", f"## {sd['defect_id']} — {sd['subject']}", "",
          f"Exact value: `{sd['exact_value']}`", "", sd["finding"], "",
          f"Classification: **{sd['classification']}**, routed to "
          f"**{sd['routed_to']}**.", "", sd["production_impact"], ""]
    return "\n".join(L)


def _hierarchy_md(h):
    L = [BANNER, "", "# K2 course hierarchy — as far as the evidence reaches", "",
         f"Course: **{h['course']['title']}**  |  programme: "
         f"{h['course']['programme']}  |  field code: `{h['course']['field_code']}`", "",
         "```",
         f"MODULES                 = {h['modules']}",
         f"PL_PACKAGES             = {h['pl_packages']}",
         f"TEACHING_PLANS          = {h['teaching_plans']}",
         f"TEACHING_PLAN_PAGES     = {h['teaching_plan_pages_total']}",
         f"CONFIRMED_UNITS         = {h['confirmed_units']}",
         f"CANDIDATE_STRUCTURES    = {h['candidate_structures']}",
         f"UNMAPPED_SOURCE_REGIONS = {h['unmapped_source_regions']}",
         f"DECOMPOSITION_COMPLETED = {h['decomposition_completed']}", "```", "",
         f"**Decomposition is not complete.** Blocked by: "
         f"{h['decomposition_blocked_by']}.", "", h["unmapped_note"], "",
         "## Module map", "",
         _tbl(["module", "packages"],
              [[m, ", ".join(p)] for m, p in h["module_map"].items()]), "",
         "## Packages", "",
         _tbl(["PL", "module", "teaching plan", "plan pages", "official title",
               "title source", "PDF start", "PDF end", "images", "tables",
               "record type"],
              [[r["pl"], r["module_code"], r["teaching_plan"],
                r["teaching_plan_pages"], r["official_title"], r["title_source"],
                r["pdf_start_page"], r["pdf_end_page"], r["image_count"],
                r["table_count"], r["record_type"]] for r in h["rows"]]), "",
         "Every `UNKNOWN_NOT_MEASURED` above needs the binary. None is reported as zero.",
         "", "## Confidence in the PL-to-module map", "",
         f"- Directly named by their own teaching plan: "
         f"{', '.join(h['pl_map_confidence']['directly_named'])}",
         f"- Inferred by ordinal position: "
         f"{', '.join(h['pl_map_confidence']['inferred_by_ordinal_position'])}", "",
         h["pl_map_confidence"]["basis"], "",
         "## Teaching plans", "",
         _tbl(["PT", "module", "pages", "tajuk"],
              [[t["pt"], t["module"], t["pages"], t["tajuk"]]
               for t in K2.TEACHING_PLANS]), ""]
    return "\n".join(L)


def retire_stale_queues():
    """Delete superseded queue files from the live tree. Git history keeps them."""
    removed, absent = [], []
    for base in RETIRED_QUEUES:
        for ext in QUEUE_EXTS:
            p = os.path.join(SRC_DIR, base + ext)
            if os.path.exists(p):
                os.remove(p)
                removed.append(base + ext)
            else:
                absent.append(base + ext)
    record = dict(
        record_id="QUEUE-RETIREMENT-01", stage=K2.STAGE,
        live_queue=LIVE_QUEUE,
        retired=[dict(artifact=b,
                      status="REMOVED_FROM_LIVE_TREE_AS_SUPERSEDED",
                      superseded_by=LIVE_QUEUE) for b in RETIRED_QUEUES],
        files_removed=removed, files_already_absent=absent,
        git_history="PRESERVED — the files remain in every commit that contained them; "
                    "only the working tree is cleaned.",
        scope_note=("The brief named v2. v1 and v3 are retired with it because the same "
                    "instruction requires automation and human-facing indexes to point at "
                    "one live queue only, and leaving two other superseded queues on disk "
                    "would contradict that. The widening is recorded here rather than "
                    "done quietly."),
        single_live_queue_check=sorted(
            f for f in os.listdir(SRC_DIR) if f.startswith("PRODUCTION_QUEUE_")))
    return record


def _retirement_md(r):
    L = [BANNER, "", "# Stale queue retirement", "", "```",
         f"LIVE_QUEUE = {r['live_queue']}", "```", "",
         _tbl(["artifact", "status", "superseded by"],
              [[x["artifact"], x["status"], x["superseded_by"]]
               for x in r["retired"]]), "",
         "## Files removed from the live tree", ""]
    L += [f"- `{f}`" for f in r["files_removed"]] or ["- none"]
    L += ["", r["git_history"], "", "## Scope", "", r["scope_note"], "",
          "## Live tree after retirement", ""]
    L += [f"- `{f}`" for f in r["single_live_queue_check"]]
    L += [""]
    return "\n".join(L)


def emit_all():
    c = K2.custody()
    h = K2.hierarchy()
    made = [
        _j("K2_BINARY_CUSTODY_v1.json", c),
        _w("K2_BINARY_CUSTODY_v1.md", _custody_md(c)),
        _j("K2_SOURCE_CONFLICT_01_v1.json", K2.CONFLICT),
        _w("K2_SOURCE_CONFLICT_01_v1.md", _conflict_md(K2.CONFLICT)),
        _j("K2_COURSE_HIERARCHY_v1.json", h),
        _w("K2_COURSE_HIERARCHY_v1.md", _hierarchy_md(h)),
    ]
    r = retire_stale_queues()
    made += [_j("QUEUE_RETIREMENT_v1.json", r),
             _w("QUEUE_RETIREMENT_v1.md", _retirement_md(r))]
    return made, r


if __name__ == "__main__":
    made, r = emit_all()
    for n in made:
        print("wrote", n)
    print("\nremoved:", r["files_removed"])
    print("live queue files now:", r["single_live_queue_check"])
