# -*- coding: utf-8 -*-
"""Stage 4.2F-D — emit the scoped location report, status model, T04 reconciliation,
K5 structures, calibration readiness and the granular production queue."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import src_run2_v1 as S   # noqa: E402


def _w(n, t):
    with open(os.path.join(OUT, n), "w", encoding="utf-8") as f:
        f.write(t)
    return n


def _j(n, o):
    return _w(n, json.dumps(o, ensure_ascii=False, indent=1) + "\n")


def _tbl(h, rows):
    o = ["| " + " | ".join(h) + " |", "|" + "|".join("---" for _ in h) + "|"]
    for r in rows:
        o.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ")
                                   for c in r) + " |")
    return "\n".join(o)


BANNER = ("<!-- GENERATED by docs/source/tools/src_run2_emit_v1.py — "
          f"Stage {S.STAGE}. Edit the model, not this file. -->")


def emit_all():
    made = []
    loc = S.source_locations()
    made.append(_j("SOURCE_LOCATION_REPORT_v1.json", loc))
    md = [BANNER, "", "# Scoped source-location and custody report", "",
          "No unqualified absence. Every statement below names where it looked.", "",
          _tbl(["package", "course", "scoped status", "binary or metadata", "bytes"],
               [[p["package"], p["course"], p["status"], p["binary_or_metadata"],
                 f"{p['bytes']:,}"] for p in loc["packages"]]), "",
          "## Locations searched", "",
          _tbl(["location", "method", "result"],
               [[x["location"], x["method"], x["result"]]
                for x in loc["locations_searched"]]), "",
          "## Locations NOT searched, and why", "",
          _tbl(["location", "reason"],
               [[x["location"], x["reason"]] for x in loc["locations_not_searched"]]), "",
          "## Connector status", "",
          _tbl(["connector", "reachable", "can", "cannot"],
               [[c["connector"], str(c["reachable"]).lower(), c["capability"], c["cannot"]]
                for c in loc["connector_status"]]), "",
          "## Uploaded archives discovered", "",
          _tbl(["archive", "bytes", "carries source", "note"],
               [[a["name"], f"{a['bytes']:,}", "yes" if a["contains_source"] else "no",
                 a["note"]] for a in loc["uploaded_archives"]]), ""]
    made.append(_w("SOURCE_LOCATION_REPORT_v1.md", "\n".join(md)))

    q = S.queue_summary()
    made.append(_j("PRODUCTION_QUEUE_v2.json", q))
    hdr = S.COLUMNS
    csv = [",".join(hdr)]
    for r in q["rows"]:
        csv.append(",".join('"' + str(r[c]).replace('"', '""') + '"' for c in hdr))
    made.append(_w("PRODUCTION_QUEUE_v2.csv", "\n".join(csv) + "\n"))

    c = q["counts"]
    al = q["alias_map"]
    md = [BANNER, "", "# Production queue v2 — granular source states", "", "```",
          f"IMMEDIATELY_EXECUTABLE_UNITS  = {c['immediately_executable_units']}", "```", "",
          "The headline. " + q["headline"]["note"], "",
          "Conditions: " + "; ".join(q["headline"]["conditions"]) + ".", "",
          _tbl(["count", "value"],
               [[k.replace("_", " "), v] for k, v in c.items()]), "",
          "## Why SOURCE_READY was retired", "", al["why"], "",
          _tbl(["old", "new", "because"],
               [[i["old"], i["new"], i["because"]] for i in al["interpretation"]]), "",
          f"**{al['retired_metric']['metric']}** is retired. "
          + al["retired_metric"]["why_retired"], "",
          "## Blockers by owner", "",
          _tbl(["owner", "count"],
               [[o, v["count"]] for o, v in q["blockers_by_owner"].items()]), "",
          "## Queue", "",
          _tbl(["course", "PL", "id", "type", "bin local", "readable", "content read",
                "boundary", "extraction", "model", "immediately executable", "owner",
                "blocker"],
               [[r["course"], r["pl"], r["unit_or_candidate_id"], r["record_type"],
                 "y" if r["binary_local"] else "n",
                 "y" if r["binary_readable"] else "n",
                 "y" if r["content_read"] else "n",
                 "y" if r["boundary_confirmed"] else "n",
                 r["extraction_status"], r["model_status"],
                 "**YES**" if r["immediately_executable"] else "no",
                 r["blocker_owner"], r["exact_blocker"][:60]] for r in q["rows"]]), "",
          q["derivation"], ""]
    made.append(_w("PRODUCTION_QUEUE_v2.md", "\n".join(md)))

    t = S.t04_page_reconciliation()
    made.append(_j("T04_PAGE_REFERENCE_RECONCILIATION_v1.json", t))
    md = [BANNER, "", "# T04_PAGE_REFERENCE_RECONCILIATION", "", "```",
          f"UNIT          = {t['unit_id']}",
          f"ROWS          = {t['rows_total']}",
          f"RESOLVED      = {t['rows_resolved']}",
          f"UNRESOLVED    = {t['rows_unresolved']}",
          f"MISMATCHES    = {t['mismatches']}",
          f"OLD_SPAN      = {t['old_span']}",
          f"FROZEN_MAP    = {t['frozen_map_span']}",
          f"REGENERATE    = {str(t['regeneration_decision']['regenerate']).lower()}",
          "```", "", t["cause"], "",
          "## Is it reviewer-facing?", "", "```",
          f"module page in storyboard PPTX     = "
          f"{str(t['learner_or_reviewer_facing']['module_page_appears_in_storyboard_pptx']).lower()}",
          f"module page in state appendix PPTX = "
          f"{str(t['learner_or_reviewer_facing']['module_page_appears_in_state_appendix_pptx']).lower()}",
          "```", "", t["learner_or_reviewer_facing"]["method"] + " — "
          + t["learner_or_reviewer_facing"]["finding"] + ".", "",
          t["regeneration_decision"]["reason"], "",
          "## Corrections", "",
          _tbl(["row", "old module page", "old rendered page", "PDF oracle module page",
                "PDF oracle rendered page", "delta", "status"],
               [[x["row_id"], x["old_module_page"], x["old_rendered_pdf_page"],
                 x["pdf_oracle_module_page"], x["pdf_oracle_rendered_page"],
                 f"{x['delta']:+d}", x["status"]] for x in t["corrections"]]), "",
          "Affected artifacts: " + ", ".join(f"`{a}`" for a in t["affected_artifacts"])
          + ".", "", t["scope_note"], ""]
    made.append(_w("T04_PAGE_REFERENCE_RECONCILIATION_v1.md", "\n".join(md)))

    k5 = S.k5_structures()
    made.append(_j("K5_STRUCTURE_INVENTORY_v2.json", k5))
    md = [BANNER, "", "# K5 PL01–PL08 structure inventory", "", "```",
          f"PAKEJ_LATIHAN            = {k5['pakej_latihan']}",
          f"CONFIRMED_UNIT           = {k5['confirmed_units']}",
          f"CANDIDATE_STRUCTURE      = {k5['recomputed_candidate_count']}",
          f"  clean                  = {k5['clean_candidates']}",
          f"  amber                  = {k5['amber_candidates']}",
          f"UNMAPPED_SOURCE_REGION   = {k5['unmapped_source_regions']} "
          f"({k5['unmapped_pages']} module pages)",
          f"PREVIOUS_COUNT_CONFIRMED = {str(k5['count_confirmed']).lower()}", "```", "",
          k5["recount_note"], "",
          "## Why no candidate was extracted", "", k5["extraction_decision"]["reason"], "",
          f"Prepared: {k5['extraction_decision']['what_is_prepared']}. "
          f"Needed: {k5['extraction_decision']['what_is_needed']}.", "",
          "## Candidate structures", "",
          _tbl(["PL", "subtopic", "PDF page span", "paragraph", "shared risk", "assessment",
                "status"],
               [[r["pl"], r["subtopic"][:46],
                 f"{r['source_page_span'][0]}–{r['source_page_span'][1]}",
                 r["paragraph_start"], "yes" if r["shared_boundary_risk"] else "no",
                 "none" if not r["assessment_available"] else "yes", r["status"]]
                for r in k5["rows"] if r["record_type"] == "CANDIDATE_STRUCTURE"]), ""]
    made.append(_w("K5_STRUCTURE_INVENTORY_v2.md", "\n".join(md)))

    cal = S.calibration_readiness()
    made.append(_j("FOUR_DECK_CALIBRATION_READINESS_v1.json", cal))
    md = [BANNER, "", "# First four-deck calibration readiness", "", "```",
          f"UNITS                = {len(cal['units'])}",
          f"ALL_SOURCE_VERIFIED  = {str(cal['all_source_verified']).lower()}",
          f"ALL_EXTRACTED        = {str(cal['all_extracted']).lower()}",
          f"ALL_MODELLED         = {str(cal['all_modelled']).lower()}",
          f"ANY_READY_TO_EMIT    = {str(cal['any_ready_to_emit']).lower()}", "```", "",
          "**Trigger:** `" + cal["trigger"]["trigger"] + "`", "",
          "Expected next stage: " + "; ".join(
              f"{i + 1}. {s}" for i, s in enumerate(cal["trigger"]["steps"])) + ".", "",
          _tbl(["unit", "source", "extracted", "rows", "modelled", "quiz drafted",
                "key status", "visuals", "attested", "ready to emit"],
               [[u["unit_id"], "yes" if u["source_verified"] else "no",
                 "yes" if u["extraction_complete"] else "no", u["extraction_rows"],
                 "yes" if u["provisional_model_complete"] else "no",
                 u["assessment_readiness"]["items_drafted"],
                 u["assessment_readiness"]["key_status"],
                 u["visual_obligation_readiness"]["subjects"],
                 u["visual_obligation_readiness"]["source_attested"],
                 "**no**"] for u in cal["units"]]), "",
          "## Per unit", ""]
    for u in cal["units"]:
        md += [f"### {u['unit_id']}", "",
               "Unresolved pattern decisions:", ""]
        md += [f"- {x}" for x in u["unresolved_pattern_decisions"]]
        md += ["", "Unresolved unit exceptions:", ""]
        md += ([f"- {x}" for x in u["unresolved_unit_exceptions"]] or ["- none recorded"])
        md += ["", f"Cast: {u['cast_blocker']}.", "",
               "Entry point after Bariah replies:", "", "```",
               u["emit_entry_point"]["command"], "```", "",
               u["emit_entry_point"]["note"], ""]
    made.append(_w("FOUR_DECK_CALIBRATION_READINESS_v1.md", "\n".join(md)))
    return made


if __name__ == "__main__":
    for m in emit_all():
        print("emitted  :", m)
